### ISSUE TITLE
Scroll Wheel Click and Drag Behaves Unexpectedly

### ISSUE THREAD

**Issue by RickGove** [ag-grid/ag-grid#7700] opened 2024-03-07 14:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Reproducible Scenario
Create a grid which has both vertical and horizontal scrolling because it's columns and rows extend off the page. Click the mouse wheel and drag to left. Then drag up.

**Current behaviour**
Grid will scroll horizontally, if that's the first direction the mouse is dragged. But it will not scroll vertically after that. And the reverse is true.

**Expected behaviour**
Grid should be able to scroll in every direction after the wheel is clicked and mouse is dragged.

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
31.1.1

* **Browser:**
Chrome

* **Language:** 
React TypeScript

**Comment by AG-Zoheil** [comment] 2024-03-07 14:47
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10947**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-03-07 14:47 UTC
Labels: AG-10947

**Comment by AG-Zoheil** [comment] 2024-03-19 15:45
**To provide an update on this:**

We have closed this item in our backlog as it will not be done. The reason for this that due to the technical implementation of the grid the horizontal and vertical scrollers are within different elements, so they are unable to work together at the same time. 

The workaround for this is to restart the scroll wheel by clicking when finished scrolling into one direction and scrolling into the other direction upon clicking again with the "new" scroll wheel.

Thank you for your understanding!
