### ISSUE TITLE
[performance] Make header columns move quicker on slower browsers

### ISSUE THREAD

**Issue by amcdnl** [ag-grid/ag-grid#2] opened 2015-03-06 18:25 UTC
The header columns move slowly when scrolling horizontally.

**Comment by ceolter** [comment] 2015-03-06 18:26
What client are you using??

**Comment by amcdnl** [comment] 2015-03-06 18:41
Chrome on MAC.  They move just aren't synced that great.

**Comment by ceolter** [comment] 2015-03-06 18:49
Chrome on PC has no sync issues. My android pad and phone do, but wasn't to
worried about that.

How did you find out about my grid??

**Comment by amcdnl** [comment] 2015-03-06 18:51
ngmodules

**Comment by lukelalo** [comment] 2015-04-03 12:43
on Safari and Mac the sync is very bad. With Chrome on Mac it seems to work better

**Comment by tannerlinsley** [comment] 2015-04-11 18:08
Not much better on Chrome than safari.  Both are pretty laggy for me.

I'm on a 2014 Retina Macbook Pro 15"

**Comment by ceolter** [comment] 2015-04-25 14:31
i've spent the last two hours looking at this and so far haven't come up with a solution. if you guys are experiencing what i am experiencing, i only notice it on my android phone and tab. on my windows 7 laptop, it's working fine with chrome, safari, firefox and internet explorer. basically the scrolling of the header lags behind the scrolling of the body.

in the code, i do this (shortened version):
```
eBodyViewport.addEventListener("scroll", function() {
    that.scrollHeader(newLeftPosition);
}

function (scrollHeader(bodyLeftPosition) {
    this.eHeaderContainer.style.left = -bodyLeftPosition + "px";
};

```

it looks like the scroll events are building up, so that if, for example, 20 scroll events are fixed, the grid refreshes the header 'left' style 20 times. i tried to drain the queue of scroll events, but putting the processing into a timer (with 0 wait) and only processing the event if it was the last to be received, but the same still happened.

to be honest, given i can't find a solution easily, and the grid's performance 'all around' are very good, i'm happy to leave this as unresolved. so unless anyone else can fix this, i'm going to close it as "happy to accept it the way it is, part of the drawback of the design"

do other grids have this problem solved??

**Comment by tannerlinsley** [comment] 2015-04-25 16:17
Leave it open. Tag or appropriately. I and others can then take a stab at it

**Comment by ceolter** [comment] 2015-04-25 17:13
sure, i look forward to seeing how this one is solved :)

**Comment by ceolter** [comment] 2015-04-27 05:43
I have just merged in a fix from tsnber re horizontal scroll and header lag. It solves the problem for me on android device. It was never a problem for my desktop. So now all devices work for me. An those on thus thread advise if the fix gas any difference for them? (I didn't do a release, you will need to build latest from master)

**Comment by tannerlinsley** [comment] 2015-04-27 05:44
Mobile keyboard? haha

**Comment by ceolter** [comment] 2015-04-27 05:46
yup - had to rip out the laptop! but now that i've updated my comment above, others will have no idea what we are talking about....

**Comment by tannerlinsley** [comment] 2015-04-27 05:46
What a shame haha

**Comment by simonnicholls1** [comment] 2016-06-15 15:05
@ceolter Was this ever fixed?

If I scroll on a tablet the table moves fine once I added the following css:

.ag-body-viewport {
  // Use momentum-based scrolling on WebKit-based touch devices.
  -webkit-overflow-scrolling: touch;
}

however I get the slow header scrolling described here, it basically stops moving the header if I swipe on the table and remove my finger, the header then eventually catches up when the table body has stopped moving.

Also I've added the ability to touch a cell to select it in order to edit a value as, as far as I could see it was mouse click event only, but I believe the above is affecting this too so hopefully it will fix both :)

**Comment by buremba** [comment] 2016-06-18 04:27
I can confirm this bug for Chrome and Safari on Mac. The header is quite sluggish compared to the grid. @ceolter I can capture a video of the browser when I'm browsing on https://www.ag-grid.com/example.php if you need.

**Comment by ceolter** [comment] 2016-06-28 13:57
this is still the same. it's not really a bug, it's a performance issue.

the header is not in the scrolling pane with the rest of the body. the scroll even on the rows part triggers the header to also be 'scrolled' (which is done by setting the headers offset, it's not really a scroll). the delay is how long it takes the browser to redraw. i have not looked into this in a while.

**Comment by simonnicholls1** [comment] 2016-06-28 14:04
Yeah no problem, it's a very small price to pay in an otherwise incredible library!

**Comment by ceolter** [comment] 2016-06-28 16:00
yea i agree - i mean - i am more excited about getting other parts fixed / implemented than spending time on this issue.

**Comment by buremba** [comment] 2016-06-29 01:57
Here is the video: https://www.youtube.com/watch?v=6D8P-sYn1XY
I'm also experiencing similar issue with pinned columns, the horizontal scroll is not enough smooth if I pin a column. I'm using a decent version Macbook and tested this issue with Chrome and Safari.

**Comment by daric81** [comment] 2016-08-05 10:42
I'm seeing this when using the grid with angular in chome on high end windows 10 PC.   If I set suppressScrollLag :true then the horizontal scroll is fine, but vertical scroll is laggy with many rows. It would be nice to only suppress the scroll lag horizontally.

**Comment by ceolter** [comment] 2017-01-23 12:22
tracked by
https://ag-grid.atlassian.net/browse/AG-37

**Comment by makinggoodsoftware** [comment] 2017-12-19 09:19
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Closed by makinggoodsoftware** 2017-12-19 09:19 UTC
Labels: enhancement

**Comment by mantuonweb** [comment] 2020-04-24 15:22
I am still facing this in ag grid version 20

**Comment by umashankar-masilamani-e2221** [comment] 2022-12-06 09:54
The issue is noticed in ag-grid community version 28.2.1 on mac based chrome versions starting from 108. It is also noticed in firefox and safari.
