### ISSUE TITLE
Typescript error when referencing gridOptions.api with strictNullChecks=true

### ISSUE THREAD

**Issue by AlejandroFlorin** [ag-grid/ag-grid#2084] opened 2017-11-29 21:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Object is possibly 'undefined'

**Expected behavior**
No compiler syntax error

**Minimal reproduction of the problem with instructions**
Set "strictNullChecks": true in tsconfig.json
reference gridOptions.api anywhere

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
Visual Studio 2017 (all updates)
npm

* **ag-Grid version:** 14.2.0

* **Browser:**

* **Language:** TypeScript 2.4

---------
The fix is to make gridOptions.api non-optional:

Change
`api?: GridApi;`
to
`api:GridApi;`

**Comment by UselessPickles** [comment] 2017-12-04 06:04
This looks like a duplicate of: https://github.com/ag-grid/ag-grid/issues/1979

See also, this comment in a related issue: https://github.com/ag-grid/ag-grid/issues/1976#issuecomment-339294971

**Comment by UselessPickles** [comment] 2017-12-04 06:10
Current workaround is to use null asserts for things that are incorrectly marked optional, but you know for sure will/should never be null:

```ts
const model = gridOptions.api!.getModel();
```

**Comment by UselessPickles** [comment] 2017-12-04 06:12
Actualy, this might subtly be not related to the other issue(s) I referenced. GridOptions is the interface for the input for a grid's options. "api" is a special property that you should never provide as an option to a grid. It is initialized by the grid itself. So it has to be optional to avoid forcing you to provide an api to a grid. This seems like a hack to me. Why is "api" in the GridOptions interface at all?

**Comment by makinggoodsoftware** [comment] 2017-12-05 14:54
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This is tracked by AG-980 Check our pipeline for more information, thanks

**Closed by makinggoodsoftware** 2017-12-05 14:54 UTC
