### ISSUE TITLE
Invisible horizontal scroll captures all pointer events after upgrading Chrome to version 105

### ISSUE THREAD

**Issue by tomasminceff** [ag-grid/ag-grid#5534] opened 2022-09-06 16:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Any example without horizontal scroll (e.g. the first demo at https://www.ag-grid.com/javascript-data-grid/column-definitions/)
- Move the cursor from the bottom of the grid. 
- The hover style is not applied on the last row in the area, where the scroll is usually shown - except for the last pixel and top of the last row. 
- Select Inspect from the context menu in that area.
The `.ag-body-horizontal-scroll-viewport` element is highlighted. But the height of the element is set to 0.

**Current behavior**
After upgrading Chrome from the version 104 to 105 we cannot target the focusable elements at the last row using mouse.
It is the problem mainly for grids with small row's height (e.g. the Live Streaming Updates demo at https://www.ag-grid.com/) and without vertical scrollbars - last row is not accessible.

**Expected behavior**
Whole elements on the last row can be target for mouse events.

**Workaround**
Always show horizontal scroll
https://ag-grid.com/angular-data-grid/grid-options/#reference-scrolling-alwaysShowHorizontalScroll

**Please tell us about your environment:**
Windows 10, VSCode, .net core, IIS

* **AG Grid version:** 
25.3.0 - 28.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Chrome Desktop: Version 105.0.5195.102 (Official Build) (64-bit)

* **Language:** all

**Comment by Cleggs** [comment] 2022-09-07 10:40
I was about to raise an issue here (and / or with Chromium) but you've described pretty much everything we are noticing in our use case (which includes a checkbox for selection in the last row that you can sometimes activate if you kind of hover _above_ the cell content).

I can add that we are running a fairly old version of ag-grid-angular at version 21.2, and noticed the same _last row selection issue_ within Microsoft Edge 105 as well.

**Comment by dirthsj** [comment] 2022-09-08 16:37
My dev team has discovered the same issues in our application. We are using Ag Grid Enterprise 28.1 -- I am currently investigating how to escalate this issue to enterprise support.

**Comment by StephenCooper** [comment] 2022-09-08 16:43
We have a ticket for this in enterprise support and so it is already on our list to investigate.

**Comment by edokan** [comment] 2022-09-09 15:44
Can confirm

AgGrid 27.0.1

No issues with v104, immediately experience after upgrading to v105

**Comment by dlfedie** [comment] 2022-09-09 18:30
Can confirm it's happening in 26.2 as well. Immediately upon v105 update, the issue appears.

**Comment by mrudowski** [comment] 2022-09-12 07:59
not fully tested yet but this should help as quick solution:

```
  .ag-body-horizontal-scroll-viewport[style*="height: 0"] {
    display: none;
  }
```

**Comment by kiril-matev** [comment] 2022-09-12 13:57
Hello @tomasminceff and everyone!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7242 When using Windows and not displaying a horizontal scrollbar, no mouse events are fired for the bottom half of the bottom row in the grid viewport**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by tomasminceff** [comment] 2022-09-19 10:34
Thank you! @mrudowski @kiril-matev

**Comment by cseramit** [comment] 2022-09-28 00:41
This issue exists even with 20.1.0
And the issue seems to have been fixed with the latest version of chrome. Tested on Chrome - 106.0.5249.62

**Comment by StephenCooper** [comment] 2022-10-05 13:31
I am going to close this issue as it has now been resolved by Chrome.

**Closed by StephenCooper** 2022-10-05 13:31 UTC
Labels: AG-7242

**Comment by diosadentro** [comment] 2025-04-22 20:27
This issue appears to be back in the latest version of Chrome and Edge on Mac (and only on mac)
Chrome Version: 135.0.7049.115 
Edge Version: 135.0.3179.85

The issue appears to be tied to screen size. For example, I can't reproduce the issue on 24 inch monitors, but I can reproduce it on my 16 inch macbook air.

Looking at the difference between a Mac Mini on big monitors and my macbook air, the only difference appears to be the inclusion of the class ag-invisible-scrollbar on the  ag-body-horizontal-scroll element.

<img width="968" alt="Image" src="https://github.com/user-attachments/assets/dbf39493-6f31-4553-9e33-649a1855d33a" />

We're on a fairly old version of ag-grid and unable to update at this time so if anyone has some suggested fixes via a CSS shim, I'd greatly appreciate it.

**Comment by kiril-matev** [comment] 2025-04-23 09:00
Hello @diosadentro,

Thanks for reaching out.

Please note that the original issue reported in this github issue was resolved. 

Please open a new github issue and provide the necessary details as per the bug submission template:
1. live example reproducing the issue (you can provide a small example on stackblitz/codesandbox or link to any documentation example which reproduces it. See our documentation archive to find the version you're on: https://www.ag-grid.com/documentation-archive/)
2. List of steps to follow to reproduce issue
3. Descriptions of Expected/Actual behavior

We're looking forward to investigating this in a new github issue.
