### ISSUE TITLE
Issue with multi row drag 

### ISSUE THREAD

**Issue by himalayabatra** [ag-grid/ag-grid#4443] opened 2021-04-14 07:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

  - While doing multi row drag, whenever i select multiple rows and just do the normal click within draggable area of any row, it will move whole selection up and down. I just did normal click no drag.
- Plunker link : https://plnkr.co/edit/xlcbg40aOU9SaCLz

I am not sure how this scenario is behaving, i am unable to find any concrete answer that why it is behaving like this. Is it any feature or bug. Please respond and help as i am in my project looking for multi row drag simultaneously looking to select and deselect my selection with click and i don't have a dedicated drag area as shown in your example i have made whole row draggable. User can click any where and start dragging, so i need both of these functionalities to work properly.

Using ag-grid-angular version - 23.1.1 with Angular 10. Tried with latest version also, issue still persists and in last issue AG-4373 it has not been resolved, but in changelog it says it has been resolved and description is different from actual issue mentioned in the ticket.

**Comment by makinggoodsoftware** [comment] 2021-04-15 15:40
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-19 16:26
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5262 When selecting multiple rows and clicking the row drag handle of the lower one, the upper one moves down to it instead of remaining in place**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-27 15:46
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-27 15:46 UTC
Labels: ag-5262, in_zendesk
