### ISSUE TITLE
Cannot refresh cells with cellRendererFramework

### ISSUE THREAD

**Issue by ha-decodeit** [ag-grid/ag-grid#1490] opened 2017-02-23 09:13 UTC
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
Updating a grid cell that has a react cell renderer (cellRendererFramework) via _node.setDataValue_ or _api.refreshCells_ results in an exception. 

Stack trace:
```
Uncaught TypeError: Cannot read property 'refresh' of null
    at ReactCellRenderer.refresh (http://localhost:3000/static/js/bundle.js:58785:30)
    at doRefresh (http://localhost:3000/static/js/bundle.js:47090:32)
    at RenderedCell.refreshCell (http://localhost:3000/static/js/bundle.js:47062:18)
    at cellChangeListener (http://localhost:3000/static/js/bundle.js:46431:24)
    at http://localhost:3000/static/js/bundle.js:33803:14
    at Array.forEach (native)
    at EventService.dispatchEvent (http://localhost:3000/static/js/bundle.js:33802:23)
    at RowNode.dispatchLocalEvent (http://localhost:3000/static/js/bundle.js:43117:32)
    at RowNode.setDataValue (http://localhost:3000/static/js/bundle.js:43129:15)
    at http://localhost:3000/static/js/bundle.js:32538:23
```

The problem is that _this.getFrameworkComponentInstance()_ in _reactCellRendererFactory_ returns null.

**Expected behavior**
It should be possible to update react rendered cells the same way as "regular" cells.

**Minimal reproduction of the problem with instructions**
Here's a gist that shows how to reproduce the problem. 
Updating the ID Cells is possible, but fails for the Name cell. (Either double click to edit or by clicking the update button)
https://gist.github.com/ha-decodeit/88e8c2979c213d789b10ad96a0dc68e3

**What is the motivation / use case for changing the behavior?**
I need to refresh cells for a custom inline-edit implementation.

* **ag-Grid version:** 
Ag Grid React 8.1.0
AG Grid Enterprise 8.1.0

* **Browser:**
Chrome 56.0.2924.87 (64-bit)

* **Language:** 
Typescript 2.1.4

**Comment by willhalling** [comment] 2017-02-23 15:26
Hello @ha-decodeit, thanks for raising this and providing the coding example. I can't replicate the error using node.setDataValue code example in version 8.0.1 & 8.10. Please, can you provide a gist for api.refreshCells?

**Comment by ha-decodeit** [comment] 2017-02-24 08:46
Interesting that the issue is not reproducable by you. 
Using the _refreshCells_ method results in the same error if I do something like this:
```
refreshNameCells() {
    let nodes = this.gridRef.api.getRenderedNodes();
    this.gridRef.api.refreshCells(nodes, ["name"]);
}
``` 

I created a minimal test case using the latest ag-grid and react version that shows the bug here:
[ag-grid-testcase.zip](https://github.com/ceolter/ag-grid/files/798698/ag-grid-testcase.zip)
(just run _npm install_ and _npm run start_)

Can you please check it out and tell me what you find out?

**Comment by ha-decodeit** [comment] 2017-02-28 08:21
@willhalling After further investigation it seems that the issue only occurs if the react component for the cell is passed as an instance of a class. If a class is passed to ag grid instead, updating the cell works as expected.

So this is working: 
```
import { NameCellRenderer } from "./NameCellRenderer";

const ColumnDefs = [
    { field: "name", cellRendererFramework: NameCellRenderer }
]
```

Where as defining the cellRendererFramework like that results in the described error when updating the cell:

```
import { NameCellRenderer } from "./NameCellRenderer";

const ColumnDefs = [
    { field: "name", cellRendererFramework: params => <NameCellRenderer params={params} /> }
]
```

**Comment by willhalling** [comment] 2017-02-28 09:13
Hi @ha-decodeit thanks for the providing a solution, appreciate it.

**Comment by colvint** [comment] 2017-04-01 00:09
Actually, I get the `Cannot read property 'refresh' of null` even if i pass the "class" itself. In my case, my renderer "class" is just a stateless component function:

```javascript
const AttendanceEventRenderer = (params) => {
  const { value: attendanceCode } = params
  const isAbsence = attendanceCode === 'A'
  const isTardy = attendanceCode === 'T'
  const isPresent = attendanceCode === 'P'
  const classes = classNames('label', { 'label-danger': isAbsence, 'label-warning': isTardy, 'label-success': isPresent })

  return (
    <span className={classes}>
      {attendanceCode}
    </span>
  )
}
```

and my colDefs are generated dynamically:

```javascript
const colDefs = [{...col defs here...}]

...
export default class SectionAttendanceList extends Component {
...
  appendAttendanceColumns() {
    const dayColumns = []
    const iter = moment('2017-09-04').twix('2018-06-15', { allDay: true }).iterate("days")
    ...
    while(iter.hasNext()) {
      ...
      dayColumns.push({
        ...
        cellRendererFramework: AttendanceEventRenderer
        ...
      })
    }
    ...
    columnDefs.push({
      children: dayColumns
    })
    
    this.api.setColumnDefs(columnDefs)
  }
...
}
```

**Comment by ha-decodeit** [comment] 2017-04-03 11:36
@colvint 
Try using a stateful component class instead. I noticed the same issue when using stateless components.
cheers

**Comment by colvint** [comment] 2017-04-11 00:54
@ha-decodeit Confirmed. `Cannot read property 'refresh' of null` error *not* thrown if renderer is a stateful component. Thanks!

**Comment by jjarcik** [comment] 2017-10-31 13:15
Can stateful component instead of stateless affect the performance?

**Comment by makinggoodsoftware** [comment] 2017-12-19 08:58
This should be fixed now

**Closed by makinggoodsoftware** 2017-12-19 08:58 UTC

**Comment by avril-verhaeghen** [comment] 2018-08-10 07:50
Hi,

Reopening this issue since I'm having this error but in another scenario.

What we're trying to achieve is to remove items from a list. This is done by selecting an item of a row where it has a checkbox column. Once the rows selected the user has to click on another button to confirm his delete action.

The columns are defined with custom HTML, so we can't use the api's `setColumnDefs` method.
To remove the row from the grid we use the `updateRowData` method. Which then results in a 

> Cannot read property 'refresh' of null

Setup for the grid:

```
this.gridOptions = <GridOptions> {};
this.gridOptions.context = this;
this.gridOptions.enableColResize = true;
this.gridOptions.suppressClickEdit = true;
this.gridOptions.suppressMovableColumns = true;
this.gridOptions.enableServerSideSorting = true;
this.gridOptions.headerHeight = 30;
this.gridOptions.rowHeight = 50;
this.gridOptions.cacheBlockSize = 50;
```

Method we use to update the grid:

`this.gridOptions.api.updateRowData({remove: [item]});`

Anyone has an idea? Thanks!

**Comment by NightBrownie** [comment] 2019-06-20 12:23
Sill an issue when `cellRendererFramework` is a stateless component.
