### ISSUE TITLE
Value columns don't restore order properly with pivoting

### ISSUE THREAD

**Issue by AndreyHaritonov** [ag-grid/ag-grid#4612] opened 2021-08-03 09:30 UTC
I think, it's a bug.

1. Open ag-grid.com example https://www.ag-grid.com/javascript-grid/pivoting/#saving--restoring-column-state-with-pivot
2. Enable pivoting
3. Remove all Column labels
4. Add Country columnt to the Row Groups
5. Add Silver and Gold columns to the Values. Apply exactly this order for columns: Gold must be after Silver.
6. Click Save State button
7. Click Reset State
8. Click Restore State
9. **Silver column will be after Gold column in the Values**

Expected behavior:
9. **Gold column is after Silver column in the Values**

Vesrion of Ag Grid: 25.3.0
Browser: Chrome

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:34
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-08-10 08:20
Hello @AndreyHaritonov!

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-5601 [Column State] Add to column state the order of value columns**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Also, as you're using an AG Grid Enterprise feature (pivoting), please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-31 14:45
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-31 14:45 UTC
Labels: in_zendesk, AG-5601

**Comment by vincent-prz** [comment] 2021-11-15 13:32
I know the issue is closed, but commenting here to upvote it, as it is a blocker for our needs.
