### ISSUE TITLE
Grid drag'n'drop crashes when trying to drag multiple collapsed items 

### ISSUE THREAD

**Issue by margarytaviter** [ag-grid/ag-grid#5156] opened 2022-05-11 15:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
 - create a grid with tree data, configured drag-n-drop behavior and enable multiple rows dragging by rowSelection="multiple" as described in docs https://www.ag-grid.com/javascript-data-grid/row-dragging/#multi-row-dragging
 - collapse more than one group row (e.g. 1st and 2nd) and select these collapsed rows with multiselection (keep Ctrl button pressed)
 - try to drag the collapsed rows to the another position

**Current behavior**
Getting an Uncaught TypeError: Cannot read properties of null (reading 'toString') in getRowIndexString function. After dropping rows are returned to the initial positions.

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at RowNode.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.RowNode.getRowIndexString (ag-grid-community.cjs.js:15342:1)
    at RowDragFeature.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.RowDragFeature.getRowIndexNumber (ag-grid-community.cjs.js:30393:1)
    at ag-grid-community.cjs.js:30372:109
    at Array.sort (<anonymous>)
    at RowDragFeature.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.RowDragFeature.doManagedDrag (ag-grid-community.cjs.js:30372:1)
    at RowDragFeature.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.RowDragFeature.onEnterOrDragging (ag-grid-community.cjs.js:30361:1)
    at RowDragFeature.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.RowDragFeature.onDragEnter (ag-grid-community.cjs.js:30339:1)
    at DragAndDropService.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.DragAndDropService.enterDragTargetIfExists (ag-grid-community.cjs.js:16313:1)
    at DragAndDropService.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.DragAndDropService.onDragging (ag-grid-community.cjs.js:16299:1)
    at DragService.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.DragService.onCommonMove (ag-grid-community.cjs.js:36079:1)
    at DragService.push../node_modules/@project/project-ui-toolkit/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.DragService.onMouseMove (ag-grid-community.cjs.js:36092:1)
    at HTMLDocument.mouseMoveEvent (ag-grid-community.cjs.js:36011:48)
    at HTMLDocument.nrWrapper (145:1499:39)
```

<img width="372" alt="image" src="https://user-images.githubusercontent.com/82871489/167886841-ebf32e3b-7897-4fbb-b2af-3a1bed7d3870.png">

**Expected behavior**
Grid works properly without error, rows are moved to their new positions on drag end.

**Please tell us about your environment:**
* **React 17.0.0**

* **AG Grid version:** 26.2.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36'

* **Language:**  ES6/7

Please note that the issue is not reproducing for expanded groups - drag'n'drop works fine when all selected group items are expanded.

**Comment by romansimeiz** [comment] 2022-05-11 18:45
Also reproducing... Any solution ?

**Comment by makinggoodsoftware** [comment] 2022-05-12 10:07
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-05-23 09:46
Hello @margarytaviter !
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6795 When using row grouping/tree data, selecting all rows with header checkbox selection, expanding a row group and dragging a row, console exceptions are thrown**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-06-10 13:17
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-06-10 13:17 UTC
Labels: in_zendesk, ag-6795
