### ISSUE TITLE
Issues with Theme Builder CSS

### ISSUE THREAD

**Issue by jason-beach** [ag-grid/ag-grid#8328] opened 2024-07-12 15:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Hello, I've created a custom theme and followed the instructions on how to add it to my application, however, I'm getting inputs that seem to be incorrect, hover, focus on inputs not appearing as the theme builder would indicate. Screenshots below.

![CleanShot 2024-07-12 at 11 28 34@2x](https://github.com/user-attachments/assets/c0fb90c6-c177-413e-8273-7dafec1ee2e5)
![CleanShot 2024-07-12 at 11 29 30@2x](https://github.com/user-attachments/assets/7b6d13fb-1b51-4ace-85e5-bc4ecff04fda)

This is only when I use custom theme builder's css. However, when I use the normal css via ag-grid.css and ag-theme-quartz.css everything seems to be fine. Only when I use custom theme builder's css I see the issues.

Normal behavior with ag-grid.css and ag-theme-quartz.css
![CleanShot 2024-07-12 at 11 34 12@2x](https://github.com/user-attachments/assets/4db45ea3-5f63-43d4-98bc-175d97aef449)
![CleanShot 2024-07-12 at 11 34 34@2x](https://github.com/user-attachments/assets/aa7c9d12-3450-4ab8-b286-3a1163ed8d34)

**Please tell us about your environment:**
Vue3

* **AG Grid version:** X.X.X
32.0.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by BernieSumption** [comment] 2024-07-16 10:27
Hi Jason thanks for reporting this issue, I can look into it for you. Since (if I understand correctly) the issue doesn't appear in Theme Builder itself only when you apply the theme to your application, there are two likely causes:

1. it may be an issue that's limited to a feature, grid option, filter configuration or column data type that you're using in your application.
2. your application may be applying styles to text inputs that override the styles set by the theme builder

Are you able to provide a reproduction of the issue?

Here's a plunker that may help, it includes a grid set up with a theme builder export, you can paste your export into the CSS file and tweak the grid options until you can see the issue, then save a version and send it back to us. https://plnkr.co/edit/WnwWTde11yauITNb?open=main.ts&preview

**Comment by jason-beach** [comment] 2024-07-16 14:16
@BernieSumption , so I've played around with the Plunker you created. I've noticed a couple things initially:

1. When I comment out `import "ag-grid-enterprise";` you'll notice that the 'Electric' column filter is messed up:
![CleanShot 2024-07-16 at 09 44 48@2x](https://github.com/user-attachments/assets/8c367cbe-47d1-41ac-88a1-5332907f37d4)

2. When I add my own theme using theme builder and have #1 still commented out I notice padding issues within the filters. I.E. the cursor is right next to the magnifying glass and has no space from the typed filter. I also see this padding issue in the theme builder on Ag Grid's website. I've narrowed that down to when I add a bunch of spacing (16px) under 'Borders and Spacing': 
![CleanShot 2024-07-16 at 09 43 30@2x](https://github.com/user-attachments/assets/d25007d1-c561-4900-9ff5-859175cbbf5b)

3. I've added tailwind to the Plunker which didn't add any issues that I can see initially.

The weird thing here is that with my Vue implementation adding the default css according to the docs everything looks fine (without enterprise). When I add a custom theme built with theme builder, is when it starts to look like in #1 & #2 above.

**Comment by BernieSumption** [comment] 2024-07-16 14:44
OK that's useful thanks. I've reproduced 2 issues that we can get onto:

1. Theme Builder themes don't work with the simple filter from the community edition (this is what's happening when ag-grid-enterprise is commented out)
2. Extra padding is required in search text inputs at large grid sizes (affects Theme Builder and regular CSS themes)

This just leaves the focus outline. If it's not reproducing in plunker it's possibly a conflict with another style in the page. Can you check your developer tools to see what's happening to the box-shadow on the focussed input?

In Chrome, right click the input and choose "Inspect", then  tick the `:focus` box in the Styles tab:

![image](https://github.com/user-attachments/assets/8cf6687e-39c9-4e79-838c-24e4d39d5506)

And find "box-shadow" in the Computed tab:

![image](https://github.com/user-attachments/assets/ffc2e8fd-d111-4017-94f2-0de485ce57d1)

The value should be similar to `color(srgb 0.129412 0.588235 0.952941 / 0.5) 0px 0px 0px 3px`.

If it's not then something is overriding the text input style. Click the blue arrow next to the value and it'll take you to the rule that is responsible.

Thanks!

**Comment by jason-beach** [comment] 2024-07-16 15:08
@BernieSumption , I've narrowed down the box shadow to be that tailwind is overriding several things: `[type='text']` and `[type='text']:focus` which is making the input larger and with a border of blue. How do I fix this? With custom css or is there a selector I can target for the inputs in the the filters?

**Comment by BernieSumption** [comment] 2024-07-17 09:55
>  I've narrowed down the box shadow to be that tailwind is overriding several things: [type='text'] and [type='text']:focus

This is odd because, as I understand it, tailwind isn't supposed to have any global styles, it's only supposed to apply styles to elements based on the classes that you add to it.

I don't supposed your app is using the [@apply feature](https://tailwindcss.com/docs/reusing-styles) to target certain tailwind styles to `input[type="text"]`?

> How do I fix this? With custom css or is there a selector I can target for the inputs in the the filters? Or is this something you guys would do on your end?

This isn't something we can fix on our end because some people want to override our default styles and we can't tell whether any instance of overriding is deliberate or not. Things you can do to avoid accidentally overriding our styles include:

* Not having rules that target every input e.g. `[type="text"]` and use class name rules instead
* If you can't avoid targeting every input (e.g. you don't control the DOM so can't add class names to inputs) use `[type="text"]:not([class^='ag-'])` to exclude grid inputs
* Moving our styles after your app's styles in the page so that our styles take precedence in cases where they have the same specificity.
* Adding additional styles to `.ag-text-field-input` to override your `[type="text"]` rule and implement the style you want (this is what you've done in your post above)

Do any of those work for your use case?

**Comment by jason-beach** [comment] 2024-07-17 17:50
@BernieSumption , thanks the solutions. I've added additional styles to `.ag-text-field-input` to override the ``[type="text"] rule. Everything seems to be in working order now.

**Comment by AG-Zoheil** [comment] 2024-07-18 08:59
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12311 & AG-12313**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-07-18 08:59 UTC
Labels: AG-12311, AG-12313
