### ISSUE TITLE
Ag-grid does not calculate size-to-fit column widths properly when container has fractional width

### ISSUE THREAD

**Issue by nzacca** [ag-grid/ag-grid#4113] opened 2020-10-02 02:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to Reproduce**
See the following stackblitz with reproduction instructions, demo of issue and possible solution: https://stackblitz.com/edit/angular-ivy-dwcfti?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
When the container of the grid has fractional units (ex. 500.93px), the size-to-fit does not properly calculate the widths of the columns causing the total width to be 1px bigger than it needs to be which produces an unnecessary horizontal scrollbar.

This only appears when the zoom level of the browser (or monitor scaling) is increased. Default scaling on some laptops we've come across are set to 150% width 1920x1080 resolution.

Relates to: https://github.com/ag-grid/ag-grid/issues/3319

**Expected behavior**
No horizontal scrollbar should appear.

**Other Notes**

One might question 'Why are fractional units even being used?' - I have no idea. This is not something explicitly set in our codebase and seems to be the result of a third-party library calculating the widths based on percentage which leads to these odd fractional widths. The hardcoded fractional units in the demo above were only used to demonstrate the issue.

Speculating here but it appears as though, however AgGrid is calculating the width of the content area, it is not rounding up the container width which causes it to be 1px off thus producing the horizontal scroll. I think if the calculation uses the Math.ceil of the container width, this should fix the issue.

**Please tell us about your environment:**
Windows 10, node 12.16.1, npm 6.14.3, Angular 10.1.4

* **ag-Grid version:** 24.0.0

* **Browser:**
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

* **Language:** Typescript 4.0.3

**Comment by makinggoodsoftware** [comment] 2020-10-13 11:05
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

Thanks

**Comment by nzacca** [comment] 2020-10-13 21:39
@makinggoodsoftware 
Thank you for your response. Could you kindly clarify your response please? I've provided a demo illustrating the bug within AgGrid. Does this mean this bug will not be fixed? Or could you clarify why this is not a bug?

**Comment by nzacca** [comment] 2020-10-21 20:06
@makinggoodsoftware 

Just following up here. My team and I are just trying to determine what criteria meets the threshold for determining whether something is a bug in ag-grid or not. From our perspective, the issue here is that ag-grid is not calculating the width of the container properly which causes an unnecessary horizontal scrollbar to appear. The last comment in #3319 asked for a reproducible demo which I have provided above. We're not asking for ag-grid's assistance in troubleshooting our codebase but believe we have identified a bug where Ag-grid does not handle fractional container widths properly.

Alternatively, if we dedicate some time to finding the line of code that is missing the `Math.ceil`, would you accept a PR for the fix? All we are talking about here is a 1px difference which leads us to believe there's some calculation happening in the ag-grid codebase that is missing `Math.ceil`.

Thank you for your time.

**Comment by ThomasOrtiz** [comment] 2020-11-23 16:26
My team also experiences this issue in Chrome while calling `sizeColumnsToFit()`.

Until its fixed we decided not to auto fit columns which isn't ideal.

**Comment by nzacca** [comment] 2020-11-24 10:26
@makinggoodsoftware 

As another community member has reached out and confirmed that they are also experiencing this same issue, may I kindly request if you could please re-evaluate this issue and reconsider the `managed-by-community` tag? Or could you kindly give us an explanation as to why this is not considered a bug by the ag-grid team? Or could you kindly answer my question above about whether your team will accept a PR to fix the issue?

Another thing you could try is zooming in on this Github issue page and inspecting the container for one of these messages in this thread. When it is viewed at 100%, note there are no fractional units. However, when you zoom in on the page, Chrome devtools shows the container width to have fractional units. This is where ag-grid is having trouble as demonstrated in the link I provided above.

Thank you again for your time.

@ThomasOrtiz 

Just in case this is an option for you, my team opted to resize some of our containers that were containing grids to be 1-2% bigger which allowed the math to work out where the horizontal scrolls did not appear when the page was zoomed. Like your team, this is not ideal for us but was a workaround until this issue could be resolved.

**Comment by Vortilion** [comment] 2020-12-02 15:44
We are having the same issue. If the user sets a Windows-Zoom of e.g. 125% you sometimes get the horizontal scrollbar when resizing the browser window. Our Tables are in a bootstrap 4 grid. It is very annoying cause it hides a row of the table, which the user can't read anymore cause of this scrollbar. 

I found a bug before with ag-grid, they decided to ignore the issue back then as well. So t.b.h. I don't expect them to fix anything coming from us "standard-version"-users...

**Comment by nzacca** [comment] 2020-12-09 22:28
@Vortilion Thank you for voicing your issue. While I can empathize with your frustration and sentiments, I do feel we should continue to engage with the ag-grid development team in a constructive manner. I'm trying to determine what about my issue filed above caused it to be flagged. If the community knows what types of issues will and won't be fixed, this will help save time for everyone. My team is willing to go about investigating a fix for this issue but only if we can get consensus from the ag-grid team.

@makinggoodsoftware Following up again on this issue. Just looking for some feedback from your team as to whether or not  this will make it into the internal bug list or if this is something the community can submit a PR to fix.

**Comment by makinggoodsoftware** [comment] 2020-12-11 10:18
Hi guys,

Seeing that this getting traction here, let us have a look at the provided stackblitz originally:

https://stackblitz.com/edit/angular-ivy-dwcfti?file=src%2Fapp%2Fapp.component.ts

We will update you as soon as possible!

**Comment by nzacca** [comment] 2020-12-11 20:06
@makinggoodsoftware 

Thank you so much for taking a look. Truly appreciate this. If you need any additional information or clarification about anything, please don't hesitate to reach out.

**Comment by kiril-matev** [comment] 2020-12-16 15:12
Hello!

Thank you for reporting this - much appreciated!

@nzacca: Thank you for your constructive approach and for engaging with us on this issue. We appreciate the time you invest in reporting these issues with a sample, detailed actual vs expected behavior descriptions and analysis of the issue.

@Vortilion: Thank you for raising this point because it allows us to make an important clarification here - we don't treat bugs reported in ag-grid-community differently from those reported in ag-grid-enterprise. Ag-grid-community and ag-grid-enterprise are not independent products. On the contrary, as ag-grid-community contains the basic functionality that all ag-grid users use, the bugs reported against ag-grid-community end up getting fixed even more quickly than those for ag-grid-enterprise as they have a greater impact. 

Back to the specific issue. Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4899 Grid container with fractional width value causes unnecessary horizontal scrollbar when increasing zoom level**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date and whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for automatic release notifications on ag-grid. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up with us.

**Comment by nzacca** [comment] 2020-12-16 21:57
@kiril-matev 

Thank you very much for your response. I look forward to the fix.

I think the concern I have is that the issue was immediately flagged without an explanation about why it was flagged and the lack of response to any of the questions I raised above. I can certainly understand and agree with Ag-grid not wanting to troubleshoot individual issues in a user's codebase. That is not Ag-grid's responsibility, but I do feel some kind of explanation for why something is not going to be fixed would be helpful.

One suggestion I can think of is adding a readme, a pinned issue, or adding it to the Issue template explaining what criteria meets the threshold for a bug. This would help future community members save time and possibly prevent user error issues from being filed.

Another suggestion I can think of is turning on the Github Discussions section when it is available to allow community members to discuss user error issues that the Ag-grid team has deemed "working as expected" but requires further community support.

Thank you again for engaging with us. I appreciate your time and the work that the Ag-grid team is doing to help support other development teams around the world.

**Comment by makinggoodsoftware** [comment] 2021-01-04 17:02
@nzacca I'll take this on board, we have been lately trying to revamp the level of support provided in github, it really is a capacity issue since we first serve our customers but we would love to extend this to noncustomers too.

I agree we should have looked into detail in the first instance, so apologies for that.

I hope to raise the bar for the support provided here through 2021

Thanks for your feedback

**Comment by nzacca** [comment] 2021-01-04 19:17
@makinggoodsoftware 

Thanks for the response. Totally understandable. I can imagine it must get very overwhelming fielding support questions from around the world. My team and I certainly do not expect the Ag-grid team to solve our support issues and fully agree your customers should come first. I'm sure the majority of the community here feels the same.

I look forward to this upcoming year and wish you and your team a very Happy New Year.

**Comment by makinggoodsoftware** [comment] 2021-01-07 15:26
Hi @nzacca 

Thanks for the kind words!

Hopefully, we will get this out in our next release.

Happy new year to you too!

**Comment by SBD580** [comment] 2021-01-21 08:46
Had the same issue, until a fix is release I have used the following workaround (after auto-sizing, for all auto-sizing columns):
`column.setActualWidth(column.getActualWidth() - 1);`

(if you are worry about the column width to not be wide enough, you can increase `autoSizePadding`)

**Comment by makinggoodsoftware** [comment] 2021-02-15 12:22
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-02-15 12:22 UTC
Labels: AG-4899, community-engaged, in_zendesk
