### ISSUE TITLE
Reset filters not working when table has no rows

### ISSUE THREAD

**Issue by bstenersen** [ag-grid/ag-grid#8431] opened 2024-07-30 05:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://codesandbox.io/s/text-filter-forked-pg42pc

**Current behavior**
When calling api.setFilterModel(null), the expected behavior is to reset the filterModel to its initial state and update the icon of the table header. However, this behavior is inconsistent depending on the presence of rows in the model. When rowData is an empty array, calling api.setFilterModel(null) does not reset the filterModel and the icon of the table header remains unchanged.

**Expected behavior**
Filtermodel is reset when calling  api.setFilterModel(null), even if the table has no rowData.

* **AG Grid version:** 32.0.2

* **Browser:**
Firefox, Edge

**Comment by sabahang** [comment] 2024-08-09 08:39
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-12532 [Filtering] Filter icon in header does not reset when rowData is empty**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed by sabahang** 2024-08-09 08:39 UTC
Labels: investigating

**Comment by sabahang** [comment] 2024-08-14 09:03
Hi @bstenersen 

After further investigation this is expected behaviour. 

If inferring cell data types, and row data is provided asynchronously and is yet to be set, the filter model will be applied asynchronously after row data is added. To always perform this synchronously, set cellDataType = false on the default column definition, or provide cell data types for every column.
