### ISSUE TITLE
update from v29.3.5 to v30.0.6 gives multiple re-render issues

### ISSUE THREAD

**Issue by devprachi** [ag-grid/ag-grid#7246] opened 2023-11-13 03:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Current behavior**
On upgrading the version to 30.0.6, ag-grid is giving following error intermittently while performing actions like filtering, row selection, deselection, specifically in client-side row model :

> rowRenderer.mjs:383 Uncaught Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
>     at RowRenderer.getLockOnRefresh (rowRenderer.mjs:383:1)
>     at RowRenderer.redrawAfterModelUpdate (rowRenderer.mjs:331:1)
>     at RowRenderer.onPageLoaded (rowRenderer.mjs:236:1)
>     at eval (eventService.mjs:110:1)
>     at Set.forEach (<anonymous>)
>     at processEventListeners (eventService.mjs:105:1)
>     at EventService.dispatchToListeners (eventService.mjs:116:1)
>     at EventService.dispatchEvent (eventService.mjs:87:1)
>     at PaginationProxy.onModelUpdated (paginationProxy.mjs:51:1)
>     at eval (eventService.mjs:110:1)

Seems like a race condition is being created in the ag-grid, which not handled it in v30.0.6 version.

**Expected behavior**
We should not get any re-render error by just upgrading, since we have not changed any logic from our end, and nothing related was mentioned in the change log. Was there any internal changes in v30 related to how the rendering is handled, which is causing this issue ?

**Please tell us about your environment:**
MacOS, VsCode

* **AG Grid version:** X.X.X
30.0.6

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment] 2023-11-16 15:50
Hi @devprachi,

Could you confirm more details that are missing from your ticket. Are you using React? If so which version?

Any reproduction of this issue would also be very helpful.

**Comment by asoov** [comment] 2023-11-17 10:25
Having the same problem. For me it happens when calling redrawRows within the callback of applyServerSideTransactionAsync. Wrapping the redrawRows call in setTimeout as advised in the error message doesn't solve the problem.

**Comment by StephenCooper** [comment] 2023-11-17 10:48
@asoov can you please let me know which React version / AG Grid version you are using?

**Comment by devprachi** [comment] 2023-11-21 04:47
@asoov I am using react version `16.3.0`

**Comment by AG-Zoheil** [comment] 2023-11-30 09:25
Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by devprachi** [comment] 2023-12-11 05:29
Hey @AG-Zoheil, 
Can you share the documentation of previous versions of aggrid. Since the version is updated again, the previous documentation would be helpful in reproducing.

**Comment by AG-Zoheil** [comment] 2023-12-11 09:07
Hi @devprachi,

Of course, there is a link to documentation archives in our footer. It looks like the version this was first reported in was `30.0.6`? If that is the version you are looking for here is a direct link to the documentation: https://ag-grid.com/archive/30.0.6/react-data-grid/.

Alternatively, if you are looking for a different version, please refer to the documentation archive in our footer.

Thank you!

**Comment by AG-Zoheil** [comment] 2024-01-15 10:30
Hello,

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-01-15 10:30 UTC
Labels: waiting-for-repro

**Comment by aarohi899** [comment] 2024-01-18 03:35
I was facing the same issue in v30.0.6, Upgrading the version to v31.0.0+ solved the problem for me.
