### ISSUE TITLE
Screen readers like NVDA and JAWS are not able to read the row selected only if checkbox selection is not used in grid

### ISSUE THREAD

**Issue by Venkat1P** [ag-grid/ag-grid#7007] opened 2023-09-04 06:48 UTC
Use case: Accessibility users use screen readers to listen the row they select and do operation based on the listening or visual skills provided by screen readers majorly NVDA or JAWS.

This is a community support request as we are using community version v27.

Reproducible scenario :

- Below is the link from Ag-grid documentation of row selection 
- Plunker link to reproduce
- [(https://plnkr.co/edit/?open=app%2Fapp.component.ts&preview)]
- Install NVDA or any accessibility tools 
- Make sure your audio sound is audible and speech viewer is opened to read all the speech run through mouse or keyboard
- Select the row from ag-grid
- Selected row is not announced.

Same above steps works fine if we have a checkbox to select in the grid:

- Below is the link from Ag-grid documentation of row selection through checkbox
- [https://plnkr.co/edit/?open=app%2Fapp.component.ts&preview]
- Row selection is announced saying "Row 2 selected, data and checked/unchecked"

**Current behavior**

1. Row selection is not getting announced after selecting a row.
2. Screen reader Speech Viewer or Audio is not announcing the row number which is selected.

NOTE: It works fine if we have a checkbox selection in the grid on each row to select. Screen readers says checked/unchecked along with row number.

**Expected behavior**

1. Row selection should be announced when there is no checkbox selection of row.
2. It should say, example "Row 2 selected, data of grid and Checked/Unchecked".

Windows 10 Environment 
Ag-Grid Version : v27
Browser: Chrome and Edge 115.0.5790
Language: Typescript and framework Angular

**Comment by AG-Zoheil** [comment] 2023-09-08 14:14
Hi @Venkat1P,

Thank you for reporting this.

I'm afraid it seems like you hadn't saved your plunkers so they are empty and we cannot view them. However based on your description we created the following plunkers but are unable to reproduce the issue you are describing using NVDA screen reader:

Row selection - https://plnkr.co/edit/vQtf6wRwa7BJewtG?open=main.js
Checkbox selection - https://plnkr.co/edit/HA8TgGpisoTI5HBx?open=main.js

In both cases, the row is announced using NVDA. I have updated the examples above to match your version (v27), however please note that we would only be fixing the current version if any bugs are discovered.
In light of that, I would encourage you to update to the latest version at your earliest convenience to take advantage of all the new features and bug fixes we've released since.

Can you please confirm if you have any issues with the latest (v30.1.0) version from our documentation page?

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment] 2023-11-06 10:50
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-11-06 10:50 UTC
Labels: waiting-for-repro
