### ISSUE TITLE
TypeScript (2.5.3) errors in ag-grid 13.3.1 with strictNullChecks

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid#1976] opened 2017-10-11 15:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Can't compile an app utilizing TypeScript w/ ag-grid 13.3.1

ERROR in c:\Workspace\nextgen-ui-pilot\packages\expressions-grid\node_modules\ag
-grid\dist\lib\filter\baseFilter.d.ts
(21,31): error TS2420: Class 'BaseFilter<T, P, M>' incorrectly implements interf
ace 'IFilterComp'.
  Types of property 'afterGuiAttached' are incompatible.
    Type '(params: IAfterGuiAttachedParams) => void' is not assignable to type '
((params?: IFilterAfterGuiAttachedParams | undefined) => void) | undefined'.
      Type '(params: IAfterGuiAttachedParams) => void' is not assignable to type
 '(params?: IFilterAfterGuiAttachedParams | undefined) => void'.
        Types of parameters 'params' and 'params' are incompatible.
          Type 'IFilterAfterGuiAttachedParams | undefined' is not assignable to
type 'IAfterGuiAttachedParams'.
            Type 'undefined' is not assignable to type 'IAfterGuiAttachedParams'

**Comment by amirburbea** [comment] 2017-10-11 15:20
My tsconfig

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "checkJs": false,
    "declaration": false,
    "emitBOM": false,
    "emitDecoratorMetadata": false,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSourceMap": false,
    "inlineSources": false,
    "importHelpers": true,
    "jsx": "react",
    "lib": [
      "dom",
      "es2015",
      "es2017.object"
    ],
    "listEmittedFiles": false,
    "locale": "en-us",
    "module": "commonjs",
    "moduleResolution": "node",
    "newLine": "LF",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "outDir": "./build",
    "preserveConstEnums": false,
    "pretty": true,
    "removeComments": true,
    "rootDir": "./src",
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true,
    "suppressExcessPropertyErrors": false,
    "suppressImplicitAnyIndexErrors": false,
    "target": "es2015"
  }
}
```

**Comment by UselessPickles** [comment] 2017-10-11 17:09
This is a duplicate of https://github.com/ag-grid/ag-grid/issues/1889, which was INCORRECTLY CLOSED! This is a bug that needs to be fixed.

The problem is that IComponent.afterGuiAttached specifies the param as optional, but the implementation of the interface method in Component is NOT marked as optional.

I believe the correct solution is to NOT mark the param as optional in the interface.

This is part of a widespread problem I have noticed: params in many interface methods and event handler methods are marked as optional when they should be expected to always have a value (not null, not undefined). I think there is a misunderstanding of what an "optional" parameter means. "optional" means that a value may not be passed in to calls to the method in some usages of the method. 

As another example, ALL of the events in GridOptions have the "event" param marked as optional. Why is the event optional? That is THE key piece of information that tells me what happened when I handle the event!  Because the event is marked as optional, when using "strict-null-checks" compiler option, I now have to perform null checks on the "event" in every event handler before accessing properties of the event, even though I'm pretty sure that the event will never be null/undefined. And what do I do in my null-check branch of code in case the event ever is null? The documentation does not describe any situation where the event is null, so I don't know how to handle it.

I think the best way to resolve these issues is for the ag-grid team to start compiling the project with the TypeScript "strict" option enabled, and revisit ALL of the optional params in interface method signatures. If the intent is that a value will ALWAYS be provided for a param when the method is called (e.g., "event" param on event handlers), then the param should NOT be marked as optional.

**Comment by JohnMasterson** [comment] 2017-10-25 11:07
Hello - this has been now recorded in our JIRA ticket - AG-980. 

You can see this in our pipeline here: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by UselessPickles** [comment] 2017-11-09 16:39
@JohnMasterson We are currently evaluating ag-grid and considering purchasing an Enterprise license, but this one issue is really causing us problems. It's forcing us to disable "strictNullChecks" on our entire Typescript project, which prevents us from catching preventable errors in our own code at compile time.

I see that AG-980 is currently in the "backlog", not targeted for any upcoming release. Would it be possible to fast-track a minimal solution to this particular compiler error (when attempting to USE ag-grid in a project with strictNullChecks), separate from solving all of the internal problems that arise when attempting compile the ag-grid project itself with structNullChecks?

If we could compile our project with strictNullChecks while using ag-grid, then it would be much easier to decide to choose ag-grid for our project.

**Comment by melcor76** [comment] 2017-11-09 16:55
What @UselessPickles said. This one is a deal breaker.

**Comment by UselessPickles** [comment] 2017-11-14 21:45
Looks like this is already fixed in v14.1.1

**Comment by makinggoodsoftware** [comment] 2017-12-05 17:13
Hi, AG-980 is going to get fixed in this release ETA:11th of December

Please track the progress in our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

**Closed by makinggoodsoftware** 2017-12-05 17:13 UTC

**Comment by JohnMasterson** [comment] 2017-12-19 13:36
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John

**Comment by vitalybe** [comment] 2018-04-10 15:31
I don't understand how it is fixed, in my project I am trying to use ag-grid with `"strictNullChecks": true` and I am getting **many** compilation errors, for example:

```
node_modules/ag-grid/src/ts/widgets/agCheckbox.ts(67,102): error TS2345: Argument of type 'null' is not assignable to parameter of type 'Column'.
node_modules/ag-grid/src/ts/utils.ts(296,37): error TS2322: Type 'null' is not assignable to type 'Date'.
node_modules/ag-grid/src/ts/rowModels/inMemory/immutableService.ts(78,17): error TS2532: Object is possibly 'undefined'
```

If I set `strictNullChecks` to false, it compiles fine. Am I missing something?

This is my tsconfig.json:

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "app",
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "app/*": ["app/*"]
    },

    "strictNullChecks": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts/config",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "app/setupTests.ts"
  ]
}
```

**Comment by Vikramalakshman** [comment] 2022-11-12 09:48
### Fixied the following excecption

_Error: node_modules/ag-grid/dist/lib/filter/baseFilter.d.ts:21:31 - error TS2420: Class 'BaseFilter<T, P, M>' incorrectly implements interface 'IFilterComp'.
  Types of property 'afterGuiAttached' are incompatible.
    Type '(params: IAfterGuiAttachedParams) => void' is not assignable to type '(params?: IFilterAfterGuiAttachedParams | undefined) => void'.
      Types of parameters 'params' and 'params' are incompatible.
        Type 'IFilterAfterGuiAttachedParams | undefined' is not assignable to type 'IAfterGuiAttachedParams'.
          Type 'undefined' is not assignable to type 'IAfterGuiAttachedParams'._


Solution is made by making the following method  as optional by adding '?' symbol in the  node_modules(node_modules\ag-grid\dist\lib\interfaces\iComponent.d.ts),

**export interface IFilterAfterGuiAttachedParams extends IAfterGuiAttachedParams {
    hidePopup?: () => void;
}**

Please let me know, if any alternative solutions are there.

Thanks.
