### ISSUE TITLE
Error by 'enableBrowserTooltips'

### ISSUE THREAD

**Issue by ps04639** [ag-grid/ag-grid#7380] opened 2023-12-22 17:02 UTC
![image](https://github.com/ag-grid/ag-grid/assets/12322078/9fac09c2-f7dc-4146-b7e5-052d5dcf0420)

![image](https://github.com/ag-grid/ag-grid/assets/12322078/da8ecf17-de21-4bbe-a067-5fc4c86550ec)

Any idea about this error ?

**Comment by AG-Zoheil** [comment] 2024-01-02 09:05
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by ernestbies** [comment] 2024-01-04 08:37
Hi @ps04639,

I had exactly the same problem. In my case, it was because a falsy value was being passed to the filter model in my _useEffect_.

Example:
```
const filterModel = {
    status: { type: 'equals', filter: variable },
};
gridApi.setFilterModel(filterModel);
```
Make sure that **variable** is not a falsy value.

**Comment by AG-Zoheil** [comment] 2024-01-29 11:19
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-01-29 11:19 UTC
Labels: waiting-for-repro
