### ISSUE TITLE
Shift + click when `enableCellTextSelection=true` and with cellRenderer does not behave as expected

### ISSUE THREAD

**Issue by zerismo** [ag-grid/ag-grid#4069] opened 2020-09-16 17:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Shift + click doesn't do anything for the selection of text when `enableCellTextSelection` is set to true when cellRenderers are present. You have to manually drag and select text.

https://plnkr.co/edit/uEwkh2Oo7rYQwQd9

**Expected behavior**
Should use the default behavior of the browser of selecting text till the point of click when the shift key is pressed. It works fine when cellRenderers are not present.

https://plnkr.co/edit/Vkt3e1rUSwSStYdt

**Please tell us about your environment:** MacOS Catalina

* **ag-Grid version:** 24.0.0

* **Browser:** Chrome/85.0.4183.102

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gportela85** [comment] 2020-09-17 13:07
The problem is not related to having a cell renderer. The shift click works on enterprise but it doesn't work on the community version.

Thanks for reporting, it will be fixed in the next release.

**Closed by gportela85** 2020-09-17 13:07 UTC
