### ISSUE TITLE
from 27.0.0 to 27.0.1: Sass error: The 'min' sass function clashes with the css 'min' function 

### ISSUE THREAD

**Issue by boltex** [ag-grid/ag-grid#4925] opened 2022-02-18 04:48 UTC
**Since 27.0.1** At this position in the base-theme, the usage of the 'min' function is problematic when sass compiles:

` ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: var(--ag-theme-row-height, 26px) is not a number.
`
**From this line in your repository :** 

https://github.com/ag-grid/ag-grid/blob/6a596b8bc5e1b7f7202dce89ecab0e2738d59812/community-modules/core/src/styles/ag-theme-base/sass/parts/_grid-layout.scss#L146

**Comment by dscheerens** [comment] 2022-02-18 08:14
Also getting the same error when upgrading to 27.0.1. This error can easily be reproduced as following:

```scss
@import 'ag-grid-community/dist/styles/ag-grid.scss';
@import 'ag-grid-community/dist/styles/ag-theme-alpine/sass/_ag-theme-alpine-mixin.scss';

.ag-theme-custom {
  @include ag-theme-alpine();
}
```

This was tested using the Angular CLI (v12.2.3)

**Comment by makinggoodsoftware** [comment] 2022-02-18 16:42
Hi guys,

Looking at this issue on our end, but we are not sure how to reproduce this, we looked at our examples and it all seems to be working fine, would you mind seeing if you can provide us with a reproducible scenario?

Thanks

**Comment by boltex** [comment] 2022-02-18 16:50
@makinggoodsoftware @kiril-matev   What version of sass do you use that doesn't clash with the 'min' function? i've tried with the latest sass 1.49.

Problem is 'min' is a function recognized by sass that uses numbers. but in your code, it's meant to be handled by the css 'min' keyword that can handle units (px, etc.) That's why i'm tempted to ask you what version of sass you're using to compile. 

(a Fix for you would be to use 'Min' with a capital first letter that sass doesn't recognize it, but gets handled by CSS which is case-incensitive)

**Comment by boltex** [comment] 2022-02-18 21:51
@dscheerens indeed many programmers (me included) also cannot use angular 13 because  it's not a LTS version. (company policy)

**Comment by gportela85** [comment] 2022-02-19 22:17
@dscheerens @boltex Maybe you can't upgrade Angular, but could update SASS only? In any case, I have pushed a quick fix for the issue here: https://github.com/ag-grid/ag-grid/commit/c2562eed673e0481a637d7f3642622d520c3ca43

**Comment by boltex** [comment] 2022-02-19 22:35
@gportela85 As I mentionned above, I tried the latest version, 1.49, and an older version... so  I don't know what you refer to as "update SASS only"? Do you mean regress instead of update? ...to a much older version of SASS which does not consider the 'Min' function...? 

Anyways, thanks for implementing a quick fix in as I have proposed. Hope it will be considered by the aggrid team soon.

**Comment by kiril-matev** [comment] 2022-02-19 23:13
Hello @boltex !
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6417 [Regression] When using older versions of SASS, theme compilation returns a SCSS compile error**
 
This should be fixed in the next release.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-03-10 16:11
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-03-10 16:11 UTC
Labels: ag-grid engaged, ag-6417

**Comment by mleimer** [comment] 2022-03-11 10:43
@makinggoodsoftware I am unable to search for AG-6417 in https://www.ag-grid.com/ag-grid-pipeline/ or https://www.ag-grid.com/ag-grid-changelog/ 
I can find AG-6416 and many other issues.
How to find AG-6417 in either lists?

**Comment by dularion** [comment] 2022-03-18 20:07
One possible fix would be to name "min" to "Min" instead, according to this thread https://github.com/sass/sass/issues/2849

**Comment by dularion** [comment] 2022-03-22 20:48
@kiril-matev  I cannot confirm this unfortunately, or maybe I am doing something wrong? 

package.json: 
```js
  "dependencies": {
    "@ag-grid-enterprise/all-modules": "^27.1.0"
```

app.ts:
```js
import '@ag-grid-enterprise/all-modules/dist/styles/ag-grid.css';
import '@ag-grid-enterprise/all-modules/dist/styles/ag-theme-alpine.css';
```

error: 
`SassError: "var(--ag-row-height, 40px)" is not a number for 'min'`

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/936076/159572800-c4e22feb-cbc6-47e9-a9c9-2968923c45dc.png">


I made sure to check the package.json included in ag-grid and its correctly using version 27.1 

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/936076/159573034-51afcb20-7696-4e16-87cd-a9aa6d380ccf.png">



**Possibly important info:** We have an enterprise licence, and I cannot reproduce the issue with community. Is it maybe fixed in community but not enterprise?

**Comment by kiril-matev** [comment] 2022-03-23 09:35
Hello @dularion,

Thanks for reaching out.

Following the bug submission template, please provide a sample project which reproduces this issue.

Also, if you're an AG Grid Enterprise license holder, please submit a support case with us.

We're keen to work with you to resolve any remaining issues.

**Comment by dularion** [comment] 2022-03-23 10:36
Thanks, I will get in touch with your support team in that case.

**Comment by bkopchains** [comment] 2022-03-28 14:40
Using React and AG Grid 27.1 here and had the same issue. I was running `"node-sass": "4.14.1"` and `"sass-loader": "8.0.2"`, and was able to get a workaround for the issue by swapping out node-sass for dart sass (`"sass": "1.49.9"` and `"sass-loader": "10.2.1"`)

**Comment by dularion** [comment] 2022-03-31 07:35
@bkopchains  yep thats the solution, node-sass is deprecated and needs to be switched out. For us, this worked pretty well and without big issues :) 
Thanks! and also thanks at aggrid support team, who pointed us in the same direction with this article: https://ag-grid.zendesk.com/hc/en-us/articles/4701639296029

**Comment by Vacarov** [comment] 2023-07-14 08:55
> Using React and AG Grid 27.1 here and had the same issue. I was running `"node-sass": "4.14.1"` and `"sass-loader": "8.0.2"`, and was able to get a workaround for the issue by swapping out node-sass for dart sass (`"sass": "1.49.9"` and `"sass-loader": "10.2.1"`)

I have exactly the same libraries and versions as you. I will try to switch to dart sass. Thank you!
