### ISSUE TITLE
cell editor getPopupPosition return value ("under") is ignored

### ISSUE THREAD

**Issue by nmz787-intel** [ag-grid/ag-grid#5158] opened 2022-05-12 02:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
here's a plnkr with `getPopupPosition` added into `CountryCellRenderer`

https://plnkr.co/edit/qunvVxjBcxIyATZl?open=main.js&preview

**Current behavior**
cell editor `getPopupPosition` return value (`"under"`) is ignored

**Expected behavior**
popup should be under the cell, as when you specify `cellEditorPopupPosition:'under'` in the column defs

**Please tell us about your environment:**
Chrome

* **AG Grid version:** X.X.X
exists in latest, and in HEAD

* **Browser:**
Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JS

here's the bad spot in ag-grid code:
https://github.com/ag-grid/ag-grid/blob/7f7ca5f17803f0ea6bf4aed219f079965ec71e15/community-modules/core/src/ts/rendering/cell/cellComp.ts#L477

here's the fix:
```
         var positionToUse = position != null ? position : cellEditor.getPopupPosition ? cellEditor.getPopupPosition() : 'over';
+        position = positionToUse;
```

**Comment by makinggoodsoftware** [comment] 2022-05-12 10:07
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by nmz787-intel** [comment] 2022-05-13 20:56
I am new to plnkr and I think I over-wrote the example I previously posted. I can't figure out if I can undo it, sorry.

**Comment by shuheb** [comment] 2022-05-16 13:04
Hi @nmz787-intel,

It seems your plunkr has some issues that are not related to the bug, if you open the developer console and edit on the Country column, you will see the following error:

```
main.js:129 Uncaught TypeError: children.split is not a function
```

Please fix this before sending us the reproducible scenario for your issue.

I've tried to reproduce the issue based on the documentation example, and it seems to be working in our end, please see the [following sample](https://plnkr.co/edit/aaPmjxsFMdfEbcu1?open=main.js).

You can see that we are returning `under` in the Custom Editor Component:

```
  getPopupPosition(params) {
    console.log('returning under...')
    return 'under'
  }
```

As this is not reproducible in our end, I will close this ticket - if you are able to reproduce the issue in a sample, please reply below and we'll investigate it again.

Thanks!

**Comment by nmz787-intel** [comment] 2022-05-16 15:48
yes I re-used that plnkr for another issue, but it didn't fork it, rather it overwrote it.

**Comment by nmz787-intel** [comment] 2022-05-16 17:30
I updated your example, and changed to the version of ag-grid I was using, 26.2.0, and it is failing as I experienced
https://plnkr.co/edit/nYvwQ7Yapz38YZq3?open=main.js

**Comment by shuheb** [comment] 2022-05-17 15:12
Thanks, we're having another look at this.

**Comment by kiril-matev** [comment] 2022-05-20 21:51
Hello @nmz787-intel!

This issue was resolved in AG Grid v27.0 as part of:
**AG-6064 [Regression] When cell editor popup is used it cannot be displayed under the edited cell (because getPopupPosition return value is ignored by editors)**

Please upgrade to AG Grid v27.0 or later to resolve.

Thank you for reporting this.

**Comment by nmz787-intel** [comment] 2022-05-20 21:57
I'll just stick with the version I have, since I've got other local hacks already like this:
https://github.com/ag-grid/ag-grid/issues/5128

**Comment by makinggoodsoftware** [comment] 2022-05-26 11:29
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-05-26 11:29 UTC
Labels: in_zendesk
