### ISSUE TITLE
node_modules/ag-grid-community/dist/styles/ag-grid.css?ngGlobalStyle  Error: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by rkromesh** [ag-grid/ag-grid#6198] opened 2023-02-21 09:49 UTC
Hi Team,

Migrating ag-grid from 24 version to 28 version and getting below error:
![Ag-grid-Angular_Migration from 24 to 28 version](https://user-images.githubusercontent.com/59644995/220309539-0e9e0026-c17d-4c4c-ae51-64f28c1011f0.jpg)

./node_modules/ag-grid-community/dist/styles/ag-grid.css?ngGlobalStyle:6:72 - Error: Module parse failed: Unexpected token (6:72)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  ****************************
| */
> ag-grid, ag-grid-angular, ag-grid-ng2, ag-grid-polymer, ag-grid-aurelia {
|   display: block;
| }

./node_modules/ag-grid-community/dist/styles/ag-theme-alpine.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-theme-alpine {
|   -webkit-font-smoothing: antialiased;
|   color: #181d1f;

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Package.json 

"dependencies": {
"@angular/animations": "^15.0.4",
"@angular/cdk": "^15.0.3",
"@angular/common": "^15.0.4",
"@angular/compiler": "^15.0.4",
"@angular/core": "^15.0.4",
"@angular/flex-layout": "^14.0.0-beta.40",
"@angular/forms": "^15.0.4",
"@angular/localize": "^15.0.4",
"@angular/material": "^15.0.3",
"@angular/platform-browser": "^15.0.4",
"@angular/platform-browser-dynamic": "^15.0.4",
"@angular/router": "^15.0.4",
"@ngrx/effects": "^12.0.0",
"@ngrx/store": "^12.0.0",
"@ngx-translate/core": "^13.0.0",
"@ngx-translate/http-loader": "^6.0.0",
"@ruf/fis-ux-assets": "^4.25.0",
"@ruf/material": "^16.3.0",
"@ruf/moment-adapter": "^2.0.0",
"@ruf/ngx-datatable": "^6.0.0",
"@ruf/pipes": "^1.0.0-rc.0",
"@ruf/prebuilt-themes": "5.9.1",
"@ruf/query-builder": "^4.0.0",
"@ruf/shell": "5.9.1",
"@ruf/theming": "5.9.1",
"@ruf/widgets": "^18.2.1",
"@swimlane/ngx-charts": "^20.1.0",
"ag-grid-angular": "^28.0.0",
"ag-grid-community": "^28.0.0",
"ag-grid-enterprise": "^28.0.0",
"css-loader": "^6.7.3",
"highcharts": "^9.3.3",
"lodash": "^4.17.21",
"moment": "^2.29.1",
"ngx-cookie-service": "^12.0.0",
"rxjs": "^7.4.0",
"sass-loader": "^13.2.0",
"style-loader": "^3.3.1",
"tslib": "^2.0.0",
"underscore": "^1.13.1",
"webpack-cli": "^5.0.1",
"webpack-dev-server": "^4.11.1",
"zone.js": "~0.11.4"
},
"devDependencies": {
"@angular-devkit/build-angular": "^15.0.4",
"@angular-devkit/core": "^15.0.4",
"@angular/cli": "^15.0.4",
"@angular/compiler-cli": "^15.0.4",
"@nrwl/schematics": "^8.12.11",
"@ruf/build-ruf": "^3.2.0",
"@ruf/schematics": "~5.9.0",
"@types/jasmine": "~3.6.0",
"@types/jest": "^29.2.5",
"@types/node": "^12.11.1",
"@types/underscore": "^1.11.3",
"codelyzer": "^6.0.0",
"eslint": "^7.29.0",
"eslint-config-standard": "^16.0.3",
"eslint-plugin-import": "^2.23.4",
"eslint-plugin-node": "^11.1.0",
"eslint-plugin-promise": "^5.1.0",
"eslint-plugin-standard": "^5.0.0",
"jasmine-core": "~3.6.0",
"jasmine-spec-reporter": "~5.0.0",
"karma": "~5.1.0",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage": "~2.0.3",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "^1.5.0",
"protractor": "~7.0.0",
"ts-node": "~8.3.0",
"tslint": "~6.1.0",
"typescript": "~4.8.4"
},

Thanks
Ramesh

**Comment by StephenCooper** [comment] 2023-02-22 15:58
It looks like you are using our old styles and need to follow the upgrade instructions for v28.

https://ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28/

Please try that in the first instance.

**Comment by rkromesh** [comment] 2023-02-23 06:50
![Ag-grid-Angular_Migration from 24 to 29 version](https://user-images.githubusercontent.com/59644995/220837438-2f08f2a4-c0b5-41dd-bb3a-4758c0a1ec9e.jpg)
![Ag-grid-Angular_Migration from 24 to 29 version_Failed](https://user-images.githubusercontent.com/59644995/220837459-a5dedfc4-bf9f-4740-999d-f63d95f4ec5a.jpg)


Hi Team,

Attached screen shot my current code-snaphost. 

./node_modules/ag-grid-community/styles/ag-grid.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-icon {
|   font-family: var(--ag-icon-font-family);
|   font-size: var(--ag-icon-size);

./node_modules/ag-grid-community/styles/ag-theme-alpine.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @font-face {
|   font-family: "agGridAlpine";
|   src: url(data:font/woff2;charset=utf-8;base64,d09GMgABAAAAABIkAAsAAAAAJkAAABHTAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIkABmAAiyoKp0ygSgE2AiQDgjALgRoABCAFhEYHhRwbXyFFIbBxAJDYv7AiqieV7P96QZO4Gu9qEMLAgorXqyjcVJKxQxvbtQieEq6u3unbTP3JwOa8v9MeN5Q8Caix/+09wyXRVJ6IfU2IWoiiiWgSIp5JhMSQaX44l/dN+kSUcPER5OzkhHT7gd9m7/PN/wkLMCowCmy8M+qHlXA73abzZiEb3DVcFEavrFyzTvMyXLeieOl4CQlIYbBNxUopM8Nip4zZ0vd82bEQmAQkTsiVYMv9DdPoIJ9DCT5BRcD/P/dqmWTV4A1khZ6f04HXNve+mwJnKdEvp5wBsgWC/5ues98OENRmp4Dl3IQnoXcm1Jydm/+MzfZ0da0rjEJkDPufQ66CYNqwBz9fhdkubhpvRgCmW3MZ9WZ/0uxT+y+dsRzmrRhA3DGcOn50v6mbLFgQE4TvcWyxpK4fl3wNVrgUXkcWRp2jpdEz0efRd9H/kLC2pYAY6p8bw1GEICmaIYgthlYsNmTaHE5dVpnJdT5rWQJjpIs2p6m7ldKIo45RDyqaUsSD6yDj7q/uKinhvdMmTBLlEbCopjVbTsRV0kGei7DXN54VtteylXaUdDSPaa+Ac+UhaYEJNa52HUV2kA3cQVq+tcAxp7Qg6+K2mETrApdi6y3eLMI7dcZFkraCSQ6fzNip7qiKcLCVq+hvOa+AcXspHXiIvvxUcX3a1wHrxZzkxYFOPnjf2Xg8Ude1oja/f90i7i5lKbx40E0ta2DETVJc1dUZ9731xTff/fQfAlOFFHn4ADa/ImNPzMrDspK+zTTH3fmko4S0xESEddPEKWoamIMWga2TmJgoWgsM4TRYdzRdSNbprCHLhgWnnE8zmBjTQzBCwjSHsNniQK3NttnmW3czBzI2JyyqamyrrpUbo0ujalAu3kWxjDzTJqyQU1wXgKVTps2ZdOequYYwYi9NleshqbVeXtI50VQwtbP69rfCNLch55ioujFqKGxo4mYj7c/yesxOmNzAPsTNyMw+pNzaEJRX6LjuTpooygim0BCQROxcCPpaO1xHDSO5mK5Y5GG4Lw4iNyIfcJu9+/DD5sAAEWaUd0mjRxqHfLH+F0FXsSNWFX9FGg/mYsDpOQqsA2IgMl1cHmJQWLcOEuU9GOwfM4UZsIU/59z49b95g/V+nXThF1LJnhHE/dZ1QxxYnrlTMF9xt6IhJF+RyJoCJwPOOJecvbaewIBgpuDiQsMiomLiEpJS0jKyctRai0rKKvhFWFPX0NTS1tHV0zcwNDI2MTUzt7C00ra2sQUhwRvONbatFefI79QbbmnxpFVf//15cb7l9tcep/1MQPQxGvpYv1cOfT/YVuAAq+AgKwCHWB2HWRI4wro4yrYBx1gJOM7SwElWxilWBE6zBs6wLHCWZYBzrIULbDtwkeWBSywFXGZNXGEdXGU54Bqr4jpr48bAHr+AvkSAEAVCDAhxICSAkARCChBSgZAGhHQgZAAhEwhZQMgGQg4QcoGQB4R8IBQAoRAIRUAoBkIJEEqBUAaEciBUAKESCFVAqAZCDRBqgVAHhHogNAChEQhNQGgGQgsQWoHQBoR2IHQAoRMIXUDoBkIP1K7TC/SmDwj9AEiyyBPxCDeJ32Jq/L5SuCTQgA+9YgrDr0OwVUVexYVeyFNcwF0FuoE0V1IcHYu52gT+0kXBK4nr6el0CcZlMiPM9IKDQY100KueobGOYYxqXmE2bizVAIvs3nqFKcc2YSnyk3Q66OkY8nTCVJah4UHTi65clskzVJytzLmz0OWG+nq6ehZcVgN2CUBdufG7YapTyZhAEsBCmDTFKiHIKIpeKyIJIV1OElQuSUcvo0RIF3kpyKIZOErmSCplKmKxYhTkUoyaXolRUsvfwaJMisimqRySziJkuA5G4YBJcQYmM1KdmYYUM2dxY/X5OURfOXuuSUKTUvLpEAvZCEemZ6S/uQf1kkyysiqfJsnvzYbNx8FV9QKi9O3ylLF1OaUYAy/Yp+PoaciqKjvhIGOqrgDDdVlkUKq4irNkPegq57Eipi6rWqrHMyGppKQSWtZGLfNK70FU8OU882IMadJnkR3cThwvKld0DA9jqsHRrq4+RLltSour902A71VtvK5RTDUNekfUY1bt7WoNqRjfi6lc227klPfOTg2uHkOUXYO8wdFJ5dTYMHeMdJ7lvq1LNQw0Gq7LDq7m3YIm6XY+omzVKGDi++/FrjYexeNdwt5ZLWnrH9vFXdPkSZeWFIuLquVlRBlPESMzkDpP5coKrg4uU+0dV0zsU2unlJP7a1RXiPGinJeSBe19ozvNZNkEOtaEyqyS9jSDpjpmVw7h6hELkuYPSG6xBbgTpKbTru2qQR7Vtr63Y6pRRLleIs0iyOpsEbnSrrMmuWbTi1HRUdmL2OLyMsXjz62Qexf9l2YprqazKVG6XCaisrR9qPEmV+jlrFDVq1cCY3GRkEovXwl+GbHYL4PilZUK5dJH8W1lBBAohXBqSMhB6HqKziZICc7AaAzByf2crEsnlgETqQA2kueLAAWoywPhAIuVlpBEliUohuuZSWdXVuVQrALl8ct4Rd4KNSy9dAwh50x3FRjg6otHl45cwKC2tRbjYChuC/a1mVROBRNh1eyBjmFtHkr5EgPF4fqz4DIWA0NuMjCZ0evIPq2gIKUKZLbn3UsbKSKaJkmCEpH0DMysVEbyRHQf/XxVHlquUi0LpQeXQFFpDBnWd0l1wRqbBwGcc2OqRxTDqlHl2Bq2Lg4sBJdS/Hb/VZgS70mk+/zGIof4Ve7j7ntDCK7GYov3eJgzRQirt5t1cC2IU4IT7lX8MbtuR0uaq8E1/CErSrZracnmx9yexUXBH+W7l5dtfyroX1kJ/buMrbNE71mwW6lRcHuvBrsgUrPXE+QZryHAuK83Dzja7GToaa8xu3UKBxyhFu1xhFaprlgTOIJXAG7bNx9Svh0TAE6fwgBvnA5l8HzFV3wlrzKbVDSoS1RTo/aeqieNT83co86TR95gAusmS1J/b6/lALsa18FKLKl5ZVWFVFIgvSxS8j0JXcLNbCTmGDUaxEjQuyjIOr+CrPdPYCS+gTyzCFdPP+XcZTcSyJ0tp8H3b5+HomdemfChsI0ZbXD9VUCKUO2xrGivk03b1tZH07k08kT6JVFe0Z5h8EHX6uoL4sX/q6Op8AJ28Zq60rDikJDisNK/WtobLw4pDfsrJ33yOzXfF3QiVRNeBVhVsOSBcu0z+XN5Q4O8UQ6h361itj7ztmfxvI8t3h8HJ4zLTUs7fWrHjrR0setzL+9ab356MzZX5T+wXugerh8dGOgqL2cwoqNO17WdPnV6Knp8/IvrpIUjJIKjBXHjCwi88rwuqG5XazcytQ0Hn8Ya4Nf7hM3Y0F+fnSN4oYceOoGjmBA/bM0+7whOYkdwZCWOYicot13nxefhQXBuXlxcXsorGUos0XKdE4TM/y+t2rhemTCDuEndAtwkbiH7/2vip3NXrP5uaPoMWTRwjzH6CVk/sMz80mbezEga8Lw/get4YiNqyo90NTHsYzVHvRfE4c8F2u+vsqdpi03s3mm2hTmXZ8M+99AE/4Ld8k7tDaYxZcIe4D8K2Qq+Zn/xTFp1Grn9rDUR6X/amrAM84fjeLztp0x6Ir/w3O+hNfcEbjPekIrpmgsWzNe1c/YWmQde9DXA+k3qYIIZvOlQyErOpYXYGI8gMiCQlHQMGSg5fgAZJIwpayqqdyuwD8prEtdABgS52gykWJ7tCe4+G7yvO7hnH4q4NWY0prsWXWnk288F2nai4hAIjB+a0FQZmac3fzq36e13v6h5myfiGDs+icwT5fVdJU4YcPyYxqlpNTlNh743+cLczDyY3kQ1B3+ia8Cx55hArTZ0ZoXdfv5eHv62C1qxmHQvobrj61usMzw8Q+ILj13UVhUGVlPQnVDfbJUREZ6SVllqcCE+O8AiprRcEZKclew00hfslezhkeQVjOmXNAblxB7FRJBYnBbhlG8eUyZR8wWg5uIt/aQ732hfdUVpuUWM+pgR/1hl1Ld0x080OZ+HdbKVVUb4x92e2qSWdhoZGhAy2+aSnv3a3FUjmsoS/jS73ur58Sd4LDh8qHB0MJZzD4iHBNj02HKhtlUkF+1vDRcVKMwPI1quwUudMEwYqhUFilp3yUXyWSqUP2sNrJMNojBR67Mk7CothruzDWLjsqXAxPbF6urI5MHIc+kVtj5wspx1GswYDC8JDS3e0NKG8FRPTrOWTiMe6UR6w45FMSR6VgkvqXMDlqmC1E9dHj+WJHoeEknyogSpgrmUzML6dNb1kJKMoCuVvMMuYWNj7q8IEhuLIL/qL5g+IvJ+8fQLBF4NrxPWyetE+/WFdSDc5S4fMr18lgX4OT6jr7yhR8JC4R+bu6HaE3leH0VT5dXtSg8OFHineqWkeKV6F4RLnbbMz1s6SVNNkRZe1hsEfFA9ufgq89WJKUdw7N5TMrMkGX/i9IkjXnzBreRuQj4gJyBT/s03BpYR6erTXavvlpd+PRwltP3BxiZl119JSdJKXR1z54iMU+9qNH//rf3nS7+vZuWPuruLNphgFhYbK3j69cbfa+q/w/9Y5t9bWIAA05HaBA+PBH3UujT9kP5QG8wCzd/D5hfhobd1bxk4BJkY3HpywZhjEuRwV7aP3aEliBxC+2mtu0dSomfde59qk/eI0HbeFfC+XTIMsUnSb93UchDe0pFvFj4VpGzUgeIWkeiArLUFUe7bhjEd/nXr5kOtteJNm2Hi3ugrqjHy6tXoul+VFLrmuqhULrmuhRda2ukq1X3Vha4XOO71Kj5cWxiSJxDkhRT+lFJuPE9QGPJTris8uJWwIS5uw6chRdqn4V8X/6yZcrv42JGXsqSZUAz/rF493qxzp0XTYbeEgUL4p4udVqXgMYeeEtiQ+k/WP6mc81tj+eRJXFxEuK1tbCxoY+uK6+DehFlmdIWSVAjHj88iBzwkoetChLAsKtxmvsR9R2FOjoG4WqloF78TEz7fbsdhJe4BSdoRG4qLkpMHB4P27oPWzW/evN78B3jNGLdRnzcvKgS9NQQAABqnMk0jSSTYabMJrYTmkyqPplkCqkAPa1/HKABvXqLr0JvOcv3oz7rGQ4qKrtaZzPRqxD8ht3UfTJSX0rUMxkm37g16DV2FNloTqmhXqNAnVVf4FzUaUg5a02WzFZVBm6wJZFOaMFPRasShjG5pLYCiLJlXie5ATZvW4x19sim9+l+py4OFtD12JZyoRwY4ugqA5Bv+fUjhjE9/oQEwflXQYVi0KpjY78hJv0woYmXN2R96//v7AiGM+n53VSkGzJ0P4PfzQiM45QhEgscGA/Q3HICGuil8dQLtmC7g4AV6vMAQwNZ6HE6NgymsBRQQHUNAwBwULmMAGzoAReAg6CDwENMFHiyDHgJvFmBA/W8g46vh4Irkd0b4kuheUomE3xiGZCU7Qfwm/1FqZDKPGzYVXd0XEopVdKZbTB3Dk6o3XjibT6ZxSSmxKcI/CNr2quX5fuMR95pb4LxhBV9E5LxIioigb7jZfYPEEonJcoz/cA0V7xsjxqPWg6Tvl8KUJkBhdYzOcrRXo+CJ+oZn9i7Bcig+tSqSkHzge1H4rh8IXLPVK4jyf6dUM/OyZgu0cNsVjGqSXt/9sAUKBg4BCQXqTwSAL/Dq1/P/n5OUyebyhWKpXKnW6o1mq93p9vqD4Wg8mc7mi+VqvdkSyriQSlu243p+pVqrN5qtdqfb6w/kWsexg2CwGpn27AhPddse2IMgwLQLlxW9WK0Rfjuem6AY3V3mDJEcKkqOZBWvinIGkrKfQCeWpsREqOzfwyFTPYImFQuKbge6LLswXOs2nHEbXt1xWWEXv7q1g5VRrHaP7hB/bGqytd8OS/d8pRq13d1Vqu6EiWX3LOWh7JRqyppe91JRw2e5n9q6SOEgxxxzXHEnJw2PiKJzpZx1h5rwmFobmxJP6HaLhnPE7VK0W2pkPSiDY+ShXsiF3g433aDK1LD355neaFcq9LpTY8Sjej80NI4nipQ20THUKnRwJ3cYdGQ2cqWCSKQ4zLblgnQwPEN5LptWIJCKGJlUIOn96swaJxsUi5G3rg0A);



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**### _Package.json_** 
 "ag-grid-angular": "^29.0.0",
    "ag-grid-community": "^29.0.0",
    "ag-grid-enterprise": "^29.0.0",



Thanks
Ramesh

**Comment by StephenCooper** [comment] 2023-02-23 09:03
Can you please provide a reproducible example for us, otherwise we are not going to be able to help you very well. I would try creating a new app with Angular 15 and testing just putting AG Grid into that. I would expect that to work as have tested that. 

You code looks fine, so potentially its a stale set of node_modules, could try deleting those and doing a fresh install as another alternative?

**Comment by rkromesh** [comment] 2023-02-23 09:24
Hi Stephen Cooper,

This is working condition  upto Angular 14(Ag-grid-angular: "^24.0.0") But its not working under below package.json file configuration.

Package.json :

"dependencies": {
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.3",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "^15.0.4",
    "@angular/localize": "^15.0.4",
    "@angular/material": "^15.0.3",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@ngrx/effects": "^12.0.0",
    "@ngrx/store": "^12.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ruf/fis-ux-assets": "^4.25.0",
    "@ruf/material": "^16.3.0",
    "@ruf/moment-adapter": "^2.0.0",
    "@ruf/ngx-datatable": "^6.0.0",
    "@ruf/pipes": "^1.0.0-rc.0",
    "@ruf/prebuilt-themes": "5.9.1",
    "@ruf/query-builder": "^4.0.0",
    "@ruf/shell": "5.9.1",
    "@ruf/theming": "5.9.1",
    "@ruf/widgets": "^18.2.1",
    "@swimlane/ngx-charts": "^20.1.0",
    "ag-grid-angular": "^29.0.0",
    "ag-grid-community": "^29.0.0",
    "ag-grid-enterprise": "^29.0.0",
    "css-loader": "^6.7.3",
    "highcharts": "^9.3.3",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "ngx-cookie-service": "^15.0.0",
    "rxjs": "^7.4.0",
    "tslib": "^2.0.0",
    "underscore": "^1.13.1",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.11.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.4",
    "@angular-devkit/core": "^15.0.4",
    "@angular/cli": "^15.0.4",
    "@angular/compiler-cli": "^15.0.4",
    "@nrwl/schematics": "^8.12.11",
    "@ruf/build-ruf": "^3.2.0",
    "@ruf/schematics": "~5.9.0",
    "@types/jasmine": "~3.6.0",
    "@types/jest": "^29.2.5",
    "@types/node": "^18.14.0",
    "@types/underscore": "^1.11.3",
    "codelyzer": "^6.0.0",
    "eslint": "^7.29.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-standard": "^5.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.0",
    "typescript": "~4.8.4"
  },

**Comment by StephenCooper** [comment] 2023-03-21 11:02
I am going to close this as there is no code reproduction for us to investigate this further.

**Closed by StephenCooper** 2023-03-21 11:02 UTC
Labels: waiting-for-repro

**Comment by rkromesh** [comment] 2023-07-19 05:55
Hi , it is existed.

Attached demo example code.

**Comment by rkromesh** [comment] 2023-07-19 05:55
[tsconfig.zip](https://github.com/ag-grid/ag-grid/files/12091547/tsconfig.zip)

**Comment by Shawkurr** [comment] 2023-12-20 18:35
"this is what it gives me" yah well i dont know so post more code or ill close the thread.... 
dude if u dont know, just say that.

**Comment by Shawkurr** [comment] 2023-12-20 18:39
also i love how @StephenCooper is like, heres a link for upgrading 
link says: upgrade it. 

gee thanks man.

**Comment by Jaydeep28** [comment] 2024-01-10 07:21
@rkromesh - Did it resolve for you?

**Comment by rkromesh** [comment] 2024-01-25 06:47
No its not resolved .


Thanks
Ramesh

**Comment by sirPhoebus** [comment] 2024-01-30 11:27
same issue with 
    "ag-grid-community": "~31.0.3",
    "ag-grid-angular": "~31.0.3",
    "ag-grid-enterprise": "~31.0.3"

./node_modules/ag-grid-community/styles/ag-grid.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-icon {
|   font-family: var(--ag-icon-font-family);
|   font-weight: var(--ag-icon-font-weight);

./node_modules/ag-grid-community/styles/ag-theme-quartz.css:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @font-face {
|   font-family: "agGridQuartz";

**Comment by derfritz** [comment] 2024-02-20 04:36
Hi @rkromesh,

i was facing the same issue when upgrading to AG-Grid 31. What helped me was this comment in a related bugreport:

https://github.com/angular/angular-cli/issues/24948#issuecomment-1494790323

Somewhere in my code i was importing scss files like a module which caused then the build error.

HTH

Cheers
JF

**Comment by bazighaliminhas** [comment] 2024-03-01 10:26
hi everyone i am facing some error which is not be resolve i am simply applied ag-grid filter in my project but its 
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-quartz.css';
are giving me error i am beginer plz help me 
https://drive.google.com/file/d/1PhPir9FNUrrNJmzqfCMa1lTjcAbyah51/view?usp=drive_link

**Comment by sjmohideen** [comment] 2024-03-04 08:25
> hi everyone and @rkromesh , i am facing some error which is not be resolve i am simply applied ag-grid filter in my project but its gives me error import 'ag-grid-community/styles/ag-grid.css'; import 'ag-grid-community/styles/ag-theme-quartz.css'; import in component.ts file. I am beginer plz help me https://drive.google.com/file/d/1PhPir9FNUrrNJmzqfCMa1lTjcAbyah51/view?usp=drive_link

Hi ,  I was facing same issue i have done below changes after that it is started working.. I am not sure it is the correct solution but it is started working.

1. Navigate to your project Node Module
2. node_modules/ag-grid-community/styles/
3. Open ag-grid.css  in nodepad+ editor
4. ctrl+a (select all the code content and delete) then save with empty file 
5. stop your angular project service(ctrl+c) comment the restart( ng service)
6.Now your application should start.. If your getting any other file same above step.. It should work properly.. I am not sure this is the correct way of doing.

**Comment by dharmeshsamritkar** [comment] 2024-03-06 16:14
Hi Everyone and @rkromesh, I am still facing same issue which you put in closed state, I am using 31 version of ag-grid in angular but getting css related issues ./node_modules/ag-grid-community/styles/ag-grid.css:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-icon {
|   font-family: var(--ag-icon-font-family);
|   font-weight: var(--ag-icon-font-weight);
 Please someone look into this, as i am stuck, I am using angular version 16.2.11 and  "@angular/animations": "^16.2.11" also same

**Comment by Amresh5824** [comment] 2025-01-30 14:19
Any updates on this? Getting this error on "ag-grid-react": "^33.0.4",:

```
You may need an additional loader to handle the result of these loaders.
|       return;
|     }
>     compGui?.parentElement?.removeChild(compGui);
|     context.destroyBean(comp);
|     if (ref) {
```

**Comment by kanikarthi7** [comment] 2025-02-14 09:52
HI @StephenCooper 

**node_modules/ag-grid-community/dist/styles/ag-grid.css?ngGlobalStyle Error: Module parse failed: Unexpected token**

am facing this issue while upgrading angular v14 to v15 ,, please give me solution ..
Thanks
