### ISSUE TITLE
When use react custom filter component, and pass the react ref object as filterParams, ref.current is not update

### ISSUE THREAD

**Issue by luox12** [ag-grid/ag-grid#4504] opened 2021-06-02 02:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

https://plnkr.co/edit/ylvjYolbGcWx5DQ6

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

when i changed ref.current outside, inside custom filter component the ref.current is still old value.
in 23.x version, it is work perfectly

**Expected behavior**

inside custom filter component the ref.current must update

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment] 2021-06-04 16:08
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2021-06-11 13:14
Hi @luox12!

Thank you for providing context to your issue.

This is expected behaviour because `filterParams` is only set once by the Grid when the Grid is first rendered, so if you are passing a reference inside the `filterParams` that gets updated, it will not update as you expect, only the initial value will be available.

Based on your example, I would recommend using the [React Context API](https://reactjs.org/docs/hooks-reference.html#usecontext) instead, as this will allow you to get the latest value, please see this example which showcases this: https://plnkr.co/edit/JdbPM2qNC3rGmBop 

Also, we have a blog post covering using the Context API with React: https://blog.ag-grid.com/react-redux-trading-platform/

Note that we will be closing this ticket as it is not a bug.

Thanks.

**Closed by shuheb** 2021-06-11 13:14 UTC
Labels: in_zendesk

**Comment by luox12** [comment] 2021-06-16 01:18
Hi @shuheb 
Thank you for reply.
I'm agree with the grid will only get the initial filterParams, that is why i use React.Ref in my example, because the ref variable self is never changed, the changes happend on ref.current, so the custom filter component should read the latest ref.current reference, this is also the common scenario of the React.Ref, the result is seem to the filterParams is be deep cloned by grid, my example is run correctly before the version 24.0, so i think this is a bug or break change. please reconsider my statement and reopen this issue, thanks.
Your example is an alternative way.
