### ISSUE TITLE
Issue with column pinning

### ISSUE THREAD

**Issue by dfgkzhang** [ag-grid/ag-grid#5541] opened 2022-09-08 21:44 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://ag-grid.com/angular-data-grid/column-menu/#example-column-menu

**Current behavior**
If you toggle the pinned column (left/right), the header disappears.  This is reproducible through the ag-grid column menu example by pinning the 'Athlete' column left and then pinning it right.

**Expected behavior**
Should be able to pin columns and the header should render properly

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by StephenCooper** [comment] 2022-09-12 08:30
Thanks @dfgkzhang, we can reproduce this so will investigate further.

**Comment by kiril-matev** [comment] 2022-09-12 14:55
Hello @dfgkzhang!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7211 Column header appears blank when the column pinning direction is changed**

This issue will be fixed in our next release.

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed by kiril-matev** 2022-09-12 14:55 UTC
Labels: in_review
