### ISSUE TITLE
AG Grid Custom Tool Panel throws exception

### ISSUE THREAD

**Issue by Vishwas-93** [ag-grid/ag-grid#7740] opened 2024-03-14 03:15 UTC
I'm submitting a bug report

Customers of AG Grid

Requesting Community Support

**Providing a Reproducible Scenario**
Happens when dynamically trying to attach components on the fly to SideBarComp. The ToolPanelInstance is probably not initialized. We might need a null check before performing refresh(params) with an optional chaining.

const hasRefreshed = toolPanelWrapper.getToolPanelInstance().refresh(params);

<img width="704" alt="Screenshot 2024-03-13 at 10 10 22 PM" src="https://github.com/ag-grid/ag-grid/assets/25495706/2b4bd1ad-6ccc-45e0-81dc-8840b5a08699">

**Current behavior**
TypeError
Cannot read properties of undefined (reading 'refresh')

**Expected Behavior**
Attach custom components on the fly to SideBarComponent.

**- AG Grid version: 31.1.1**

**- Browser:**
      -All browsers

**- Language:**
      -TypeScript

**Comment by AG-Zoheil** [comment] 2024-03-14 09:27
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by himanshu-dev** [comment] 2024-03-19 07:35
I am also facing the same issue.

**Comment by barelyhuman** [comment] 2024-03-22 09:36
@AG-Zoheil Not sure if I can create a repro that emulates it every time but for now here's the things that happen. 
- Custom Sidebars that depend on Network Data and re-render cause the above issue where the instance of the siderbar is lost. 
- File `enterprise-modules/side-bar/src/sideBar/siderBarComp.ts` which invokes `getToolPanelInstance()` is returned with `undefined` because the above instance was lost, I'm still trying to figure out why the instance was lost but for now just adding a check on `getToolPanelInstance()` solves the problem. (hack but not sure that's the root cause)

Hope that helps, I'll post a repro once I can get it to crash every time.

**Comment by AG-Zoheil** [comment] 2024-05-20 11:03
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-05-20 11:03 UTC
Labels: waiting-for-repro

**Comment by michael-vasyliv** [comment] 2024-06-10 17:42
https://codesandbox.io/p/sandbox/custom-stats-forked-9nl9zt?file=%2Fsrc%2Findex.js

I've created a ticket in zendesk so should be fixed soon

**Comment by AG-Zoheil** [comment] 2024-06-13 11:24
Thanks @michael-vasyliv,

This will be fixed in the next version (`v32`) of our grid!
