### ISSUE TITLE
Floating Filter : changing text filter using a Backspace resets the cursor

### ISSUE THREAD

**Issue by amit-coditas** [ag-grid/ag-grid#1616] opened 2017-04-28 11:19 UTC
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In a scenario where the floating filters are enabled and the filter type is set to text, we try to edit the text in the textbox by using a delete/backspace key, this in turn resets the cursor to the end of the textbox 

**Expected behavior**
the cursor should not be reset to the end of the textbox

**Minimal reproduction of the problem with instructions**
On the demo grid page for floating filters, https://www.ag-grid.com/javascript-grid-floating-filter-component/?framework=react#gsc.tab=0 in the 'Complex example with JQuery' section, for the Country column, set type of filter to 'Contains' instead of 'Equals' and then type in 'Australia'. Which works fine. Now, move the cursor in between the word like 'Austra|lia' and press the delete or backspace key. you notice that the cursor is now pushed to the end of the word like 'Austrlia|'. 

**What is the motivation / use case for changing the behavior?**
Not a intuitive user experience to keep moving the cursor

**Please tell us about your environment:**

* **ag-Grid version:** 
Latest

* **Browser:**
Chrome Latest
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment] 2017-04-28 13:06
Hi

I've just tried this with OSX & Chrome but cannot reproduce it I'm afraid

**Comment by amit-coditas** [comment] 2017-04-28 13:12
I tried to record this behavior and upload a video. 
https://drive.google.com/file/d/0B_IZukOZf_Wlb3JiT200bGdtTnc/view

**Comment by amit-coditas** [comment] 2017-04-28 14:58
Please confirm if you see this and if you think it's a bug.

**Comment by makinggoodsoftware** [comment] 2017-05-02 08:44
Hi,

This is a bug, it will get fixed as part of this ticket AG-392, we still don't have a timeline for this, but it's in our backlog I would say is likely to be in the next or in two releases from now.

**Comment by makinggoodsoftware** [comment] 2017-12-07 12:07
This should be fixed now

**Closed by makinggoodsoftware** 2017-12-07 12:07 UTC
Labels: bug
