### ISSUE TITLE
Copy functionality works incorrect

### ISSUE THREAD

**Issue by vmartseniuk** [ag-grid/ag-grid#5671] opened 2022-10-11 11:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Hi, I would like to inform you about the broken behavior "Copy" logic. 
For "Master Detail" when provided defaultCsvExportParams property, "Copy functionality" starts to use "Export" logic, such as 'getCustomContentBelowRow' to build clipboard data.

**Current behavior**
Copying from the master row will also copy the whole data from the child.

**Expected behavior**
Copying from the master row will only current cell data to the clipboard.

**Plunker Reproduction**
https://plnkr.co/edit/ddjLxuCy4eZHMzzm?open=main.ts - Plunker example from the documentation, Import & Export > Excel Export > Master Detail.
Just copy data from the first parent cell (Nora Thomas) and paste it into the console.

**Please tell us about your environment:**

* **AG Grid version:**  28^
* **Browser:** any
* **Language:** all

**Comment by StephenCooper** [comment] 2022-10-12 09:18
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7376 Copy functionality works incorrect

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-10-13 08:57 UTC
Labels: AG-7376
