### ISSUE TITLE
Chrome 85 Update breaks the ag-grid ui and scroll in RTL

### ISSUE THREAD

**Issue by ahmadi3d** [ag-grid/ag-grid#4048] opened 2020-08-31 11:00 UTC
**Reporting critical bug in chrome +85.0 version**
After Chrome update 85+ the **AgGrid** scroll stops working correctly as it only scrolls the headers and not the content and in some cases even the content breaks and the cells become white.

-**This only happens when you update to Chrome +85**
-**I tested this with Ag-Grid 21.x and 23.x, this happens in both versions.**
-**Environment is reactjs**

Component settings while testing : 
```
enableRtl: true,
pagination: true,
enableCellTextSelection: true,
enableRangeSelection: true,
paginationAutoPageSize: true,
paginationPageSize: 17,
animateRows: true,
```
**Please note enableRtl must be true for you to see this bug**

By the way it seems about a year ago, something similar to this issue was posted and fixed in later versions, but it seems this bug is happening again after chrome update
this is the link to the mentioned issue : 
[https://github.com/ag-grid/ag-grid/issues/2914](https://github.com/ag-grid/ag-grid/issues/2914)

Thank you.  

**Update 1.0 (20200831):** 
I just found out that if you go to chrome://flags and then **disable** CSSOM View Scroll Coordinates this will fix this bug

**Comment by MehdiSaeedifar** [comment] 2020-08-31 16:13
Duplicate #4045.

**Comment by d3viance** [comment] 2020-09-01 08:10
Doest someone fix this issue without disabling "CSSOM View Scroll Coordinates"?

And if you do, How?

Thanks.

**Comment by mohsen69** [comment] 2020-09-01 09:27
@d3viance Did you mean the problem will solve temporarily if we disable "CSSOM View Scroll Coordinates"?

**Comment by d3viance** [comment] 2020-09-01 09:37
> @d3viance Did you mean the problem will solve temporarily if we disable "CSSOM View Scroll Coordinates"?

The problem is solved if you disable "CSSOM View Scroll Coordinates" under chrome plugin.

I meant if is there a fix fo this **without** using the above solution, because if im using Ag Grid for world wide customers i cant "ask" them to turn of this plugin.

**Comment by leibole** [comment] 2020-09-01 12:17
I added this snippet which makes the grid at least usable:

```
if (getChromeVersion() === 85) {
      var sheet = window.document.styleSheets[0];
      sheet.insertRule(
        ".ag-body-viewport { direction: ltr; }",
        sheet.cssRules.length
      );
      sheet.insertRule(
        ".ag-cell-wrapper { direction: rtl; }",
        sheet.cssRules.length
      );
      sheet.insertRule(
        ".ag-body-horizontal-scroll-viewport { direction: ltr; }",
        sheet.cssRules.length
      );
    }
```
The initial display is on the wrong side, but at least users can use it.

**Comment by d3viance** [comment] 2020-09-01 12:40
> I added this snippet which makes the grid at least usable:
> 
> ```
> if (getChromeVersion() === 85) {
>       var sheet = window.document.styleSheets[0];
>       sheet.insertRule(
>         ".ag-body-viewport { direction: ltr; }",
>         sheet.cssRules.length
>       );
>       sheet.insertRule(
>         ".ag-cell-wrapper { direction: rtl; }",
>         sheet.cssRules.length
>       );
>       sheet.insertRule(
>         ".ag-body-horizontal-scroll-viewport { direction: ltr; }",
>         sheet.cssRules.length
>       );
>     }
> ```
> 
> The initial display is on the wrong side, but at least users can use it.

Its not really work well...

Someone found a good solution?

Thanks.

**Comment by gportela85** [comment] 2020-09-05 10:25
Closing a duplicate of https://github.com/ag-grid/ag-grid/issues/4045

**Closed by gportela85** 2020-09-05 10:25 UTC
