### ISSUE TITLE
`null` in `getContextMenuItems` gives blank menu item after v29.1.0

### ISSUE THREAD

**Issue by havardthom** [ag-grid/ag-grid#6555] opened 2023-05-04 06:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Reproduced scenario: https://plnkr.co/edit/EdwzQOFC4nPceCpF?open=main.js&preview

**Current behavior**

After version 29.1.0:  Adding `null` to list in `getContextMenuItems` will generate an blank menu item which is hoverable. See context menu in reproduced scenario above.

**Expected behavior**

Before version 29.1.0:  Adding `null` to list in `getContextMenuItems` does not generate a menu item. Change ag-grid version to 29.0.0 in reproduced scenario above to see expected context menu without blank menu item.

**Please tell us about your environment:**

* **AG Grid version:** `>= 29.1.0`

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment] 2023-05-04 10:39
Can I ask why you are passing `null` to this callback? I accept there is a change in behaviour but want to understand your use case here.

**Comment by havardthom** [comment] 2023-05-04 13:48
We have conditional menu items and use ternary operators when creating the list. 

```
[
   someCondition ? createMenuItem(params) : null,
   someOtherCondition ? someOtherMenuItem(params) : null,
   someCommonMenuItem(params)
]
```
Ofcourse there are many alternatives, e.g. we can build the list dynamically with `Array.push` or create many separate menu lists, but ternary gives a compact solution where its relatively easy to get an overview of menu items and their order. Our workaround for now is just filtering the `null`s from the list.

**Comment by StephenCooper** [comment] 2023-05-04 13:54
I would agree that filtering the `null` values is the correct fix. The fact that this worked before is more of a coincidence then a feature of the grid. Our typings for this method does not support `null` values so the behaviour is not fixed.

https://ag-grid.com/javascript-data-grid/grid-options/#reference-accessories-getContextMenuItems

```
  interface GetContextMenuItems<TData = any> {
    (params: GetContextMenuItemsParams<TData>) : (string | MenuItemDef)[]
}
```

I am going to close this ticket as the issue is resolved.

**Closed by StephenCooper** 2023-05-04 13:54 UTC
