### ISSUE TITLE
The column.series.fill of chartThemeOverrides not work in cross-filter chart

### ISSUE THREAD

**Issue by YuerLee** [ag-grid/ag-grid#5578] opened 2022-09-22 10:06 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**

Cannot use `column.series.fill` in `chartThemeOverrides`in the cross-filter chart.

[plnkr](https://plnkr.co/edit/wTYWCmEYUg8MNTx7?open=main.js&preview)

![image](https://user-images.githubusercontent.com/2075566/191718955-290d082f-f7e4-4d3d-b104-b0f572f59d4b.png)

**Expected behavior**

It works in the range chart.

[plnkr](https://plnkr.co/edit/46Dzku8Yn46cdaK9?open=main.js&preview)

![image](https://user-images.githubusercontent.com/2075566/191719259-7ab57daa-bddd-4e9b-a800-6410a491af75.png)

* **AG Grid version:** 28.1.3

* **Browser:**
```
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
```
* **Language:** ES6

**Comment by StephenCooper** [comment] 2022-12-05 16:04
Hello,

Thank you for reporting this - much appreciated! Sorry for the long review time. 

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7642 [Charts] Unable to override series fill for Cross-Filtering charts.**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7642) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2022-12-05 16:04 UTC
Labels: in_review
