### ISSUE TITLE
agPopupSelectCellEditor blocks onCellClicked being triggered

### ISSUE THREAD

**Issue by kzvt** [ag-grid/ag-grid#3471] opened 2019-10-26 16:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://stackblitz.com/edit/aggridreact-singleclickedit-issue?file=Grid.js

**Current behavior**
onCellClicked event is not being triggered when agPopupSelectCellEditor options are expanded. First click on any other cell cause only the agPopupSelectCellEditor options close the dropdown.

**Expected behavior**
Clicking on any cell while having agPopupSelectCellEditor expanded, cause not only close the dropdown  but also triggers onCellClicked. So user don't have to click another time to make this cell switch to edit mode. 

**Please tell us about your environment:**
**OS:** Ubuntu 18.04.2 LTS
- ag-grid-community21.2.1
- ag-grid-enterprise21.2.1
- ag-grid-react21.2.2
- react16.10.2
- react-dom16.10.2
- react-loadable5.5.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
or 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
![ghag](https://user-images.githubusercontent.com/12370502/67623110-d143c700-f821-11e9-977f-97891131c810.gif)

**Comment by davis4acca** [comment] 2019-11-15 13:10
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2019-11-19 12:18
Hi,

Thanks for your message.

After investigating this issue, we've concluded that is not a bug with ag-grid but is the default behaviour of HTML Select tags (which agPopupSelectCellEditor uses).

We have found the standard HTML select to behave odd when in the grid. This is because the browser doesn't have a great API for opening and closing the select's popup. We advise you don't use it unless you have to - that is we advise against agSelectCellEditor and agPopupSelectCellEditor as they give poor user experience, especially if using keyboard navigation. If using ag-Grid Enterprise, then you should use the provided agRichSelectCellEditor.

As this is not a bug, I will close this ticket.

Kind Regards,
Shuheb

**Comment by shuheb** [comment] 2019-11-19 12:19
Hi,

We will leave this ticket as managed by community.

Shuheb

**Closed** 2019-12-19 13:15 UTC
Labels: managed-by-community, wontfix
