### ISSUE TITLE
[27.0.1] - React : Grid "ref" isn't initialize, and so api isn't available. 

### ISSUE THREAD

**Issue by CyrilSiman** [ag-grid/ag-grid#4915] opened 2022-02-11 14:08 UTC
**I'm submitting a ...** 
```
[X] bug report
```

**Providing a Reproducible Scenario**

Directly inspired by your sample :  a little grid where in a useEffect I would use gridApi. You can show in the console of sandbox gridRef.current.api value.

- In 27.0.X the ref seems to be initialize after a delay

https://codesandbox.io/s/ag-grid-27-0-1-c696j?file=/src/App.js

- On 26.2.X, gridRef is correctly initialize immediately

https://codesandbox.io/s/ag-grid-26-2-1-s9932?file=/src/App.js

From my side this bug is important because we can't use Grid API for any kind of action.

**Current behavior**

gridRef.current isn't correctly initialize.

**Expected behavior**

gridRef.current initialize with the current griApi object.

**AG Grid version:** 
27.0.1

**Browser:**
Any

**Comment by seanlandsman** [comment] 2022-02-11 14:39
You should alter your `useEffect` to have the ref as a dependency and check for when the API is ready 

```
  useEffect(() => {
    if (gridRef.current.api) {
      console.log("API Ready", gridRef.current.api);
    }
  }, [gridRef.current]);
```

Check our this forked example: https://codesandbox.io/s/ag-grid-27-0-1-forked-ert0f?file=/src/App.js

**Comment by CyrilSiman** [comment] 2022-02-11 16:01
In this sample I voluntarily omit tests, 

```
  useEffect(() => {
    if (gridRef.current.api) {.    <---- good practice 
      console.log("API Ready", gridRef.current.api);
    }
  }, [gridRef.current]); <---- With this dependency, this effect will be never call without outside event.
```

Now as Ag-grid is directly bind with react rendering, the grid ref can be available after the first rendering (as in 26.2.0) an so available in useEffect

In your sample, I can't made modification on the grid after the first rendering.

Maybe we have to use onGridReady event again with 27.0.X ? To be sure that ag-grid is init ?

**Comment by CyrilSiman** [comment] 2022-02-11 16:04
You can confirm a change between 26.2.X and 27.0.X, on my side the behavior on 26.2 was better and perfectly fine.

**Comment by makinggoodsoftware** [comment] 2022-02-23 16:51
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2022-03-02 17:20
Hi @CyrilSiman

Thanks for raising this with us.

We've investigated this and found that this is expected behaviour because v27 uses React UI by default (all of the grid's core rendering is rendered using React). This also means that `gridRef.current.api` is not available until after the async creation of the Grid.

If you want to do something when the grid is ready, please do it in `onGridReady` where the API is always available:

```
onGridReady = params => {
    console.log('gridRef', gridRef.current.api);
}
```

Alternatively, please reference the API as shown below:
```
useEffect(() => {
if (gridRef.current.api) {
console.log('gridRef', gridRef.current.api);
}
}, [rowData]);
```

Note that we will be soon closing this ticket as it is not a bug.

Thanks again for raising this.

**Closed** 2022-03-03 15:29 UTC
