### ISSUE TITLE
[27.0.1] Checkbox Selection not aligning vertically if the field has no text

### ISSUE THREAD

**Issue by NehalDamania** [ag-grid/ag-grid#4918] opened 2022-02-12 03:14 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Accepted reproducible scenarios are
- When using an empty field with checkbox selection, the checkbox is not aligning in the middle like before. Please check the examples below
- [Stackblitz Reproducible Example](https://stackblitz.com/edit/ag-grid-react-hello-world-thss4a?file=index.js)

If reporting a bug make sure to state.

Current behaviour. The column is not getting right aligned
[Current Behavior on 27.0.1 Stackblitz Example](https://stackblitz.com/edit/ag-grid-react-hello-world-thss4a?file=index.js)
Expected behaviour. The column gets right Aligned as mentioned in docs in prior versions 
[Perfectly working Stackblitzexample in 26.2.0](https://stackblitz.com/edit/ag-grid-react-hello-world-hno4lw?file=index.js) <-Version 26.2.0

* **AG Grid version:** 27.0.1

* **Browser:**
all

* **Language:** [all]

**Comment by lakhi** [comment] 2022-02-16 15:39
facing the same issue. would be great if you'll could kindly look into it @ag-grid team: @eviltester @gportela85

**Comment by gportela85** [comment] 2022-02-17 02:12
@NehalDamania @lakhi 
Here is a quick fix if you are using Theme Alpine

```css
  .ag-cell-wrapper
    > *:not(.ag-cell-value):not(.ag-group-value) {
    height: min(var(--ag-theme-row-height, 40px), 40px);
  }
```

**Comment by gportela85** [comment] 2022-02-17 02:46
I have filed an issue AG-6402 - It can be tracked here: https://www.ag-grid.com/pipeline/

**Comment by kiril-matev** [comment] 2022-02-17 13:03
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced the checkbox alignment issue as a regression. 

I can see you've also reported a second issue about the right-alignment of values - 4917. We will respond to that issue in the other ticket.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6402 [Regression] When rendering cells with empty values, checkbox or row drag elements inside these cells are aligned to the top of the cell instead of centered in the middle**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-23 16:52
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-23 16:52 UTC
Labels: ag-grid engaged, ag-6402
