### ISSUE TITLE
[ReactUI] Crash when using the prop getRowStyle

### ISSUE THREAD

**Issue by akiver** [ag-grid/ag-grid#4632] opened 2021-08-20 17:49 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When setting the new `reactUi` prop to `true` and defining the `getRowStyle` prop function, there is a crash because it's trying to access an undefined variable:

```
Uncaught TypeError: Cannot set property 'backgroundColor' of undefined
```

Example: https://plnkr.co/edit/U8Hd6qjDx5cv8y5o

Based on the stack trace, it looks like the issue comes from this call https://github.com/ag-grid/ag-grid/blob/latest/community-modules/react/src/next/rows/rowComp.tsx#L122 (`rowStyles` is  undefined)

**Expected behavior**

The row style defined in `getRowStyle` should be applied.

* **AG Grid version:** 26.0.0

* **Browser:** All

* **Language:** All

Thank you

**Comment by kiril-matev** [comment] 2021-08-23 11:47
Hi @akiver,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5661 When using reactUI and with the getRowStyle callback, an exception in thrown**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-09-06 15:40
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-09-06 15:40 UTC
Labels: bug, ag-5661
