### ISSUE TITLE
Filtering does not bring back all results when getRowHeight is used to dynamically set row height

### ISSUE THREAD

**Issue by aclark09** [ag-grid/ag-grid#4414] opened 2021-03-22 17:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I've set up a plunker that lets you reproduce the bug. Steps to reproduce:
- Set row height to 125px using the button
- Filter country using the Contains option and the text 'singapore'
- Only 3 results show up, despite there being 6 rows with the country of Singapore
- Use the horizontal scroll bar to scroll right and left - the remaining 3 results now show up.

If the steps aren't done in that order, the bug won't happen, so it's important not to set any filters before changing the row height.
The plunker:
https://plnkr.co/edit/ug6dJM57okIYngw7

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When getRowHeight is used to set the row height to anything other than the default height, column filters don't return all results until the user scrolls, resizes their browser window, or sorts the column. At that point, the remaining rows show up, without making any further changes to the filter.

**Expected behavior**
All filtered rows should show up, even when using getRowHeight.

* **AG Grid version:** 25.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

* **Language:** JS

**Comment by makinggoodsoftware** [comment] 2021-03-25 16:55
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-07 17:37
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v25.0.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5233 [Regression] When setting dynamic row height and filtering, not all matching records are rendered until you scroll**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-12 15:56
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-12 15:56 UTC
Labels: ag-5233, in_zendesk
