### ISSUE TITLE
Exception is thrown when React.lazy is used for cellRenderer

### ISSUE THREAD

**Issue by aleckravets** [ag-grid/ag-grid#6557] opened 2023-05-04 12:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Ag-grid throws exceptions when React.lazy is used for cellRenderer: "**AG Grid: unable to find bean reference frameworkOverrides while initialising BeanStub**". The same cell renderer works fine without exceptions if used directly without React.lazy

Simple way to reproduce the bug: 
```
const SimpleRenderer = props => <span>{props.value}</span>;

const LazySimpleRenderer = React.lazy(() => Promise.resolve({
  default: SimpleCellRenderer
}));

const [columnDefs] = useState([
       {
           headerName: "Colour 1",
           field: "value",
           cellRenderer: LazySimpleRenderer
       },
       ...
  ]);

  return (
	<React.Suspense fallback={<div>Loading...</div>}>
		<div className="ag-theme-alpine">
		  <AgGridReact
			 columnDefs={columnDefs}
			 ...other properties
		  />
		</div>
	</React.Suspense>
  );
```

**Expected behavior**
no exceptions

**Please tell us about your environment:**
Windows 11, Webstorm, npm, webpack devserver

* **AG Grid version:** 29.3.3

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

* **Language:** TypeScript 4.8.4

**Comment by StephenCooper** [comment] 2023-05-04 13:56
Could you please provide a code reproduction of the issue to make it easier for us to investigate.

**Comment by aleckravets** [comment] 2023-05-04 17:06
> Could you please provide a code reproduction of the issue to make it easier for us to investigate.

@StephenCooper here is the sample [https://ag-grid-react-hello-world-ajhxff.stackblitz.io](https://ag-grid-react-hello-world-ajhxff.stackblitz.io)

Notice exceptions in the console. It used to work fine before but seems to have been broken in latest versions. Eg. works fine with version 29.1

**Comment by StephenCooper** [comment] 2023-05-04 17:56
Thanks! That's helpful. 

Can I ask what is your main motivation for loading a cell renderer lazily? Is it particularly large in terms of download size or is there another reason for this approach?

**Comment by aleckravets** [comment] 2023-05-05 06:18
> Thanks! That's helpful.
> 
> Can I ask what is your main motivation for loading a cell renderer lazily? Is it particularly large in terms of download size or is there another reason for this approach?

Yes, we keep renderers with their dependencies in modules which are loaded only by demand

**Comment by StephenCooper** [comment] 2023-05-10 09:33
I have linked this to an existing and related issue that I have been making progress towards resolving. So we should be able to resolve this in our next release. 

Thanks for a good reproduction!

<hr>

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8220 Grid Throws an Error when used within React Suspense Component**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by StephenCooper** [comment] 2023-05-23 12:12
Hi @aleckravets,

While looking into this issue I have found there is an existing workaround with the only change being moving the Suspense boundary to the cell renderer instead of around the entire grid. 

See https://plnkr.co/edit/sGOX9xsfbhtRk7Ne?open=index.tsx

I appreciate this is not the full fix but I thought I would share this with you as it may be good enough?

**Comment by StephenCooper** [comment] 2023-07-14 10:26
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8220 Exception thrown when React.lazy is used for CellRenderer**

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

**Closed by StephenCooper** 2023-07-14 10:26 UTC
Labels: AG-8609
