### ISSUE TITLE
Cannot edit empty cell when colDef includes `autoheight: true`

### ISSUE THREAD

**Issue by CapnCrunchsna** [ag-grid/ag-grid#4871] opened 2022-01-14 14:44 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
A plunker of this bug can be found here: https://plnkr.co/edit/CTz4VbVPtwIEioFw.  

**Current behavior**
When attempting to edit an empty cell when the column definition has `autoHeight: true` the user cannot double click that cell to begin editing.  It appears as though autoHeight is setting the clickable area of the height to 0 or near 0, since double clicking the very top of the empty cell will result in editing working as normal.

In the provided Plunker the example cell is the empty cell in the first row, "Last Name" column.  This column is editable, and all populated cells in that column can be clicked to initiate editing, but the empty one exhibits the behavior described above.

**Expected behavior**
The autoHeight property should not prevent the user from double clicking anywhere in an empty cell to initiate editing.

**Please tell us about your environment:**
The created Plunker was forked from the ag-grid documentation, using the Angular Data Grid ([this example](https://www.ag-grid.com/angular-data-grid/cell-editing/#example-cell-editing) in particular).

* **AG Grid version:** 
26.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

* **Language:**
All

**Comment by makinggoodsoftware** [comment] 2022-01-18 15:15
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-18 20:23
Hello @CapnCrunchsna!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6143 [Regression] When a column has autoHeight: true and rendering a null/undefined/empty cell value, the default cell renderer has no height and cannot be clicked**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by CapnCrunchsna** [comment] 2022-01-19 17:07
Thank you very much for the quick response, and for looking in to the issue!

**Comment by tienhvbrains** [comment] 2022-09-08 11:30
Sorry but is this issue fixed?
I am facing the same problem. I wonder if there is any workaround?

**Comment by StephenCooper** [comment] 2022-09-08 13:10
> Sorry but is this issue fixed? I am facing the same problem. I wonder if there is any workaround?

AG-6143 - This was fixed in v27. What version are you using?

**Comment by magantoine** [comment] 2022-11-21 11:50
Still an issue in 28.2.1

**Comment by StephenCooper** [comment] 2022-11-21 12:06
@magantoine I am struggling to reproduce this issue in 28.2.1. Can you please share your reproduction?

**Closed** 2022-12-05 14:14 UTC
Labels: in_zendesk, waiting-for-repro, ag-6143
