### ISSUE TITLE
Angular component gridOptions binding update

### ISSUE THREAD

**Issue by csisy** [ag-grid/ag-grid#6422] opened 2023-04-04 08:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

There is no real demo example, however [according to the docs](https://www.ag-grid.com/angular-data-grid/grid-interface/#grid-options-1) a single `gridOptions` object can be bound to the angular component. However, updating this binding does not properly update the grid in the background. To reproduce this issue:

- Create a `gridOptions` object.
- Bind it to the `ag-grid-angular` component (like shown in the example)
- Change the `gridOptions` object to another one
- This causes the [ngOnChanges](https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts#L238) to run
- In turn, the `ComponentUtil.processOnChange` is called with a `{ gridOptions: ... }` change object
- However the `gridOptions` property is not handled explicitly so the `api.__setProperty` [is called](https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/core/src/ts/components/componentUtil.ts#L176) with the `gridOptions` key and a whole `GridOption` object

**Current behavior**

Changing the `gridOptions` binding has no real efffect.

**Expected behavior**

The `gridOptions` bound parameter should be handled accordingly (e.g. by destructing it). 

**Please tell us about your environment:**

* **AG Grid version:** 29.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

* **Language:** TypeScript 4.7.2 | ES6/7

**Comment by StephenCooper** [comment] 2023-04-04 09:13
Hi @csisy,

This has been raised before and is being tracked under **AG-7557 Make gridOptions top level property reactive**. 


You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-04-04 09:13 UTC
Labels: AG-7557

**Comment by AG-Zoheil** [comment] 2023-12-06 16:12
Hi @EmmanuelRoux,

Thank you for your comment.

Once an issue has been identified and assigned to our backlog the corresponding GitHub issue gets tagged with the reference number and closed. We will not be providing further updates on the individual GitHub issues but rather our releases and the fixes contained therein can be best be followed in the following manner:

- See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page: https://www.ag-grid.com/ag-grid-pipeline/

- Sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out

- Check whether this specific item was implemented in a release on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/)

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Thank you for your understanding!

Kind regards,
Zoheil

**Comment by EmmanuelRoux** [comment] 2023-12-07 10:36
> A potential work around is to move the properties that are required to be reactive out of the static gridOptions.

What do you mean? I was not talking about updating the `gridOptions` object : 

>  It seems ag-grid-angular component simply ignores any __binding__ update!

**Comment by StephenCooper** [comment] 2023-12-07 10:50
Hi Emmanuel,

I am confused by your last statement as it seems the original issue raised was about updating gridOptions

> However, updating this binding does not properly update the grid in the background

I have made a small example that shows the difference between updating a property, `rowHeight` and how this works if row height is passed directly to the `ag-grid-angular` component. It also shows how providing a new gridOptions object with a changed row height does not update the grid.

https://plnkr.co/edit/RlGu70jWdjFfCUMg?open=app%2Fapp.component.ts

If you are not talking about updating gridOptions then I am not sure what the issue is.

**Comment by EmmanuelRoux** [comment] 2023-12-07 11:03
Ok, I find out my bug is fixed in version 31, by this commit : https://github.com/ag-grid/ag-grid/commit/74eae2c6884d9b6fdb1d08fc184d529099bb8865

Angular bindings seems to be incorrectly updated prior to this change (because the old code was not reading `.currentValue` in the changes object... <sup><sub>such a basic mistake 🙊</sub></sup>).

By the way, the commit has reference "AG-9440", but I can't find out where it is tracked, it does not appear at all on your [changelog page](https://www.ag-grid.com/changelog/) or [pipeline page](https://www.ag-grid.com/pipeline/)... 

So exhausting 😅

**Comment by StephenCooper** [comment] 2023-12-07 11:19
The commit you referenced was part of a larger project to improve the reactivity of the grid. AG-9439 We don't list every sub jira publicly that we work on.

The fact that `currentValue` appears in the component is the result of a refactor. We were previously reading the `currentValue` elsewhere in the codebase. 

I am glad the issue is resolved in v31.

**Comment by SeraphyBR** [comment] 2025-09-26 21:34
@AG-Zoheil Hi,

I know this was marked as "Won't Do", but I noticed something while working with Angular signals and computed gridOptions that might be worth reconsidering.

When I create a gridOptions object using a signal computed, it triggers the ngOnChanges in ag-grid-angular and I get this confusing warning in the browser:

```
AG Grid: invalid gridOptions property 'gridOptions' did you mean any of these: onGridOptionsChanged, groupHideOpenParents, dragAndDropImageComponentParams...
```

Looking at the logic, it seems like the ngOnChanges method receives a key that is literally "gridOptions", and then tries to set that as a property on the grid API.

I'm wondering if this could be fixed with just a small adjustment in the ngOnChanges method - like checking if the key is "gridOptions" itself and then iterating over its properties instead of treating it as a single property?

I'm not expecting the grid to react to changes in all gridOptions fields, just to have the same behavior as individual inputs - so properties that are already reactive would work the same way whether passed individually or through the gridOptions object.

Is there any chance this could be reconsidered given how minimal the change might be, or am I missing something about why this approach wouldn't work?

Thanks!
