### ISSUE TITLE
[React ag-grid] Tooltip issue in safari browser

### ISSUE THREAD

**Issue by hsree-1** [ag-grid/ag-grid#8681] opened 2024-09-11 18:30 UTC
**I'm submitting a ...**  (check one with "x")
```

[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I am using ag grid react in Mac os in safari browser
I am using tooltip for cells using tooltipValueGetter
O have fixed rowheight so whenever the data is in truncated mode that is displayed with ellipsis the default tooltip is also visible with ag grid tooltip.
Which should not happen as the browsertooltip option is not enabled
I even tried setting enableBrowserTooltithefalse explicitly but did not work.

**Expected behavior**

If we are using ag grid tooltip the browser default tooltip should not be shown unless it is enabled

**Please tell us about your environment:**

Mac Os
Safari browser

* **AG Grid version:** X.X.X
* ag-grid-react - 32.1.0
* 

Yes this issue is observed in safari browser

* **Browser:**
* safari
* 

The issue is Reproducible in safari browser.
1. Go to the first example provided in ag grid tooltip docs
https://www.ag-grid.com/react-data-grid/tooltips/
2.open the example in safari browser
https://codesandbox.io/p/sandbox/f9sl5k?file=%2Fpackage.json
3. Resize any column to make the ellipsis visible showing the truncated data
4. hover above cell and you can see ag grid tooltip along with default browser tooltip is displayed

Please look into this issue as we cannot do anything to hide default browser tooltip

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React, typescript

**Comment by sabahang** [comment] 2024-10-07 15:35
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13080 [Safari] browser tooltip is shown when cell content is truncated even when enableBrowserTooltips = false**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed by sabahang** 2024-10-07 15:35 UTC
