### ISSUE TITLE
ag-grid Memory Build-up

### ISSUE THREAD

**Issue by jfuehner** [ag-grid/ag-grid#1868] opened 2017-08-31 10:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using ag-grid with AngularJS for an application where data is continually loaded into the grid. I've noticed that the FireFoxes memory slowly builds over time and will cause the browser to crash. 

Originally I was using ag-grid's infinite scrolling calling the **successCallback** each time new data was received. Using this I was seeing the browser crash anywhere between 4-6 hours.

I switched to just the basic **setRowData** and the crash time last night was around 16 hours.

I wasn't able to find a known memory issue with the grid anywhere on the Internet but I also wasn't able to find an example where the grid was being used in a similar real-time/constant refresh fashion.

Curious if anyone else has ran into such an issue with ag-grid and perhaps a memory leak when the grid is constantly refreshed over time? Anyway, to force the memory to release/clear?

Any help would be great!

**Expected behavior**
I would expect the browser not to crash...

* **ag-Grid version:** X.X.X
ag-grid 12.0.2

* **Browser:**
FireFox 38.1.0 and FireFox 52.2.0

**Comment by jfuehner** [comment] 2017-08-31 21:16
To add to my additional issue, we are using the angularCompiledRows setting with a couple of cellRenderer columns that have some angular directives. Additionally, we load ~500 rows every 15 seconds or so.

Just seems like memory is not being released or released fast enough when the app is ran for an extended period of time. 

We initially thought it had to do with our $interval but we are for sure clearing/canceling in as appropriate.

**Comment by seanlandsman** [comment] 2017-09-01 08:27
Duplicate of https://github.com/ag-grid/ag-grid/issues/1234

**Closed by seanlandsman** 2017-09-01 08:27 UTC
