### ISSUE TITLE
Custom Column Types not honoring Floating Filter

### ISSUE THREAD

**Issue by VitaliiK91** [ag-grid/ag-grid#4441] opened 2021-04-09 21:55 UTC
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi there,
I want to leverage the column types in the project. I noticed that when I set floating filter as part of column type it does not work. Only works if `floatingFilter: true` is set on columnDef or defaultColumnDef

[Plunker](https://plnkr.co/plunk/amg8RR3usbJZ3XYZ
)
I debugged the code and it seems that issue is in ColumnController:

```
ColumnController.prototype.hasFloatingFilters = function () {
        var defaultColDef = this.gridOptionsWrapper.getDefaultColDef();
        return (defaultColDef != null && defaultColDef.floatingFilter === true) ||
            (this.columnDefs != null && this.columnDefs.some(function (c) { return c.floatingFilter === true; }));
    };
```

**Current behavior**
Floating filter does not appear when floatingFilter is true in columnTypes

**Expected behavior**
Floating filter does appear when floatingFilter is true in columnTypes

**Please tell us about your environment:**
Widnows 10, vanilla JS, node, yarn

* **AG Grid version:** X.X.X
25.1

* **Browser:**
Google Chrome

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment] 2021-04-15 15:37
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-19 15:15
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-5260 When setting floatingFilter property in the columnType, the value is not respected by the column

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:**
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-27 15:46
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-27 15:46 UTC
Labels: ag-5260, in_zendesk
