### ISSUE TITLE
[filtering - groups] Filtering is not working in Master Detail Grids

### ISSUE THREAD

**Issue by bamminger** [ag-grid/ag-grid#1324] opened 2016-12-09 09:29 UTC
When using a master detail grid, the filter of all columns is empty.
Demo can be found on the ag-grid website.
When disabling getNodeChildDetails the filter works as expected.

![grafik](https://cloud.githubusercontent.com/assets/22851567/21044057/47d43f72-bdfa-11e6-8a1d-512523a932dd.png)

**Comment by ceolter** [comment] 2017-01-04 16:25
verified and this is true. i've updated the example to remove filtering.

the problem is filters work at the leaf level. this only makes sense when the parent rows are aggregations of the child rows. there is another issue open to allow filtering on the group node, until this is done, this will remain to not work.

**Comment by bamminger** [comment] 2017-02-24 11:00
Is this bug already scheduled for a new release?

**Comment by MolallaComm** [comment] 2017-04-21 15:40
Just ran into this issue myself - +1 for a fix.  I like the way master detail works - i was able to easily display multiple related tables using an ionic segment bar and odata - but filtering/grouping not working on the master when using master detail is enabled unfortunately may be a deal breaker for us.

![image](https://cloud.githubusercontent.com/assets/1542219/25284943/6eb184e8-266d-11e7-816c-5349cea565ac.png)

**Comment by bettinalechner** [comment] 2017-04-21 15:42
Running into this as well. We have an enterprise license as well and would like to see this fixed soon. Thank you!

**Comment by bamminger** [comment] 2017-04-21 16:01
Have you tried this workaround: https://ag-grid.com/forum/showthread.php?tid=5135

**Comment by MolallaComm** [comment] 2017-04-21 17:25
Thanks so much for that work around - I can confirm that it does allow the default enterprise set filters to work normally, so that is a step in the right direction - but alas it does not seem to fix grouping.  Here is my getNodeChildDetails function FWIW:

```
  public getNodeChildDetails(record) {
    if (record.IsChild) {
      return null;
    }
    else {
      let set = (<any>this).gridOptionsWrapper.gridOptions.context.navParams.data.Set;
      record["IsChild"] = true;
      return {
        group: true,
        // the key is used by the default group cellRenderer
        key: record[set.Keys[0]],  // hack - need to test if it works with for records that use composite keys - hopefully you can just pass in an array of colIds?
        // provide ag-Grid with the children of this group -
        children: [record]   // this is a hack to make grouping/filtering work with master detail
      };
    }
  }
```
And here is what it looks like when I try to group:

![image](https://cloud.githubusercontent.com/assets/1542219/25288839/fc0b1dc8-267b-11e7-9c74-4ae26d7006eb.png)

I'm not familiar enough with their data model yet, but seems like this should be able to work - it is not different than grouping by first one column and then another - but it seems to be reusing the children instead of creating a new group level from the parent?

**Comment by makinggoodsoftware** [comment] 2017-12-19 09:09
This should be fixed now

**Closed by makinggoodsoftware** 2017-12-19 09:09 UTC
Labels: enhancement

**Comment by bamminger** [comment] 2017-12-19 21:50
Included in v15?

**Comment by hetal1110** [comment] 2018-02-23 11:03
@makinggoodsoftware Included in v15?

**Comment by ghetal** [comment] 2018-02-23 11:10
I am facing the same issue. Aftre filtering master grid, expanding child grid doesn't work. 
Is it fixed now?

**Comment by hetal1110** [comment] 2018-03-02 05:36
Any Updates?

**Comment by prafful-garg** [comment] 2018-03-29 10:46
I am also facing the same issue, i have enterprise license for the grid

**Comment by bamminger** [comment] 2018-03-31 20:49
I haven't checked if the bug was fixed. For all of you who have an enterprise license, just create an open issue in the enterprise support portal.
