### ISSUE TITLE
floating filter stuck when rendered on-demand

### ISSUE THREAD

**Issue by JeyoungKwon** [ag-grid/ag-grid#5057] opened 2022-04-05 14:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Reproduction:

https://plnkr.co/edit/t7FYyxStyjP5c9LY

**Current behavior**
If the floating filter gets rendered only after scrolling (in the plunkr I spammed some extra columns to guarantee the filters start out un-rendered), then the filter gets stuck on a certain value. Logging the value shows that the adjusted value is getting sent, but quickly overridden by the stuck value. 

**Expected behavior**
filter works as in https://www.ag-grid.com/react-data-grid/component-floating-filter/#example-floating-filter-component

**Please tell us about your environment:**

* **AG Grid version:** 27.1.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36'
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Occurs using Typescript 4.6 and also in the plunkr

**Comment by makinggoodsoftware** [comment] 2022-04-21 13:39
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-04-22 21:38
Hello @JeyoungKwon!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

Until this issue is resolved you can work around this issue by using legacy React mode as shown here:
https://plnkr.co/edit/FBOaCenrrk9XAmiF?open=index.jsx

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6709 [Regression] When using React with custom filters in columns which are out of view, custom filter value is reset to initial value**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-04-28 15:27 UTC
Labels: in_zendesk, ag-6709
