### ISSUE TITLE
First grouping row disappears on SSRM Pagination with Child Rows

### ISSUE THREAD

**Issue by jurczas** [ag-grid/ag-grid#6510] opened 2023-04-25 12:51 UTC
Example from official documentation.
https://www.ag-grid.com/examples/server-side-model-pagination/pagination-with-groups/packages/angular/index.html

First grouping row disappears on expansion.

**Comment by kiril-matev** [comment] 2023-04-25 15:18
Hello @jurczas,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v29.2.

You have two options - please roll back to v29.2 or in v29.3 please set **paginateChildRows**=true to resolve this issue. This will cause child rows to be paginated and will resolve this issue at this time. See this shown here:
https://www.ag-grid.com/javascript-data-grid/server-side-model-pagination/#example-paginate-child-rows

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8437 [Regression] When using SSRM with group pagination, expanding the top row group hides the group row**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by StephenCooper** [comment] 2023-05-25 09:02
A fix for this was released in our patch `29.3.4`.

**Closed by StephenCooper** 2023-05-25 09:02 UTC
Labels: AG-8420
