### ISSUE TITLE
Issue with isExternalFilterPresent method; called too often

### ISSUE THREAD

**Issue by haquee** [ag-grid/ag-grid#5030] opened 2022-03-29 15:49 UTC
I'm submitting a bug
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
version 27
https://plnkr.co/edit/5a2pB3sVKHiZRFUE?preview

version 24
https://plnkr.co/edit/tTHgMl6246ENqYy8?preview

**Current behavior**
As shown in version 27 in plunker above, there is a bug regarding isExternalFilterPresent method. It seems to be called for every row when an external filter is applied.

**Expected behavior**
According to the [documentation](https://www.ag-grid.com/vue-data-grid/filter-external/), it should be called exactly once every time the
grid senses a filter change.

**Please tell us about your environment:**
Reproduced in plunker using example from [documentation](https://www.ag-grid.com/vue-data-grid/filter-external/)

* **AG Grid version:** 27.1.0
Issue is present in current version and was last working as expected in version 24

* **Browser:**
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

* **Language:**
All

**Comment by makinggoodsoftware** [comment] 2022-04-07 10:16
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-04-21 18:43
Hello @haquee!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v25.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6703 [Regression] When using external filtering and changing the external filter, isExternalFilterPresent callback is called multiple times instead**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-04-28 15:26
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-04-28 15:26 UTC
Labels: in_zendesk, ag-6703
