### ISSUE TITLE
Full Width Rows - applyTransaction flushSync Error

### ISSUE THREAD

**Issue by bo-hyeon** [ag-grid/ag-grid#6752] opened 2023-06-13 00:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Current behavior**
I copied the [Full Width Rows](https://www.ag-grid.com/react-data-grid/full-width-rows/) first example and updated the data through 'forEachNodeAfterFilterAndSort' and 'applyTransaction'.
However, there was an error as below. If you delete 'full width row', there will be no error.
```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.

```

**Expected behavior**
However, the grid results are as desired. Can I ignore this error?

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

* **Browser:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:**  React

**Comment by kiril-matev** [comment] 2023-06-13 10:13
Hi @bo-hyeon,

Thank you for reporting this.

It's essential that we get a reproduction example of the exact scenario you have to reproduce this error.

Please see the plunker below:
https://plnkr.co/edit/YP1o2IU7pply9pm5?open=index.jsx

Please FORK, update it to reproduce the issue and send it back here, so we can investigate further.

Looking forward to your response.

**Comment by bo-hyeon** [comment] 2023-06-15 04:24
Reproduced on this site. But this site doesn't have a 'flushsync' error, but my local workspace has a 'flushsync' error. But there is no error because 'getRowId' return value is not 'row_key'.
like... 
```
getRowId={(params) => params.data.name} //=> no error, but if you press it several times -> flushsync
getRowId={(params) => params.data.row_key} //=> flushsync error
```
![test](https://github.com/ag-grid/ag-grid/assets/112597959/d9f0e767-eaef-47e9-bda5-fba13de17fe7)


 What is happening?

https://plnkr.co/edit/0RMOqeFJiVpGOQCx?open=index.jsx

**Comment by kiril-matev** [comment] 2023-06-15 10:58
Hello @bo-hyeon,

Thanks for your response.

So you cannot reproduce the flushSync issue with the plunker sample you sent? Does this mean it's only reproducible in your project? Please try to find out the differences between your project and the plunker sample and modify the plunker to reproduce the issue.

Also you can try reproducing this in a stackblitz example:
https://stackblitz.com/edit/ag-grid-react-hello-world?file=index.js

We cannot investigate this as we can't reproduce this ourselves. Please look into the changes you've made recently to cause this issue to identify the one that's causing it so you can build a reproduction example. 

We're looking forward to your response.

**Comment by StephenCooper** [comment] 2023-06-15 18:17
Reproduction. Error is a dev only issue. I have updated the plunker to use the dev code and now we can reproduce the issue.

https://plnkr.co/edit/vYzk8Aa1fSreg2jP?open=index.jsx

**Comment by bo-hyeon** [comment] 2023-06-15 22:35
@StephenCooper 
Thank you very much. I look forward to hearing from you.

**Comment by kiril-matev** [comment] 2023-06-16 08:56
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8788 [Regression] When using React with full-width rows and setting new row data with the same row id for a full-width row that was previously used by a non-full-width row, flushSync exception is thrown**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-06-16 08:57 UTC
Labels: AG-8788
