### ISSUE TITLE
Custom components have their styles altered by theme CSS

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#3727] opened 2020-03-19 10:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Since I upgraded from version 22 to 23 my css isn`t working anymore. I am using cellrendererFramework with a material-ui button inside.

Normally it should look like this (version 22):
![aggrid1](https://user-images.githubusercontent.com/25934591/77055721-b42ab300-69d1-11ea-99ec-42a37af05ae7.PNG)

With version 23 it looks like this:
![aggrid2](https://user-images.githubusercontent.com/25934591/77055796-d02e5480-69d1-11ea-98e4-b1f3479ea536.PNG)

I have read the css changes from here [Migrate css to version 23](https://www.ag-grid.com/javascript-grid-themes-v23-migration/). I have not modified anything on the css. I use the standard theme: ag-theme-balham

In the browser-console I get the following message:

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
>     in NoSsr
>     in button
>     in ForwardRef(ButtonBase)
>     in WithStyles(ForwardRef(ButtonBase))
>     in ForwardRef(Button)
>     in WithStyles(ForwardRef(Button)) (at manageChampionships.tsx:304)
>     in Fragment
>     in cellRendererFramework

When I am using version 23 I have another strange behavior as well. All other buttons on my page (not only in the table) have a wrong css.

I have made a codesandbox example, which shows the button before the table in red color. (This is correct) and in the table with the wrong css.
[Codesandbox example](https://codesandbox.io/s/react-functional-component-b5103)

**Current behavior**
See picture2

**Expected behavior**
It should look like in picture 1

**Please tell us about your environment:**
Windows 10, Intellij, npm latest version

* **ag-Grid version:** X.X.X
Old working version: 
22.1.1
New version 
ag-grid-community: 23.0.1
ag-grid-react: 23.0.0

* **Browser:**
Chrome and Firefox

* **Language:**
react 16.13.0
typescript 3.7.4

**Comment by rmc-software** [comment] 2020-03-19 10:54
Thank you for raising this. This issue is being tracked by: 'AG-3987 - Custom components have their styles altered by theme CSS'.

This fix will be included in our next patch release scheduled next week.

**Comment by BernieSumption** [comment] 2020-03-19 12:17
Hi @Paul6552 thanks for letting us know about this issue. I've renamed the issue to match our internal tracking system. The console warning you're getting is not related to this issue and comes from React server-side rendering. It's probably nothing to do with ag-Grid at all - we don't use `useLayoutEffect` in our React integration.

**Comment by Paul6552** [comment] 2020-03-19 12:29
To the console warning: I am not so experienced that I can debug it myself. However, I know that this bug is thrown in the cellRendererFramework component. If I switch to version 22, this error does not appear. Maybe your ag-grid-fix will fix the console warning as well as a side effect. Maybe maybe...

**Comment by BernieSumption** [comment] 2020-03-19 16:49
Sorry, it won't - the style bug, and the associated fix, fix is CSS only and this error comes from JavaScript.

I take it your app is doing server-side rendering. Something in your app is calling `useLayoutEffect` on the server, and React doesn't like that. It can't be ag-Grid because our codebase doesn't contain that function. It is strange that the issue doesn't happen with v22, but my best guess is that some difference in behaviour between v22 and v23 triggers a code path that contains `useLayoutEffect` in either your app of one of your other dependencies, perhaps Material UI.

**Comment by BernieSumption** [comment] 2020-03-19 16:55
The grid isn't really designed with server-side rendering in mind, if you're doing SSR with Material UI and getting issues server-rendering the grid you might try wrapping the grid in https://material-ui.com/components/no-ssr/ - do let us know if that helps.

**Comment by Paul6552** [comment] 2020-03-20 09:30
useLayoutEffect is used in the <button>-component of material-ui.

I am not using server-side-rendering. The only thing I can think about is that webpack is creating a server-side-rendering behind the scenes for debugging.

I tried to fix the error in several ways:
Surrounding the whole ag-grid-div:
```
<NoSsr>
	<div
		className="ag-theme-balham"
		style={{
			height: '80vh',
			width: '100%',
		}}>
		<AgGridReact
			rowHeight={50}
			columnDefs={columnsMeisterschaftenAGGrid}
			rowData={tempMeisterschaften}
			getRowNodeId={getRowNodeId}
			onRowDataChanged={onRowDataChanged}
			enableCellTextSelection={true}
			onFirstDataRendered={autoSizeAll}
			onGridReady={onGridReady}>
		</AgGridReact>
	</div>
</NoSsr>
```
and only the cellrendererFramework component:
```
        cellRendererFramework: (params: any) => {
            return (<>
                <NoSsr>
                <Button variant="contained" color="primary"
                        fullWidth={false}
                        onClick={(evt) => startChampionship(params.data)}>
                    Manage championship
                </Button>
                </NoSsr>
            </>);
        },
```

Still getting the javascript error :-/

Because as you said it is not an error of ag-grid I will wait for the patch release of ag-grid. After this I will open a issue-ticket in material-ui. Hopefully a more experienced person can help out there.

**Comment by BernieSumption** [comment] 2020-03-20 10:03
Oh I do apologise, it is our bug after all! Our new React integration uses SSR for rendering and this is causing issues with Material UI. This issue is being tracked by "AG-3992 - React custom components with useLayoutEffect cause console errors".

We'll need to do some investigation before we can get a timeline for a fix.

**Comment by BernieSumption** [comment] 2020-03-20 10:07
In the mean time, try passing `disableStaticMarkup={true}` in your grid options, that should remove the error for now.

**Comment by seanlandsman** [comment] 2020-03-20 14:19
@Paul6552 thank you for the detail you've provided here 

You can track the progress of AG-3992 in our pipeline (it may take a few hours for it to appear there): https://www.ag-grid.com/ag-grid-pipeline/

I'll ensure that a fix for this is in place for our next release.

thanks

**Closed by seanlandsman** 2020-03-20 14:19 UTC

**Comment by seanlandsman** [comment] 2020-04-01 07:01
@Paul6552 the example you originally provided appears to have been updated and no longer throws the error you mention.

Can you please provide an example of this error once again?

**Comment by Paul6552** [comment] 2020-04-01 09:01
@seanlandsman I am sorry. I have overwritten the sandbox to show the next bug.

[New Link](https://codesandbox.io/s/react-functional-component-xfwt7)

The good thing is, I have tried to update to the latest ag-grid-community and ag-grid-react version. CSS is working in the latest version, but the `useLayoutEffect` error is still present.

**Comment by seanlandsman** [comment] 2020-04-01 09:01
thanks @Paul6552

**Comment by alfonmga** [comment] 2020-04-12 00:02
> In the mean time, try passing `disableStaticMarkup={true}` in your grid options, that should remove the error for now.

That worked for me too.

Could you explain me what `disableStaticMarkup` prop does exactly? I can't find anything about it in the docs. Is it safe to leave it in a production environment? thanks.

BTW I can't find `AG-3992` in the ag-Grid pipeline.

**Comment by BernieSumption** [comment] 2020-04-12 14:23
Although it is "safe" to use `disableStaticMarkup={true}` in production, we recommend that for the moment you ignore the console error and only use `disableStaticMarkup={true}` if you are observing issues with behaviour.

Static markup rendering is an internal performance optimisation we introduced in v23 to render React components faster. When used on a component that uses `useLayoutEffect` you get this console warning, but it should not have any adverse affect on behaviour. We are looking at ways to silence the warning in the next release, but in the mean time it is safe to ignore.

**Comment by juhahinkula** [comment] 2020-04-15 11:51
I have the same issue with ag-grid and Material-UI.  `disableStaticMarkup` helps but is there coming any fix for this? I can't either find AG-3992 in the pipeline.

**Comment by seanlandsman** [comment] 2020-04-15 14:04
AG-3992 fixes this and will be in our next release. It isn't appearing in our pipeline due to a minor internal issue but this should be rectified soon.

AG-3992 has however been implemented so will definitely be available in our next release.

**Comment by Paul6552** [comment] 2020-05-04 08:13
@seanlandsman 
There is still something wrong with ag-grid and css. It is working with version 22.1.1
Pls have a look here: 
[Codesample](https://codesandbox.io/s/react-functional-component-xfwt7?file=/src/index.js)
The button are green colored. Perfect

Now change the ag-grid version to 23.1.0
The buttons are blue. I don`t know why, but ag-grid is altering material-UIs css.

**Comment by seanlandsman** [comment] 2020-05-04 08:41
@Paul6552 thanks for reporting this - I've raised an issue our side (AG-4177).

You can track its progress in our pipeline: https://www.ag-grid.com/ag-grid-pipeline/

thanks

**Comment by Paul6552** [comment] 2020-05-26 12:41
Maybe you found time to find the problem?
We are still on version 22 because of this bug (sadly there is another annoying bug, fixed in version 23.1.0)

**Comment by lohithram** [comment] 2020-10-29 14:44
Hi Paul6552 and anyone else interested in the solution for this issue.
Wrap the custom component you are using with `<StylesProvider injectFirst>`

The root cause is - when ag-grid does server side rendering, the components somehow loose access to context. Without the style options and custom theme unavailable, the CSSinJSS starts injecting core MUI styles at the bottom of the head which has higher specificity than the CSS injection before it. This was causing the issue in my case and am guessing you might have faced the same problem.

**Comment by Paul6552** [comment] 2020-11-09 18:45
@lohithram 
Thank you for that information! I will try it out.

I think this information is important for @seanlandsman , as many "React Portal issues" have been on the "next release" agenda for several versions, but they have not yet been resolved.

**Comment by seanlandsman** [comment] 2020-11-09 19:54
I agree - and thanks @lohithram for raising/discovering it

fwiw we've put aside resources to focus exclusively on React over the next couple of releases to resolve these outstanding issues 

With any luck the next, but failing that the release after, will resolve most if not all outstanding React related issues.
