### ISSUE TITLE
paste data cell focus case screen scroll

### ISSUE THREAD

**Issue by jjsuo** [ag-grid/ag-grid#4206] opened 2020-11-19 02:58 UTC
when I Slide to the hidden position of the table's header，then use Ctrl+C and Ctrl+V paste data.it will happen.
![issue](https://user-images.githubusercontent.com/6995664/99615287-1a327300-2a56-11eb-837e-294c7a0024e5.gif)
I want prevent scroll

**Comment by makinggoodsoftware** [comment] 2020-11-19 11:31
Hi,

Just tried this on my end, using this example with Chrome/MacOs

https://www.ag-grid.com/javascript-grid-clipboard/#more-complex-example

Could not reproduce it...

Could you let us know what browser/OS you are using?

Thanks

**Comment by jjsuo** [comment] 2020-11-20 01:59
> Hi,
> 
> Just tried this on my end, using this example with Chrome/MacOs
> 
> https://www.ag-grid.com/javascript-grid-clipboard/#more-complex-example
> 
> Could not reproduce it...
> 
> Could you let us know what browser/OS you are using?
> 
> Thanks
chrome 86.0.4240.75/windows 10

**Comment by jjsuo** [comment] 2020-11-20 01:59
chrome 86.0.4240.75/windows 10

**Comment by jjsuo** [comment] 2020-11-20 02:00
chrome 86.0.4240.75/windows 10  @makinggoodsoftware

**Comment by makinggoodsoftware** [comment] 2020-11-24 15:19
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2020-11-25 19:19
Hello jjsuo!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4827 Pasting a value when the grid is partially out of view scrolls the page up to headers then back down to pasted cell**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date and whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/


I would recommend signing up for automatic release notifications for ag-grid. Then, following a release, check whether the item was implemented by looking for it in the ag-grid.com changelog page.

Thanks again for bringing this up with us.

**Comment by makinggoodsoftware** [comment] 2020-12-02 12:20
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2020-12-02 12:20 UTC
Labels: in_zendesk
