### ISSUE TITLE
this.rowIndex is null in relation to cleanup in empty grids that use reactUi

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4767] opened 2021-11-10 17:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I don't have time to create a repro atm, but this is the scenario:
1. I have a grid with `reactUi={true}` and that uses the partial serverside model, along with masterDetail
2. The grid gets initialized and fetches data, 0 rows are returned (expected) so the grid is empty
3. I update the datasource (since one of the params in getRows gets updated), which should trigger another data fetch.
4. Instead, the grid crashes with the following stack:

![Screen Shot 2021-11-10 at 6 50 40 PM](https://user-images.githubusercontent.com/649260/141166320-34021774-3715-4bb1-833a-5f169086418e.png)

Setting `reactUi` to `false` fixes it.

**Expected behavior**
It should not crash.

**Please tell us about your environment:**
React 17.0.2

* **AG Grid version:** Enterprise 26.1.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0"

* **Language:** TypeScript 4.4

**Comment by makinggoodsoftware** [comment] 2021-11-12 15:47
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by fgblomqvist** [comment] 2021-11-15 17:14
It is not a support question, it is a bug report, and while we have a license, it is more useful to post issues here where everyone can see them and find them rather than on a closed platform where it will only benefit the enterprise users.

**Comment by harokevin** [comment] 2022-04-21 17:57
Should be reopend

**Comment by margarytaviter** [comment] 2022-05-11 15:18
The error is pretty much similar to this DnD issue: https://github.com/ag-grid/ag-grid/issues/5156

**Comment by kiril-matev** [comment] 2022-08-16 10:30
Hi @fgblomqvist!

Thank you for reporting this. 

You are correct - this is a bug report and we'd like to look into this further. 

I'm not sure how you get the impression we believe the new React renderer is perfect - we welcome your feedback and are looking forward to partnering with the community to take AG Grid to the next level in terms of stability and performance. This channel is a key part of this effort so please keep the feedback coming.

We're keen to start our investigation of this specific issue. We need a live sample to reproduce the issue as per our bug report template. 

Can you please provide a live example reproducing this issue?

We're looking forward to your response so we can progress this.

**Comment by StephenCooper** [comment] 2023-05-02 09:13
I am going to close this issue as without a reproduction we are unable to resolve this. 

If this is still happening in v29 then feel free to re-open but I suspect that with all the improvements to the React UI since v26 this will have been fixed.

**Closed by StephenCooper** 2023-05-02 09:13 UTC
Labels: in_review
