### ISSUE TITLE
sticky group header bug

### ISSUE THREAD

**Issue by Alkimay** [ag-grid/ag-grid#6451] opened 2023-04-12 11:12 UTC
when using rtl localize, when grouping by some field,  and pinning the grouped item to right, and using sticky group feature,  when scrolling it change the sticky header position mixed it do weired stuff

https://user-images.githubusercontent.com/96352572/231440577-17174192-6a89-4c6c-8a32-34ddc590374b.mp4

**Comment by StephenCooper** [comment] 2023-04-17 08:56
Thanks for the video but would it be possible for you to reproduce the issue in a minimal code sample?

That will help us investigate this issue further.

**Comment by StephenCooper** [comment] 2023-05-25 09:12
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8639 Sticky group header bug

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-05-25 09:12 UTC
Labels: AG-8639

**Comment by gportela85** [comment] 2023-05-30 12:51
@Alkimay We have patched the issue shown on your video, however, there is a different problem related to Sticky Rows + RTL that happens because Chrome scrolls RTL containers when their size becomes 0. 
We have submitted a BUG report here https://bugs.chromium.org/p/chromium/issues/detail?id=1449429 

It would be ideal if you and other people you know who care about this issue could "star" this issue to make it more noticeable by the Chromium team.
