### ISSUE TITLE
ensureIndexVisible(rowNode.rowIndex, 'top'); not working in V30

### ISSUE THREAD

**Issue by sonicviz** [ag-grid/ag-grid#6794] opened 2023-06-21 15:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I just updated from V28.2.1 to V30
All looked ok and then I noticed that my rows were no longer scrolling back to the top with 
                this.gridApi.ensureIndexVisible(rowNode.rowIndex, 'top');

I have paginated scrolling that is triggered when a reset Grid button is clicked, to find the right page, and then scroll to the correct current selected and highlighted row index.

            if (rowNode) {
                rowNode.setDataValue('selected', true)
                var page = Math.floor(rowNode.rowIndex / this.pageSize);
                this.gridApi.paginationGoToPage(page);
                this.gridApi.ensureIndexVisible(rowNode.rowIndex, 'top');
            }

In V30, I can navigate to another page, scroll down, hit my reset grid button to trigger the above code, and it will gp back to the correct page but it will not scroll the selected highlighted row into view. 

**Expected behavior**

Without the bug the selected highlighted row is scrolled to the top of the page when I reset the grid that triggers the above code. I can page to another page, scroll down, hit "reset grid" to tigger the above code, and the grid will navigate to the correct page (80 rows per page) and then show the selected highlighted row at the top. 

                this.gridApi.ensureIndexVisible(rowNode.rowIndex, 'top');

I reverted back to V28.2.1 and the expected behavior is back. 
In V30 the code shown in current behavior correctly goes back to the right page, but no longer scrolls the selected row into view at the top. 

ensureIndexVisible as shown under scrolling https://www.ag-grid.com/javascript-data-grid/grid-api/

**Please tell us about your environment:**

Win 11 X64

* **AG Grid version:** V30 and V28.2.1

* **Browser:**

"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/604.1.38 (KHTML, like Gecko) Chrome/49.0.2623 Safari/604.1.38 CoherentGT/2.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Javascript

**Comment by kiril-matev** [comment] 2023-06-21 16:24
Hello @sonicviz,

We're keen to look into this but we can't reproduce the issue you've reported based on the context you provided.

**Please send us a live reproduction example (plunker sample) we can use to investigate.**

Looking forward to your response.

**Comment by kiril-matev** [comment] 2023-06-21 18:31
Hi @sonicviz,

Thanks for this response.

We don't doubt your report that there is an issue on your end so a video would really help. We are keen to investigate and we can't investigate what we can't reproduce locally. 

In case you can't reproduce this in a plunker sample, please build a separate small project to reproduce it, then ZIP the source code and send over to us. 

Looking forward to your response.

**Comment by sonicviz** [comment] 2023-06-22 04:41
Hi Kiril, 

Here's a video (unlisted) that demonstrates V28.2.1 (expected behavior, first half of video) with V30 (not working as expected, second half, no code changes just swapped the import): https://youtu.be/XzSEAWghYe8 

I did a PNKR with the basic functionality with both versions, but the error doesn't reoproduce: https://plnkr.co/plunk/SaPbDchbcHvkQRYp

As explained above in other message, and as you can see in the video, libraries etc tend to only show certain issues when used in context of an application in situ. In this case you can certainly see the behavior is different. In particular, not the strange double flash on the selected row of the ATR plane test in V30 when it should be scrolling to the top as it does in V28.2.1

Not sure what else to try here. No code on my side has changed, just the library.

**Comment by kiril-matev** [comment] 2023-06-23 10:19
Hi @sonicviz,

Thank you for this response.

Thank you for the plunker sample. However, it's not useful because it's not clear what series of steps you're following to cause the issue. This is why when providing a reproduction sample, please include a list of steps to execute (a test case) with the sample and a description of the actual vs expected behavior.

I agree the correct operation of **ensureIndexVisible** API is key for a good user experience. However, we still don't have the necessary information needed to reproduce this issue. 

I understand that some issues are only reproducible as part of a larger application and this makes them harder to reproduce separately. However, as we don't have the larger application you're working with, it's impossible for us to know what the circumstances of this issue are, so we can reproduce it and investigate it. 

Our bug submission process requires submitting a sample and you are best-positioned to build one as you can see the issue in action and you can go through a process of narrowing it down to identify the circumstances of it occurring. For example:
1. You can use different versions of AG Grid in your application to see the exact version where this behavior changed
2. You can try out different configurations of AG Grid (for example, hiding some of the columns or modifying the size of row buffer or turning off row virtualization altogether) to see if the issue is resolved or not
3. You can update the way application supplies data or makes API calls to the grid to see if the issue is resolved or not

We cannot do any of this and we won't be productive doing any investigation of an issue we cannot reproduce. By following this process you can identify the minimal reproduction scenario and can build a separate sample to reproduce this which you can send to us.

**Comment by sonicviz** [comment] 2023-06-23 10:50
It seems like you didn't even watch the video, which clearly demonstrates the issue. 
I also explained clearly why this is difficult to provide you with a reproducable demo. 

You know the code best, so it must be possible to at least infer what might be the issue with that particular functional area no?

**Comment by kiril-matev** [comment] 2023-06-23 12:34
Hi @sonicviz,

You're right - trying to make a reproducible demo in plunker/stackblitz would be time consuming for you, but it is still possible because you have the application where this is reproducible. As we don't have this application, it is practically impossible for us or anyone else to build a reproduction example.

I think narrowing down the cause in terms of which version introduced the issue may be of little use, so I wouldn't recommend spending time on this or on investigating the particular line of code in AG Grid that causes this. This is because unless we have a test case to reproduce the issue locally we can't investigate it. Unless we have a test case we can execute locally, we can't validate the issue was fixed after we make a change. 

This is why the best use of time is to build a standalone example which reproduces the issue. 

I would recommend an iterative approach:
1/ Progressively reduce the configuration applied to AG Grid to identify a minimum configuration where this occurs. Here are examples of reducing the configuration of AG Grid:
1.1 If you're using 10 columns in AG Grid and it's reproducible with just one, remove the 9 columns)
1.2 If you're using row/range selection and it's reproducible without, remove row/range selection
1.3. If you're using custom cell renderers and it's reproducible without, remove the custom cell renderers
1.4 Any additional configuration that can be removed while still reproducing the issue, remove it. 

This way you'll identify the minimal configuration that causes this issue.

I understand your application is complex and uses external APIs to get data, etc. This is why, when building the reproduction example:
2/ Use a mock backend of your application, providing static dummy data 
3/ Use buttons in the UI to call AG Grid API functions that your application calls automatically to cause the issue.

Looking forward to your response.

**Comment by sonicviz** [comment] 2023-06-23 13:31
Thanks for the info. 

It was definitely introduced in V29, which I just tested. 
Other suggested tests in your initial reply above fail to have any impact.

Question is, what changes did you introduce in V29 that cause this to happen?

 Version issue appears at:
		○ OK
			§ V28.2.1
		○ Fails
			§ V29 
	• Modifying the size of row buffer 
		○ See [Row Buffer](onenote:
		○ rowBuffer: 0 FAIL
		○ rowBuffer: 50 FAIL
		○ rwoBuffer: 150 FAIL (just for kicks)
	• Turning off row virtualization altogether
		○ See [Row Buffer](onenote:
		○ suppressRowVirtualisation: true,
		○ FAIL
	• suppressMaxRenderedRowRestriction: true,
		○ FAIL

**Comment by sonicviz** [comment] 2023-06-23 14:25
I'm seeing this in the log, with debug on:

[Log] PC2 UpdateSelectedPlane resetSelectedPlane moved to page: 0 rowNode.rowIndex: 63 (PlaneSelection.js, line 2344)
[Log] AG Grid.selectionService: reset (ag-grid-community.min.js, line 8)
[Log] AG Grid.selectionService: reset (ag-grid-community.min.js, line 8)
[Log] PC2 UpdateSelectedPlane index: 63 Name: Late-631 (PlaneSelection.js, line 2311)
[Log] PC2 UpdateSelectedPlane this.currentSelectedAircraft: 63 (PlaneSelection.js, line 2323)
[Log] PC2 UpdateSelectedPlane rowNode:  (PlaneSelection.js, line 2330)
[Log] e {rowIndex: 63, key: null, childrenMapped: {}, displayed: true, rowTop: 2898, …} (PlaneSelection.js, line 2331)
[Log] PC2 UpdateSelectedPlane resetSelectedPlane moved to page: 0 rowNode.rowIndex: 63 (PlaneSelection.js, line 2344)

Is "[Log] AG Grid.selectionService: reset (ag-grid-community.min.js, line 8)" relevant at all?

**Comment by kiril-matev** [comment] 2023-06-23 15:53
Hi @sonicviz,

Thanks for this response.

Logs and event stack traces aren't helpful in reproducing an issue. We need to have a reproduction scenario that we can use to reproduce the issue and validate a fix of the issue.

As you can see, AG Grid v29 introduced a great number of changes listed here:
https://ag-grid.com/changelog/?fixVersion=29.0.0

We cannot pinpoint a particular change that's causing this based on the context you've provided.

As I mentioned earlier, the only way to report this issue to us is with a reproduction example, especially in this case as even you can't reproduce the issue outside of your application. You need to iteratively strip out parts of your application backend and replace it with a mock backend if that's needed to reproduce the issue in a standalone project you can send to us.

Building an isolated reproduction example takes time but in our experience it's the quickest way to work on an issue. 

We are ready to investigate this potential issue once we receive a reproduction example.

**Comment by sonicviz** [comment] 2023-06-23 16:14
>>Logs and event stack traces aren't helpful in reproducing an issue. 

I have to disagree with that.
Logs and tracing are most definately useful when you can't physically reproduce an issue. 
I had a user in the UK recently who's controllers were not switching, the only way I could debug it was to send a custom instrumented build to trace out what was happening. With enough information from debugging and logging you can deduce where the issue lies, if the system is instrumented to output useful information like that. 

Doesn't debug provide anything useful?

I'm guessing it has something to do with:

Selection

selectIndex, deselectIndex - removed, use rowNode.setSelected(isSelected) instead.
selectNode, deselectNode - removed, use rowNode.setSelected(isSelected) instead.
getSelectedNodesById - removed, use getSelectedNodes instead.
isNodeSelected - removed, use rowNode.isSelected instead.
getRangeSelections - removed, use getCellRanges instead.
addRangeSelection - removed, use addCellRange instead.

or 

Display

ensureColIndexVisible - removed, use ensureColumnVisible instead.
doLayout - removed, no longer required as grid now responds to size changes.
checkGridSize - removed as was legacy and no longer required.
getFirstRenderedRow, getLastRenderedRow - removed, use getFirstDisplayedRow, getLastDisplayedRow instead.
addVirtualRowListener - removed, use addRenderedRowListener instead.

But I'm not using any of those. 
It has to be related to selection and scrolling, somehow. 

Are you supposed to be using rowNode.setSelected(isSelected) for ensureIndexVisible to work now?

>>You need to iteratively strip out parts of your application backend and replace it with a mock backend if that's needed to reproduce the issue in a standalone project you can send to us.

That's not feasible. There's also no guarantee it will work.

**Comment by sonicviz** [comment] 2023-06-24 03:37
I tried debugging using the unminified version but it would not load it, so reduced to debugging with the minified version.
Stepping through the relevant code in ensureIndexVisible shows that V30.0.2 is coming up with the wrong numbers. 
Also, added from V29 on was gridBodyComp\fakeVScrollComp.ts , which didn't exist in V28.2.1

V28.2.1 Debug
![image](https://github.com/ag-grid/ag-grid/assets/200370/2009d556-3e91-42b2-8a7d-5b8743628032)

V30.0.2 Debug
![image](https://github.com/ag-grid/ag-grid/assets/200370/0cf3c57e-70ac-466d-be04-39e9a6592a49)

**Comment by annaclatworthy** [comment] 2023-06-29 06:03
Hi - I have been having similar problems with ensureIndexVisible(top) where it is not producing the result I'm expecting, and I am currently working off the [car example data](https://www.ag-grid.com/example-assets/row-data.json). 

My environment: Angular 14, and Ag-Grid is the latest at 30.0.2. 

Say I call i = this.agGrid.api.getFirstDisplayedRow() and then later on call this.agGrid.api.ensureIndexVisible(i, 'top'), There is a 10 row difference in the results. If I call this.agGrid.api.ensureIndexVisible(i +10 , 'top'), I get the result I would expect.

Why is this?

**Comment by kiril-matev** [comment] 2023-06-29 09:25
Hi @annaclatworthy,

Thanks for reaching out.

It would be helpful if you provide examples to illustrate the specific configuration you're using. For example, you've not mentioned if you're using server-side row model, or whether you're using row auto-height, whether you're setting rowBuffer or any other setting. 

Settings in AG Grid can modify behavior to a great extent and it's very difficult to speculate which of the many (thousands) of configurations you're using. This is why we ask for sample projects to avoid delays due to multiple rounds of communication until we identify your actual configuration.

See below:
1. Open
https://plnkr.co/edit/9OdiN65EgQq9cOyR?open=main.js
2. Open console
3. Scroll down to row 40
4. Click SAVE VERTICAL SCROLL POSITION button above grid
Actual & Expected: Console shows first displayed row index as 29.
5. Scroll down a few rows
6. Click SCROLL SAVED ROW INTO VIEW button above grid
Actual & Expected: Row 29 scrolled into view
This is because the grid has a default **rowBuffer** value of 10 - this means 10 rows are rendered above and below the visible rows. The purpose is to have rendered rows to display when the user is scrolling instead of rendering them on the spot. See this documented here:
https://www.ag-grid.com/javascript-data-grid/dom-virtualisation/#row-buffer

This is why the first rendered row is 10 rows above the top row shown in the grid, and the last row rendered is 10 rows below the last row shown in the grid.

It seems to me you're using this approach to save and restore scrolling position. You have three options at this time:
1/ Using the approach you have now, you can add the default rowBuffer value to the first visible row index. This way you get the index of the actual first visible row on screen and then call ensureIndexVisible with this index.
https://plnkr.co/edit/BP711tKVT1tbuuqT?open=main.js

2/ Using the approach you have now, you can set rowBuffer=0. In this case the first displayed row is the top row shown in the grid. This way you can get the first displayed row index and provide it to the ensureIndexVisible method. Read the documentation above for the effect of setting rowBuffer.
https://plnkr.co/edit/IHKQNmUHVcP8feeC?open=main.js

3/ Using the **bodyScroll** event. You can save/restore the vertical and horizontal scroll positions using internal API members (as internal members they are subject to change):
1. Open
Example (JS): https://plnkr.co/edit/STPMHNk8wW2gl6S4 
Example (Angular): https://plnkr.co/edit/QrDOQiw4Zs2OuW11
2. Scroll the grid down
3. Scroll the grid right
4. Refresh the plunker preview using the small refresh button in the plunker preview pane (not the entire browser window)
Actual & Expected: Grid reloads, earlier scrollbar positions restored

Note in this sample the scroll position gets saved to local storage inside the onBodyScroll event handler. Also, onBodyScroll event handler gets called when the grid first initializes so we ignore the first call. The scroll positions get restored inside the **firstDataRendered** event handler which gets fired when the grid is rendered for the first time.

**Comment by zoheil-ag** [comment] 2023-07-31 08:55
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by zoheil-ag** 2023-07-31 08:55 UTC
Labels: waiting-for-repro

**Comment by sonicviz** [comment] 2023-07-31 09:01
Closing issues that are not resolved only to have them repopened?

**Comment by zoheil-ag** [comment] 2023-07-31 09:11
Hi @sonicviz,

Thank you for your response. Leaving older issues open will only clog up the view and make it more difficult for both AG-Grid and the wider community to provide support.

Following up on this thread, besides the lengthy explanation Kiril gave in the last comment, we have been waiting for a reproducible example/sample project. Not to open up the conversations surrounding that again, but the point remains that we will not be able to effectively look into this until we can reproduce it.

In any case, if you are able to provide an example/sample project we'd be more than happy to take a look and of course to re-open the issue. If you need any further guidance on that, please do let us know.

Kind regards,
Zoheil

**Comment by sonicviz** [comment] 2023-07-31 09:16
>> Kiril gave in the last comment, we have been waiting for a reproducible example/sample project. Not to open up the conversations surrounding that again, but the point remains that we will not be able to effectively look into this until we can reproduce it.

This tells me you didn't really listen to what I said. 
You cannot solve bugs with complex user issues with the only method being "give is a reproducable project or we can't do anything". Software doesn't work like that. It's only under user conditions that certain issues arise. 

I've solved two extremely hard user issues with my addsons using AG-grid that both involved elements of remote debugging, giving the users debug builds in order to gain insight into issues within their context. 

Your approach to demanding reproducable projects is a very limited system for solving hard problems that only show up in production on user systems. 

Why doesn't the logging work?
Why isn't their more extensive debugging insight? 

If there was I might be able to resolve it myself.
It would also, ultimately, benefit you to have better debug and logging tools in the application so users are better enabled to solving problems they may encounter in production environments.

**Comment by sonicviz** [comment] 2023-10-03 15:14
Good news. Just tried AGGrid V30.2.0 and vertical scroll is back.
Not sure if it was related to "AG-8914 [Regression] Vertical scroll position is wrong after calling api.ensureNodeVisible" from V30.1.0 as I didn't test that version. 

In any event, issue is now resolved without me having to change any code, and performance also seems improved. 

Whatever was changed, thanks!

**Comment by SalmanVolvoGit** [comment] 2024-08-20 08:47
So was any solution related to this provided from Ag-grid side ?

**Comment by sonicviz** [comment] 2024-08-20 12:32
No, no solution. Not interested in any of my feedback/suggestions either. 🤷‍♀️
