### ISSUE TITLE
AG Grid Custom Tool Panel throws exception

### ISSUE THREAD

**Issue by Vishwas-93** [ag-grid/ag-grid#7402] opened 2024-01-07 07:53 UTC
**I'm submitting a  bug report** 

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Tried a bunch to reproduce the problem but seems like a timing issue. The ToolPanelInstance is probably not initialized. We might need a null check before performing getState().

<img width="649" alt="Screenshot 2024-01-07 at 1 19 13 PM" src="https://github.com/ag-grid/ag-grid/assets/25495706/37122dba-1cbe-427f-9f0f-40036a3c3368">

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Cannot read properties of undefined (reading 'getState')

**Expected behavior**
Shouldn't throw an exception (Cannot read properties of undefined (reading 'getState'))

* **AG Grid version:** 31.0.1

* **Browser:**
All browsers

* **Language:** 
TypeScript

**Comment by olsio** [comment] 2024-01-08 08:13
Having the same issue. It does not show up in the documentation example when loading the dependency from the CDN but in a NPM project it always fails.

Custom component can be as simple as returning an empty div.

**Comment by AG-Zoheil** [comment] 2024-01-08 09:29
Hi @Vishwas-93 and @olsio,

Thank you for reporting this. If I understand correctly, you are saying you cannot reproduce the error on the available examples from our website but only on your projects.

If this is the case, please send us a mini-project to show the issue. This should be the most simplest form only consisting of the minimum code to replicate the error you are describing. This would be the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by olsio** [comment] 2024-01-08 13:29
Can't publish from company network. Had a ZenDesk ticket opened.

**Comment by jakeboone02** [comment] 2024-01-09 17:26
Looks like this is resolved with 2c23ea523f9f3679bc3e2a7b4a4c20941b521fbd. Hopefully released in 31.0.2 soon?

**Comment by AG-Zoheil** [comment] 2024-01-10 10:02
Hello,

Good find!

Yes **AG-10168** will be in our release next week.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-01-10 10:02 UTC
Labels: AG-10168
