### ISSUE TITLE
Cell class & refreshing data causes an internal error

### ISSUE THREAD

**Issue by inthegarage** [ag-grid/ag-grid#4812] opened 2021-12-03 17:44 UTC
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
When using cell class (I think) or maybe cell style, upon refreshing the data an exception is seen:

```
ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at CellCustomStyleFeature.applyClassesFromColDef (ag-grid-community.cjs.js:20788)
    at CellCtrl.refreshCell (ag-grid-community.cjs.js:22001)
    at ag-grid-community.cjs.js:22920
    at Array.forEach (<anonymous>)
    at RowCtrl.onRowNodeDataChanged (ag-grid-community.cjs.js:22919)
    at ag-grid-community.cjs.js:1350
    at Set.forEach (<anonymous>)
    at processEventListeners (ag-grid-community.cjs.js:1345)
    at EventService.dispatchToListeners (ag-grid-community.cjs.js:1355)
    at EventService.dispatchEvent (ag-grid-community.cjs.js:1334)
```

This appears at this code point which was introduced after version 25.3.0:

        if (this.staticClasses.length) {
            this.staticClasses.forEach(function (className) { return _this.cellComp.addOrRemoveCssClass(className, false); });
        }

This should be (this.staticClasses && this staticClasses.length) 

My cell definition ends as follows:

`
      cellClass: this.processEditableClass,
`

I am happy to send through a plunkr, please provide a link if available. This has to be 26.2.0 however of ag-grid.

Current behaviour.
When the data is got the second time (upon paging or filtering) using a datasource the error is seen. If I regress to 25.3.0 the error is no longer present. The version in error is 26.2.0

Expected behaviour.

There should be no error and use the trap above to ensure staticClasses aren't checked.

**Environment**
Angular, NG12 Windows or Linux

* **AG Grid version:*** 

26.2.0

* **Browser:**
All browsers show this.

* **Language:**

Typescript 4.4.5

**Comment by ldeveber** [comment] 2021-12-08 20:53
I'm seeing a similar trace in 26.2.0

```
Uncaught TypeError: this.staticClasses.forEach is not a function
    at CellCustomStyleFeature.applyClassesFromColDef (ag-grid-community.cjs.js?7fb8:20793)
    at CellCustomStyleFeature.setComp (ag-grid-community.cjs.js?7fb8:20729)
    at CellCtrl.setComp (ag-grid-community.cjs.js?7fb8:21636)
    at new CellComp (ag-grid-community.cjs.js?7fb8:44407)
    at RowComp.newCellComp (ag-grid-community.cjs.js?7fb8:44913)
    at eval (ag-grid-community.cjs.js?7fb8:44887)
    at Array.forEach (<anonymous>)
    at RowComp.setCellCtrls (ag-grid-community.cjs.js?7fb8:44883)
    at Object.setCellCtrls (ag-grid-community.cjs.js?7fb8:44830)
    at eval (ag-grid-community.cjs.js?7fb8:22802)
```

**Comment by inthegarage** [comment] 2021-12-09 12:38
I cannot get a plunkr to work with the latest Angular/AG Grid, so that was a bit of non-starter for me. I tried stackblitz, and when it does work (occasionally) it seems to have some problem showing the grid. However here is my sample project, which should show the error if you set it up in your local:

https://stackblitz.com/edit/angular-ivy-ywsgbp

If you change the filters, there should be the error in the console.

If you need any further input let me know.

**Comment by inthegarage** [comment] 2021-12-10 16:07
I also noticed this in the console, but I don't see anything in the code that is doing this:
`
Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.refreshView(), call setTimeout(function() { api.refreshView(); }, 0). To see what part of your code that caused the refresh check this stacktrace.`

**Comment by ZanyZephy** [comment] 2021-12-12 03:02
If cellclass is a function, it must have a return value
`cellClass:(params)=>{}`

**Comment by inthegarage** [comment] 2021-12-13 08:47
@ZanyZephy That is what my code in stackblitz does, please check. This is regression in V.26 of the library, if you move the version down to 25, you see that the error is gone.

This line is faultive in ag-grid code:

    if (this.staticClasses.length) {

It should check the presence of staticClasses too. (train wreck anti-pattern)

**Comment by makinggoodsoftware** [comment] 2021-12-22 14:56
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by inthegarage** [comment] 2021-12-22 15:00
@makinggoodsoftware thanks for that. Looking forward to the fix.

**Comment by VyacheslavAS** [comment] 2021-12-30 16:08
Hi,
I found [this issue](https://stackoverflow.com/questions/69220165/react-typescript-ag-grid-cannot-read-property-addorremovecssclass-of-undefi) on StackOverflow, two people reported it and I faced the same today.

Could you please tell if it's the same and will be fixed with the current one or not?

**Comment by inthegarage** [comment] 2021-12-30 16:11
@VyacheslavAS 
Appears different to me, as in its different code, but similar train crash antipattern. If you think its a. Issue create a stackblitz with a simple example.

**Comment by yogeshkudikala** [comment] 2022-01-01 08:04
I am also facing same issue using ag-grid in vue 2. 
![image](https://user-images.githubusercontent.com/51023000/147846614-b2a5b3f6-0556-44bf-be8f-5c88d4ed5b1c.png)

**Comment by crumhorn** [comment] 2022-01-06 15:26
> If cellclass is a function, it must have a return value

This seemed to fix it for us, just ensuring that all paths return a value. Still annoying that this suddenly changed.

**Comment by kiril-matev** [comment] 2022-01-11 12:15
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v26.1

Until this is fixed please use the following workaround - add a  return statement with an empty string to cover other potential paths of the cellStyle function, as shown in the following example: 
https://plnkr.co/edit/QwSn5XrLufuJw1Xx

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6235 [Regression] When setting cellClass for a column but not returning any value for some cells, an exception is thrown and cells without a style set aren't rendered**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-01-17 16:13
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-01-17 16:13 UTC
Labels: in_zendesk

**Comment by Takobz** [comment] 2022-01-25 14:59
In my case I had something like this in my Column definition array :
`cellClass: function (params) {
     if(condition) return"someClassName";
     return null;
 }`
 
As mentioned by @crumhorn above returning `null` made my grid rendering fail. It was hard to debug since this happened sometimes as I returned `null` or a string depending on some condition.

Thank you very much guys, saved my life!!

**Comment by nandysouvik** [comment] 2023-07-31 10:37
i also noticed

Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
