### ISSUE TITLE
autoSizeAllColumns(true) not working

### ISSUE THREAD

**Issue by MadalenaPavao** [ag-grid/ag-grid#4843] opened 2021-12-21 16:40 UTC
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior** I want to adapt column width to the content of the column, not taking into account the headers. But using autoSizeAllColumns with the boolean skipHeaders set to true, the columns collapse. 
```
onFirstDataRendered={() => {
          gridRef.current.columnApi.autoSizeAllColumns(true);
        }}
```
![image](https://user-images.githubusercontent.com/32294501/146965448-653a80a7-4678-4c49-b423-7277276f9872.png)

**Expected behavior** Columns to adapt their width to the content (skipping the headers)

**Please tell us about your environment:** Ubuntu, VSCode, npm, React 17.0.1

* **AG Grid version:** 26.2.1

* **Browser:** Google Chrome

* **Language:** Javascript

**Comment by gportela85** [comment] 2021-12-21 22:10
Can you post a plunker reproducing the issue?

**Comment by MadalenaPavao** [comment] 2021-12-22 15:17
> Can you post a plunker reproducing the issue?

It's not really possible, but I can show a bit more code if it helps.

**Comment by MadalenaPavao** [comment] 2021-12-22 15:18
```
<Grid
      style={{
        height: 400,
        width: "100%",
        border: "1px solid red",
        padding: "20px",
      }}
      className="ag-theme-material"
    >
      <AgGridReact
        modules={AllModules}
        columnDefs={columnDefs}
        ref={gridRef}
        rowModelType={"serverSide"}
        onFirstDataRendered={() => {
          console.log("onFirstDataRendered");
          gridRef.current.columnApi.autoSizeAllColumns(true);
          //gridRef.current.api.sizeColumnsToFit();
        }}
        frameworkComponents={frameworkComponents}
      />
    </Grid>
```

**Comment by gportela85** [comment] 2021-12-22 17:39
This code is running fine locally and also works well in our docs examples. I'll close this issue as "Cannot Reproduce" right now, but if you manage to create a reproducible scenario, feel free to post it here and I'll reopen it. 

However, because you are using SSRM, maybe add the  `columnApi.autoSizeAllColumns(true);` to your `getRows()` method, after you set params.success(). It could be a timing issue.

**Closed by gportela85** 2021-12-22 17:39 UTC
