### ISSUE TITLE
Context menu can easily end up cut off when grid is small and near edge of screen. Need option to provide a target parent that will hold the menu or auto-scroll on no space.

### ISSUE THREAD

**Issue by crumhorn** [ag-grid/ag-grid#1448] opened 2017-01-31 14:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have an Ag-Grid somewhere near the edge of the screen (mostly it's at the bottom where this bug  presents itself), a big context menu (bigger than the grid height) easily gets cut off unless the grid also has a lot of height. A small grid can't contain a big menu and doesn't scroll vertically or offer options to show the menu elsewhere (in a higher up parent div).

**Expected behavior**
It would be expected that the context menu goes into scroll-mode when it can't fit the given space. Even better would be that it both does this, and that the user can define a div ID/Class ID where the menu should show up rather than being contained within the grid div. I tested this briefly by overriding some methods in the popupService.js and it works fine, unfortunately I couldn't override everything so there's no workaround for moving it to another div. 

**Minimal reproduction of the problem with instructions**
I haven't made a Plunkr. If the issue isn't clear let me know and I can make one. Essentially a big context menu in a small grid within some containing divs at the bottom of the page (where the context menu can't cover the outer divs) is all it takes.

**Workaround: Auto-scroll when no space (using Angular 2 in my case, not required)**
Note: this workardound is not universal, it's just to show how it could work. 
To force the menu into scroll mode when it dosn't fit, with the help of jQuery (".ag-blue" is a class on my ```<ag-grid-ng2 />``` tag

```
ngAfterViewInit() {
       this.gridOptions.api.addEventListener("cellContextMenu", (ev) => {
            setTimeout(() => {
                let menu = $(".ag-menu");
                let offset = $(menu).offset();
                let calc = ($(menu).outerHeight() + offset.top);

                if (calc > window.innerHeight) {
                    $(menu).height($(".ag-blue").height());
                    $(menu).css('overflow-y', 'scroll');
                }
            });
        });
}
```

**What is the motivation / use case for changing the behavior?**
The motivation would be that the context menu in its current way is not usable in our project context.

**Please tell us about your environment:**
Angular 2.4.5, Windows

* **ag-Grid version:** X.X.X
Ag-Grid 7.2.2/7.2.4 Enterprise

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2. ES6.

**Comment by seanlandsman** [comment] 2017-01-31 14:56
Hi

Thanks for reporting - this is a known issue and already on our backlog (https://www.ag-grid.com/ag-grid-pipeline/): AG-179

I'll add a comment referencing this issue too though

**Comment by crumhorn** [comment] 2017-06-28 11:26
It's been a while since I checked in on this feature, I no longer see this issue in the list, but taking out my workaround code doesn't seem to show a scroll bar in the context menu. What happened to the issue?

**Comment by seanlandsman** [comment] 2017-06-29 08:35
Hi

I've taken a look and can see that AG-179 has been marked as a duplicate of AG-62. Please reference AG-62 going forward for this issue

thanks

**Comment by makinggoodsoftware** [comment] 2017-12-19 09:06
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Closed by makinggoodsoftware** 2017-12-19 09:06 UTC
Labels: bug
