### ISSUE TITLE
[bug] row background-colors flicker with high frequency prepends

### ISSUE THREAD

**Issue by daenerysIII** [ag-grid/ag-grid#5037] opened 2022-03-31 10:12 UTC
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/kLUAwWYdled5uRsN

**Current behavior**
the background colors are inconsistent and flicker, they dont keep their background color based on odd/even
video: https://www.youtube.com/watch?v=MJGYub6mRAg

**Expected behavior**
the background color of the rows should be consistent

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
ag-grid-enterprise@26.2.1

* **Browser:**
Chrome/Brave

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
vue2

**Comment by makinggoodsoftware** [comment] 2022-04-07 10:17
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-04-21 17:53
Hello @daenerysIII!
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a regression from v26.2.
 
Until this is addressed, please use the workaround below, setting the cellStyle property on the defaultColDef (so it applies to all columns).
https://plnkr.co/edit/tqmqxvJ7g4EjONd6
 
Please note that clicking the button above the grid to add new rows doesn't cause flicker in the above sample.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6702 [Regression] When setting row style dynamically, adding new rows via applyTransaction causes row styles to flicker**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment] 2022-06-21 11:23
Hello @daenerysIII,

We've looked into this and found it to be expected behavior because of the way the styles are applied. 

In order to avoid the flickering of row styles when adding new rows, please call the refreshCells API method after applying a transaction:
https://plnkr.co/edit/0Hig9QvOeg2hJsws

Click the button above the grid to add new rows and not rows no longer flicker.

Please use this approach to resolve this in your code.

Thank you for your time in reporting this!

**Comment by daenerysIII** [comment] 2022-06-23 19:19
hello @kiril-matev ,

there is still a problem with this solution if you have high frequency inserts.
I recorded a small video: https://www.youtube.com/watch?v=GWkzEI5IV6I

I changed the interval to 10 Milliseconds and then you can get 2 rows after another that display the same color.

thanks for looking into this :)

**Comment by kiril-matev** [comment] 2022-06-30 15:01
Hi @daenerysIII,

I've updated the earlier live sample to use 10ms delay as you suggested but I cannot reproduce the flickering of row styles.

Please see the GIF recording below for an illustration.

Steps to follow:
1. Open
https://plnkr.co/edit/iEtaRPZ7hGj2dxk2?preview
2. Click button above grid
Actual & Expected: New rows added to grid, no style flickering

![CPT2206301600-637x571](https://user-images.githubusercontent.com/60937283/176710593-19c73150-7240-4377-97e3-8d919825b8aa.gif)

Can you reproduce this behavior with the sample above?

**Comment by daenerysIII** [comment] 2022-07-07 11:22
@kiril-matev,
the flickering is gone for me too, but the issue that 2 rows get the same color still happens for me.
I recorded it with your example link

https://www.youtube.com/watch?v=2z6soxxMaeE

**Comment by kiril-matev** [comment] 2022-07-29 22:06
Hi @daenerysIII,

Thanks for this response.

Can you please provide a reproduction sample for this so we can investigate further?

**Comment by daenerysIII** [comment] 2022-07-30 08:18
@kiril-matev 

the video is the example that you posted
https://plnkr.co/edit/iEtaRPZ7hGj2dxk2?preview

its just that I have dark mode on and so it looks different

**Comment by kiril-matev** [comment] 2022-08-10 16:30
Hi @daenerysIII,

Thanks for this.

I activated dark mode on a Windows PC and opened the plunker in Chrome/Firefox/Edge. However, the plunker sample never changed its appearance to the dark one you have in your video and works as expected.

Please answer the questions below:
1. What OS and browser are you using?
2. If you turn off dark mode, can you reproduce this issue?

**Closed** 2022-09-28 15:40 UTC
Labels: ag-6702, in_review
