### ISSUE TITLE
Grid collapses if data is changed quickly on version 30+

### ISSUE THREAD

**Issue by PointSingularity** [ag-grid/ag-grid#6885] opened 2023-07-19 13:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Disclaimer: bad code  - [reproduction](https://codesandbox.io/s/kind-shtern-k88gk8?file=/src/grid.tsx) 

Basically, if the data is changed very quickly, the grid collapses.
If you change the version number of AG-Grid to 29.2.0 in the sandbox, this error doesn't happen.

My real code does not change data this quickly, but there are some parts that cause a chain reaction of changes, which results with a small flickering, which did not occur on versions under 30.

Maybe there is a way to circumvent this, so if you have any insight, that would be helpful.
Thank you in advance!

**Please tell us about your environment:**
Windows 10
VS Code

* **AG Grid version:** 30.0.5

* **Browser:** Chrome 115

* **Language:** React 18.2.0 | TypeScript 5.1.6

**Comment by StephenCooper** [comment] 2023-07-25 09:18
Hi @PointSingularity,

Can I just confirm that the intention with the reproduction is to show the effect of continuously calling AG Grid with new row data in a loop for a short period of time? As in when profiling I see when the random number is over 80 there is a loop causing continual rowData state updates. 

I think this is intentional to exaggerate the issue for us to investigate? Just making sure I am understanding the setup correctly.

**Comment by StephenCooper** [comment] 2023-07-25 10:23
Thanks for clarifying and putting together a reproduction for this. I am working closely on the React components now so this is a helpful example for me to gain more information.

**Comment by PointSingularity** [comment] 2023-07-25 13:16
@StephenCooper Thank you!

**Comment by StephenCooper** [comment] 2023-07-25 14:53
Just tried this against a rough spike of my React changes and I can see the behaviour is a lot more stable. So I am going to carry on with my work and keep this as a test case for when those changes are complete. I have a rough idea what is going on here and why it may have changed in v30. 

<hr>

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8906 [React Rendering] Row Components

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-08-07 09:07 UTC
Labels: AG-8906
