### ISSUE TITLE
undoRedoCellEditing does not work on grid with readOnlyEdit enabled

### ISSUE THREAD

**Issue by pummra** [ag-grid/ag-grid#5398] opened 2022-07-25 18:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Plunkr Link:
https://plnkr.co/edit/F9KImjuUZAXs8pGy?open=index.jsx

**Current behavior**
When working with a table which has data from an immutable source and using readOnlyEdit to allow for editing it is not possible to undo/redo edits with keyboard shortcuts. 

**Expected behavior**
When using undo/redo I would expect onCellEditRequest to be called with the appropriate newValue to allow the edits to be undone or redone. 

* **AG Grid version:** 
28.0.2

* **Browser:**
all

* **Language:** 
all

**Comment by StephenCooper** [comment] 2022-07-26 14:11
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-AG-7044
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7044) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/
 
Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-08-09 11:18 UTC
Labels: AG-7044

**Comment by kiril-matev** [comment] 2023-07-10 17:57
Hi @pummra,

Thank you for bringing this up with us. 
 
We've taken a second look at this and found that the behavior you described isn't a bug. This is actually expected behavior - data updates performed via API reset the undo/redo stack (and a data update is required when using readOnlyEdit=true). This is why we have now closed **AG-7044** as **rejected** and we have added a feature request in our backlog to track this requirement and implement it in the future.
 
You can track it with this reference:
**AG-4103 [Cell Editing] Allow pushing your own cell update operations to undo/redo stack to capture data changes performed in user code via API calls**
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!
