### ISSUE TITLE
Invalid parameter `--ag-borders: none`

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#6018] opened 2023-01-17 09:48 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I migrate styles from v28 to v29, and there is something strange with `borders` property:
```
@use "@ag-grid-community/styles" as ag;
@include ag.grid-styles((
  theme: alpine,
  borders: false,
));
```

> SassError: "Error in alpine parameters: Invalid parameter `--ag-borders: none` (expected either `none`, or a CSS border-style and size (e.g. `solid 1px`), or a boolean (true -> `solid 1px` and false -> `none`))"

* **AG Grid version:** 29.0.0

**Comment by StephenCooper** [comment] 2023-01-23 09:37
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7878 When setting Sass variables to "none", "false" or "true", theme fails to build**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7878) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-01-23 09:37 UTC
Labels: in_review, AG-7878
