### ISSUE TITLE
onCellEditRequest should be fired before calling isCancelBeforeStart on next cell editor

### ISSUE THREAD

**Issue by AlexTalis** [ag-grid/ag-grid#5502] opened 2022-08-24 00:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
https://plnkr.co/edit/KdnJlPJcIx1k4uQJ?open=index.tsx&preview

The example grid has readOnlyEdit=true.

Click and type something in the first column, then tab to the next cell. Grid first calls isCancelBeforeStart on the new cell editor, then fires onCellEditRequest for the previous edit. The example logs messages to the console for each of these events.

There is no way to use latest data in isCancelBeforeStart because client code has not been notified about the change made in the first edit. This is a problem if isCancelBeforeStart needs the latest value from the previously edited cell.

When readOnlyEdit=false and I use valueSetter for the first column the value setter is called first, before isCancelBeforeStart. That is the correct sequence of events.

**Please tell us about your environment:**
OS: Mac OS Monterey
AG Grid: 28.1.1
React: 18.2.0
Browser: Google Chrome

**Comment by StephenCooper** [comment] 2022-08-31 21:51
Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7216 onCellEditRequest should be fired before calling isCancelBeforeStart on next cell editor**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7216) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-09-01 20:59 UTC
Labels: AG-7216

**Comment by kiril-matev** [comment] 2022-10-03 11:55
Hello @AlexTalis,

We've looked into this further and found this is expected behavior. 

The reason why **isCancelBeforeStart** is called before **onCellEditRequest** is because all callback functions that are added in the form of “on<EventName>” to the GridOptions are async.

For example, “onCellEditRequest” will probably request an update from a server and there is no reason for us to freeze the grid until this request is fulfilled so we can then call **isCancelBeforeStart**. If your application has a particular scenario that allows for **onCellEditRequest** to be synchronous, they should use the property suppressAsyncEvents={true}. This will produce the behavior you described.

As this is expected behavior, we're closing this bug as rejected.

Thank you for using AG Grid!
