### ISSUE TITLE
refreshInfiniteCache doesn't trigger getRows when last call didn't get any results.

### ISSUE THREAD

**Issue by Ignasimg** [ag-grid/ag-grid#4415] opened 2021-03-23 14:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
At least since version 24.1.0 when using rowModelType infinite, and the getRows callback from the datasource is called with an empty array (0 rows), a call to api.refreshInfiniteCache() will not trigger a refresh for getRows().

**Expected behavior**
I'd expect api.refreshInfiniteCache() functionality not to be depending on whether last time getRows was executed got any results or not. 
And personally I think it should always trigger getRows() as it used to do at least until version 21.2.2

**Samples**
Same code but one with ag-grid-angular & ag-grid-community 21.2.2, and the other ^25.0.0 
Bug appears in the later when toggling.
21.2.2 - https://stackblitz.com/edit/ag-grid-angular-hello-world-hvsp5g?file=src/app/app.component.ts
^25.0.0 - https://stackblitz.com/edit/ag-grid-angular-hello-world-qfgfmp?file=src/app/app.component.ts

**AG Grid version:**
At least since 24.1.0 (used to work in 21.2.2) - still a bug in 25.1.0

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0

**Comment by makinggoodsoftware** [comment] 2021-03-25 16:55
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-07 16:49
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v23.0.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5232 [Regression] When using infinite row model and setting lastRow=0 in successCallback, calling refreshInfiniteCache no longer gets new data as getRows is not called anymore**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. 
The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-12 15:56
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-12 15:56 UTC
Labels: AG-5232, in_zendesk
