### ISSUE TITLE
Production build broken with 19.1.1 - Modules not found

### ISSUE THREAD

**Issue by martor** [ag-grid/ag-grid#2754] opened 2018-11-06 12:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
Modules are missing in dist/lib which are required for the build to work.
Checked current package in npm for version 19.1.1.

[ERROR] ERROR in ./node_modules/ag-grid-community/dist/lib/exporter/gridSerializer.js
[ERROR] ERROR in ./node_modules/ag-grid-community/dist/lib/columnController/autoGroupColService.js
[ERROR] Module not found: Error: Can't resolve './balancedColumnTreeBuilder'...
[ERROR] ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
[ERROR] Module not found: Error: Can't resolve './columnController/balancedColumnTreeBuilder'...
[ERROR] ERROR in ./node_modules/ag-grid-community/main.js
[ERROR] Module not found: Error: Can't resolve './dist/lib/columnController/balancedColumnTreeBuilder'...

The issue occurs when I try to build in production with AOT.
No issue in development without AOT.

**Expected behavior**
Building in production (AOT = true) should work.

**Please tell us about your environment:**
- Angular 6.1.4

* **ag-Grid version:** 19.1.1

* **Browser:** None

* **Language:** TypeScript 2.7.2

**Comment by martor** [comment] 2018-11-12 10:55
Unfortunately the issue persists in v19.1.2. Build fails with AOT enabled.

**Comment by makinggoodsoftware** [comment] 2018-11-13 15:47
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment] 2018-11-26 10:57
Hi this should have been fixed in 19.1.2]

**Comment by makinggoodsoftware** [comment] 2018-11-26 10:57
Sorry, looking at the history I can see that I jumped the gun, reopening it

We are investigating the AOT issue

**Comment by mbacon-edocs** [comment] 2018-12-11 16:32
What's the status of this? Can we expect a fix soon?

**Comment by makinggoodsoftware** [comment] 2019-02-06 15:54
Hi,

We can't reproduce this in our end anymore, can you check with v20? If this is still an issue, could you please follow up with a new issue and a reproducible scenario?

Thanks

**Closed by makinggoodsoftware** 2019-02-06 15:54 UTC
Labels: in_zendesk

**Comment by asanchezfe** [comment] 2019-04-29 13:51
Seems to be happening again in 20.2.0.

    Angular 7.2.12
    ag-Grid version: 20.2.0
    Browser: None
    Language: TypeScript 3.2.4
