### ISSUE TITLE
Trouble with tooltips inside custom chart renderer for a cell

### ISSUE THREAD

**Issue by paddymul** [ag-grid/ag-grid#6988] opened 2023-08-24 18:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**

I am using recharts inside of a custom cell renderer.  The charts display properly, but the tooltips are positioned outside of the chart area, and are obscured by the other pieces of the ag-grid layout.  I have tried setting `zIndex` of the tooltip to 999_991 (higher than the zindexs inside of ag-grid which are 99_999).  the tooltip is still obscured.

Here is a screenshot of the problem.
<img width="296" alt="Screen Shot 2023-08-24 at 2 17 33 PM" src="https://github.com/ag-grid/ag-grid/assets/40453/8a7eaef2-1e28-47a2-9a4f-3d8e69c33ee1">

Here is a plunker with that reproduces the problem.
https://plnkr.co/edit/UhSpd9j0708Dqqlf

Making the row tall enough to accommodate the tooltip is not a reasonable solution.

**Expected behavior**
I expect there to be a described way of setting `zIndex` or the other CSS required so that the tooltips will display completely.

* **AG Grid version:** X.X.X

* **Browser:**
* firefox
* chrome

**Comment by paddymul** [comment] 2023-08-24 18:33
I made another plunker that is just raw css in a custom component.  Still can't get the green box outside of the header.  I have tried different combinations of position for the enclosing divs. 

https://plnkr.co/edit/u8r1SQCyHsEjcvfo
<img width="650" alt="Screen Shot 2023-08-24 at 2 33 05 PM" src="https://github.com/ag-grid/ag-grid/assets/40453/251378ec-99e4-42b7-b2ba-34dd4f96a860">

**Comment by AG-Zoheil** [comment] 2023-10-23 10:09
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-10-23 10:09 UTC
Labels: managed-by-community

**Comment by paddymul** [comment] 2023-10-23 11:49
That's a bit duplicitous given that I filed a reproduceable bug report, there was no action from the community or ag-grid, and now you are closing it based on "no-action".  I get that you want people to pay for commercial support, but still.  Could you at least close it as "closed-wont-fix" or "closed-wont-advise".

**Comment by paddymul** [comment] 2023-10-23 11:51
FWIW I was eventually able to get the desired behavior from these mods to Rechart
https://github.com/paddymul/buckaroo/blob/main/js/components/RechartTooltip.tsx#L319-L335

and 
this custom header implementation
https://github.com/paddymul/buckaroo/blob/main/js/components/CustomHeader.tsx

I think `createPortal` was one of the key pieces.

**Comment by AG-Zoheil** [comment] 2023-10-23 15:45
Hi @paddymul,

Apologies for the misunderstanding.

As you mentioned we do not provide support via Github and you tagged your issue as "Support Request" not as "Bug" (please see your original comment/submission).
Hence it was tagged as `managed-by-community`. However to prevent plugging up this space we do not leave this open indefinitely and as there was no further interaction I closed this today.

In any case, we've now looked at this and it is not a bug. You are adding the tooltip to the cell itself which is causing the cut-off. The tooltip needs to be rendered in the `popupParent`. See a similar scenario here: https://ag-grid.com/react-data-grid/context-menu/#popup-parent.

Kind regards,
Zoheil

**Comment by paddymul** [comment] 2023-10-23 15:49
Thank you for the clarification.  I'll look at popup-parent, hopefully this
will help the next user who runs into this issue.
