### ISSUE TITLE
Error in /turbo_modules/ag-grid-community@25.1.0/dist/ag-grid-community.cjs.js (43842:37) Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by flgame** [ag-grid/ag-grid#4395] opened 2021-03-15 03:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. change the filter by the filter icon
2. click the update button 
3. exception
```
Error in /turbo_modules/ag-grid-community@25.1.0/dist/ag-grid-community.cjs.js (43842:37)
Cannot read property 'forEach' of null
```

sample code：
```
import React, { useState } from "react";
import { render } from "react-dom";
import { AgGridColumn, AgGridReact } from "ag-grid-react";

import "ag-grid-enterprise";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-alpine.css";

let N = 1;
const gridOptions = {
  defaultColDef: {
    filter: "agMultiColumnFilter",
    floatingFilter: true,
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter"
        },
        { filter: "agSetColumnFilter" }
      ]
    }
    // sideBar: {toolPanels: ['filters'] },
  }
};
const App = () => {
  const [gridApi, setGridApi] = useState(null);
  const [gridColumnApi, setGridColumnApi] = useState(null);

  const [rowData, setRowData] = useState([
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 }
  ]);

  function onGridReady(params) {
    setGridApi(params.api);
    setGridColumnApi(params.columnApi);
  }
  function changeData() {
    setRowData([
      { make: "Toyota" + N, model: "Celica", price: 36000 },
      { make: "Ford" + N, model: "Mondeo", price: 32000 },
      { make: "Porsche" + N, model: "Boxter", price: 72000 }
    ]);
    N += 1;
  }
  return (
    <div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
      <input type="button" value="update" onClick={changeData} />
      <AgGridReact
        gridOptions={gridOptions}
        onGridReady={onGridReady}
        rowData={rowData}
      >
        <AgGridColumn field="model" />
        <AgGridColumn field="make" />
        <AgGridColumn field="price" />
      </AgGridReact>
    </div>
  );
};

render(<App />, document.getElementById("root"));
```

**Current behavior**
 I get an error "Cannot read property 'forEach' of null" in every grid.

**Expected behavior**
No errors in the console.

* **AG Grid version:** 
25.1.0、24.1.0

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment] 2021-03-22 16:55
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

---

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by flgame** [comment] 2021-03-24 01:36
this is a demo
https://plnkr.co/edit/rJ3BkhaOBdIWo2TF

![image](https://user-images.githubusercontent.com/19725668/112240944-44a27000-8c84-11eb-81eb-b463edf0fb83.png)

![image](https://user-images.githubusercontent.com/19725668/112240964-5421b900-8c84-11eb-928a-278512f329c4.png)

**Comment by makinggoodsoftware** [comment] 2021-03-25 16:46
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-07 16:24
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5231 When using multi filter, modifying the set filter item selection and setting new data throws an exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid.

The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-15 15:31
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-15 15:31 UTC
Labels: AG-5231
