### ISSUE TITLE
custom toolPanel throw warning for icon 'none'

### ISSUE THREAD

**Issue by headhancho** [ag-grid/ag-grid#4851] opened 2021-12-29 19:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When using custom side bar toolPanels, using `iconKey: 'none'` throws warning "AG Grid: Did not find icon none".
Take this example plunker from the website (https://www.ag-grid.com/react-data-grid/side-bar/#side-bar-customisation) and change the iconKey to 'none' and see the warning

**Expected behavior**
Warning should not be thrown, icon 'none' is listed as one of the valid options here: https://www.ag-grid.com/react-data-grid/custom-icons/#replace-the-icons-by-changing-the-icon-font

* **AG Grid version:** X.X.X
26.0.0 +

**Comment by makinggoodsoftware** [comment] 2022-01-11 16:40
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-18 15:57
Hello @headhancho!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6263 When using the theme icon "none" as a tool panel icon, the grid can't find it**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:35
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:35 UTC
Labels: in_zendesk, AG-6263

**Comment by kiril-matev** [comment] 2022-02-24 10:56
Hello @headhancho,

We looked into this and this is not a bug in AG Grid. 

When setting the icons via gridOptions you need to use the following list of icon names: 
https://www.ag-grid.com/javascript-data-grid/custom-icons/#set-the-icons-through-gridoptions-javascript 

In this case, the 'none' icon is actually 'sortUnSort' - see this implemented here: 
https://plnkr.co/edit/BYe85E2iTJ9J7GD1

As this isn't an issue with AG Grid we're closing **AG-6263** as rejected.

**Comment by vamshia03** [comment] 2022-08-19 23:01
Hi @kiril-matev 
I have a similar question. I want to not display any icon at all. What should I use for the `iconKey` parameter? When I use none or anything else it gives a console warning. Is there an option to not display any icon at all and not get any console warning? Or do I have to definitely display an icon?

**Comment by kiril-matev** [comment] 2022-08-23 15:09
Hi @vamshia03,

You can hide the icon in the custom tool panel item by using a CSS style. 

Please see this in the sample below:
https://plnkr.co/edit/5Nat6mRVLIoyqKrj

Please note no icon is shown in the custom tool panel item and there's no console warning displayed.
