### ISSUE TITLE
rowGroupExpandState Type 'expanded' | 'collapsed' | 'match' have no Idea How  to use

### ISSUE THREAD

**Issue by sunnystark** [ag-grid/ag-grid#6911] opened 2023-07-26 17:32 UTC
**I'm submitting a .x..**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

rowGroupExpandState
Type
'expanded' | 'collapsed' | 'match'

new feature is not working 

'use strict';

import React, { useCallback, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-enterprise';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import './style.css';

var getRows = (params) => {
  const rows = [
    {
      outlineLevel: 1,
      cells: [
        cell(''),
        cell('Call Id', 'header'),
        cell('Direction', 'header'),
        cell('Number', 'header'),
        cell('Duration', 'header'),
        cell('Switch Code', 'header'),
      ],
    },
  ].concat(
    ...params.node.data.callRecords.map((record) => [
      {
        outlineLevel: 1,
        cells: [
          cell(''),
          cell(record.callId, 'body'),
          cell(record.direction, 'body'),
          cell(record.number, 'body'),
          cell(record.duration, 'body'),
          cell(record.switchCode, 'body'),
        ],
      },
    ])
  );
  return rows;
};

const cell = (text, styleId) => {
  return {
    styleId: styleId,
    data: {
      type: /^\d+$/.test(text) ? 'Number' : 'String',
      value: String(text),
    },
  };
};

const GridExample = () => {
  const gridRef = useRef();
  const containerStyle = useMemo(() => ({ width: '100%', height: '100%' }), []);
  const gridStyle = useMemo(() => ({ height: '100%', width: '100%' }), []);
  const [rowData, setRowData] = useState();
  const defaultCsvExportParams = useMemo(() => {
    return {
      getCustomContentBelowRow: (params) => {
        const rows = getRows(params);
        return rows.map((row) => row.cells);
      },
    };
  }, []);
  const defaultExcelExportParams = useMemo(() => {
    return {
      getCustomContentBelowRow: (params) => getRows(params),
      columnWidth: 120,
      fileName: 'ag-grid.xlsx',
    };
  }, []);
  const [columnDefs, setColumnDefs] = useState([
    // group cell renderer needed for expand / collapse icons
    { field: 'name', cellRenderer: 'agGroupCellRenderer' },
    { field: 'account' },
    { field: 'calls' },
    { field: 'minutes', valueFormatter: "x.toLocaleString() + 'm'" },
  ]);
  const defaultColDef = useMemo(() => {
    return {
      flex: 1,
    };
  }, []);
  const detailCellRendererParams = useMemo(() => {
    return {
      detailGridOptions: {
        columnDefs: [
          { field: 'callId' },
          { field: 'direction' },
          { field: 'number', minWidth: 150 },
          { field: 'duration', valueFormatter: "x.toLocaleString() + 's'" },
          { field: 'switchCode', minWidth: 150 },
        ],
        defaultColDef: {
          flex: 1,
        },
      },
      getDetailRowData: (params) => {
        params.successCallback(params.data.callRecords);
      },
    };
  }, []);
  const excelStyles = useMemo(() => {
    return [
      {
        id: 'header',
        interior: {
          color: '#aaaaaa',
          pattern: 'Solid',
        },
      },
      {
        id: 'body',
        interior: {
          color: '#dddddd',
          pattern: 'Solid',
        },
      },
    ];
  }, []);

  const onGridReady = useCallback((params) => {
    fetch('https://www.ag-grid.com/example-assets/master-detail-data.json')
      .then((resp) => resp.json())
      .then((data) => {
        setRowData(data);
      });
  }, []);

  const onBtExport = useCallback(() => {
    gridRef.current.api.exportDataAsExcel({rowGroupExpandState :{'Nora Thomas : 'collapsed ', Alvin: 'Match'});
  }, []);

  return (
    <div style={containerStyle}>
      <div className="container">
        <div>
          <button
            onClick={onBtExport}
            style={{ marginBottom: '5px', fontWeight: 'bold' }}
          >
            Export to Excel
          </button>
        </div>
        <div className="grid-wrapper">
          <div style={gridStyle} className="ag-theme-alpine">
            <AgGridReact
              ref={gridRef}
              rowData={rowData}
              defaultCsvExportParams={defaultCsvExportParams}
              defaultExcelExportParams={defaultExcelExportParams}
              columnDefs={columnDefs}
              defaultColDef={defaultColDef}
              masterDetail={true}
              detailCellRendererParams={detailCellRendererParams}
              excelStyles={excelStyles}
              onGridReady={onGridReady}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

const root = createRoot(document.getElementById('root'));
root.render(<GridExample />);

kindly update here 
https://plnkr.co/edit/?open=index.jsx&preview

**Comment by zoheil-ag** [comment] 2023-07-27 08:20
Hi @sunnystark,

Thank you for submitting a report. I'm afraid it is not clear what is not working for you.
The plunker you have included is empty - please make sure to fork and save the plunker before sending it on.

In any case, you can see in this example https://plnkr.co/edit/siXoegomqdxNC0iB?open=main.js that the `rowGroupExpandState` property is working as intended. You can read about the property [here](https://ag-grid.com/javascript-data-grid/excel-export-api/#reference-ExcelExportParams-rowGroupExpandState).

If you still need support, please clearly define your problem and provide a working plunker sample.

Kind regards,

**Comment by zoheil-ag** [comment] 2023-08-07 09:10
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for AG Grid or the wider community to support.

Kind regards,
Zoheil

**Closed by zoheil-ag** 2023-08-07 09:10 UTC
Labels: waiting-for-repro
