### ISSUE TITLE
error in type of getMainMenuItems function

### ISSUE THREAD

**Issue by oleurud** [ag-grid/ag-grid#7458] opened 2024-01-18 15:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

The following example of the section https://www.ag-grid.com/vue-data-grid/column-menu/#example-column-menu is an example, specifically here:

```js
const athleteMenuItems = params.defaultItems.slice(0);
athleteMenuItems.push({
  name: 'AG Grid Is Great',
  action: () => {
    console.log('AG Grid is great was selected');
  },
});
```
Using typescript, the object inside the `push` function will be errored: `Argument of type '{ name: string; action: () => void; }' is not assignable to parameter of type 'string'.ts(2345)`

**Tentative solution**

The problem seems to be in https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/core/src/ts/interfaces/iCallbackParams.ts#L24 and the solution could be changing:

from:
```
defaultItems: string[];
```

to:
```
defaultItems: (string | MenuItemDef)[];
```

**Comment by AG-Zoheil** [comment] 2024-01-19 15:37
Hi @oleurud,

Thank you for your feedback.

We've reviewed your suggestion and would like to provide a response explaining why this is not a bug.

The `defaultItems` property provided to the callback is always a `string[]`, which is why it's typed accordingly.
 
When doing const `athleteMenuItems = params.defaultItems.slice(0);`, the type of `athleteMenuItems` will therefore be inferred as `string[]`. This means a `MenuItemDef` cannot be assigned to it.
 
The solution to this is to explicitly define the type of `athleteMenuItems`:
`const athleteMenuItems: (string | MenuItemDef)[] = params.defaultItems.slice(0);`

I hope the above helps and clarifies the reason for our implementation.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-01-19 15:37 UTC
Labels: in_zendesk
