### ISSUE TITLE
Invisible filter button causes error when clicked on.

### ISSUE THREAD

**Issue by technobuddha** [ag-grid/ag-grid#5621] opened 2022-09-29 18:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When no floatingFilter or filter is specified for a column (and other columns are configured for floatingFilters) ag-grid renders an invisible div that when clicked on generates an error.

**Expected behavior**
Either the invisible div should not exist, or it shouldn't throw an error when clicked.

**Please tell us about your environment:**
    "ag-grid-community": "^28.1.1",
    "ag-grid-react": "^28.1.1",

* **AG Grid version:** 28.1.1

* **Browser:** Chrome 105.0.5195.127 (Official Build) (64-bit)

* **Language:** TypeScript 4.8

https://user-images.githubusercontent.com/105307/193113532-e4902285-f189-4405-bbc3-a253f8f38472.mp4

The column in question is defined as

```typescript
      {
        field: 'token.token',
        headerName: 'TOKEN',
        cellRenderer: CellToken,
        sortable: false,
        unSortIcon: true,
        flex: 4,
      },
```

Other columns have filter & floatingFilter set

**Comment by kiril-matev** [comment] 2022-10-05 14:23
Hello @technobuddha,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7347 [React] When using ReactUI and having a column without a floating filter, clicking inside the empty space throws an exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by StephenCooper** [comment] 2022-11-07 16:57
Can you provide us a reproduction based of our latest doc examples that uses 28.2.1?

**Comment by AnabelSalomone** [comment] 2022-11-08 08:07
Columns with floating filters on are configured like this:

```
         {
            field: /*field name>*/
            filter: 'agTextColumnFilter',
            floatingFilter: true,
            floatingFilterComponent: 'floatingFilterComponent',
            filterParams: {
                filterOptions: [
                    'contains',
                    'startsWith',
                    'notEqual',
                    'equals',
                    'greaterThan',
                    'lowerThan',
                ],
                suppressAndOrCondition: true,
                defaultOption: 'contains',
            },
        }
```

while those that don't have floating filter on are configured with `filter: false, floatingFilter: false`

I'm using:
```
"ag-grid-community": "28.2.1",
"ag-grid-enterprise": "28.2.1"
```

https://user-images.githubusercontent.com/22484956/200506821-5036ef43-e180-423c-8e6b-9aecb0a0f0e3.mov

Let me know if you need extra information.

**Comment by kiril-matev** [comment] 2022-11-08 14:57
Hello @AnabelSalomone!

Thank you for getting back to us about this.

I'm glad to hear that you've now upgraded ag-grid-react and this solves the problem!

Thank you for your time!

**Closed** 2022-11-16 14:47 UTC
Labels: waiting-for-repro, AG-7347
