### ISSUE TITLE
ctrl & C and ctrl & V on range cells not working with RU keyboard layout

### ISSUE THREAD

**Issue by Ternovskiy** [ag-grid/ag-grid#5108] opened 2022-04-20 17:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

**Providing a Reproducible Scenario**
When switching keyboard layout from ENG key ctrl & C and ctrl & V stops working. This is reproduced on https://plnkr.co/edit/KK1nohjMCV8uvisa?open=app%2Fapp.component.ts. 

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Сopy and paste to clipboard does not work on Russian keyboard

**Expected behavior**
It worked on previous versions, it should continue to work

**Please tell us about your environment:**
Bug appears in your Plunker setup

* **AG Grid version:** 27.1.0

* **Browser:** Google Chrome v100

* **Language:** TypeScript 4.6.2

**Comment by icedjello** [comment] 2022-04-25 11:16
Hello Ternovskiy!
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-6641 - [Regression] When using Windows with a non-Latin keyboard layout, keyboard shortcuts CTRL+C and CTRL+V to copy and paste grid cell values no longer work
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-6641) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/
 
Thanks again for bringing this up with us - we appreciate your time!

**Closed by icedjello** 2022-04-25 11:16 UTC
Labels: in_zendesk
