### ISSUE TITLE
How can I edit the chart on the fly my moving the data points on the line charts itself.

### ISSUE THREAD

**Issue by praveenkumar91** [ag-grid/ag-grid#7674] opened 2024-03-01 20:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by praveenkumar91** [comment] 2024-03-01 20:40
I am trying to use ag chart for my project where I need make changes in the displayed chart by drag and drop of data points in the charts. Is this possible in ag charts ?

**Comment by AG-Zoheil** [comment] 2024-03-04 12:01
Hi @praveenkumar91,

Thank you for getting in touch.

We are not quite sure what your requirement is based on the description you've provided.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-DavidG** [comment] 2024-03-07 14:42
Hello @praveenkumar91 

Thank you for bringing this up with us. 

This exact behaviour is not currently available in AG Charts. 

It is possible to update values in the chart at runtime via the [update api methods](https://charts.ag-grid.com/javascript/api-create-update/). It is also possible to receive user interactions via [click events](https://charts.ag-grid.com/javascript/events/#series-event---nodeclick) or [custom actions in the Context Menu](https://charts.ag-grid.com/javascript/context-menu/#custom-actions). 

Based on this, you could provide your own controls externally or use the click or context menu to receive input from the user, and update the chart data accordingly.

However, the feature described would be useful and we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-10946 - [Charts] Allow series markers to be draggable

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10946) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by AG-DavidG** 2024-03-07 14:42 UTC
Labels: waiting-for-repro
