### ISSUE TITLE
rowBuffer is not working with client side rendering

### ISSUE THREAD

**Issue by wmbutler** [ag-grid/ag-grid#6057] opened 2023-01-20 20:06 UTC
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
rowBuffer does not work with client side rendering.

**Current behavior**
When rendering 2000 client side data in rows, 500 rows render initially instead of in batches of 10 per the default spec of `10`

**Expected behavior**
According to the docs, the default behavior should render rows to the DOM in batches of 10. With 2000 rows in my client side data, I'm seeing 501 rows rendered which is the max number of rows that can be rendered without sending `[suppressMaxRenderedRowRestriction]="true"`. Observing the DOM as I scroll, all rows are delivered at initial render.

**Please tell us about your environment:**
node.js / Angular / npm

* **AG Grid version:** 29.0.0

* **Browser:**
```'
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
```

* **Language:**
* TypeScript ES6/7

**Comment by StephenCooper** [comment] 2023-01-23 10:01
I cannot reproduce this. 

In this [example](https://plnkr.co/edit/2zS6g1ZdTfoBm5XS?open=app%2Fapp.component.ts) using v29 if I do not set the row buffer then I see the medal renderer is created for the number of visible rows + 10. 

When I change the row buffer I see the number of rows rendered changes accordingly. 

I am going to close this as I do not see an issue. If you can provide a reproduction that shows your issue then we could investigate futher.

**Closed by StephenCooper** 2023-01-23 10:01 UTC
