### ISSUE TITLE
Grabbing Scrollbar with left mouse button does not scroll in Firefox (Win10) after scrolling once with mouse-wheel

### ISSUE THREAD

**Issue by githubuser234** [ag-grid/ag-grid#4518] opened 2021-06-11 06:13 UTC
In Firefox (Windows 10), after scrolling once with the mouse-wheel, grabbing the scrollbar with left mouse button and moving the mouse (without mouse-wheel) does not scroll the grid. In Chrome, it works as expected.

This issue was first posted here: https://github.com/ag-grid/ag-grid/issues/4500
It seems that you didn't test this on a windows machine?

I've now clarified the reproducible scenario including an animation. Furthermore, I've now additionally tested this in a completly fresh and clean Firefox Developer Edition 90.0b5 (64-Bit) which also suffers from this bug. Also on a second Win10 machine, the bug appears in FF.

**Providing a Reproducible Scenario**

- Open Firefox (Windows 10) and go to Startpage: https://www.ag-grid.com/
- On the upper example, scroll first with mouse-wheel
- Now release mouse-wheel and only scroll with grabing the scroll-bar and moving the mouse
Here is an animation demonstrating the issue
![Animation](https://user-images.githubusercontent.com/83961121/121639179-73aecd80-ca8c-11eb-88e1-17ee116a7cac.gif)

**Current behavior**
No scrolling while grabbing.

**Expected behavior**
It should scroll smoothly while grabbing the scrollbar.

**Please tell us about your environment:**

* **AG Grid version:** version from https://www.ag-grid.com/

* **Browser:**
Firefox 88.0.1 (64-Bit) AND 90.0b5 (64-Bit)

* **OS:**
Windows 10

**Comment by jonahmolinski** [comment] 2021-06-14 18:07
Same issue happens when you select a row in the grid. If you try to move the scroll bar it jumps to the bottom.

**Comment by makinggoodsoftware** [comment] 2021-06-18 16:17
Hi,

You guys are right, this would be a dupe of this that has a ticket associated already:

https://github.com/ag-grid/ag-grid/issues/4500#issuecomment-859419479

I will proceed to close this but feel free to add more feedback there

**Closed by makinggoodsoftware** 2021-06-18 16:17 UTC
