### ISSUE TITLE
Mouse scroll on pinned columns does not work correctly

### ISSUE THREAD

**Issue by sdd330** [ag-grid/ag-grid#1730] opened 2017-06-29 02:51 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trigger mouse scroll on pinned columns, the page does not scroll correctly, unpinned columns works ok.

**Expected behavior**
The behavior of mouse scroll should be consistent with unpinned columns

**Minimal reproduction of the problem with instructions**

Given one grid with one row, a pinned column and several unpinned columns on top of a web page (2000px height)
1. Do scroll up on unpinned columns, the web page will scroll up
2. Do scroll up on the pinned column, nothing happen

**What is the motivation / use case for changing the behavior?**

Provide a consistent user experience

**Please tell us about your environment:**

Mac OS Sierra

* **ag-Grid version:** X.X.X

10.1.0

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment] 2017-07-03 10:03
Hi,

Thanks for reporting this. I've been able to reproduce it and have raised an issue for it our side (AG-581).

We'll update this thread with updates as soon as we have any.

thanks

**Comment by seanlandsman** [comment] 2017-07-03 10:23
Hi

As a workaround you can add the suppressPreventDefaultOnMouseWheel: true and it should fix this for you

**Comment by sdd330** [comment] 2017-07-05 09:14
Thanks

**Comment by makinggoodsoftware** [comment] 2017-12-19 08:09
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Closed by makinggoodsoftware** 2017-12-19 08:09 UTC
Labels: bug
