### ISSUE TITLE
Cell Editor: getPopupPosition() return value gets ignored

### ISSUE THREAD

**Issue by lbueker** [ag-grid/ag-grid#4796] opened 2021-11-23 19:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I've made two versions one with ag-grid version 26.2.0, where the issue occurs,
and another one with version 25.3.0 where it is working as expected.

This is a fork of the "Simple Editor Components" plunker from the docs, with the addition of the getPopupPosition() function in the `MoodEditor` class in `moodEditor.js`, which always returns 'under'.

Broken version: https://plnkr.co/edit/w1f8pEvN8K7xuJwV?preview
Working version: https://plnkr.co/edit/lXiK6JkjJl7LIRyJ?preview

**Current behavior**
The return value of the getPopupPosition function in a cell editor gets ignored. Resulting in the position of the editor always getting placed over the cell, even when the function returns 'under'.

![grafik](https://user-images.githubusercontent.com/61975758/143093636-93dbc9f5-583f-40db-94c8-8e453966b4ee.png)

**Expected behavior**
When the getPopupPosition function returns 'under' the cell editor should be placed below the cell.

![grafik](https://user-images.githubusercontent.com/61975758/143093683-ded4e71c-9c01-461d-9d06-78e5db115c99.png)

**Please tell us about your environment:**

* **AG Grid version:** 26.2.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36'

* **Language:** all

Additional Note: I've already identified the problem and provided a potential fix in #4792

**Comment by gportela85** [comment] 2021-11-24 20:36
fixed by https://github.com/ag-grid/ag-grid/pull/4792

**Closed by gportela85** 2021-11-24 20:36 UTC

**Comment by kiril-matev** [comment] 2021-11-26 14:12
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6064 [Regression] When cell editor popup is used it cannot be displayed under the edited cell (because getPopupPosition return value is ignored by editors)**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
