### ISSUE TITLE
Aggrid not compatible with @Component decorator 

### ISSUE THREAD

**Issue by Ida0107** [ag-grid/ag-grid#4144] opened 2020-10-16 05:15 UTC
I am using ag-grid-vue version 24.0.0 with vue version: 2.6.11 and typscript version: 3.8.3.
On building my project , I am running into issues. Below is the build error:

ERROR in C:/Users/Somalee.Gupta/Desktop/EnergyExemplarProjects/Cloud.Web/source/EnergyExemplar.Cloud.Web/node_modules/ag-grid-vue/lib/AgGridVue.d.ts(1,10):
1:10 Module '"../../../../../../../../../../Users/Somalee.Gupta/Desktop/EnergyExemplarProjects/Cloud.Web/source/EnergyExemplar.Cloud.Web/node_modules/vue-class-component/lib"' has no exported member 'Vue'. Did you mean to use 'import Vue from "../../../../../../../../../../Users/Somalee.Gupta/Desktop/EnergyExemplarProjects/Cloud.Web/source/EnergyExemplar.Cloud.Web/node_modules/vue-class-component/lib"' instead?
  > 1 | import { Vue } from 'vue-class-component';
      |          ^
    2 | import { Module } from 'ag-grid-community';
    3 | export declare class AgGridVue extends Vue {
    4 |     static VERSION: string;
ERROR in C:/Users/Somalee.Gupta/Desktop/EnergyExemplarProjects/Cloud.Web/source/EnergyExemplar.Cloud.Web/node_modules/ag-grid-vue/lib/AgGridVue.d.ts(15,15):
15:15 Type 'VNode' is not generic.
    13 |     private gridOptions;
    14 |     private emitRowModel;
  > 15 |     render(): import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
       |               ^
    16 |         [key: string]: any;
    17 |     }>;
    18 |     globalEventListener(eventType: string, event: any): void;
ERROR in C:/Users/Somalee.Gupta/Desktop/EnergyExemplarProjects/Cloud.Web/source/EnergyExemplar.Cloud.Web/VueApp/Components/TablesForComparison/AgGrid/InputDataGrid.vue(18,2):
18:2 No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> & ThisType<...>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.       
    Type 'typeof AgGridVue' is not assignable to type 'VueConstructor<Vue> | FunctionalComponentOptions<any, PropsDefinition<any>> | ComponentOptions<never, any, any, any, any, Record<...>> | AsyncComponentPromise<...> | AsyncComponentFactory<...>'.       
      Type 'typeof AgGridVue' is missing the following properties from type 'VueConstructor<Vue>': extend, nextTick, set, delete, and 9 more.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ components: { AgGridVue: typeof AgGridVue; }; }' is not assignable to parameter of type 'VueClass<Vue>'.      Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?
    16 | import { AgGridVue } from 'ag-grid-vue';
    17 | 
  > 18 | @Component({ components: { AgGridVue } })
       |  ^
    19 | export default class InputDataGridAg extends Vue {
    20 |     @Prop() items;
    21 | 

I tried upgrading to 24.1.0 and facing the same issue.

**Comment by seanlandsman** [comment] 2020-10-16 07:30
Hi - do you have a repo of this that we can take a look at?

In the meantime, you could try adding ```"skipLibCheck": true,``` to your tsconfig and see if this helps

**Comment by Manubi** [comment] 2020-10-16 09:13
I do have the same error.

package.json
```
"@ag-grid-community/vue": "^24.1.0",
"@ag-grid-enterprise/all-modules": "^24.1.0",
"vue-class-component": "^7.2.6",
"vue-property-decorator": "^9.0.2",
"vue": "^2.6.12"
```

<img width="975" alt="npm_run_serve" src="https://user-images.githubusercontent.com/20935138/96239571-2d0ddf80-0fa0-11eb-8378-0d0bfa9cf6fd.png">

**Comment by tjgambs** [comment] 2020-10-16 15:55
@seanlandsman I am also experiencing this issue. I looked a bit at the commit history and I see some code that looks like it is for vue3 instead of vue2?

Upon further digging in, I see that there is a folder at [ag-grid-vue-legacy](https://github.com/ag-grid/ag-grid/tree/master/grid-packages/ag-grid-vue-legacy) that appears to be for vue2. How can we install this legacy version instead? My project is built on vue2 and we don't have plans to upgrade to vue3 yet.

**Comment by tjgambs** [comment] 2020-10-16 16:21
@seanlandsman I'm not sure how to fix this, but I think I found the problem?

The types being used in this situation are `@ag-grid-community/vue/lib/AgGridVue.d.ts` but they are using vue2 so the types should be coming from `@ag-grid-community/vue/lib/legacy/AgGridVue.d.ts`.

I'm not sure why the incorrect types are being used. Any thoughts?

**Comment by tjgambs** [comment] 2020-10-16 16:41
@Ida0107 @Manubi 

Downgrade from `24.1.0` to `24.0.0`. `24.0.0` is the latest version working with vue2 from what I can tell. I originally had the same problems as you, but now it works again.

```
...
"@ag-grid-community/vue": "24.0.0",
"@ag-grid-enterprise/all-modules": "24.0.0",
...
```

**Comment by Manubi** [comment] 2020-10-19 08:17
Downgrading to 24.0.0 was also the only thing that worked for me.

```
"@ag-grid-community/vue": "^24.0.0"
 "@ag-grid-enterprise/all-modules": "^24.0.0"
```

**Comment by makinggoodsoftware** [comment] 2020-10-19 10:33
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by oscar6echo** [comment] 2020-10-20 09:00
With these modules:
```
    "@ag-grid-community/core": "^24.0.0",
    "@ag-grid-community/all-modules": "^24.0.0",
    "@ag-grid-enterprise/core": "^24.0.0",
    "@ag-grid-enterprise/clipboard": "^24.0.0",
    "@ag-grid-enterprise/column-tool-panel": "^24.0.0",
    "@ag-grid-enterprise/filter-tool-panel": "^24.0.0",
    "@ag-grid-enterprise/master-detail": "^24.0.0",
    "@ag-grid-enterprise/range-selection": "^24.0.0",
    "@ag-grid-enterprise/row-grouping": "^24.0.0",
    "@ag-grid-enterprise/side-bar": "^24.0.0",
    "@ag-grid-enterprise/status-bar": "^24.0.0",
    "@ag-grid-community/vue": "^24.0.0",
```
I still get these errors:

```
 WARN  Compiled with 2 warnings
 WARN  in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js
"export 'Options' was not found in 'vue-class-component'
 WARN  in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js
"export 'Vue' was not found in 'vue-class-component'
 ERROR  Failed to compile with 1 errors
This dependency was not found:
* @vue/reactivity in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js
```
I had to downgrade to `23.2.1` for my nuxt app to compile...

**Comment by somalee-ee** [comment] 2020-10-20 11:15
Hi @makinggoodsoftware @seanlandsman ,
here is the link to the demo repo I created: 
https://github.com/somalee-ee/AgGridVueDemo/tree/master

The issue started with 24.0.0, if you downgrade version to 23.2.1 it seems to work.

**Comment by Manubi** [comment] 2020-10-20 11:17
@oscar6echo as I see your using all the different modules, what is/was/would be your workflow in changing from the single package approach to using different modules to decrease the app size?
Thanks!

**Comment by oscar6echo** [comment] 2020-10-20 11:38
@Manubi Well I *am* trying to pick only those packages I need to reduce bundle size - taking inspiration from this [page in the doc](https://www.ag-grid.com/javascript-grid-modules-more-details/). But trial&error and this [issue](https://github.com/ag-grid/ag-grid/issues/3510#issuecomment-553401927) show that @ag-grid-community/all-modules is necessary to use @ag-grid-community/vue - it seems.  
  
Since you mention it what I think lacks in the docs is the full tree of dependencies among all ag-grid modules.  Or it is somewhere ?

PS: I'm under my personal id, waiting for my pro email to be registered - I have a licence.

**Comment by Manubi** [comment] 2020-10-20 11:43
@oscar6echo Thanks for the quick answer!
I've the enterprise version and a license key and can't find anything helpful except the link you've provided. I think a good process from switching from all-modules to the single modules is not mentioned in the docs.

**Comment by oscar6echo** [comment] 2020-10-20 11:45
@Manubi hopefully they will add it. It seems this section of the docs is still in construction. For example the [modules overview](https://www.ag-grid.com/javascript-grid-modules/) is empty now.

**Comment by seanlandsman** [comment] 2020-10-20 16:27
> Hi @makinggoodsoftware @seanlandsman ,
> here is the link to the demo repo I created:
> https://github.com/somalee-ee/AgGridVueDemo/tree/master
> 
> The issue started with 24.0.0, if you downgrade version to 23.2.1 it seems to work.
> 
> P.S. I am @Ida0107 , continuing here with my work id as we are in the process of acquiring the license.

Thanks @somalee-ee - I'll take a look at this tomorrow

**Comment by seanlandsman** [comment] 2020-10-20 16:29
> @Manubi Well I _am_ trying to pick only those packages I need to reduce bundle size - taking inspiration from this [page in the doc](https://www.ag-grid.com/javascript-grid-modules-more-details/). But trial&error and this [issue](https://github.com/ag-grid/ag-grid/issues/3510#issuecomment-553401927) show that @ag-grid-community/all-modules is necessary to use @ag-grid-community/vue - it seems.
> 
> Since you mention it what I think lacks in the docs is the full tree of dependencies among all ag-grid modules. Or it is somewhere ?
> 
> PS: I'm under my personal id, waiting for my pro email to be registered - I have a licence.

@oscar6echo you should still be able to pick and choose modules - this issue shouldn't have any bearing on being able to use individual modules. 

In fact the modules are only core grid functionality - the framework support is independent of the modules (individual or all-modules) you use

**Comment by seanlandsman** [comment] 2020-10-20 16:30
> @Manubi hopefully they will add it. It seems this section of the docs is still in construction. For example the [modules overview](https://www.ag-grid.com/javascript-grid-modules/) is empty now.

@oscar6echo I'm afraid I'm not seeing what you're seeing regarding empty docs - the module documentation is complete. Can you please try force refresh this (and other) pages?

**Comment by oscar6echo** [comment] 2020-10-21 07:02
@seanlandsman yesterday several attempts to refresh this page always returned a blank page, but this morning I can see the content... Indeed it does provide a lot of information about how to install and use a selection of modules.  

However it appears that [this example](https://www.ag-grid.com/javascript-grid-modules/#providing-modules-globally) does not work if you replace `@ag-grid-community/react` with `@ag-grid-community/vue` because the latter depends on `@ag-grid-community/all-modules`, it seems.  Tested with version `23.2.1`.  

With version `24.1.0` the error messages are in the [comment above](https://github.com/ag-grid/ag-grid/issues/4144#issuecomment-712703923). The only difference is that I have removed module `@ag-grid-community/core` from the dependencies as it is included in `@ag-grid-community/all-modules`. Now maybe this is not the right issue to discuss this problem ?

**Comment by makinggoodsoftware** [comment] 2020-10-23 11:39
Hi,

We just released v24.1.1, which includes:


AG-4723 |   | 24.1.1 | [Regression] When building an ag-Grid Vue.Js application, you get error AgGridVue.js dependency was not found
-- | -- | -- | --



Would you mind checking if this fixes the issues on your end?

**Comment by Manubi** [comment] 2020-10-23 11:45
As far as I can see it there is no release yet.

**Comment by tjgambs** [comment] 2020-10-25 02:13
@makinggoodsoftware `v24.1.1` works for me, thanks!

@Manubi Try updating your package.json to the below:
```
...
"@ag-grid-community/vue": "^24.1.1",
...
```

**Comment by oscar6echo** [comment] 2020-10-25 20:02
I can confirm that this combination of packages works for me:

```
    "@ag-grid-community/all-modules": "^24.1.0",
    "@ag-grid-enterprise/core": "^24.1.0",
    "@ag-grid-enterprise/clipboard": "^24.1.0",
    "@ag-grid-enterprise/column-tool-panel": "^24.1.0",
    "@ag-grid-enterprise/filter-tool-panel": "^24.1.0",
    "@ag-grid-enterprise/master-detail": "^24.1.0",
    "@ag-grid-enterprise/range-selection": "^24.1.0",
    "@ag-grid-enterprise/row-grouping": "^24.1.0",
    "@ag-grid-enterprise/side-bar": "^24.1.0",
    "@ag-grid-enterprise/status-bar": "^24.1.0",
    "@ag-grid-community/vue": "^24.1.1",
```

**Comment by makinggoodsoftware** [comment] 2020-11-02 12:05
Hi, 

This seems to be working now, I am going to close this ticket, please feel free to raise a new ticket if you are still seeing this issue.

Thanks

**Closed by makinggoodsoftware** 2020-11-02 12:05 UTC
Labels: AG-4723, ag-grid engaged, in_zendesk
