### ISSUE TITLE
AG Grid Accessibility Issues and aggrid iPad,iphone filter issue and resize issue

### ISSUE THREAD

**Issue by BhagyashriDhanak-web** [ag-grid/ag-grid#6141] opened 2023-02-09 09:36 UTC
Hi Team,

I have successfully implemented Ag-grid and its working fine in desktop browser, but when we open our application in iPad, we get below issues :

Issue # 1:- When I click on resizable icon, then sometimes column resizes, sometimes it doesn't.
Issue # 2:- When we open our application in iPad, iPhone then filter function is not working in it, but floatingFilter work.

**When I was doing accessibility testing of AG Grid using Wave Tool then I found 8 issues in it.**
1. There are 8 Missing form label errors.

**For your reference:**

**ARIA tabindexMissing form label issue**
similar 8 type of issues we found it.

``<input ref="eInput" class="ag-input-field-input ag-checkbox-input" type="checkbox" id="ag-47-input" tabindex="-1">``

* **AG Grid version:**  v28.2.1

* **Browser:** Chrome

* **Language:** Javascript

**Please resolve these issues as early as possible.**

**Comment by BhagyashriDhanak-web** [comment] 2023-02-09 09:37
Please resolve these issues as early as possible

**Comment by kiril-matev** [comment] 2023-02-09 10:54
Hello @BhagyashriDhanak-web.

Thank you for using AG Grid.

You've submitted 3 issues without reproducible samples and without following the template for issue submission. This generates delays in processing and creates confusions for other users who will struggle to track 3 separate issues in a single GitHub issue.

Please when submitting issues, submit only one issue per GitHub issue and follow the bug submission template we provide which requires a live sample, list of steps to reproduce and descriptions of actual/expected behavior.

Issue #1:
This is logged as 
**AG-7955 [Regression] When using a touch device, grid columns cannot be resized by touch**

This bug will be fixed in our next release. Please sign up for release notifications to be notified of our next release.

Issue #2:
Please be more specific in how filtering doesn't work. I assume you mean you can't open the filter popup on a touch device because the column menu cannot be opened on a touch device as by default it's only shown when the column header cell is hovered. 

You can easily fix this. In order to use the columns menu on a touch device, you need to always show it by setting this property:
https://ag-grid.com/javascript-data-grid/grid-options/#reference-accessories-suppressMenuHide

See this shown here - the column menu button is always shown and you can touch it on a mobile device to show the filter popup.
https://plnkr.co/edit/N91PRc2l6HCjJ0Tg?open=main.js

Issue #3 - potential accessibility issue:
We're keen to investigate this further. Please open a **new** GitHub issue about this providing a sample where we can reproduce this potential accessibility issue with Wave. You can open one of our documentation samples in plunker, modify its code to reproduce the issue, save it and use it in your issue report.

Thank you for your time and for using AG Grid!

**Closed** 2023-02-15 10:24 UTC
Labels: AG-7955

**Comment by BhagyashriDhanak-web** [comment] 2023-02-15 11:10
Have these issues been resolved?

**Comment by StephenCooper** [comment] 2023-02-15 11:12
> Issue https://github.com/ag-grid/ag-grid/pull/1:
This is logged as
AG-7955 [Regression] When using a touch device, grid columns cannot be resized by touch
This bug will be fixed in our next release. Please sign up for release notifications to be notified of our next release.

The only actionable issue from this ticket has been and will be part of our next release available next week.

**Comment by BhagyashriDhanak-web** [comment] 2023-02-20 07:24
Hi @kiril-matev

The issue of accessibility is being reproduced on this **aggrid_widthandmoredata1.html** page, but I have to host this page so where should I host it? so that you can see the accessibility issues. I will create new issue for accessibility.

please inform me as soon as possible where should I host this html page.

**Comment by kiril-matev** [comment] 2023-02-22 17:23
Hi @BhagyashriDhanak-web,

Bug AG-7955 was resolved in AG Grid v29.1. You can get an update on any item by looking into our changelog:
https://ag-grid.com/changelog/

Please attach the page which reproduces issue #3 to this thread - simply drag the file into the editor when responding.

Looking forward to your response.
