### ISSUE TITLE
Grabbing Scrollbar with left mouse button does not scroll in Firefox

### ISSUE THREAD

**Issue by githubuser234** [ag-grid/ag-grid#4500] opened 2021-05-31 13:14 UTC
In Firefox, grabbing the scrollbar with left mouse button does not scroll the grid. In Chrome, it works as expected.

**Providing a Reproducible Scenario**

- Open Firefox and go to Startpage: https://www.ag-grid.com/
- On the upper example, scroll with mouse-wheel
- Try to grab scroll-bar with your mouse and try to scroll
![grafik](https://user-images.githubusercontent.com/83961121/120199300-60496a00-c223-11eb-9986-225fcb7d9eb9.png)

**Current behavior**
No scrolling while grabbing.

**Expected behavior**
It should scroll smoothly while grabbing the scrollbar.

**Please tell us about your environment:**

* **AG Grid version:** version from https://www.ag-grid.com/

* **Browser:**
Firefox 88.0.1 (64-Bit)

**Comment by makinggoodsoftware** [comment] 2021-06-04 16:06
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment] 2021-06-10 12:30
Hi,

Thanks for reaching out.

From your steps to reproduce, we weren't sure whether you were scrolling with the mouse wheel or by moving the cursor, after grabbing the scrollbar, so we investigated both scenarios. If scrolling with the mouse wheel, this doesn't appear to be an issue specific to AG Grid, but Firefox in general, we've attached a gif showing this problem on this page on Github.

If you're not using the mouse wheel to scroll, unfortunately, we're unable to see the issue on our end after following the steps to reproduce you've provided, please find a gif showing our attempt attached.

We're going to close this issue now but if we've misunderstood, please feel free to reach out to us again, clarifying what we've missed in a new issue.

![Jun-10-2021 10-57-20](https://user-images.githubusercontent.com/56586582/121506799-fa57a200-c9db-11eb-82fa-ab8081eb2ac5.gif)
![Jun-10-2021 11-07-23](https://user-images.githubusercontent.com/56586582/121506890-122f2600-c9dc-11eb-8a22-3b9a100c30be.gif)

**Closed by LouisMoore-agGrid** 2021-06-10 12:30 UTC
Labels: in_zendesk

**Comment by githubuser234** [comment] 2021-06-11 06:16
I've now clarified the reproducible scenario including an animation. Furthermore, I've now additionally tested this in a completly fresh and clean Firefox Developer Edition 90.0b5 (64-Bit) which also suffers from this bug.

see https://github.com/ag-grid/ag-grid/issues/4518

**Comment by githubuser234** [comment] 2021-06-11 06:37
Did you try to reproduce this on a Windows machine?

**Comment by kiril-matev** [comment] 2021-06-11 09:14
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug using Firefox on a Windows machine.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5433 [Website] When scrolling using the mouse wheel in Firefox on Windows on the ag-grid homepage, you can't scroll using the vertical scrollbar thumb anymore**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment] 2021-07-28 08:42
Hi @githubuser234!

We've now looked into this issue in detail and determined it to be caused by a bug in Firefox.

We have logged this issue with Mozilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1722308

As this isn't an issue with AG Grid (but with Firefox instead), we have rejected this bug:
AG-5433 [Website] When scrolling using the mouse wheel in Firefox on Windows on the ag-grid homepage, you can't scroll using the vertical scrollbar thumb anymore

**Please follow the Mozilla issue using the link above and track that to its resolution in a new version of Firefox.**

Thanks once again for reporting this - much appreciated!
