### ISSUE TITLE
Multiple column filters are opened in tablet device

### ISSUE THREAD

**Issue by Praveen-Bandi** [ag-grid/ag-grid#6919] opened 2023-08-01 11:19 UTC
Following behavior observed on the tablet device.

On click of a column filter, the corresponding column's filter popup is launched. And when we click on another column's filter icon without closing the previous column's filter popup, a column filter for this column is also launched without closing the previous column's filter popup. 

Is it the expected behavior? Is there any workaround for this issue?

**Comment by zoheil-ag** [comment] 2023-08-01 11:45
Hi @Praveen-Bandi,

Thanks for raising this. For us to able to look into it could you please provide the following:

1) A link to an example from our documentation on which we can reproduce it
2) The specific device/browser you are having issues with

Looking forward to your response.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment] 2023-08-02 10:46
Hi @KirthirajS,

Thanks for that.
The problem you are experiencing on the tablet - can you confirm if you can see it on the examples in our documentation too? Simply open the example of the feature you are having issues with (e.g. floating filter) on the tablet and advise of the outcome.

Also, you haven't confirmed device make/model and browser OS?

Kind regards,

**Comment by KirthirajS** [comment] 2023-08-02 10:56
No in documentation we are not finding the same issue , but while i am trying replicate your example it is showing above error.

**Comment by Praveen-Bandi** [comment] 2023-08-03 05:36
@zoheil-ag,

Thanks for the quick response. We are seeing this issue with following environment. 

- We are using Samsung Galaxy Tab A8.
-  "ag-grid-angular": "^29.3.5"
-  "ag-grid-community": "^29.3.5"
- "@angular/core": "^14.2.12"
- "@angular/platform-browser": "^14.2.12"

We are using the example provided in the following AG Grid documentation.
https://www.ag-grid.com/angular-data-grid/filtering/

In addition to above example, we have added following custom css logic to show our own filter icon.
 .ag-header-cell-filtered {
        .ag-icon-menu {
            background: #056fcf4d !important;
            border-radius: 8px;
            &::before {
                filter: invert(15%) sepia(95%) saturate(2910%) hue-rotate(197deg) brightness(94%) contrast(102%)
            }
        }
        .ag-filter-icon {
            display: none;
        }
    } 

    .ag-icon-menu::before {
        background: url('../../../../../assets/icons/icon_filter.svg');
        background-size: contain;
        height: 20px;
        width: 20px;
        display: inline-block;
        content: ''
    }

Please note that, we are not able to see the filter icons when we open above AG Grid example in Samsung Galaxy Tab A8. Hopefully same would be the behavior in all the android devices and not just in Samsung Galaxy Tab A8.

Refer below screenshot for the reported problem in our application
![image](https://github.com/ag-grid/ag-grid/assets/79447519/76566b41-788f-4515-94b2-721dab091171)
![AGGrid](https://github.com/ag-grid/ag-grid/assets/79447519/9a5bf8ca-71f7-4208-b9c7-d26fb97b1c89)

**Comment by zoheil-ag** [comment] 2023-08-03 10:08
Hi @Praveen-Bandi,

Thank you for the extra information.

I'm unable to reproduce this on the devices available to me using the example from our documentation. Can you confirm if the issue you are facing also occurs without your custom css?
In other words can you replicate the issue with our unaltered examples from the documentation?

Also, I didn't get this part: "Please note that, we are not able to see the filter icons when we open above AG Grid example in Samsung Galaxy Tab A8.". Can you clarify, are you saying the default unaltered examples do not render the filter icons for you?

Kind regards,

**Comment by Praveen-Bandi** [comment] 2023-08-03 10:21
Hi @zoheil-ag ,

Can you please try accessing the below link from android device and check if we can use filter functionality?
https://www.ag-grid.com/examples/filtering/provided-filters/packages/angular/index.html

In our case, by following above example, we are not able to use filter functionality on android device. So, we have added custom css which shows filter icon always. Thus, we are able to use filter functionality on Android devices (or on touch screens).

Regards,

**Comment by zoheil-ag** [comment] 2023-08-03 11:12
Hi @Praveen-Bandi,

To use the column menu for filters on touch-devices you have two options:

1) Tap and hold the column header area to open the column menu (this should work by default and works with the link you've sent above)
2) Alternatively, you can force the column menu button to always show so that you can tap on it without need to hold by using the property `suppressMenuHide`. You can see this implemented here: https://plnkr.co/edit/yMHpqt13tRFjHenq?open=main.js

Does that help?

**Comment by AG-Zoheil** [comment] 2023-09-11 15:27
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-09-11 15:27 UTC
Labels: waiting-for-repro
