### ISSUE TITLE
Flickering group headers

### ISSUE THREAD

**Issue by rochecompaan** [ag-grid/ag-grid#5533] opened 2022-09-06 15:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Group headers flicker when rowData is updated.
Normal headers don't show this behaviour, only group headers.

**Expected behavior**
Group headers should not flicker.

**Code sandbox showing the bug**
https://codesandbox.io/s/smoosh-monad-vrlcvj
**To reproduce**: Click on "Remove record". Notice how the grouped column header "Continent" is flickering.

* **AG Grid version:**
28.1.1

* **Browser:**
Any browser

* **Language:**
all

**Comment by rochecompaan** [comment] 2022-09-07 12:49
@StephenCooper thank you for the update and the recommendation. I went down a similar path after revisiting the updates to the AgGrid documentation that were made when v27 was released, and I could see it working with columnDefs.

**Comment by rochecompaan** [comment] 2022-09-07 16:37
@StephenCooper, unfortunately, group headers still flicker even with your recommended approach. I updated your sandbox to illustrate the problem: https://codesandbox.io/s/divine-butterfly-uh6l7r

Clearly there must be an issue in that re-renders only make **group** headers flicker, no other headers?

**Comment by kiril-matev** [comment] 2022-09-12 15:22
Hello @rochecompaan!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7249 [React] When column definitions have a dependency on a state variable, changing the state valuable value causes column group headers to flicker**

Until this is fixed, avoid having the Column Defs change each time the state variable changes. Instead, when you need to update the column headers in response to a state variable change, you can achieve this without updating Column Definitions by using a custom Column Header Component that would react to the state variable change.

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by rochecompaan** [comment] 2022-09-13 07:33
@kiril-matev thank you for your feedback. We will try the workaround you suggested in the meantime.

**Closed** 2022-09-28 15:28 UTC
Labels: AG-7249

**Comment by SBFrancies** [comment] 2023-01-19 12:56
Is there any update on this. The backlog item AG-7249 now seems to refer to a completely different issue in the changelog (Provide support for Vue 3 urlql).

**Comment by Cleanshooter** [comment] 2023-03-14 14:43
This is was marked as fixed in AG-Grid 28.2.1 - AG-7247 (NOT AG-7249 as indicated above).

From the changelog: "This issue is fixed and requires that the groupId property of column definitions for column groups is set." 

I have added a **groupId** to all my column groups and I still experience the flickering behavior of the column headers, I have also ensures that my **columnDefs** utilize a **useMemo** function. 

I believe this is needs to be re-opened.

**Comment by gaurease** [comment] 2023-09-07 05:52
Hi @StephenCooper , I have updated to version 29.2 and it's still flickering. Was it fixed ?

**Comment by AG-Zoheil** [comment] 2023-09-07 11:12
Hi @gaurease,

Sorry to hear you are still having issues with this. Are you able to provide a plunker showing the issue?

I am unable to reproduce it on `29.2.0` - see here: https://plnkr.co/edit/eUM6K0I3h7RfEXj7?open=index.tsx

Thanks,
Zoheil
