### ISSUE TITLE
Infinite / strange / erroneous sorting on column of type number or date in Vanilla JavaScript

### ISSUE THREAD

**Issue by CyNETT** [ag-grid/ag-grid#7604] opened 2024-02-13 15:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
I am testing AG Grid version 31.0.2 and there is a BUG (this BUG is also in all previous versions): when I have ordinary dataset: select * from some_table from MS-SQL (or ORACLE - it doesn' matter) with approximately 1000 or more rows, and there are some columns of type number or date (eg. numeric(20,2) ) and I press sort on such column (of type number) - sometimes sorting will never end - Grid can not stabilise itself and is trying to sorting infinitely... (this happens randomly when sorting is ascending or descending)
**This BUG appears only if numbers in such columns are the same (eg 100 rows with number 1234.56 - kind of "duplicate rows"); when the numbers in rows are different - then it is sorting well..**

AG Grid is in Vanilla JavaScript (so no any 3rd-party buggy "frameworks" like angular/react/vue/etc..)

**Customers of AG Grid**
For now, I am testing, BUT I will be payable customer of AG Grid, when such bugs gone..

**Providing a Reproducible Scenario**
I can't reproduce it, because it is private / sensitive data, but may be I can record some video with blurr of sensitive data.

**Current behavior**
sorting of columns of type number or date (when the numbers / dates are the same) fails / tends to sort for infinite

**Expected behavior**
I am expected normal sorting :-)

**Please tell us about your environment:**
WEB server: Windows 10 Enterprise 22H2 (for developing), IIS version 10
Tested solutuion is developed in .NET framework 4.8 (server-side in ASPX / C#; client-side: Vanilla JavaScript / HTML)
Tested in: Brave, Google Chrome, MS EDGE

* **AG Grid version:** X.X.X
31.0.2

* **Browser:**
brave/chrome: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
EDGE: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by AG-Zoheil** [comment] 2024-02-15 10:36
Hi @CyNETT,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
I have attempted to simulate your describe scenario with the following plunker but have been unable to do so: https://plnkr.co/edit/m7IsNMs7QmbMnUM7?open=main.js.

Please either fork and adjust the above plunker or send us a new live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by CyNETT** [comment] 2024-02-15 15:06
I must note, that I am testing: rowModelType: 'serverSide'
How to test serverSide in plunker ?
..and my select looks like:
select
	order_field,
	some_field1,
	some_field2
from MS_SQL_TABLE
order by order_field asc offset 0 rows fetch next 100 rows only

**Comment by CyNETT** [comment] 2024-02-16 16:13
See attached video.

https://github.com/ag-grid/ag-grid/assets/122586221/75329461-572f-4d79-acd5-fea9c143c501

**Comment by AG-Zoheil** [comment] 2024-02-22 15:45
Right, thanks for the video @CyNETT.

I'm afraid we would need to be able to reproduce this to effectively investigate and diagnose this.

Are you able to configure any of the SSRM examples we have in our documentation to match the behaviour you are experiencing?

For example, looking at the first example from [here](https://www.ag-grid.com/javascript-data-grid/server-side-model-sorting/#server-side-sorting):

https://plnkr.co/edit/tzeULHIG8NvtKnk7?open=main.js

When I sort by the column SILVER which has many values that are "0" (ie duplicate) I am unable to reproduce the behaviour that can be seen in your video.

**Comment by andrew-w-ross** [comment] 2024-03-21 21:14
@AG-Zoheil I'm getting the exact same behaviour 31.2.0 using react. But it doesn't seem to have anything to do with numbers but duplicate row id's. Took a while but [here is a plunker](https://plnkr.co/edit/gCVBWMKmjxbuDbLl?open=main.js) to duplicate it. If you scroll down the page a bit you'll see it will fetch constantly and show the same behaviour @CyNETT had.

**Comment by AG-Zoheil** [comment] 2024-03-22 15:18
Hello @andrew-w-ross,

Thank you for the reproduction scenario - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11124**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-03-22 15:18 UTC
Labels: AG-11124
