### ISSUE TITLE
AG-Grid cell edit behaviour inconsistent with official documentation

### ISSUE THREAD

**Issue by JSB97** [ag-grid/ag-grid#4571] opened 2021-07-08 10:06 UTC
Submitting a bug report

**Current behavior**
In the grid I created, some key presses edit the cell content (eg 0,a,q), while others such as (1,2,3,4,5,p) do not. A reproducible example is [here](https://codesandbox.io/s/aggridautoresizetofitcontainer-forked-jrn46?file=/src/simpleGrid.tsx), under ./src/simpleGrid.tsx.

**Expected behavior**
According to the [ag-grid](https://www.ag-grid.com/react-grid/cell-editing/#enter-key-navigation) documentation, entering keys such as  (1,2,3,4,5,p) should result in the cell content being edited:

> If you have colDef.editable=true set for a column, editing will start
> upon any of the following:  ... Printable Key Pressed: Any of the
> following characters are pressed: 
> abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!"£$%^&amp;*()_+-=[];\'#,./\|<>?:@~{}
> 
> If this happens then params.charPress will contain the character that
> started the edit. The default editor places this character into the
> edit field so that the user experience is they are typing into the
> cell.

**AG Grid version:** 
"ag-grid-react": "^25.3.0",

**Browser:**
Firefox 89.0.2
Chrome 91.0.4472.114 

**Language:** [ ES6/7 ]

**Comment by makinggoodsoftware** [comment] 2021-07-20 16:09
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2021-07-22 13:13
Hello!

Thank you for the context you've provided.

We are trying to reproduce your issue on our end, but we can't.

Please take a look at the gif below:

![editing-bug-poc](https://user-images.githubusercontent.com/37620997/126644605-5ef170eb-b95a-494e-9bc2-1ee847fd20c1.gif)

As you can see in the above gif, it seems to be working on our end. 

We tested this on Chrome Version 92.0.4515.107.

We will be closing this issue as it is not a bug, however, if you have more information on how we can reproduce the issue, feel free to reopen the issue.

**Closed by shuheb** 2021-07-22 13:13 UTC
Labels: in_zendesk

**Comment by lucasflomuller** [comment] 2024-11-01 16:01
> Hello!
> 
> Thank you for the context you've provided.
> 
> We are trying to reproduce your issue on our end, but we can't.
> 
> Please take a look at the gif below:
> 
> ![editing-bug-poc](https://user-images.githubusercontent.com/37620997/126644605-5ef170eb-b95a-494e-9bc2-1ee847fd20c1.gif) [ ![editing-bug-poc](https://user-images.githubusercontent.com/37620997/126644605-5ef170eb-b95a-494e-9bc2-1ee847fd20c1.gif) ](https://user-images.githubusercontent.com/37620997/126644605-5ef170eb-b95a-494e-9bc2-1ee847fd20c1.gif) [ ](https://user-images.githubusercontent.com/37620997/126644605-5ef170eb-b95a-494e-9bc2-1ee847fd20c1.gif)
> 
> As you can see in the above gif, it seems to be working on our end.
> 
> We tested this on Chrome Version 92.0.4515.107.
> 
> We will be closing this issue as it is not a bug, however, if you have more information on how we can reproduce the issue, feel free to reopen the issue.

This seems to happen when I use my numbers too, on any aggrid example. It might work on a numpad but I can't test it
