### ISSUE TITLE
Performance bottleneck when using immutable data

### ISSUE THREAD

**Issue by travikk** [ag-grid/ag-grid#4239] opened 2020-12-11 03:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
When using dataset with row id of type string, performance of regrouping (by assigning updated dataset) is vastly different compared to when row id is of type number.
For a dataset of 10000 rows, when using string id, regrouping all of the rows takes around 18s. Same scenario, when using rows with number id, regrouping operation takes 2s.

The biggest performance degradation can be observed when going from one group to many groups. To reproduce that scenario first click on "Same product" and then "Random products" button to move rows to one group and then many groups.

Additionally you can tweak whether the code is using rows with number or string id in *main.js* file by toggling *ROW_ID_IS_STRING* property.

https://plnkr.co/edit/GKzfJyoYIZwAlD6F

**Note:** this can be only observed when using immutable data.

**Expected behavior**
Expected behavior is that when using rows with string identifier the performance of regrouping operation is as fast as when using number identifiers.

**Please tell us about your environment:**
MacOS 11.0.1, Chrome 87

* **ag-Grid version:** 24.1.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

* **Language:** all

**Please note I am enterprise customer but we are not allowed to submit anything through our enterprise channel hence I am using github**

**Comment by makinggoodsoftware** [comment] 2020-12-16 12:26
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by travikk** [comment] 2021-01-07 02:24
Hi, could you provide any update if available? @makinggoodsoftware

**Comment by makinggoodsoftware** [comment] 2021-01-07 15:34
Hi,

We were able to reproduce this:


updating the rows grouped property is slow when row id’s are strings and gridOptions.immutableData = true
https://plnkr.co/edit/hJnjHkWFJkiulo07
note: if you change any of the following properties then the updates are much quicker:
row id’s from type string to type numbers (change ID_TYPE_STRING variable from true to false)
the field being grouped in the grid is not being updated (e.g. changing rowGroup:true from country column to year column)
turn off immutable data (comment out line 40)

We are currently raising this with the dev team, we should update here soon

Thanks for the patience

**Comment by travikk** [comment] 2021-01-11 06:06
@makinggoodsoftware so I tested on 25.0.0 and the issue is somewhat resolved. Now, the update takes ~70ms (with the link above) in both scenarios, which is very good. However, when after the update all items for a group are removed, the group node itself isn't removed from the grid and appears as a row with 0 entities inside.

**Comment by makinggoodsoftware** [comment] 2021-01-11 15:59
Hi,

You nailed the update 😄 

I was going to let you know that this was indirectly fixed in v25 but that there was an outstanding bug in this area

The issue you are seeing is tracked by AG-4938

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

AG-4938 | CSRM and Transactions, empty groups are not removed
-- | --


Note that we are expecting to fix this in our next release

**Comment by makinggoodsoftware** [comment] 2021-01-18 16:09
Hi,

This was fixed in v25.0.1 

Can you please check if this is fixed now on your end?

Thanks

**Comment by travikk** [comment] 2021-01-19 05:35
Hey @makinggoodsoftware yeah, looks like the issue has been addressed. Thanks for the swift turnaround.

**Closed** 2021-01-21 17:13 UTC
Labels: AG-4938, ag-grid engaged, in_zendesk

**Comment by DAVIDSUSAIRAJ** [comment] 2022-08-29 17:28
I applied immutable data and getRowNodeId at the time if the two name are equal in the first column,automatically created one row. What is the reason? Why is happening? How do i fixed that one.
