### ISSUE TITLE
Multi Column Sorting with Comparator

### ISSUE THREAD

**Issue by yvgrant** [ag-grid/ag-grid#7850] opened 2024-04-15 13:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Multi Column Sorting when columns are using a comparator fails. The first column sorts just fine, but the comparator for any other columns added to the sort is not called. The below Plunker has separate comparators for each column, but the same behavior exists if the defaultColDef has a comparator instead of defining for each column.

Plunker: https://plnkr.co/edit/Dams7qmPzWG6tAHA?open=main.ts

**Current behavior**
Using the aforementioned Plunker, sort on the Country column, then hold ctrl and sort on the Athlete column to apply multi column sorting. Note that the Country column is correctly sorted, but the Athlete column retains its original order though its column header shows that sorting is applied. Clicking the Athlete column header again shows that it should now be ordered in descending order, but the data remains in the original order.

**Expected behavior**
Sorting on more than one column when using comparators for the columns accurately applies multi column sorting.

* **AG Grid version:** X.X.X
I'm assuming the Plunker is using the latest version of AG-Grid, but in my specific environment, I'm using Javascript Ag-Grid version v29.3.5

* **Browser:**
Browser: Chrome and Edge

* **Language:** TypeScript

**Comment by AG-Zoheil** [comment] 2024-04-16 09:34
Hello @yvgrant,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11331**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-04-16 09:34 UTC
Labels: AG-11331

**Comment by AG-Zoheil** [comment] 2024-07-29 13:12
Hi @yvgrant,

Whilst reviewing this, we've noticed that the comparator in your example has not been defined properly.
Please see here for a working version: https://plnkr.co/edit/UNSReMj3yg1qSdXo?open=main.ts&preview

We are therefore deleting this item from our backlog as it is not a bug.

Kind regards,
Zoheil

**Comment by yvgrant** [comment] 2024-07-29 14:11
Ok yes, I see that now, thank you.

Grant Shoemaker
YardView|Director of Software Engineering
P: (303)962-6434
C: (303)877-5603
________________________________
