### ISSUE TITLE
When in viewport row mode, setRowCount in datasource works slow

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#3516] opened 2019-11-15 09:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**
I am Paid Customer of ag-grid (working in Deutsche Bank TechCenter), you can contact me via alexander.makhov@db.com

**Providing a Reproducible Scenario**
https://next.plnkr.co/edit/sjoHDjYQNHLCsGpo
1. setup grid in viewport row mode
2. generate frequent setRowCount

**Current behavior**
setRowCount triggers re-inserting rows into ag-grid which is heavy

**Expected behavior**
1. setRowCount should not redraw rows which are left in place

**Please tell us about your environment:**
plunkr...

* **ag-Grid version:**
22.0.0

* **Browser:**
Actually Chrome
navigator.userAgent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"

**Comment by catahoc** [comment] 2019-11-15 09:40
I'm wrong: that is fixed in ag-grid@22.0.0, I was just incorrectly setting rowData for viewport

**Comment by catahoc** [comment] 2019-11-15 09:49
Reopening issue as setRowCount still does redundant work
![image](https://user-images.githubusercontent.com/2704650/68933751-6a715800-07a6-11ea-98be-dc68cc3688c7.png)

**Comment by davis4acca** [comment] 2019-11-15 14:03
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment] 2019-11-18 10:19
Hi,

I am not sure what your issue is given the description, note that to be able to offer support efficiently, we need to be able to reproduce your issue on our end, and given this information, we are not sure how to proceed.

Could you please explain what you mean by: 

> Current behavior
> Each insert/remove triggers 2 events:
> 
> setRowCount (+1 or -1). triggers re-inserting rows into ag-grid which is heavy
> setRowData was slow in ag-grid@20.1.0 but improved in ag-grid@22.0.0 - thanks to ag-grid team
> Expected behavior
> 
> setRowCount should not redraw rows which are left in place

From the provided plunker, I'm not sure how I can do this. 

If these are intended as instructions for the code, can you please specify where and exactly how the codev needs to be manipulated to illustrate your issue? 

Thanks

**Comment by catahoc** [comment] 2019-11-18 10:34
Hi, icedjello,
That is my fault - I initially raised the issue at ag-grid@20.* where both .setRowCount and .setRowData worked slow. Then I switched to ag-grid@22.* and found out, that .setRowData now works relatively good - it keeps already rendered rows instead of redrawing them.

So I changed issue accordingly and the issue is that .setRowCount for viewport mode triggers unwanted rows redraw. This can heavily impact performance of grid with many custom renderers.

And I don't see rationale for that behavior - just as setRowData, setRowCount can keep already rendered rows

**Comment by icedjello** [comment] 2019-11-18 15:13
Hi, 

Thank you for your email. Please allow us some time to do some research, we will come back to you as soon as possible with an update.

Regards

**Comment by icedjello** [comment] 2019-11-19 13:12
Hi, After looking further into this. We have concluded that setRowCount does not explicitly trigger a redraw/refresh. The row model you are using is highly dependent on the how the you utilise the pattern to get/set data, thus if the model is not followed explicitly, such effects may occur. 

Please have a look at the following example showing how the viewport is intended to be used: 
https://next.plnkr.co/edit/zlcuDWNThugKJfG7 

Furthermore, if you refer to our docs, you will note that: 
```
// datasource calls this method when the total row count changes. 
// This in turn sets the height of the grids vertical scroll.
setRowCount: (count:number) => void;
```

I'll now be closing this thread. 

For further assistance please contact us via Zendesk. 

Many thanks,

**Closed by icedjello** 2019-11-19 13:12 UTC
Labels: in_zendesk

**Comment by catahoc** [comment] 2019-11-19 14:16
Hi, icedjello, thanks for your response,
You obviously wrong, because your example is limited: row count never changes. In real life applications when you create some event grids, row count changes much more frequently (usually incrementing by 1  at a time, for example 10000 => 10001 => 10002 and so on)

I've forked your plunk by adding setInterval which changes rowCount at line 298 and disabling periodic updates - issue is still reproducing:
![image](https://user-images.githubusercontent.com/2704650/69153975-35d80600-0af0-11ea-872d-9323ca5798ad.png)

**Comment by davis4acca** [comment] 2019-11-21 11:23
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3594 - Improve performance of setRowCount in the Viewport Row Model
