### ISSUE TITLE
getSelectedRows doesn't use type param TData

### ISSUE THREAD

**Issue by bviebahn** [ag-grid/ag-grid#8538] opened 2024-08-13 08:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
The type for `getSelectedRows` doesn't get correctly inferred. I have this function:
```ts
const handleSelectionChanged = (e: SelectionChangedEvent<string>) => {
  const api = e.api; // GridApi<string>
  const getSelectedRows = api.getSelectedRows; // () => any[] ??
}
```
I think this was introduced in the latest release 32.1.0, it seemed fine in 32.0.2.

**Expected behavior**
type gets inferred correctly:
```ts
const handleSelectionChanged = (e: SelectionChangedEvent<string>) => {
  const api = e.api; // GridApi<string>
  const getSelectedRows = api.getSelectedRows; // () => string[]
}
```

**Please tell us about your environment:**
MacOS, VSCode, pnpm

* **AG Grid version:**
* 32.1.0

* **Browser:**
Chrome

* **Language:** [TypeScript 5.5.4]

I created this patch, which seems to solve this specific issue. Not sure if the types are wrong in other places.
```
# generated by patch-package 6.4.10
#
# command:
#   npx patch-package ag-grid-community
#
# declared package:
#   ag-grid-community: ^32.1.0
#
diff --git a/node_modules/ag-grid-community/dist/types/core/api/gridApi.d.ts b/node_modules/ag-grid-community/dist/types/core/api/gridApi.d.ts
index 942f887..fb0578e 100644
--- a/node_modules/ag-grid-community/dist/types/core/api/gridApi.d.ts
+++ b/node_modules/ag-grid-community/dist/types/core/api/gridApi.d.ts
@@ -893,8 +893,8 @@ export interface _AdvancedFilterGridApi {
      */
     hideAdvancedFilterBuilder(): void;
 }
-export interface _CoreModuleGridApi extends _CoreGridApi, _StateGridApi, _RowSelectionGridApi, _RowGridApi, _ScrollGridApi, _KeyboardNavigationGridApi, _EventGridApi, _CellGridApi, _CommunityMenuGridApi, _SortGridApi, _OverlayGridApi, _PinnedRowGridApi, _RenderGridApi, _DragGridApi, _ColumnGridApi, _DragGridApi, _EditGridApi, _FilterGridApi, _ColumnFilterGridApi, _QuickFilterGridApi, _PaginationGridApi, _CsrmSsrmSharedGridApi, _SsrmInfiniteSharedGridApi {
+export interface _CoreModuleGridApi<TData> extends _CoreGridApi, _StateGridApi, _RowSelectionGridApi<TData>, _RowGridApi, _ScrollGridApi, _KeyboardNavigationGridApi, _EventGridApi, _CellGridApi, _CommunityMenuGridApi, _SortGridApi, _OverlayGridApi, _PinnedRowGridApi, _RenderGridApi, _DragGridApi, _ColumnGridApi, _DragGridApi, _EditGridApi, _FilterGridApi, _ColumnFilterGridApi, _QuickFilterGridApi, _PaginationGridApi, _CsrmSsrmSharedGridApi, _SsrmInfiniteSharedGridApi {
     dispatchEvent(event: AgEvent): void;
 }
-export interface GridApi<TData = any> extends _CoreModuleGridApi, _ClientSideRowModelGridApi<TData>, _SideBarGridApi, _StatusBarGridApi, _InfiniteRowModelGridApi, _CsvExportGridApi, _RowGroupingGridApi<TData>, _RangeSelectionGridApi, _ServerSideRowModelGridApi, _MenuGridApi, _MasterDetailGridApi, _ExcelExportGridApi, _ClipboardGridApi, _GridChartsGridApi, _AdvancedFilterGridApi {
+export interface GridApi<TData = any> extends _CoreModuleGridApi<TData>, _ClientSideRowModelGridApi<TData>, _SideBarGridApi, _StatusBarGridApi, _InfiniteRowModelGridApi, _CsvExportGridApi, _RowGroupingGridApi<TData>, _RangeSelectionGridApi, _ServerSideRowModelGridApi, _MenuGridApi, _MasterDetailGridApi, _ExcelExportGridApi, _ClipboardGridApi, _GridChartsGridApi, _AdvancedFilterGridApi {
 }

```

**Comment by StephenCooper** [comment] 2024-08-13 15:51
Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-12581 [Typing] Pass Generics to Sub Api Interfaces

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2024-08-13 15:51 UTC
Labels: AG-12581
