### ISSUE TITLE
Table header row and body do not horizontally scroll together / can misalign

### ISSUE THREAD

**Issue by ryan-mccaffrey** [ag-grid/ag-grid#6875] opened 2023-07-13 16:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

For some context, I'm using AG Grid to create a table in which the header cells have an input box that users can type a queries into, as if to perform a search that would populate the cells below the header in the same column. I've found an issue where the alignment of the header row can detach itself from the alignment of the rest of the table cells, specifically when an input box that is partially overflowed is focused and a user types into the input box such that their cursor would go offscreen. A screenshot of what this looks like from my sandbox application:

<img width="1239" alt="Screen Shot 2023-07-13 at 12 53 31 PM" src="https://github.com/ag-grid/ag-grid/assets/15670042/8f743547-82d2-4cee-81de-e5e7791bcddc">

I've found that this issue occurs for AG Grid version >=29.3.0 and is a product of the removal of styling the `ag-header-container` class with a `transform:` attribute, which changed in [this PR](https://github.com/ag-grid/ag-grid/commit/52d1b464ed9b0cc1b2f1bbf9a10c6cf7ccbd25f2). With the `transform:` attribute in the older versions of AG Grid, it appears that the horizontal position of the grid is fixed until the user physically scrolls the table, whereas without the transform the horizontal position can be changed through other means, such as a cursor going offscreen.

I've created a playground in CodeSandbox that uses the latest AG Grid 30.0.3, where the issue is still present: https://codesandbox.io/s/react-typescript-playground-forked-ns5fvz?file=/src/ExampleTable.tsx (I had difficulty trying to make a react typescript environment in plunker).

To reproduce in the playground:
1. Focus on the input box that is partially offscreen
2. Begin typing content into the input box. The more that is typed, the more that the header row begins to offset itself from the rest of the table
3. Horizontally scrolling the table after the header and body are misaligned will generally cause the table to snap back into alignment (I've run into certain scenarios where this is not always the case in production, but haven't been able to reliably reproduce it).

Expected behavior:
If I were to type into an input box that is partially offscreen, either the header does not move and the typing occurs offscreen, or if the header does offset, then the rest of the table would offset with it.

* **AG Grid version:** >= 29.3.0 (ongoing: Yes)
* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 
* **Language:** TypeScript 4.5, though i suspect this is reproducible in all languages.

**Comment by adithram** [comment] 2023-07-13 16:56
Running into the same issue. Would appreciate assistance.

**Comment by kiril-matev** [comment] 2023-07-14 17:00
Hello,

Thank you for bringing this up with us. 

Scrolling the grid viewport from the header row isn't currently supported and wasn't part of the requirements initially when the scrolling feature was built. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-2065 [Scrolling] Allow scrolling horizontally using the trackpad/mouse wheel when over the column headers**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by ryan-mccaffrey** [comment] 2023-07-14 17:05
Hi @kiril-matev ,

Thanks for the quick response here. I am fine that the header row does not allow for scrolling the grid viewport, but the current version of AG Grid does unintentionally allow for the header to scroll separately from the rest of the viewport. I believe this is a bug rather than a feature request, and think this should be marked separately from AG-2065, unless there is specific thought that implementing AG-2065 will also fix this bug

**Comment by CyNETT** [comment] 2023-08-06 19:54
I also have this issue: when scrolling using bottom (horizontal) scroll bar, header sometimes does not scroll synchronously with columns. Tested with version 30.0.5

**Comment by kiril-matev** [comment] 2023-08-07 10:48
@CyNETT 
We're keen to look into the behavior you've described. 

Please a separate GitHub issue for this so we can process it. Please follow the issue submission format - sample project reproducing the issue, a test case (a list of steps to follow to reproduce it), actual/expected behavior descriptions.

**Comment by AG-Zoheil** [comment] 2023-09-18 10:53
The original issue reported here has been assigned to our backlog. For any further issues, please open a new Github issue so it can be processed in a clean and efficient manner.

If the issue has already been resolved by other means, you can ignore this.

In light of the above and as this has been open without any further interaction for a while, I will be closing this issue.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-09-18 10:53 UTC
Labels: ag-2065

**Comment by jainKinjal02** [comment] 2025-01-22 10:05
Is this issue fixed ? Because I am facing the same issue, on scrolling column headers , disturbs the alignment with table data.

<img width="644" alt="Image" src="https://github.com/user-attachments/assets/00a3af7d-aec8-4974-ac3a-ce1e2d634a58" />

**Comment by EvPng** [comment] 2025-08-05 18:50
If anyone's encountering the same issue, I fixed it by disabling a global style I had that set scroll behavior to smooth. Now the header and rows are scrolling horizontally in sync and instantly.

**Comment by omlondhe** [comment] 2025-09-26 18:52
You saved me with this solution @EvPng ❤️

> If anyone's encountering the same issue, I fixed it by disabling a global style I had that set scroll behavior to smooth. Now the header and rows are scrolling horizontally in sync and instantly.
