### ISSUE TITLE
Stop editing when double click header

### ISSUE THREAD

**Issue by lotfilouzir** [ag-grid/ag-grid#4472] opened 2021-05-06 16:09 UTC
Hello, 

I have an issue with stop editing when i double click on a header has children columns.
**Reproduction**
Double click on a cell to edit.
Double click on a header (Athlete Details or Sports Results).
https://plnkr.co/edit/Lc4UUzgcWZSXOu04

**Current behavior**
Stop editing when double click on the header (Athlete Details or Sports Results).

**Expected behavior:**
Do not stop editing when double click on the header (Athlete Details or Sports Results).

The double click on the header child "Athlete" do not stop editing, but the double click on the header "Athlete Details" stop editing.

**Comment by makinggoodsoftware** [comment] 2021-05-11 16:04
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-05-14 10:14
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5340 When editing a grid cell, clicking a column header cell doesn't end the cell edit**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment] 2021-05-17 09:43
Hello!

We've taken a look at this and found you can implement the behavior you want by setting the stopEditingWhenGridLosesFocus property to true.

Steps to illustrate:
1. Open
https://plnkr.co/edit/ZCDX8j6SyMN04tJd
2. Double-click a cell to start editing
**Actual & Expected**: Cell enters edit mode

3. Click a column header cell
**Actual & Expected**: Edited cell is no longer in edit mode

I hope this helps. As you can achieve the functionality requested with AG Grid as shown above, we will close this bug as rejected.

Thank you for reporting this - much appreciated!

**Closed** 2021-06-04 15:53 UTC
Labels: ag-5340, in_zendesk
