### ISSUE TITLE
After updating to v24 community edition on vue v2 I get compile warnings.

### ISSUE THREAD

**Issue by sdwru** [ag-grid/ag-grid#4147] opened 2020-10-16 14:04 UTC
I am assuming this is because of vue v3 compatibility and everything will still work on v2?  

So far, everything I am using still seems to work on Vue v2.  

I tried suppressing the warnings but I cannot.  Even if I disable or remove eslint.  The warnings seem to be coming from npm not lint.  Seems to me this is something that should probably be checked in the Ag Grid code.

```
 warning  in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js

"export 'Options' was not found in 'vue-class-component'

 warning  in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js

"export 'Vue' was not found in 'vue-class-component'

 warning  in ./node_modules/@ag-grid-community/vue/lib/VueComponentFactory.js

"export 'createApp' was not found in 'vue'

 warning  in ./node_modules/@ag-grid-community/vue/lib/VueComponentFactory.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@ag-grid-community/vue/lib/VueComponentFactory.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@ag-grid-community/vue/lib/VueComponentFactory.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@ag-grid-community/vue/lib/VueComponentFactory.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@ag-grid-community/vue/lib/AgGridVue.js

"export 'h' was not found in 'vue'
```

**Comment by makinggoodsoftware** [comment] 2020-10-19 10:46
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is flagged with waiting-for-repro.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by orim181** [comment] 2020-10-20 14:03
I reported it as well being an enterprise user and AG-Grid acknowledged the regression bug and logged it under:
AG-4723 [Regression] When building a ag-Grid with vue.js, you get error AgGridVue.js dependency was not found

Just letting you know.

**Comment by makinggoodsoftware** [comment] 2020-10-22 11:50
Hi @orim181 

Thanks for the udpate, I was about to also add the reference here:


AG-4723 | [Regression] When building an ag-Grid Vue.Js application, you get error AgGridVue.js dependency was not found
-- | --




Note that since that we don't have a repro scenario we can't guarantee that these two tickets are related, but it looks like they are

**Comment by makinggoodsoftware** [comment] 2020-10-23 11:39
Hi,

We just release v24.1.1 which contains a fix for this, would you mind checking if the issue is now fixed?

Thanks

**Comment by sdwru** [comment] 2020-10-23 13:40
The warnings appear to be gone now.  Thanks for the quick resolution guys!

**Comment by Scozzi** [comment] 2020-10-25 17:16
I was seeing this same issue as well as when I load the app I get this error:
Object prototype may only be an Object or null: undefined:

this is my component code:
`js
<template>
  <ag-grid-vue style="width: 500px; height: 500px;"
      class="ag-theme-alpine"
      :columnDefs="columnDefs"
      :rowData="rowData">
  </ag-grid-vue>
</template>

<script>
import axios from 'axios';
import { AgGridVue } from "ag-grid-vue3";

export default {
  name: 'GuildDiscovery',
  props: {},
  data () {
    return {
      name: 'GuildDiscovery',
      columnDefs: null,
      rowData: null
    }
  },
  components: {
    AgGridVue
  },
  mounted: function () {
    this.$log.info("CONTEXT : ", this.name + " : MOUNTED");
    this.hitServer('/');
    this.hitServer('/guilds');

    this.columnDefs = [
      { headerName: 'Guild ID', field: 'guildID' },
      { headerName: 'Guild Name', field: 'name' },
      { headerName: 'Master', field: 'master' },
      { headerName: 'Tag', field: 'tag' },
      { headerName: 'Race', field: 'Race' },
      { headerName: 'Members', field: 'members' },
      { headerName: 'Total Points', field: 'totalPoints' },
      { headerName: 'Average Points', field: 'avgPoints' },
      { headerName: 'Description', field: 'description' },
      { headerName: 'Lieutenants', field: 'lieutenants' },
      { headerName: 'Guild Members', field: 'guildMembers' },
    ];
  },
...
...
`

left of the axios stuff there.  Anyway I tried it with both ag-grid-vue 3 and ag-grid-vue.  
    "@ag-grid-community/vue3": "^24.1.1",
    "ag-grid-community": "^24.1.0",
    "ag-grid-vue": "^24.1.1",
    "ag-grid-vue3": "^24.1.1",
@sdwru which are you using?

@sdwru, @makinggoodsoftware if anything wrong there stands out please let me know.  Im using vue cli and vue3 (but honestly the project is mostly composed in a vue 2 style and not typescript)

**Comment by Scozzi** [comment] 2020-10-25 19:21
it also asked I add a bunch of other dependencies I didnt expect..
"vue-loader-v16": "^16.0.0-beta.5.4"
"vue-property-decorator": "^9.0.2"

**Closed** 2020-12-24 11:24 UTC
Labels: managed-by-community, wontfix
