### ISSUE TITLE
Issue regarding custom editor getValue() method in vue 3 <script setup>+ vite

### ISSUE THREAD

**Issue by pvsairohith** [ag-grid/ag-grid#8542] opened 2024-08-14 08:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

In our project we are using aggrid so i created a custom cell editor (vue 3 composition api + vite ) with <script setup>  for a particular column and exposed the getValue() method by using defineExpose() but the grid is not accessing the get value but when we change the code format to vue3 composition api with out setup method then it is accessing the get value

https://github.com/ag-grid/ag-grid/issues/7970 this is already existing issue could you please look into it

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by pvsairohith** [comment] 2024-08-14 08:37
the aggrid version is 31.2.1
browser : chrome
Typescript: 5.3.0

**Comment by AG-Zoheil** [comment] 2024-08-14 08:41
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10708**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-08-14 08:41 UTC
Labels: AG-10708

**Comment by pvsairohith** [comment] 2024-08-16 03:16
hi @AG-Zoheil  i have seen in pipeline that AG-10708 is not added in the backlog could you please guide me if anything i missed

**Comment by AG-Zoheil** [comment] 2024-08-16 08:10
Hi, 

This was due to an admin error and has now been rectified.

Thank you!
