### ISSUE TITLE
ApplyColumnDefOrder does not affect order of autoGrouped columns

### ISSUE THREAD

**Issue by ppatliakevych** [ag-grid/ag-grid#4626] opened 2021-08-16 13:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Hello, AgGrid Team,

I'm facing the issue when after setting new `ColDefs`, autoGroup columns are not reordered. I'm setting `applyColumnDefOrder`  to `true` and `groupMultiAutoColumn`  to `true`  in the `gridOptions` and it has effect only for non-autoGroup columns.

Steps to reproduce:
1) set `applyColumnDefOrder`  to `true` and  `groupMultiAutoColumn`  to `true` in the `gridOptions`;
2) set initial colDefs to AgGrid;
3) after some time (setTimeout can be used), please set a new colDefs, where autoGroup columns are reordered.

Expected behavior:
AutoGroup columns are being reordered;

Current behavior:
AutoGroup columns are not reordered;

Link to plunkr:  https://plnkr.co/edit/W2dLzPtSognvrS0R?preview

* **AG Grid version:** 25.3.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"

* **Language:**  TypeScript 4.1.3

**Comment by makinggoodsoftware** [comment] 2021-08-31 14:56
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-09-01 23:38
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v23.2.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5710 [Regression] When calling setColumnDefs with a different group column order, the grouping is not updated**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-09-06 15:39
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-09-06 15:39 UTC
Labels: ag-5710

**Comment by kiril-matev** [comment] 2021-11-12 10:45
Hello!

We've looked into this with the product team and determined this isn't a bug. 

Instead of setting updated column definitions to rearrange the row group positions, please set these positions explicitly using the rowGroupIndex property.

See this approach illustrated in the plunker below which changes the rowGroupIndex  values via api.applyColumnState():
https://plnkr.co/edit/saxwCmHbtXYQ0Zz8

As the grid is working as expected and there's a clear way to implement this functionality using the approach described above, we're closing this bug as rejected.

Thank you for bringing this up with us.
