### ISSUE TITLE
onRowSelected event : (event?: Event | null)  is always null while clicking checkbox for selecting row.

### ISSUE THREAD

**Issue by madhupprasad26** [ag-grid/ag-grid#5802] opened 2022-11-18 10:39 UTC
I'm submitting a ...

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behaviour:**
In onRowSelected event -> when row is selected via checkbox click, (event?: Event | null) is always null.

**Expected behaviour:**
In onRowSelected event -> when row is selected via checkbox click, (event?: Event | null) should be returning Event object.

**Providing a Reproducible Scenario:**
plunker : https://plnkr.co/edit/BSJVpwcKWFJpyQS7?open=index.jsx

**AG Grid version: 27.1.0**

**Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

**Language**: Javascript | React

**Comment by StephenCooper** [comment] 2022-11-21 09:53
Hi @madhupprasad26 

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7558 onRowSelected event : (event?: Event | null) is always null while clicking checkbox for selecting row.

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7558) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-11-22 14:08 UTC
Labels: AG-7558
