### ISSUE TITLE
Missing argument for comparators when sort is inversed

### ISSUE THREAD

**Issue by jgrenat** [ag-grid/ag-grid#1608] opened 2017-04-24 09:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When using a comparator function, arguments are properly given when the order is not inverted, but when the sort is inverted, the second argument is always null.

**Expected behavior**
Second argument should not be null

**Minimal reproduction of the problem with instructions**
I'm using the following comparator function:
```js
const numbersComparator = (value1, value2, ...rest) => {
  console.log(value1, value2, rest);
  return parseFloat(value1) - parseFloat(value2);
};
```

Some output examples when the sort is inverted:

```console
933251.79923797 null [RowNode, RowNode, true]
5604595.7685302 null [RowNode, RowNode, true]
1470436.0506139 null [RowNode, RowNode, true]
1526318.2476297 null [RowNode, RowNode, true]
```

**What is the motivation / use case for changing the behavior?**
Sort is broken when inversed

**Please tell us about your environment:**
Windows 7 Enterprise

* **ag-Grid version:** 9.0.3

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

* **Language:** TypeScript

**Comment by seanlandsman** [comment] 2017-04-25 09:03
Hi,

I'm unable to reproduce this on one or two of the examples we have - do you have a plunker or similar that reproduces this?

thanks

**Comment by seanlandsman** [comment] 2017-05-04 09:45
No repro so closing - please feel free to reopen if you can provide a reproducible test case

**Closed** 2017-10-12 13:43 UTC
Labels: needs_repro
