### ISSUE TITLE
Draging grid column or rows causes other parts of application to highlight blue and stay as it is even after drag end. It is only hapenning in Safari. Chrome is okay

### ISSUE THREAD

**Issue by ssg-financial-com** [ag-grid/ag-grid#6496] opened 2023-04-20 19:25 UTC
Current behaviour.
Step to reproduce
1) Grab a column from agrid and start dragging in safari browser.
2) See the drop zone area is highlighted in blue.
3) After drag end. Still some section of the application is left with blue highlight

Expected behaviour: After drag end blue highlight should be gone

**Please tell us about your environment:**
MAC OS, Safari version: 15.3

* **AG Grid version:** X.X.X
AG grid version: v26.1.0 And ag-grid-vue: v26.1.0

* **Browser:**
Safari: v15.3

Framework
Vuejs

Screenshots
![image](https://user-images.githubusercontent.com/104846817/233467011-21aa8a4b-2b48-4a7d-86a0-be8af46b12ab.png)

![image](https://user-images.githubusercontent.com/104846817/233467067-32b15550-bfe9-45f6-90c2-88124d721867.png)

**Comment by AndrewGlazier** [comment] 2023-04-26 12:22
Hello!

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example plunker (you can fork an existing example from our docs)
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by ssg-financial-com** [comment] 2023-04-27 19:53
Hi Andrew,

You can reproduce this issue at the ag-grid demo from your website: https://www.ag-grid.com/example

Steps to reproduce
1) Open the above ag grid demo in Safari Macbook.
2) Grab a column/row by holding the mouse click on the column header. Drag the column to other parts of the website outside of grid. 
3) Try dragging up and down as shown in the video. See the drop zone is highlighted blue. Now, leave the mouse clicked, that is you let go dragging of the column. You still see blue highlight even after dragging is stooped and you are not holding the column.
4) Do a mouse click somewhere else on website the blue highlight goes away.

Current behaviour
The blue highlight stays even after you let go dragging of the column

Expected behaviour
After you stop dragging the column header and not holding the column with mouse click the highlight should go away. OR may be if we drag column outside of grid there should be no blue highlight in other parts of app.

It only happens in safari browser. With chrome it's not reproducible


https://user-images.githubusercontent.com/104846817/234976106-e4763e9c-6190-4b14-a57c-2df67e274567.mp4

Thanks,

**Comment by ssg-financial-com** [comment] 2023-05-02 14:07
Hello, any update, are you guys able to reproduce it. Let me know if you need anything else. Thanks

**Comment by AndrewGlazier** [comment] 2023-05-09 14:16
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8527 - When dragging to outside of the grid, content is highlighted (Safari)

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-8527) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by AndrewGlazier** 2023-05-09 14:16 UTC
Labels: in_review
