### ISSUE TITLE
Un-tick header checkbox on de-selection of a row

### ISSUE THREAD

**Issue by lunanigra** [ag-grid/ag-grid#2931] opened 2019-02-05 14:00 UTC
When using ag-Grid with headerCheckboxSelection=true you can select all rows via header tick-box. But when de-selecting a row the header tick-box stays selected.

Expected behaviour would be to un-tick the header checkbox as not all rows are selected.

Or other use-case... Select all rows manually - and the header checkbox gets ticked automatically. But it stays ticked even when un-selecting all rows.

Looks like a bug... Please try on sample site...
https://www.ag-grid.com/javascript-grid-selection/#example-header-checkbox-entire-set

**Comment by makinggoodsoftware** [comment] 2019-02-06 15:43
Hi,

This seems like a duplicate of this:

https://github.com/ag-grid/ag-grid/issues/2924

I would suggest you follow that issue

Thanks

**Closed by makinggoodsoftware** 2019-02-06 15:43 UTC
