### ISSUE TITLE
Value formatter: typeof value is changed from number to string for row group nodes

### ISSUE THREAD

**Issue by liamm14** [ag-grid/ag-grid#5619] opened 2022-09-29 09:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
**Current behavior**

https://plnkr.co/edit/vgPkYxCtkTUCrw5K?open=index.tsx
Expand a row, view console, is group is true, typeof params.value is string, if false, type is number.

**Expected behavior**

Typeof params.value to be number for all rows and row groups

**Please tell us about your environment:**

Plunkr

* **AG Grid version:** X.X.X

28.1.1

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6/7

**Comment by AndrewGlazier** [comment] 2022-09-29 10:58
Hi Liam,

When using the grids built in grouping we use string keys by design, this is because inconsistent data types passed to the grid are grouped by their string values.

For example, if you passed the grid: "2006", "2007", Number(2006), the generated group for 2006 would have two rows in it, both with inconsistent data types.

If you're confident in your data type being consistent across all nodes and require access to the original data type, you can access the data from the child nodes used to generate that group node using:
`(params) => params.node.childrenAfterGroup[0].data`

I'm going to close this ticket as this behaviour is by design.

Regards,

**Closed by AndrewGlazier** 2022-09-29 10:58 UTC
