### ISSUE TITLE
Size of Header Cell's click/touch target for sorting is smaller than it used to be

### ISSUE THREAD

**Issue by jneuhaus20** [ag-grid/ag-grid#5632] opened 2022-09-30 22:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

As stated, the size of a header cell's touch/click target keeps shrinking since 26.  The impact is that users think "sorting is broken" because the invisible box of acceptable clicking has shrunk and what used to work no longer works.  Note that the cursor on desktop browsers does not change to indicate this boundary, as it is set at a higher div.

Here's a series of plunkers derived from the row sorting example from different versions with `.ag-header-cell-label` highlighted for easy visual comparison.  Attempting to sort these columns will show that the green area is where you must click to sort.

[In 26](https://plnkr.co/edit/Ues1510eQ9EuXEF6)
[In 27](https://plnkr.co/edit/Ar5n7hfc9PDfsqzX)
[In 28](https://plnkr.co/edit/0hrZakyRPEVO5WO4)

You can see in 28 that this has become a very tight box around the text.

**Current behavior**
There's a very narrow strip you can click on to sort, with no visual distinction of the extents aside from the label text.

**Expected behavior**
The target should be the entire header cell, or the cursor should accurately indicate what area is clickable.

**Please tell us about your environment:**
VS Code, Windows

* **AG Grid version:** 28

* **Browser:**
(Chrome Desktop) Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

* **Language:** Angular/Typescript

**Comment by StephenCooper** [comment] 2022-10-05 10:31
Thank you for the clear reproductions. I have raised in our internal ticketing system for further investigation.

**Comment by StephenCooper** [comment] 2022-10-05 14:49
Based on your description we've now reproduced this issue.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7205 When clicking the column header just above or below the column header text, column isn't sorted**

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7205) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-10-12 10:21 UTC
Labels: AG-7205
