### ISSUE TITLE
Range selection gets cleared with open context menu

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#6824] opened 2023-06-28 18:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

PLUNKER: https://plnkr.co/edit/mqBhIlUTkWD6wCKT?open=main.js

**Current behavior**
- when I select a range of cells and ctrl-click to open the context menu on that range of cells - the range selection overrides the context menu event and creates a new range which is the cell I clicked even if that cells is within the current range 

https://github.com/ag-grid/ag-grid/assets/6043499/3b8d8b0c-72d2-4eb9-9b3d-703181de2627

**Expected behavior**
- I would like to select a range and ctrl-click to open a context menu on that selected range. I think that even if you have `suppress multi range selection set to 'true'` that I would still be able to open the context menu on the current selection. 

**details**
AgGrid Vue
```
:enableRangeSelection="true"
:suppressMultiRangeSelection="true"
```

**Comment by destradafilm** [comment] 2023-06-28 19:00
if I can at least get the pointer event in the `RangeSelectionChangedEvent` then I can do a hacky solution. 

If the user has the 'ctrl' button pressed and the cell clicked is within the previous selected range then I can programmatically set the range to be the same as previous range

**Comment by zoheil-ag** [comment] 2023-08-07 11:56
Hi @destradafilm,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

However whilst going through it, I noticed I am unable to replicate the behaviour you've reported on your plunker. When I select a specific range and right-click (with or without CTRL) the context menu does not reduce to a single cell selection. Rather my previous cell range still remains selected.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by zoheil-ag** 2023-08-07 11:56 UTC
Labels: managed-by-community

**Comment by mappicaross** [comment] 2023-08-07 15:54
@zoheil-ag we are experiencing the same problem as @destradafilm describes. We also have `enableRangeSelection={true};suppressMultiRangeSelection={true}`. It appears it may be a mac-specific problem: when I'm on a mac and open the plunker shared above, select multiple cells, then cmd+click anywhere on them, the context menu opens but the selected range is removed. My colleague (working on a PC) reports that it functions as intended on his machine (the selected range stays selected on right click).

I'm running macOS 13.2.1. This happens in both Chrome (version 115.0.5790.170) and Safari (version 16.3).

Thanks for looking into this!

**Comment by zoheil-ag** [comment] 2023-08-07 16:15
Hi @mappicaross,

Thank you very much for the extra information. This does indeed seem to be a Mac-related problem and as a Windows user I was not able to recreate it.

We have now been able to reproduce it on a Mac and raised it as a bug in our backlog with reference: **AG-9052**.

Thanks again.

Kind regards,

**Comment by mappicaross** [comment] 2023-08-07 16:26
Thanks @zoheil-ag!

**Comment by destradafilm** [comment] 2023-08-07 16:58
thanks @mappicaross and @zoheil-ag !

**Comment by AG-Zoheil** [comment] 2023-08-30 08:15
Hi @destradafilm,

Correct, once an issue has been triaged and raised in our backlog the corresponding Github issue gets closed. Using the reference (**AG-9052** in this case) you will be able to track this change in our [pipeline](https://ag-grid.com/pipeline/) and/or [changelog](https://ag-grid.com/changelog/). We won't be updating this Github issue once **AG-9052** is released.

Kind regards,
Zoheil
