### ISSUE TITLE
Fuzzy search and searchDebounceDelay don't work

### ISSUE THREAD

**Issue by pezig** [ag-grid/ag-grid#4469] opened 2021-05-04 16:14 UTC
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproduction**

Angular - https://plnkr.co/edit/G1JC3yTOR5Jv1iNb
JS - https://plnkr.co/edit/SvEnLfuBigzyiHE0

Behavior is the same in both frameworks. 

1. Click on a cell in the Country column to open the dropdown, then

Issue 1: Type in "can". This will highlight Cambodia rather than Canada

Issue 2: Notice that the search is responding in 300ms rather than 5000ms as passed in to the parameter on line 271 of app.component.ts (Angular) or line 238 of main.js

Issue 3: Type in "ch" quickly. This will highlight the second country starting with ch

**Current behavior** 

1. Typing in "Can" highlights Cambodia not Canada 
2. Changing the searchDebounceDelay has no effect on the debounce
3. "Ch" will highlight the second country starting with "CH"

**Expected behavior**: 
1. "Can" should highlight Canada not Cambodia
2. Debounce should correspond to the parameter
3. "Ch" should highlight the first country in the list

**Please tell us about your environment:** Windows 10, VS Code, NPM

* **AG Grid version:** 22.1.2

* **Browser:** Chrome

* **Language:** Typescript 4.1.5

**Comment by makinggoodsoftware** [comment] 2021-05-11 15:58
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-05-17 12:04
Hello @pzigic!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5345 When typing inside a agRichSelectCellEditor to search the items the incorrect item is highlighted**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-06-04 15:53
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-06-04 15:53 UTC
Labels: ag-5345, in_zendesk
