### ISSUE TITLE
onFirstDataRenderer called before cell render data with React 18 new root API

### ISSUE THREAD

**Issue by Nicolai8** [ag-grid/ag-grid#5388] opened 2022-07-21 11:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
[stackblitz example](https://ag-grid-react-hello-world-fmbzkv.stackblitz.io)

**Current behavior**
no data rendered, can't resize coulmns
![image](https://user-images.githubusercontent.com/2829389/180203826-90f61f92-24bc-4a8c-aafd-c57367f87198.png)

**Expected behavior**
data shown can apply autoResize
![image](https://user-images.githubusercontent.com/2829389/180204062-5ad086ef-a94b-4f47-9a5a-0b69c08829de.png)

* **AG Grid version:** 28.0.2

* **Language:** React 18.2.0

**Comment by kiril-matev** [comment] 2022-07-21 17:14
Hello @Nicolai8!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7018 When using React 18 with new root API, firstDataRendered event is fired before all column headers are displayed and calling autoSizeAllColumns doesn't auto-size columns**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by seanlandsman** [comment] 2022-08-03 12:01
Hi,

Version 28.1.0 have AG-Grid has been released, which includes a fix for this issue.

Thank you for reporting this.

**Closed by seanlandsman** 2022-08-03 12:01 UTC
Labels: ag-7018
