### ISSUE TITLE
27.0.1 - cellClass with empty string breaks rendering

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#4919] opened 2022-02-14 16:54 UTC
**I'm submitting a ...**  (check one with "x")**

[x] bug report => see 'Providing a Reproducible Scenario'

**Current behavior**

Providing an empty cell string as cell style breaks rendering in 27.0.1. **This was working with 26.2.0. Now it only works with `null`**, so assume there was some truthy/falsy check converted to an explicit null check in the code somewhere...

![image](https://user-images.githubusercontent.com/8479925/153909638-7c19bcc3-2fbd-400c-a8e6-7952d25e887d.png)

![image](https://user-images.githubusercontent.com/8479925/153909366-3e3c07b6-faa3-4ea7-9b40-2f17038fc763.png)

See https://plnkr.co/edit/jWOP7kh0YELaMqDi

**Expected behavior**

Empty styles should not be applied, neither their values are empty strings or nulls.

**Please tell us about your environment:**
Angular 13

**AG Grid version:** 
27.0.1

**Browser:**
Google Chrome 98.0.4758.82

**Language:**
TypeScript

**Comment by himeyon** [comment] 2022-02-15 00:00
Looking at the change log, it looks like the response is complete, but it still occurs in my environment.
AG-6235

https://www.ag-grid.com/changelog/

**Comment by spyro2000** [comment] 2022-02-16 07:51
So...? :)

**Comment by shuheb** [comment] 2022-02-16 09:54
Hi!

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks!

**Comment by kiril-matev** [comment] 2022-02-16 10:45
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression. Until this is addressed, please return null values instead of empty strings in cellClass.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6393 [Regression] When returning an empty string in cellClass, an exception is thrown and no grid rows are displayed**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by spyro2000** [comment] 2022-02-16 14:42
Many thanks.

**Closed** 2022-02-16 15:21 UTC
Labels: in_zendesk, ag-6393
