### ISSUE TITLE
[27.0.0] Ag grid column sorting issue. RowGroup label is missing after sorting

### ISSUE THREAD

**Issue by ppatliakevych** [ag-grid/ag-grid#4911] opened 2022-02-09 12:23 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello everyone,

I have just upgraded my Ag Grid to 27.0.0 and I've noticed one strange behavior with sorting. I use  groupDisplayType: 'multipleColumns', with rowGroups columns and after I set a sorting to a value column, 1st group column label disappeared. I'll describe all details below. It worked before upgrade and I guess It is a bug. Thanks in advance!

**Providing a Reproducible Scenario**
plnkr: https://plnkr.co/edit/ZxhEFGY96T3bqeBO

Steps to reproduce:
1) You need to have several columns with rowGroup: true and groupDisplayType: 'multipleColumns' in the gridOptions. (see plnkr)
2) Expand all grouping columns.
3) Set 'ASC' sorting to the value column ("Athlete" column in the plnkr).

Current behaviour.
RowGroup label in the 1st group column moves down, there is no label in the first column.

Expected behaviour.
While setting sorting, for this case 1st group column label should not move.

**Please tell us about your environment:**

Windows 10, VS Code, Yarn

* **AG Grid version:** 27.0.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36'

* **Language:** [TypeScript 4.1.3]

**Comment by kiril-matev** [comment] 2022-02-09 15:49
Hello @ppatliakevych!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6349 When using React with row grouping and groupHideOpenParents=true, expanding all the row groups and sorting on a non-group column, the top row values don't include the group names anymore**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-17 10:49
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-17 10:49 UTC
Labels: ag-6349
