### ISSUE TITLE
The `autoHeight` not working with Column Spanning

### ISSUE THREAD

**Issue by donnguyen** [ag-grid/ag-grid#5687] opened 2022-10-16 09:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

We have 2 columns, both with `autoHeight=true`.

**Current behavior**
- Seems like the auto height is not working with a row that spanning on both columns. Like the following image:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/3904511/196028705-031ba16f-ea89-435b-9817-a8e212b398ad.png">

**Expected behavior**
- The autoHeight should be working as normal, even the row is spanning on multiple columns (all with `autoHeight=true)

**Please tell us about your environment:**

* **AG Grid version:** 28.2.0

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42

* **Language:** [all]

**Comment by jpike88** [comment] 2022-10-17 08:32
maybe related to #5688

**Comment by StephenCooper** [comment] 2022-10-19 09:39
This seems to be working in this example. Note how Row 1 changes the row height if you change the width of Column B.

https://plnkr.co/edit/QZT1InENPIB34vgp?open=main.ts

Can you provided / update this to show how it does not work?

**Comment by donnguyen** [comment] 2022-10-26 09:53
hi @StephenCooper,

Thanks for your response and sorry for the reply.

We just need to make the 3rd column in your example to `autoHeight` (that is what I meant by `We have 2 columns, both with autoHeight=true.`),  the issue will happen like following:
<img width="1381" alt="Screenshot 2022-10-26 at 16 50 40" src="https://user-images.githubusercontent.com/3904511/197995497-73b3c1a7-92d1-495b-9dfa-476abd181a9e.png">

Hope this helps

**Comment by kiril-matev** [comment] 2022-12-11 21:21
Hello @donnguyen,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7523 When a column with autoHeight & wrapText=true spans into another column with autoHeight & wrapText=true, the row has default instead of auto-height and the cell value appears on a single row instead of wrapped**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-12-12 09:41 UTC
Labels: in_review
