### ISSUE TITLE
[bug 24.1.0] autoHeight not working anymore (react)

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#4138] opened 2020-10-13 18:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I am not providing a reproducible scenario, because you are not taking your time to look at it 
(We can see it [here](https://github.com/ag-grid/ag-grid/issues/4105)) Thank you for that.

**Current behavior**
autoHeight is not working anymore with version 24.1.0. It was working with 24.0.0
![image](https://user-images.githubusercontent.com/25934591/95901410-940a7900-0d93-11eb-9f6c-a374dfcf64a9.png)

**Expected behavior**
The row should expand
![image](https://user-images.githubusercontent.com/25934591/95901018-03339d80-0d93-11eb-8a1d-343101668503.png)

**Please tell us about your environment:**
react 16.13.1, I am using **cellRendererFramework**

* **ag-Grid version:** 24.1.0

* **Browser:**
Chrome and firefox

* **Language:** [TypeScript 3.9.7|  ES5]

**Comment by Paul6552** [comment] 2020-10-14 09:09
@gportela85 
Closing the ticket without comment is not a solution.

**Comment by gportela85** [comment] 2020-10-14 10:02
@Paul6552 auto Row Height example with React: https://plnkr.co/edit/bFnSGngeGHcWkK2w
To be able to acknowledge bugs we need a scenario. I'm happy to reopen the issue if one is provided.

**Comment by Paul6552** [comment] 2020-10-14 14:01
@gportela85 

It is not the problem to create a scenario ([Here you have it](https://codesandbox.io/s/react-functional-component-forked-mes7d?file=/src/index.js)). The problem is when one is created but the time is still not taken to look at the example. (See ticket [4105).](https://github.com/ag-grid/ag-grid/issues/4105) Sadly this is not the first time.

The community should be valued more here. We are preparing bug reports for ag-grid free of charge and are also interested in improving ag-grid. Right now it feels like we are a necessary evil.

**Comment by makinggoodsoftware** [comment] 2020-10-19 10:25
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment] 2020-10-20 08:51
Hi There,

I am head of support on ag-grid, as mentioned in this ticket:

https://github.com/ag-grid/ag-grid/issues/4120

We are going to change our approach when giving support through gitHub, I'll include the relevant bits from that ticket above

> Thanks for all the feedback! We are taking this on board!
> 
> Before anything else, let me assure you guys that whatever your impression is of ag-grid as a company is nothing like what I can see you guys describing there, but this means to me that we are not doing a good job with comms on github MY BAD!
> 
> ag-grid is basically a company formed by a bunch of programmers, me including! And being part of the open-source community is something we take very seriously!
> 
> From today I will make sure that we do a better job replying to the github issues!
> 
> Instead of closing an incomplete issue, request more information and leave it open for others to join in and collaborate (eventually it might become complete enough to where you will work on it, or perhaps someone from the community will submit a PR).

Will do!

> 
> Make sure you at least respond with a single sentence to every PR that you close without merging, stating the reason why you didn't merge it. That's common courtesy.

Will do!

> 
> Stop closing PRs and fixing the issues yourselves. Why not just save yourself the work and give people some credit for actually taking the time to fix it? It literally takes you a minute to merge something.

Will raise this, the problem we have with the PRs is that our build is not easy to run, so that is why we do it manually

> 
> Stop spamming your own issues with useless comments saying that you don't provide support here. Just leave them be instead, people will understand.

Will do!

**Comment by makinggoodsoftware** [comment] 2020-10-21 08:36
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___

AG-4724 | [Regression] Row autoHeight doesn't work with cellRendererFramework and styled components
-- | --

**Comment by makinggoodsoftware** [comment] 2020-11-02 12:04
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Comment by mentierd** [comment] 2020-11-09 17:33
not working "anymore" LOL. this has been broken for a few version now. **Ag-Grid.** My company has been a paying customer for 2 years now and this issue has yet to be fixed. Your requests to put these bugs into your own system is BS; most developers do not have direct access to the username and password for these issues. If we are paying for your product, we also expect to be paying for these services.  Please stop closing out issues when they are clearing still issues AND make the effort to add these bugs to your pipeline yourself. If this practice of closing bugs with boilerplate text doesn't change; I'll be lobbying extremely hard in the next couple of months to move away from you.

**Comment by Paul6552** [comment] 2020-11-09 18:23
@mentierd 
There is a very good conversation behind this issue [CLICK ME](https://github.com/ag-grid/ag-grid/issues/4120). 
Ag-grid wants to improve in this regard.

**Comment by zorzysty** [comment] 2021-01-06 11:26
Any progress on the issue? We're evaluating different grids for our project and this is a must-have for us.
It seems to be working fine on `ag-grid-react@24.0.0` but fails on any newer - including `25.0.0`.

**Comment by Paul6552** [comment] 2021-01-06 11:42
@zorzysty You're confusing something. Version 25.0 is still not published. It should be fixed in the version 25 coming on 8th of january.
Look for the issue ticket "AG-4724" in the ag-grid pipeline. [Pipeline](https://www.ag-grid.com/ag-grid-pipeline/)

**Comment by zorzysty** [comment] 2021-01-06 14:13
I'm testing on codesandbox. 
Here it is working on v24.0.0:
https://codesandbox.io/s/react-functional-component-forked-tiubf?file=/src/index.js

and here's the same codebase, but on ag-grid 25.0.0 and it's not working: https://codesandbox.io/s/react-functional-component-forked-siort

**Comment by Paul6552** [comment] 2021-01-06 16:27
According to ag-grid pipeline it should be fixed, but as we can see it isnt working. So you can open a new issue ticket and reference to this one.

I'm tired of working with ag-grid. Therefore, if an alternative is also sought, react-table from tannerlinsley. Typescript support is not really available yet, but the table is already very good.

**Comment by kiril-matev** [comment] 2021-01-11 14:16
Hi Paul6552,

Thank you for getting in touch.

I can confirm that AG-4724 was entered as FIXED in v25 by mistake - this is an active issue that is yet to be addressed. 
I've now returned this issue to an active one, so you can see it in our pipeline. We are looking into this issue and we will try to fix it in an upcoming release.

We are committed to raising the standard in product quality and the level of service we provide. We're not happy with this oversight and I'd like to personally apologize for this error and for the impact it's having on your work. We want to work with you to resolve any remaining issues you're seeing.

Please let me know if you have any questions.

Thank you.

**Comment by makinggoodsoftware** [comment] 2021-01-21 17:12
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-01-21 17:12 UTC
Labels: AG-4724, community-engaged, in_zendesk
