### ISSUE TITLE
Filter remains applied on discard

### ISSUE THREAD

**Issue by ManuelBonjean** [ag-grid/ag-grid#1944] opened 2017-09-26 15:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

RowModel: Infinite
I'm about to apply a filter on a column: I click on the column header and fill in the value for a filter, but I exit the "window filter" without confirming the filter. Then, I reorder the column by clicking on the header title.
However, in the "filterModel" object the filter is present and is wrongly used to filter the data in the grid.

**Expected behavior**

When I exit the "windows filter", the filter, if is not applied, should be reset.

**Minimal reproduction of the problem with instructions**

1. Set FilterParams apply a true
2. Open filter and insert text without applying
3. Close "window filter"
4. Sort column

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

AngularJS

* **ag-Grid version:** 13.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by rmc-software** [comment] 2017-10-06 09:19
Hi,

We're closing this as we can't reproduce this. See plunker: http://plnkr.co/edit/X7WUcylRXPb8SVxNv2Uk?p=preview

If you can provide evidence of this issue we'll reopen it accordingly.

Thanks

**Comment by ManuelBonjean** [comment] 2017-10-09 09:42
Hi, for reproducing the issue you should set sort and filter in server side
Thanks

**Comment by seanlandsman** [comment] 2017-10-09 09:53
Hi

If you can provide something we can look at we'd be happy to investigate. Can you perhaps modify the plunker above to illustrate what you're seeing?

thnks

**Comment by ManuelBonjean** [comment] 2017-10-09 10:12
Hi,
here's the plunker:  https://plnkr.co/edit/apQOgnvSjQU3sYckmtL5

Thanks

**Comment by ManuelBonjean** [comment] 2017-12-13 14:37
?

**Comment by makinggoodsoftware** [comment] 2017-12-18 16:06
Hi,

I can confirm that this is a bug.

Is is tracked by AG-1336, you can see the progress of our items in the pipeline https://www.ag-grid.com/ag-grid-pipeline/

This should be fixed in the next 1/2 releases

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Closed by makinggoodsoftware** 2017-12-18 16:06 UTC
Labels: needs_repro
