### ISSUE TITLE
api.getRowNode() returns undefined. Wrong Typings : getRowNode(id: string): RowNode | null;

### ISSUE THREAD

**Issue by 5te1n** [ag-grid/ag-grid#4554] opened 2021-07-01 12:39 UTC
The api.getRowNode() method returns undefined instead null if the row is not existing. **Wrong Typings : getRowNode(id: string): RowNode | null;**

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Click anywhere on the grid. There is an "onClick" handler implimented in app.component.ts at the end of the file. The method tries to get a row node that does not exist. The getRowNode method does not return null, but undefined.

- A plunker: https://plnkr.co/edit/LRQJnh6Nd1biiV9G

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
api.getRowNode() returns undefined, if the row is not existing.

**Expected behavior**
api.getRowNode() returns null like mentioned in the typings-filev, if the row is not existing.

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:**
chrome

* **Language:** [all | TypeScript 4.2

**Comment by makinggoodsoftware** [comment] 2021-07-14 16:16
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by Kvek** [comment] 2021-07-26 17:08
Any update on this issue? I've got the same isse, I had to `toString()` my `id` yet it still doesn't work.

**Comment by kiril-matev** [comment] 2021-08-03 16:00
Hello @5te1n,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5583 [Typing] getRowNode gridApi method has incorrect return type null, and actual return type undefined which isn't documented**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:14
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-09 10:14 UTC
Labels: ag-5583
