### ISSUE TITLE
Ag-Charts: Series is filled with unexpected black background when setting series visible to false on initial create.

### ISSUE THREAD

**Issue by Ruud-cb** [ag-grid/ag-grid#7174] opened 2023-10-21 15:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

When setting a series on `visible : false`, the chart produces a very wierd black filled series. An image says more then words:
![image](https://github.com/ag-grid/ag-grid/assets/10037514/be141485-18ee-425a-b53b-3e50fbdd7765)

See Plunker, I simply added 1 line 'visible:false' on line 42. After running, put the petrol series back on.
https://plnkr.co/edit/LGwjYJsyu65CAhFw?open=main.js&preview

**Expected behavior**
Would not expect the series to be filled with black.

**Please tell us about your environment:**
Chrome, latest.

* **AG Grid version:** X.X.X

8.2.0, latest version on examples website has the same issue.

* **Browser:**

Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36'
* **Language:**  TypeScript 5.1.3 (or whatever version is used on your site).

**Comment by AG-DavidG** [comment] 2023-10-23 07:31
Hello,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-9626 - [Charts] Unexpected fill when initialising a line series with visible=false
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
 
David‍
Technical Product Analyst | AG Grid

**Closed by AG-DavidG** 2023-10-23 07:31 UTC
