### ISSUE TITLE
suppressKeyboardEvents cancels events 

### ISSUE THREAD

**Issue by ntnskrds** [ag-grid/ag-grid#3078] opened 2019-04-15 14:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Check the following example in the documentation.
 https://www.ag-grid.com/javascript-grid-keyboard-navigation/#example-suppress-keys

The example uses the suppressKeyboardEvent callback to suppress the grid's default behavior for a number of keys including the Home/End keys. Home/End normally focus the top-left/bottom-right keys but because they are suppressed they do not alter the focused cell. Now begin editing a cell by double-clicking in it and press 'Home' or 'End' when the editor appears in the cell. Normally, when an input box has the focus these keys move the caret within the input box to the start/end of the contained text. However this is not the case any more. I suspect  the internal keyboard handler is calling preventDefault on these keyboard events thus preventing the browser from doing the default behavior in input text boxes. 

I believe this is a bug and should not be the case (i.e. preventDefault should not be called). I am almost certain that this worked in previous versions of the grid i.e grid behavior was suppressed but the event was allowed to reach the editor without being cancelled (no stopPropagation or preventDefault was called on it).

**Comment by svanetten1976** [comment] 2019-04-15 14:57
@ntnskrds having this same exact issue as of ag-grid 20.2.0 and it is driving me nuts. Preventing use of the arrow keys inside custom text editors inside cells for me. I'm going to go ahead and agree with you that this was not happening pre ag-grid 20 and its a really bad bug

**Comment by svanetten1976** [comment] 2019-04-15 15:02
@ntnskrds https://github.com/ag-grid/ag-grid/issues/3078

**Comment by svanetten1976** [comment] 2019-04-15 15:44
@ntnskrds looking into this a little further, it appears the bug begins manifesting itself in the current version of ag-grid (20.2.0) and does not occur in 20.1.0. Reverting to this prior minor version fixed the issue for me, but hopefully this is addressed soon or its going to be a problem in future releases. This is absolutely definitely a bug

**Comment by NeKJ** [comment] 2019-04-16 02:39
@svanetten1976 I concur, this is definitely a regression that needs to be fixed as it breaks a wide range of deployed functionality that depends on the correct documented behaviour.

**Comment by ntnskrds** [comment] 2019-04-16 07:40
> 
> 
> @ntnskrds having this same exact issue as of ag-grid 20.2.0 and it is driving me nuts. Preventing use of the arrow keys inside custom text editors inside cells for me. I'm going to go ahead and agree with you that this was not happening pre ag-grid 20 and its a really bad bug

@svanetten1976 Our other alternative (using key event listeners on the renderer\editor components and calling stopPropagation as described [here](https://www.ag-grid.com/javascript-grid-cell-editor/#option-1-stop-propagation)) also does not work because of #3077. We are left between a rock and a hard place !

**Comment by svanetten1976** [comment] 2019-04-16 13:17
@ntnskrds Yeah, I just rolled back to 20.1.0 and all the features that we had in place are working again, namely left and right arrow keys in inputs inside custom text editors inside grid cells. Hopefully this issue gets addressed soon so we can update to the current version

**Comment by makinggoodsoftware** [comment] 2019-04-16 15:33
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment] 2019-04-16 15:34
Hi guys,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by svanetten1976** [comment] 2019-04-16 19:56
@makinggoodsoftware hey thanks for getting in touch about this issue. I've fixed the problem in our application for now by rolling back from ag-grid 20.2.0 to 20.1.0 so that is currently my solution to the issue for the moment. I'm just not going to update until I know this is fixed. I had described this issue in another ticket with a code example here https://github.com/ag-grid/ag-grid/issues/3077. It will take me some time to put together a Plunkr to illustrate the issue, as I've got my own workload to deal with, but its definitely a problem

**Comment by ntnskrds** [comment] 2019-04-17 07:29
@makinggoodsoftware thanks for engaging !
This is actually readily reproducible in one of your documentation examples.

1. Open [this](https://www.ag-grid.com/javascript-grid-keyboard-navigation/#example-suppress-keys)
2. Select the first cell by clicking in it.
3. Now press Home/End on your keyboard. Note how they do not change the focused cell because surpressKeyboardEvent returns true for these keys. This is correct, expected behavior
4. Now double-click on the first cell to start editing.
5. After editing begins and with the caret in the cell press Home/End. Note that the caret doesn't move in the cell. This is wrong . Expected behavior would be the caret to move to the start/end of the contained text as is normal with any textbox in a browser. Previous versions of the grid exhibited the expected behavior

If I were to take a guess I would say that this is because the grid's internal keyboard event handler 
1. is capturing events and...
2. ... it calls preventDefault() on the keyboard event at some point. 

Thus, when the event finally reaches its target textbox it is already cancelled and the browser does not proceed with the default behavior (which would be to move the caret) . But, that's just my guess ...

Again, thank you very much for following up on this issue... I hope it is resolved soon ..

**Comment by MehdiSaeedifar** [comment] 2019-04-18 04:15
We also have the same issue since 20.2.0.

**Comment by gportela85** [comment] 2019-04-18 14:41
Fixed in the latest branch, thanks for reporting the issue.

**Closed by gportela85** 2019-04-18 14:41 UTC
Labels: ag-grid engaged
