### ISSUE TITLE
Angular AG-GRID without zone

### ISSUE THREAD

**Issue by Jordan-Hall** [ag-grid/ag-grid#4392] opened 2021-03-12 22:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
I'm happy to create a PR myself to handle this but is this something you would accept or would it be better to manage it outside of AG-Grid?

**Providing a Reproducible Scenario**
- create an angular application without zone turned on.
- use custom components inside ag-grid

**Current behavior**
Uncaught ReferenceError: Zone is not defined

**Expected behavior**
Expect it to either run without zone or handle the error so we can trigger change detection manually

* **AG Grid version:** 25.1.0

* **Browser:**
All

* **Language:** Typescript

**Comment by makinggoodsoftware** [comment] 2021-03-22 16:54
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment] 2021-03-31 16:16
Hi,

Thank you for creating this ticket.

I'm struggling to reproduce this scenario.

I created an ag-grid-angular project with zone.js turned off and created a custom cell renderer component, but I don't see any errors thrown.

Here is the example: 

https://stackblitz.com/edit/ag-grid-angular-hello-world-v5fbrt?file=src%2Fapp%2Fapp.component.ts

Do you mind forking the example and include a scenario where this breaks as you describe?

Many thanks,

**Comment by Jordan-Hall** [comment] 2021-03-31 19:02
Hey @davis4acca  the issue can be found here https://stackblitz.com/edit/ag-grid-angular-hello-world-3aca88?file=src%2Fapp%2Fapp.component.ts

Its when you dispatch an event. The error is related to this section of the codebase https://github.com/ag-grid/ag-grid/blob/master/grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/angularFrameworkOverrides.ts


I'm thinking of something like this that could resolve the issue (Ivy only)

```typescript
import { Injectable, NgZone, ɵglobal, ɵdetectChanges as detectChanges } from "@angular/core";
import {VanillaFrameworkOverrides} from "ag-grid-community";

@Injectable()
export class AngularFrameworkOverrides extends VanillaFrameworkOverrides {
    private isEmitterUsed: (eventType: string) => boolean;

    constructor(private _ngZone: NgZone) {
        super();
    }

    setEmitterUsedCallback(isEmitterUsed: (eventType: string) => boolean) {
        this.isEmitterUsed = isEmitterUsed;

    }

	public setTimeout(action: any, timeout?: any): void {
			if (this._ngZone) {
				this._ngZone.runOutsideAngular(() => {
					window.setTimeout(() => {
						action();
					}, timeout);
				});
			}
        
    }

    addEventListener(element: HTMLElement, eventType: string, listener: EventListener | EventListenerObject, useCapture?: boolean): void {
			if (this.isOutsideAngular(eventType)) {
					if (this._ngZone) {
						this._ngZone.runOutsideAngular(() => {
							element.addEventListener(eventType, listener, useCapture);
						});
					} else if (this.isViewEngineIvy()) {
						detectChanges(this)
					}
            
        } else {
            element.addEventListener(eventType, listener, useCapture);
        }
    }

    dispatchEvent(eventType: string, listener: () => {}): void {
        if (this.isOutsideAngular(eventType)) {
            this._ngZone.runOutsideAngular(listener);
        } else if(this.isEmitterUsed(eventType)) {
            // only trigger off events (and potentially change detection) if actually used
            if(!NgZone.isInAngularZone()) {
                this._ngZone.run(listener);
            } else {
                listener();
            }
        }
		}
	
	private isViewEngineIvy(): boolean {
		// credit to RX-angular  https://github.com/rx-angular/rx-angular/blob/47b6dbb66deac7b44cb7aa0f348bc45cd64541fb/libs/template/src/lib/experimental/core/utils/view-engine-checks.experimental.ts
		const ng: any = ɵglobal.ng;

		// Is the global ng object is unavailable?
		// ng === undefined in Ivy production mode
		// View Engine has the ng object both in development mode and production mode.
		return (
			ng === undefined ||
			// in case we are in dev mode in ivy
			// `probe` property is available on ng object we use View Engine.
			ng.probe === undefined
		);
	}
}
```

**Comment by Jordan-Hall** [comment] 2021-03-31 19:38
I change the approach for the PR, feel free to close it or change anything.

**Comment by makinggoodsoftware** [comment] 2021-04-07 15:32
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by Jordan-Hall** [comment] 2021-04-07 15:34
> his means that this is a candidate to be in a future release.
> 
> At this moment we do

Thats not what you have said before. Apparently, it was in Zendesk already so an enterprise person raised it. ALso PR done if u do want it

**Comment by kiril-matev** [comment] 2021-04-08 08:09
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v24.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5237 [Regression][Angular] When disabling ngZone, clicking a row in AG Grid throws an exception in console**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-04-15 15:30
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-04-15 15:30 UTC
Labels: AG-5237, ag-grid engaged, good_suggestion
