### ISSUE TITLE
[X] BUG REPORT:  'TypeError' When Editing a Date Field using cellEditorSellector

### ISSUE THREAD

**Issue by KorucuTech** [ag-grid/ag-grid#8000] opened 2024-05-21 22:36 UTC
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Following code does not work and produces an error.
I tried this with agDateCellEditor, agDateStringCellEditor
I tried it with and without the "params" for the component in the EditorSellector
parser & formatter is not even called.
I tried with and without the parser and formatter.

```
function cellEditorSelector(params) {
            if (params.data.name === "requested_date") {
                return {
                    component: "agDateStringCellEditor",
                    popup: true,
                    popupPosition: 'under',
                    params: {
                        valueFormatter: dateValueFormatter,
                        valueParser: dateValueParser
                    }
                }
            }
            return undefined;
}


function dateValueParser(params) {
    console.log("dateValueParser",params);
}

function dateValueFormatter(params) {
    console.log("dateValueFormatter:",params)
}

```

<img width="541" alt="image" src="https://github.com/ag-grid/ag-grid/assets/6124584/1eb6e52c-3607-4b1f-bcae-c31985370e84">

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Editing a date field is not possible

**Expected behavior**
Should be able to update the value of a cell that is type date.

**Please tell us about your environment:**
Mac OS 14.1.2  VSCode, Pure Java Script

* **AG Grid version:** X.X.X
31.3.2

* **Browser:**
Crome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Java Script

**Comment by AG-Zoheil** [comment] 2024-06-26 15:41
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-06-26 15:41 UTC
Labels: waiting-for-repro

**Comment by FrenchMajesty** [comment] 2024-10-04 10:38
I am experiencing the same issue. @AG-Zoheil I made a reproducible example. See here:
https://codesandbox.io/p/sandbox/overriding-pre-defined-cell-data-types-forked-kgh9z7

**Comment by AG-Zoheil** [comment] 2024-10-22 11:39
Hi,

Please note we do not provide support via GitHub. You can see `agDateStringCellEditor` working in our example here: https://www.ag-grid.com/javascript-data-grid/provided-cell-editors/#example---cell-data-types-cell-editors.

Kind regards,
Zoheil

**Comment by amks1** [comment] 2025-01-14 14:52
@KorucuTech / @FrenchMajesty were you able to resolve this issue? I've got the same problem.

**Comment by FrenchMajesty** [comment] 2025-01-14 20:39
I used a workaround but it’s been a while since I was involved in that
freelance project so I don’t remember what is was.
