### ISSUE TITLE
Angular Ivy distribution (ag-grid-angular)

### ISSUE THREAD

**Issue by stefnedelchev** [ag-grid/ag-grid#4820] opened 2021-12-07 14:20 UTC
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

It seems that currently the Angular package of ag-grid doesn't use Ivy. After migrating to Angular 13, you can see this message while building:

```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @ag-grid-community/angular [es2015/esm2015] (git+https://github.com/ag-grid/ag-grid.git)
Encourage the library authors to publish an Ivy distribution.
```

It's related to the fact that Angular are deprecating their View Engine in favour of Ivy which means in Angular v14 and later this library won't compile.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Generate a new Angular project with v13 of the CLI.
- Install the core ag-grid package and the Angular one, and initialize the `AgGridModule` in your `app.module.ts` file.
- Build the application with `ng build`.

**Please tell us about your environment:**
Windows, NPM v6.14.15, Angular CLI v13.0.4

* **AG Grid version:** 26.2.0

* **Browser:** Browser doesn't matter

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment] 2021-12-22 15:02
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by makinggoodsoftware** [comment] 2022-01-11 16:19
Hi,

We can confirm that this has been selected to be added to our next release!

Keep an eye on our pipeline for more information

https://www.ag-grid.com/pipeline/

Thanks for your suggestion!

**Comment by stefnedelchev** [comment] 2022-01-12 08:59
@makinggoodsoftware  great to hear that, thanks for the support!

**Comment by rubenb994** [comment] 2022-01-18 11:58
I've been looking through the pipeline list which you recommended @makinggoodsoftware. I was not able to find any item within the list referencing this GitHub issue. Could you please point out for which AG issue tag I should look on the pipeline page?

**Comment by stefnedelchev** [comment] 2022-01-18 12:08
> I've been looking through the pipeline list which you recommended @makinggoodsoftware. I was not able to find any item within the list referencing this GitHub issue. Could you please point out for which AG issue tag I should look on the pipeline page?

I believe he meant us to look at the pipeline and the task should eventually appear soon, not that it's already there

**Comment by StephenCooper** [comment] 2022-01-18 12:20
To provide some additional details to this ticket as to why it has not appeared in the public pipeline yet despite us considering it internally already. 

At this point in time AG Grid supports Angular applications from v8 onwards and we will continue to support older Angular versions. As dictated by Angular, applications should only consume libraries that were built with a lower or matching library version.

As the Ivy distribution is only support from v12 we would have to create a package that was built off v12 which would then not be compatible for users <12. This is not a viable option for us as we need to support older Angular applications too.

Our current thinking on this is that we will have to produce two packages, one for v8-11 and one for +v12. So there are a few more things for us to consider before we will enable you to not have the warning. We are aware that our deadline for this is v14 as that will no longer support View Engine.

**Comment by stefnedelchev** [comment] 2022-01-20 06:38
> To provide some additional details to this ticket as to why it has not appeared in the public pipeline yet despite us considering it internally already.
> 
> At this point in time AG Grid supports Angular applications from v8 onwards and we will continue to support older Angular versions. As dictated by Angular, applications should only consume libraries that were built with a lower or matching library version.
> 
> As the Ivy distribution is only supported from v12 we would have to create a package that was built off v12 which would then not be compatible for users <v12. This is not a viable option for us as we need to support older Angular applications too.
> 
> Our current thinking on this is that we will have to produce two packages, one for v8-11 and one for +v12. So there are a few more things for us to consider before we will enable you to not have the warning. We are aware that our deadline for this is v14 as that will no longer support View Engine.

This doesn't seem entirely correct, why would Ivy distribution be supported by v12 and above? Every Angular version above v9 uses Ivy by default, we've been building apps using Ivy for 2 years. Angular 9 also supports Ivy (that's when it was introduced) but it's optional there and not default. The only difference in Angular 14 is that they will entirely drop the backwards compatibility and libraries that only use the ViewEngine won't compile.

**Comment by StephenCooper** [comment] 2022-01-20 09:04
You are correct that Angular applications have been on ivy from v9 but this hasn't been the case for libraries. It is only from v12 that the Angular team recommends libraries be published to npm using the Ivy distribution format and only applications from v12 onwards that will be able to consume this.

More details can be found here https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4

**Comment by Zeroile** [comment] 2022-02-02 17:18
By any chance, is the support of ag-grid in angular 13 is rolled out?

**Comment by StephenCooper** [comment] 2022-02-02 17:26
@Zeroile AG Grid supports Angular 13 but you will just see the warning above when building. You should be fine to ignore this for now. 

Please see my comment above for how this will be resolved in a future release.

**Comment by Zeroile** [comment] 2022-02-02 17:32
Thank you for replying,  Stephen. I am getting the error stating "ag-grid-angular" is not a known element. Also in app-module, i am unable to import the module "withcomponents(componentname)". Did an npm install and could see the package details in package.json as well. Any hunch??

**Comment by Zeroile** [comment] 2022-02-02 17:37
Thank you Stephen. I am new bie and just got stuck when I saw the error "ag-grid-angular" as unknown element. Thanks again.

**Comment by salmoro** [comment] 2022-04-07 10:44
BTW this is not just about the Angular build errors. This is also a blocker for anyone trying to migrate to Yarn PnP. For now we forked this repository to support PnP via compiling with Angular 13.

**Comment by StephenCooper** [comment] 2022-04-07 12:42
@salmoro Thank you for this additional context. Could you point me at your fork as I would be interested to see what changes you made to get it working for you.

**Comment by salmoro** [comment] 2022-04-07 17:16
@StephenCooper Sure. I just incrementally upgraded Angular until I got to 13:
```
ng update @angular/core@10 @angular/cli@10 && ng update @angular/core@11 @angular/cli@11 --allow-dirty && ng update @angular/core@12 @angular/cli@12 --allow-dirty && ng update @angular/core@13 @angular/cli@13 --allow-dirty
```
Then built the module: (`ng build --configuration production`).

See the last 2 commits on this branch:
https://github.com/bdb-opensource/ag-grid/commits/b27.1.0

**Comment by thekip** [comment] 2022-04-14 08:28
@salmoro have you pushed it somewhere? We also blocked to switching to pnpm or yarn by this, and this only one lib which is left for ngcc.

**Comment by DiogoVCS** [comment] 2022-05-25 11:40
@StephenCooper just saw [this PR](https://github.com/ag-grid/ag-grid/pull/5214) created 2 days ago (amazing work btw), have you any ideia of the timeline plan for this to be released, can we expect any news soon? We are using a monorepo with multiple applications using pnpm and this is the only package giving problems, and it is really a blocker for the usage of this library. Thanks for the good work! :+1:

**Comment by StephenCooper** [comment] 2022-05-30 13:40
@DiogoVCS @salmoro Could either you point me at the error you get when using yarn / pnpm so that I can check that I am able to reproduce the issue and then validate our new package fixes it?

**Comment by marklagendijk** [comment] 2022-07-01 09:56
It seems that the `27.3.0-beta.0` release has only be done for the community modules, not the enterprise ones:
``` json
    "@ag-grid-community/angular": "27.3.0-beta.0",
    "@ag-grid-community/client-side-row-model": "27.3.0-beta.0",
    "@ag-grid-community/core": "27.3.0-beta.0",
    "@ag-grid-enterprise/charts": "27.3.0",
    "@ag-grid-enterprise/clipboard": "27.3.0",
    "@ag-grid-enterprise/core": "27.3.0",
    "@ag-grid-enterprise/excel-export": "27.3.0",
    "@ag-grid-enterprise/menu": "27.3.0",
    "@ag-grid-enterprise/server-side-row-model": "27.3.0",
```
That is probably the reason it breaks on:
```ts
ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  GridChartsModule,
  ClipboardModule,
  EnterpriseCoreModule,
  ExcelExportModule,
  MenuModule,
  ServerSideRowModelModule,
]);
```

**Comment by StephenCooper** [comment] 2022-07-01 10:02
@marklagendijk yes sorry we did not perform the beta release across all enterprise modules.

v28 is targeted for end of next week dependant on how our regression testing progresses.

**Comment by marklagendijk** [comment] 2022-07-01 11:12
Would it be possible to release the beta for those enterprise modules in the mean time, or is that tricky?

**Comment by StephenCooper** [comment] 2022-07-01 11:20
I am afraid we won't be doing a full beta release across all modules. These were just selected as an initial POC and not intended to be a full release.

**Comment by StephenCooper** [comment] 2022-07-06 09:56
v28 has now been released with Ivy distribution format enabled. Please try out version 28.0.0 and let us know if you have any issues.

For more details check the [Angular Compatibility](https://ag-grid.com/angular-data-grid/angular-compatibility/) doc page.

**Closed by StephenCooper** 2022-07-06 09:56 UTC
Labels: good_suggestion
