### ISSUE TITLE
AgGrid doesn't grow cell if has a minWidth

### ISSUE THREAD

**Issue by JoniJnm** [ag-grid/ag-grid#6782] opened 2023-06-19 16:45 UTC
**I'm submitting a ...** 
```
[x] bug report
[] feature request
[] support request
```

I have a table with few columns. Only one of them (comment) can grows. I attach two captures:

![image](https://github.com/ag-grid/ag-grid/assets/577282/e6ca5276-a538-439f-9007-fe7bd2d8ec53)

![image](https://github.com/ag-grid/ag-grid/assets/577282/5f73a499-65bf-4737-9cde-4af9bd865b20)

I want to set a minWidth for the comment column, but when I do it agGrid sets the width as the minWidth and the cells doesn't grow:

![image](https://github.com/ag-grid/ag-grid/assets/577282/8214384e-cbec-4e1b-adce-82b169266211)

**Reproducible project**

https://plnkr.co/edit/sPwphlCybsd7CIGg

Just uncomment the line `// minWidth: 300,`

**Current behavior**
When I set a minWidth the cell always use this as the width. The cell doesn't grow.

**Expected behavior**
AgGrid should grows the cell as if I don't set a minWidth, but the width should has at least the defined minWidth.

**AG Grid version:** 30.0.2

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Language:** all

**Comment by kiril-matev** [comment] 2023-06-22 09:28
Hello @JoniJnm ,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8817 When calling api.sizeColumnsToFit() it doesn't grow column width if it has a minWidth set and the grid's width is less than 1400px**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Closed by kiril-matev** 2023-06-22 09:28 UTC
Labels: in_zendesk
