### ISSUE TITLE
[bug] "columnMoved" wrong event source

### ISSUE THREAD

**Issue by Ka100loM** [ag-grid/ag-grid#5940] opened 2023-01-03 09:12 UTC
**I'm submitting a BUG**

**Reproducible Scenario**
- Move column using the Columns Tool Panel UI
[Code Sand Box](https://codesandbox.io/s/ag-grid-column-moved-event-source-bug-cgfcnq?file=/src/App.tsx)

**Current behavior**
Moving columns from Tool Panel event source = "api"

**Expected behavior**
Moving columns from Tool Panel event source = "toolPanelUi"

**Please tell us about your environment:**
Win10, Vs Code, yarn, Web Pack

* **AG Grid version:** 28.2.1

* **Browser:**
Chrome Version 108.0.5359.125

* **Language:** [all]

**Comment by StephenCooper** [comment] 2023-01-03 10:49
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7732

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7732) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by StephenCooper** [comment] 2023-01-03 11:01
This has been corrected and will be released in the upcoming release. Thanks for reporting!

**Closed by StephenCooper** 2023-01-03 11:01 UTC
Labels: AG-7732
