### ISSUE TITLE
column filter - overlapping text in filter menu

### ISSUE THREAD

**Issue by srikanthmooli** [ag-grid/ag-grid#1989] opened 2017-10-17 19:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I filter on a column with a long text, the filter data is displayed incorrectly(overlapping text) as shown in the screenshot in the filter column menu.

**Expected behavior**
No overlapping of text in the filter menu

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE -
1.) Grid has a column with long text (Screenshot - EventName column is being filtered upon).
2.) Filter on the above column, the column data displays overlapped.

**What is the motivation / use case for changing the behavior?**
The overlapping text is not readable and not looking good.

**Please tell us about your environment:**
Windows 7/10, Chrome, Visual Studio Code, NPM

* **ag-Grid version:** X.X.X
13.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.5.3
![filter_data_overlapping text](https://user-images.githubusercontent.com/32304087/31685354-419c331e-b348-11e7-9499-0f4a02025d1b.png)

**Comment by petyosi** [comment] 2017-10-23 06:08
Hi, the issue should be fixed in the next release, due in a week or two. If the problem persists after that, please provide a reproduction of it. Thank you.

**Closed by petyosi** 2017-10-23 06:08 UTC

**Comment by gspeedtech** [comment] 2019-02-14 00:47
Is there a fix for this?
I am having the same issue where the Quick Search Filter box is overlapping the Select All checkbox

**Comment by RayaMukhopadhyay** [comment] 2024-01-15 09:09
Is there a solution to this issue?

**Comment by AG-Zoheil** [comment] 2024-01-15 10:04
Hi

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from **four years ago**.

The grid has naturally advanced a lot since then. If you are still having problems in the latest version, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
