### ISSUE TITLE
Position of the filter dialog moves to starting of the grid while we touch filter button and navigation to other page in navbar at a time

### ISSUE THREAD

**Issue by KirthirajS** [ag-grid/ag-grid#6927] opened 2023-08-03 08:48 UTC
The Position of the filter in the ag grid will appear to start of the grid when we perform the touch on filter icon and touch on navigation to other page at a time in the application.

device:- Tablet device

![image](https://github.com/ag-grid/ag-grid/assets/117440800/c8da5d88-e7be-4d42-8a6e-13961caba37a)

**Comment by zoheil-ag** [comment] 2023-08-03 11:13
Hi @KirthirajS,

Thanks for raising this.

Are you able to link us to a reproducible scenario from our documentation where we can observe this behaviour?

Thank you,
Zoheil

**Comment by KirthirajS** [comment] 2023-08-08 09:51
HI @zoheil-ag 
you can reproduce this with ag grid examples only by following our example what we have explained.

**Comment by zoheil-ag** [comment] 2023-08-08 10:24
Hi @KirthirajS,

I attempted this with the [floating filter](https://ag-grid.com/javascript-data-grid/floating-filters/) example and I was unable to reproduce what you are experiencing. Is there a specific example you'd like us to look at?

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment] 2023-09-11 15:28
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-09-11 15:28 UTC
Labels: waiting-for-repro
