### ISSUE TITLE
Calling the API early crashes if reactUi={true}

### ISSUE THREAD

**Issue by alippai** [ag-grid/ag-grid#4649] opened 2021-08-31 21:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Using the API via hooks is sometimes broken if `reactUi={true}` is set.
https://plnkr.co/edit/y2FMy62MmqHphTRH this works, but if you add `reactUi={true}` then it breaks.
What I'm trying to do is adding a loading state before data is added. 
Similar happens with `get/setColumnDefs()` in a hook if `reactUi={true}`.

All the above is working without `reactUi={true}`.

* **AG Grid version:**
26.0.0

* **Browser:**
Chrome

* **Language:**
all

**Comment by makinggoodsoftware** [comment] 2021-09-01 07:32
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2021-09-02 06:44
Hi @alippai 

Thanks for the context and information.

This is not a bug as there are parts of the grid that are not yet ported to reactUI. This is why specific elements/functionality such as overlays are not supported at this time with ReactUI, as documented here: https://www.ag-grid.com/react-data-grid/reactui/#how-much-of-ag-grid-is-now-react-ui 

Hope that helps, note that I will be closing this issue as it is not a bug.

Kind Regards,
Shuheb

**Closed by shuheb** 2021-09-02 06:44 UTC
Labels: in_zendesk
