### ISSUE TITLE
Fixed a column on the right, dragging the column width will result in a blank space in the middle?

### ISSUE THREAD

**Issue by andyFang94** [ag-grid/ag-grid#7334] opened 2023-12-08 15:43 UTC
![image](https://github.com/ag-grid/ag-grid/assets/54627989/2f68e065-9056-4b86-8d8b-d704ac44540e)

**Providing a Reproducible Scenario**
https://codesandbox.io/p/sandbox/ag-grid-packages-forked-qkkyrl?file=%2Fsrc%2Findex.js%3A44%2C48

**Current behavior**
Fixed a column on the right, dragging the column width will result in a blank space in the middle. How to solve this issue?

**Expected behavior**
Don't have blank space.
**Please tell us about your environment:**
chrome

* **AG Grid version:** X.X.X
31.0.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment] 2023-12-13 11:56
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10107**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-12-13 11:56 UTC
Labels: AG-10107

**Comment by GizzmoSan** [comment] 2025-02-19 10:29
Hello all, can you please explain me why this Task AG-10107 is rejected?

**Comment by AG-Zoheil** [comment] 2025-02-19 13:30
Hi @GizzmoSan,

This is not a bug but the current expected behaviour. I've unlinked the original bug reference that was rejected and linked it to the feature request reference in our backlog: **AG-3670**.

Thank you!

**Comment by GizzmoSan** [comment] 2025-02-19 13:55
Hi @AG-Zoheil,
thank you for this information i thought that is a expected behaviour but i wanted to make sure.
I will take a look at the backlog item.

Thank you :-)
