### ISSUE TITLE
SizeColumnsToFit doesn't take borders in calculation

### ISSUE THREAD

**Issue by jmalStorm** [ag-grid/ag-grid#4230] opened 2020-12-04 06:57 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/nh9Tq9Z3UZWr1xkV
![image](https://user-images.githubusercontent.com/50706363/101131933-ca83a800-360e-11eb-98c5-89b02c2a76a8.png)
**Important detail it happens on my monitor with scale set to:**
![image](https://user-images.githubusercontent.com/50706363/101149534-c0ba6e80-3627-11eb-9e2e-d609fdb2c84e.png)

**Current behavior**
I keep having a horizontal scrollbar on the grid after calling sizeColumnToFit. I suspect that it is caused by border style applied on grid. When I remove these borders (`border: 0 !important;`), the scrolls disappears so I suppose the width calculation doesn't take into account the borders... Also it does not happen always, it seems to depend on grid width. I have freeze example with `width: 839.2px` so bug is reproduced always.

**Expected behavior**
Not to have a scrollbar when using sizeColumnsToFit

**Please tell us about your environment:**
Windows 10, VSCode, NPM 6.12.1, Node v10.15.3

* **ag-Grid version:**
24.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

* **Language:**
TypeScript 3.9

**Comment by makinggoodsoftware** [comment] 2020-12-10 15:34
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___

AG-2550 | [Cell Rendering] Support Zoom in/out of the browser
-- | --

**Comment by nzacca** [comment] 2020-12-16 22:01
This is a duplicate of: https://github.com/ag-grid/ag-grid/issues/4113

**Comment by makinggoodsoftware** [comment] 2021-01-04 17:03
Hi,

Ill close as a duplicate then!

:)

**Closed by makinggoodsoftware** 2021-01-04 17:03 UTC
Labels: AG-2550, community-engaged
