### ISSUE TITLE
e2e and integration tests get stuck when filter or cell editor popups are opened (window.setInterval)

### ISSUE THREAD

**Issue by raukouski** [ag-grid/ag-grid#4480] opened 2021-05-14 13:04 UTC
Since ag-grid version 25, there is an issue that e2e and integration tests get stuck when the filter or cell editor popups are opened.
There was no such issue in version 24.

After deep dive into that issue, I found that in the version 25 there were some changes that `popupService.addPopup` started to get `anchorToElement` parameter and then `keepPopupPositionedRelativeTo` started to run `window.setInterval(..., 200)` to keep the popup positioned.
After we updated ag-grid to version 25 our integration and e2e tests started to get stuck. I believe it's because `setInterval` is running not outside Angular.
I would propose adding 
```
setInterval(action, timeout) {
        if (this._ngZone) {
            this._ngZone.runOutsideAngular(() => {
                window.setInterval(() => {
                    action();
                }, timeout);
            });
        }
        else {
            window.setInterval(() => {
                action();
            }, timeout);
        }
    }
```
method to `AngularFrameworkOverrides` class and use that method like `this.frameworkOverrides.setInterval(...)` instead of `window.setInterval()...` not to make the fixture unstable. It would be also great to check for other places we need to run `setTimeout` or `setInterval` outside Angular.

Thanks!

**Comment by raukouski** [comment] 2021-05-25 08:50
Hello @makinggoodsoftware 
You marked the issue as 'waiting-for-repro'.
But it can be difficult to create a good example with unit and e2e tests that fail.
The main point here is that setInterval is run inside Angular in some places (f.e. keepPopupPositionedRelativeTo function).
And that can cause some known issues so I asked your team to take a look into that and I provided a possible solution above.
Let me know please if you have any questions.

**Comment by makinggoodsoftware** [comment] 2021-06-04 15:57
Hi,

I am afraid that without a reproducible scenario we won't be able to have a look at this, I hope you understand our position.

I will keep this open thought see if there is any chance you can come up with something that shows the error, this could be for instance a github project

Hope this makes sense

**Comment by raukouski** [comment] 2021-06-15 09:18
Hi @makinggoodsoftware, I've created a reproducible application: https://plnkr.co/edit/fTrz69g7G9nkmszR
I've added ngDoCheck Angular method to see how often it runs when the filter popup is closed or opened.
You can open the browser console and see the console logs when the filter popup is opened.
Let me know if you have any questions.

**Comment by makinggoodsoftware** [comment] 2021-06-18 16:07
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-06-23 17:18
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5470 [Regression][Angular] When opening the column menu or context menu, ngDoCheck is called repeatedly**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-07-01 16:02
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-07-01 16:02 UTC
Labels: ag-5470, in_zendesk
