### ISSUE TITLE
Grid updating on new row added, only first time

### ISSUE THREAD

**Issue by playinglife** [ag-grid/ag-grid#5125] opened 2022-04-28 13:08 UTC
[x] bug report

**Providing a Reproducible Scenario**

**Current behavior**
I load the data into the grid. 
I have a clickEvent which adds a new row.
On first click the new row is added into the data and also reflected in the grid.
On second click the new row is added into the data but not reflected in the grid.
The grid is updated correctly if I run this in the code: params.api.setRowData(data.rowData)

[https://plnkr.co/edit/CgwUHC0GWUHNSXM8?open=lib%2Fscript.js](url)

**Expected behavior**
The new row should always be reflected in the grid.

**Please tell us about your environment:**
Windows11
HTTP local server
NPM 8.5.0

I am using the following packages
├── @babel/core@7.17.9
├── @babel/eslint-parser@7.17.0
├── @mdi/font@6.6.96
├── @vue/cli-plugin-babel@5.0.4
├── @vue/cli-plugin-eslint@5.0.4
├── @vue/cli-service@5.0.4
├── @vuepic/vue-datepicker@3.1.1
├── ag-grid-community@27.2.1
├── ag-grid-vue3@27.1.0
├── axios@0.26.1
├── core-js@3.22.0
├── eslint-plugin-vue@8.6.0
├── eslint@7.32.0
├── material-design-icons-iconfont@6.6.0
├── pinia@2.0.13
├── roboto-fontface@0.10.0
├── sass-loader@10.2.1
├── sass@1.51.0
├── vue-axios@3.4.1
├── vue-cli-plugin-vuetify@2.4.8
├── vue@3.2.33
├── vuetify-loader@2.0.0-alpha.9
├── vuetify@npm:@vuetify/nightly@3.0.0-next-20220416.0
└── webfontloader@1.6.28 

**AG Grid version:** 
27.2.1

**Browser:**
Firefox 99.0.1

**Language:**
Vue3

**Comment by kiril-matev** [comment] 2022-05-06 10:07
Hello @playinglife!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6753 When using Vue3 and adding new rows to rowData as reactive, only the first new row is added**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by alaarihan-temco** [comment] 2022-05-18 17:25
I have not find this AG-6753 in the pipleline page nor in the changelog page!

**Comment by kiril-matev** [comment] 2022-05-19 10:13
Hi @alaarihan-temco,

Thanks for reporting this.

You're correct - this item is not currently displayed in our pipeline. We will correct the filtering logic to ensure it does.

I'd like to assure you this is an active item for us and as it's a bug we will try to fix it as part of our next release.

**The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

**Comment by makinggoodsoftware** [comment] 2022-05-26 11:23
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-05-26 11:23 UTC
Labels: in_zendesk, ag-6753
