### ISSUE TITLE
Rendering order bug when combined with pagination

### ISSUE THREAD

**Issue by RazAbk** [ag-grid/ag-grid#6293] opened 2023-03-12 12:31 UTC
**Bug report - Rendering order bug when combined with pagination** 

**Reproducible Scenario**
Rows rendering order is reversed when combined with client-pagination.

- Set a new grid with pagination, set slow rendering cell renderers to better emphasise this bug.
- Scroll around the first page a bit, to trigger a bottom to top rendering order.
- Go to another page:
  - From this moment, every time switching to a different page, the render order remains bottom to top, although it is expected to be top to bottom.

Plunker:
https://plnkr.co/edit/gAFWdbWrA33iNuqh?open=app%2Fapp.component.ts

**Current behavior**
After changing page (with pagination) , sometimes the rendering order is from bottom to top (which doesnt look good)

https://user-images.githubusercontent.com/85071405/224544798-486d1bb7-221c-4394-8372-f7a046aa44bf.mov

**Expected behavior**
When moving to a different page (with pagination), the scrollbar is reseted to top, but sometimes the rendering order is from bottom to top, where I expect it to be top to bottom, when reaching to a new page.

Browser: Google Chrome
Ag Grid version: 26.2.0
System: Macbook M1 pro, macOS Monetery 12.6, VS Code

**Comment by StephenCooper** [comment] 2023-03-14 10:30
Thanks for reporting this, I have raised this in our internal system.

**Comment by kiril-matev** [comment] 2023-03-14 17:20
Hello @RazAbk,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8189 When scrolling the viewport to the right edge, up or paging, cell values are rendered from the bottom row up instead of from the top row down**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-03-21 11:14 UTC
Labels: AG-6293
