### ISSUE TITLE
AgGrid inside of WebComponents - Reorder Columns not possible

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#5586] opened 2022-09-22 22:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Reordering of Columns is not possible cause the call to eDocument.elementsFromPoint in the DragAndDropService.prototype.findCurrentDropTarget does not return the elements from a shadowRoot

**Expected behavior**
It should be possibe to use the shadowRoot of the grid div:
var elementStack = this.gridOptionsWrapper.eGridDiv.getRootNode().elementsFromPoint(mouseEvent.clientX, mouseEvent.clientY);

**Please tell us about your environment:**
Windows120
* **AG Grid version:** X.X.X
28.1.1

**Comment by jogibear9988** [comment] 2022-09-24 19:02
change was introduced here: https://github.com/ag-grid/ag-grid/commit/fea16a6ed97662fbd9ee5050dd9db238c3e93932

**Comment by VitaliiK91** [comment] 2022-09-26 16:35
@jogibear9988 I think we are discussing same issues and ways to fix it here https://github.com/ag-grid/ag-grid/issues/5358

**Comment by jogibear9988** [comment] 2022-09-26 17:36
You could hotfix the issue , if you assign a patched version of the method to 
agGrid.DragAndDropService.prototype.findCurrentDropTarget

**Comment by jogibear9988** [comment] 2022-09-26 17:44
we use webcomponents with ag-grid inside of webcomponents

**Comment by VitaliiK91** [comment] 2022-09-27 15:09
@jogibear9988 You are correct. I overrode the prototype of this method and was able to make it work. We also have same setup with Lit based web components, for both components and the web app.

**Comment by yveslange** [comment] 2022-09-29 07:43
A more cleaner way is to set the getDocument on the options

```javascript
      options.getDocument = () => {
        let d = this.shadowRoot;
        d.documentElement = this.shadowRoot.getElementById('grid');
        return d;
      },
```

**Comment by jogibear9988** [comment] 2022-10-01 14:10
@StephenCooper Why managed by community? Isn't this an issue wich should be solved in the framework?

**Comment by jogibear9988** [comment] 2022-10-01 14:14
@yveslange for me your solution does only work partly. if I do this, then the drag overlay is not shown any more.

**Comment by jogibear9988** [comment] 2022-11-16 15:37
i also could create a pull with a fix.

**Comment by StephenCooper** [comment] 2022-11-16 16:19
If you do create a PR then it will have to contain reproductions that will show the bug currently so that we can truly validate that this is a fix.

**Comment by jogibear9988** [comment] 2022-11-16 18:35
how can I do them in a pr? is a jsfiddle okay to show the issue and fix?

**Comment by jogibear9988** [comment] 2022-11-16 20:04
@StephenCooper
Here is a fiddle showing the issue: https://jsfiddle.net/gxL15fum/
And if you remove the comment from line 7 to 67 the issue is fixed.
the code is mostly the same then yours in the patched method
fix is in this line: https://github.com/ag-grid/ag-grid/blob/521cb1c4f453c7cbe3bd4cc551a2164a6c1f7690/community-modules/core/src/ts/dragAndDrop/dragAndDropService.ts#L341

**Comment by kiril-matev** [comment] 2022-12-12 16:21
Hello @jogibear9988,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7673 Grid columns cannot be moved via drag and drop when AG Grid is contained in a Shadow DOM**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-12-12 18:08 UTC
Labels: managed-by-community

**Comment by Inophage** [comment] 2023-01-03 08:51
> > @StephenCooper Why managed by community? Isn't this an issue which should be solved in the framework?
> 
> @jogibear9988 We do not officially support using AG Grid within WebComponents which is why I have added the managed by community label. The degree to which the grid works within a web component depends very much on the features required.
> 
> There has of yet been insufficient demand for us to spend the time and effort to make AG Grid fully supported within a WebComponent. Until that changes we will leave it open for our users to share knowledge as above.

Hi, your product is really great but this kind of issue is blocker for our company (+20k).
We need to create standalone web components used across all departments. We benchmark all available libs to pick and test some of them and decide which one we will use for our customer projects.
The fact this issue is not considered "high priority" by your company let us think this will never be fixed or not maintained.
Can you tell us more about your process regarding this issue to avoid some assumptions? Do you put some delay to fix it? ...

I did try this dirty fix (https://github.com/ag-grid/ag-grid/issues/5358#issuecomment-1258136242) but this one generates other issues; quick filter boxes are not placed at mouse pointer for example:
![image](https://user-images.githubusercontent.com/1100263/210324917-3e29d123-4910-40ee-9865-61080606ba31.png)

Best Regards

**Comment by jogibear9988** [comment] 2023-01-03 10:29
@Inophage try the fix from my fiddle: https://github.com/ag-grid/ag-grid/issues/5586#issuecomment-1317601054

and according to pipeline, it will be fixed in next version

**Comment by jogibear9988** [comment] 2023-01-03 10:30
@Inophage I also think when youre a paying customer, you could look at the issue tracker. (i think)

**Comment by jhuesos** [comment] 2023-01-03 10:40
My employer (ING Bank) is also using WebComponents as it is a key part of our technology stack. I wanted to point this out as agGrid not playing well with WebComponents/ShadowRoot is a deal breaker for us, too. So please reconsider the priority of the support of WebComponents

**Comment by kiril-matev** [comment] 2023-01-03 11:54
Hello @jhuesos! 

As mentioned above, we have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7673 Grid columns cannot be moved via drag and drop when AG Grid is contained in a Shadow DOM**

**As with all of our bugs/feature requests, you can see whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/**

This item is scheduled for release as part of our next release in mid-January.

**Comment by jogibear9988** [comment] 2023-01-03 11:59
> My employer (ING Bank) is also using WebComponents as it is a key part of our technology stack. I wanted to point this out as agGrid not playing well with WebComponents/ShadowRoot is a deal breaker for us, too. So please reconsider the priority of the support of WebComponents

I use AG-grid inside of a WebComponent since years. And only the the Bug of the column reordering was any issue I had with it. (I use AG Grid even before there was a commercial version). I don't see any other issues with shadowroot, but of course, I also don't use some of the aggrid features (for example filtering, I have a much more advanced complex filter wich is directly handeled via backend)

**Comment by StephenCooper** [comment] 2023-04-21 09:34
In v29.3 there have been a number of improvements so that AG Grid now supports Shadow Dom as mentioned in our latest release post. 

https://blog.ag-grid.com/whats-new-in-ag-grid-29-3/

So you may want to upgrade to v29.3 and see if that resolves / removes the need for any workarounds to have AG Grid working inside your web components.

**Comment by vinodneppalli62** [comment] 2024-03-13 18:51
ag-grid column header filter components does not have key events like escape and proper tab navigation in shadow dom.

**Comment by holomekc** [comment] 2024-11-07 18:30
Custom filter also do not work properly in a ShadowDom. In case the custom filter is creating a popup overlay inside the ShadowDom features like described here: https://www.ag-grid.com/javascript-data-grid/component-filter/#custom-filters-containing-a-popup-element also do not work.

Without debugging too deep it looks like ag-grid checks on document level, where only the click on the shadowDom root is visible and then does not see the class on the popup.

**Comment by kiril-matev** [comment] 2024-11-08 09:24
Hello @holomekc!

Thanks for reporting this.

This github issue is about a different topic and has been closed for a while. We'd like to avoid having multiple issues reported under the same github issue to avoid spamming the users on this thread unnecessarily with unrelated issues.

Please open a new github issue about this following the issue submission template - specifically - providing a live example demonstrating this issue and steps to reproduce.

We're looking forward to your new github issue, so we can get started.
