### ISSUE TITLE
React - className 'ag-row-last' remains after pagination change

### ISSUE THREAD

**Issue by frtelg** [ag-grid/ag-grid#4846] opened 2021-12-23 13:29 UTC
**I'm submitting a bug report** 

**Providing a Reproducible Scenario**
To reproduce:
Given
- A grid with > 5 data rows
- Pagination enabled, default to 5

When
- Pagination is changed

Then
- The fifth row, which previously was the last row in the grid, still has className 'ag-row-last', therefore it isn't styled properly.

I made a small project in which I have reproduced the issue: https://github.com/frtelg/demo-ag-grid-last-bug

* **AG Grid version:** 26.2.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

* **Language:** TS 4.5

**Comment by frtelg** [comment] 2021-12-23 15:20
A workaround for this issue is to redraw the data rows: `event.api.redrawRows();`

**Comment by makinggoodsoftware** [comment] 2022-01-11 16:35
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-17 13:21
Hello @frtelg!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

**Until we address this, please use this workaround - after you change the page size, call api.redrawRows() to refresh the row styling:
https://plnkr.co/edit/23CRPTCxR6pBFrhR**

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6261 When using pagination and changing the page size, the row styles don't get reapplied**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:33
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:33 UTC
Labels: in_zendesk
