### ISSUE TITLE
Detail Grids Bug in v32

### ISSUE THREAD

**Issue by JunwayGuo** [ag-grid/ag-grid#8569] opened 2024-08-16 20:28 UTC
After upgrading to v32, an error is reported when repeatedly expanding the detailed grid of the mesh (more than three times), backtracking to v31 does not have this problem.

![image](https://github.com/user-attachments/assets/402f0eed-d125-49dd-a104-bc5c0a19962a)

**Comment by ava-utting** [comment] 2024-08-27 13:10
Hi

Thank you for reporting this.

Unfortunately we have been unable to reproduce this issue. 

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Ava

**Comment by AG-Zoheil** [comment] 2024-09-30 11:20
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-09-30 11:20 UTC
Labels: waiting-for-repro
