### ISSUE TITLE
Disappearing filter in last column

### ISSUE THREAD

**Issue by britvik** [ag-grid/ag-grid#1957] opened 2017-10-02 10:51 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Popup filter disappears if used in last column and number of filtered rows is lower than max number of visible renderable rows after filtering (simply put -> vertical scrollbar disappears after filtering + popup filter disappears too).

**Expected behavior**
Filter should stay opened after filtering.

**Minimal reproduction of the problem with instructions**
1. https://www.ag-grid.com/example.php
2. Scroll horizontally to the last column (scrollbar must be completely at the end)
3. Open filter popup
4. Input value that matches no (or few) rows
5. Filter now disappeared :-(

**Please tell us about your environment:**

* **ag-Grid version:** 13.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

* **Language:** [all]

**Comment by rmc-software** [comment] 2017-10-06 15:10
Closing as this can't be reproduced in latest version: 13.3.1.

**Comment by britvik** [comment] 2017-10-06 15:39
@rmc-software I'm sorry but the bug is still there :( (v13.3.1). Maybe my explanation was incomprehensible, sorry about that. I made a video which shows the bug:
![ag-grid-filter-bug](https://user-images.githubusercontent.com/4123430/31285927-e827f018-aabc-11e7-96c7-f1cc00ec98b1.gif)

**Comment by rmc-software** [comment] 2017-10-06 15:43
Reopened. Thanks for the follow up with the video.

I have created AG-890 to track this and we'll provide updates here once we have them.

**Comment by britvik** [comment] 2017-10-06 15:51
No problem. Should have made a video in the first place. It explains it much better. No stress though, it's just a minor issue and should have a low priority. Thanks for looking into it.

**Comment by rmc-software** [comment] 2017-11-22 11:42
Hi,

We can't reproduce this in v14. Are you still seeing this issue. If so could you provide more detail regarding environment.

Thanks

**Comment by britvik** [comment] 2017-11-22 14:09
@rmc-software Unfortunately the bug is still there. It's reproducible in ag-grid demo page. I'm using the newest version of Chrome to test this.
You need to scroll all the way to the last column and filter only few rows => vertical scrollbar and filter disappears. If you use filter again (and show more/all rows) and then filter only few rows again, the filter won't disappear - because the horizontal scrollbar is not all the way at the end. But if you move the scroll, then filter will disappear again.

**Comment by makinggoodsoftware** [comment] 2017-12-19 11:57
I just tried this

open demo
scroll far right
filter dec > 70000
filter dec > 7000
filter dec > 70000

It all worked fine...

Does this work for you?

**Comment by britvik** [comment] 2017-12-19 16:32
@makinggoodsoftware nope, bug is still there. Maybe you have smaller screen resolution or console open? I tried the scenario on smaller browser window and it worked fine. But on big screen the filter disappears. The only difference I noticed is that on big screen the number of filtered rows fits on "one screen" so scrollbar disappears. On smaller screen the scrollbar remained.

**Comment by patryknut** [comment] 2018-01-09 14:48
Hello,

I have experienced similar issue with my application. It seems that custom floating filters are re initialized why scrolling horizontally away and back. 

I changed your Angular Floating Filters plunker a little bit to demonstrate this:
https://plnkr.co/edit/lPsS36mDQG22dWDH1lKJ

**Current behavior**
Custom floating filters are reset after horizontally scrolling back to them.

**Expected behavior**
Filters should stay unchanged after scrolling.

**Minimal reproduction of the problem with instructions**

1. Open provided plunker:  https://plnkr.co/edit/lPsS36mDQG22dWDH1lKJ
2. Set filter value on Gold column. For example set filter to 4 to have 4 rows displayed in the table.
3. Scroll horizontally to the right (to Bronze Column)  - you should not see Gold column anymore.
4. Scroll back to Gold column.
5. Filter on Gold column is reset. All rows are displayed in the table (39 rows).
6. Check console logs. The agInit() on SliderFloatingFilter was called agin while scrolling back to Gold column.

If you are unable to reproduce this issue, please increase the width of Silver and Bronze columns.

**Please tell us about your environment:**

**ag-Grid version: 15.0.0**

**Browsers:**
Firefox, Chrome

**Comment by patryknut** [comment] 2018-04-16 12:53
Any progress on that? It seems to be very major issue and is observed in aggrid since at least 13.0.0.

**Comment by makinggoodsoftware** [comment] 2018-10-11 15:41
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

**Closed by makinggoodsoftware** 2018-10-11 15:41 UTC
Labels: possible bug

**Comment by gelevanog** [comment] 2021-06-11 13:17
try set `suppressColumnVirtualisation` to true.

**Comment by uma5999** [comment] 2025-04-19 10:41
@gelevanog  @makinggoodsoftware @britvik @rmc-software @patryk-beekeeper 

I am worried about this bug of aggrid enterprise version. 
i am using below 
aggrid-enterprise version 18.01
framework react 16

Found the root cause, actually if  we scroll to last column and click on unSelectAll in filter of agmenu, filter will disappear because of overscroll: auto css property and overflow auto is resetting it's body elements

Given 100% working fix. Dear aggrid team please give below fix in upcoming versions

**.ag-theme-bootstrap .ag-body-viewport {
  overflow-x: scroll; 
  overflow-y: scroll; 
}**


please reach out  to me 

Thanks,
Uma Mahesh
