### ISSUE TITLE
Row style is not updating based on state

### ISSUE THREAD

**Issue by njain9104** [ag-grid/ag-grid#5027] opened 2022-03-28 11:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

We want to update the header, row, and cell styles based on external input. We are managing this using states, while the header and cell styles are getting updated, row styles are not

**Expected behavior**

Row styles should get updated as well

**Please tell us about your environment:**

OS: Windows 10, IDE: VS Code, package manager: npm 

* **AG Grid version:** X.X.X

27.1.0

* **Browser:**

Google Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

Reproducible Link:
https://codesandbox.io/s/holy-brook-yc4nh8?file=/src/App.js

**Comment by makinggoodsoftware** [comment] 2022-04-07 10:15
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by njain9104** [comment] 2022-04-11 11:16
Hey @makinggoodsoftware , can you suggest a workaround for the timebeing, that will be really helpful.

Thanks!

**Comment by kiril-matev** [comment] 2022-04-21 14:04
Hello @njain9104!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

Until this is addressed, please use the workaround below calling redrawRows API method to force a re-render of the rows with the updated style:
https://plnkr.co/edit/t8DxZlGspToiFX67

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6700 When using React and setting rowClass via state, this doesn't cause a re-rendering of the rows with the new rowClass value**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by njain9104** [comment] 2022-04-25 05:07
Hey @kiril-matev , thanks for the quick response.

**Comment by makinggoodsoftware** [comment] 2022-04-28 15:26
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-04-28 15:26 UTC
Labels: in_zendesk, ag-6700
