### ISSUE TITLE
Regression bug: Maximum cell content length 

### ISSUE THREAD

**Issue by ddehghan** [ag-grid/ag-grid#1902] opened 2017-09-10 00:46 UTC
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In version 
    "ag-grid": "12.0.2",
    "ag-grid-angular": "12.0.0",

When a cell content was set to a lot of text it would render correctly. 

After upgrading to 
    "ag-grid": "13.1.1",
    "ag-grid-angular": "13.1.1",

Our angular 4.3 app crashes and the page is re-rended. Unfortunately as a result is not easy to see what the error code was. We may investigate more in the future. But downgrading to version 12.0.2 solves the immediate problem. 

We can't find documentation on what is the max length for the cell text content.

**Expected behavior**
We are not sure what was the limit of the cell length before and what it is now. But is better truncate the text and not crash. 

**Minimal reproduction of the problem with instructions**

columnDefs: [{headerName: "Text", field: "col0", width: 200}]
rowData: [{col0: "amazon kinesis golang - Google Search"}]   <=  this data can be arbitrary large.  

**What is the motivation / use case for changing the behavior?**
we dont control the data that the user is trying to put into the column

**Please tell us about your environment:**
Angular  4.3
OSX, chrome 60

* **ag-Grid version:** X.X.X
repros on 13.1.0 and 13.1.1

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

    "typescript": "<2.4.0",

**Comment by rmc-software** [comment] 2017-09-11 10:36
There is no max text. If the text does not fit, it gets clipped by the browser via css.

This has not been reported by anyone else.

Please provide a plunker with the issue demonstrated, or give steps on how we can re-create on one of the online examples as we cannot reproduce this.

We are going to close this but will re-open it if you provide a plunker or similar with problem reproduced.

**Closed by rmc-software** 2017-09-11 10:36 UTC
