### ISSUE TITLE
Cell innerHTML click event listener issue after 31.3.2 update

### ISSUE THREAD

**Issue by awdorrin** [ag-grid/ag-grid#8083] opened 2024-06-13 13:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a column defined with cellRenderer to define some spans and icons with different click handler for each icon.
The click handler is firing, but the resulting Material Dialog is no longer displaying content.
This was working in AG-Grid 30.2.1, but with the latest update to 31.3.2, this no longer works.

```
        cellRenderer: (params) => {
          const span = document.createElement('span');
          span.innerHTML =
            `${this.getSpanPairFromValues(params.data.prevEprsProgramRating)}` +
            `${this.getSpanPairFromValues(params.data.eprsProgramRating)}` +
            '<br>' +
            `<span class='material-icons' id="prev-${params.colDef.field}-${params.rowIndex}">article</span>` +
            `<span class='material-icons' id="next-${params.colDef.field}-${params.rowIndex}">article</span>`;

          span.querySelector(`#prev-${params.colDef.field}-${params.rowIndex}`)
            .addEventListener('click', this.showSSRSPrevPerfData.bind(this, params.data));

          span.querySelector(`#next-${params.colDef.field}-${params.rowIndex}`)
            .addEventListener('click', this.showSSRSPerfData.bind(this, params.data));

          return span;
        },
```
As an example, the showSSRSPerfData method:
```
  showSSRSPerfData(data: SubcExecSumDTO) {
    let jsonParams = {
      "AcctPeriod": data.eprsReportDate.toFormat('L/d/yyyy'),
      "Program": data.pmmProgramId
    };
    let dialogRef = this.matDialog.open(SsrsDialogComponent, {
      minWidth: '90vw',
      height: 'auto',
      data: {
        rptSvr: this.ssrsURL,
        rptUrl: 'Program/Program_5Block-Subreport',
        rptParams: JSON.stringify(jsonParams),
        title: `${jsonParams["AcctPeriod"]} [${data.pmmProgramId}] ${data.pmmProgramName}`,
      }
    });

    dialogRef.afterClosed().subscribe( (result) => { console.log("showSsrsDialog result: ", result); } );

  }
```
Wondering if this is a context or angular zone issue?
If I comment out the code that adds the Listen Handlers, and add a single 'onCellClicked', choosing one of the click handler, everything works as expected:
```
        onCellClicked: (param) => {
          this.showSSRSPerfData(param.data);
        }
```

**Expected behavior**
The Material Dialog should display its content.

**Please tell us about your environment:**
.Net core back-end/Angular 17 front end, hosted locally on Windows or on Linux Cloud Foundry server.

* **AG Grid version:** 31.3.2

* **Language:** 
Angular 17.1

**Comment by awdorrin** [comment] 2024-06-13 13:54
Just found if I wrap the content of my click handler with a NgZone run, it resolves the issue:

```
  showSSRSPrevPerfData(data: SubcExecSumDTO) {
    this.zone.run(() => {
      let jsonParams = {
        "AcctPeriod": data.prevEprsReportDate.toFormat('L/d/yyyy'),
        "Program": data.pmmProgramId
      };
      let dialogRef = this.matDialog.open(SsrsDialogComponent, {
        minWidth: '90vw',
        height: 'auto',
        data: {
          rptSvr: this.ssrsURL,
          rptUrl: 'Program/Program_5Block-Subreport',
          rptParams: JSON.stringify(jsonParams),
          title: `${jsonParams["AcctPeriod"]} [${data.pmmProgramId}] ${data.pmmProgramName}`,
        }
      });
      dialogRef.afterClosed().subscribe(
        (result) => { console.log("showSsrsDialog result: ", result); }
      );
    });
  }
```

**Comment by sabahang** [comment] 2024-06-18 10:39
I'm closing this issue as it seems that the issue is resolved. If any more investigation is needed please provide a live sample (plnkr, codesandbox etc.) with steps to follow

**Closed by sabahang** 2024-06-18 10:39 UTC
