### ISSUE TITLE
`onStoreRefreshed` is called non-deterministically

### ISSUE THREAD

**Issue by nwrahnema** [ag-grid/ag-grid#6668] opened 2023-05-25 20:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**
The `storeRefreshed` event is sometimes not fired after calling `refreshServerSide`.

Example:
https://plnkr.co/edit/AXTyS7cKhblx0VL0?open=index.tsx
Calling `refreshServerSide` inside `onGridReady` does not trigger the `storeRefreshed` event on completion.

This seems to happen when there is already a `getRows` request in progress. While the example is contrived, this makes it so that we can't use the event to determine when a refresh completes, since it may or may not get called. In our case, we are calling `refreshServerSide` on an interval, and `storeRefreshed` does not fire for many of these calls.

**Expected behavior**
Expect that `onStoreRefreshed` is always called whenever `refreshServerSide` is called.

* **AG Grid version:** 29.3.5

**Comment by timothyblue** [comment] 2023-06-06 18:27
I'm no expert, but I believe that onStoreRefreshed will only fire if the rows have been retrieved at least once.  I could not figure out why my onStoreRefreshed was not firing, and it was because I had never expended the node I was refreshing so the call never happened.

**Comment by zoheil-ag** [comment] 2023-07-17 14:42
Hi @nwrahnema ,

Thank you for reporting this.

Whilst investigating the issue we were unable to reproduce your described scenario. Can you look at the below plunker and confirm if it matches your scenario and your expectations of the outcome? You can see we are refreshing with set intervals and can notice the `onStoreRefreshed` event triggering each time.

https://plnkr.co/edit/7zyrQZ5zJGFVZLxQ?open=index.tsx

If this does not match your scenario, please modify the plunker so it reproduces what you are experiencing and send it back so we can take a look.

Looking forward to hear back from you.

Kind regards,
Zoheil

**Comment by nwrahnema** [comment] 2023-07-22 17:43
In this scenario: https://plnkr.co/edit/3daKbROf4teJxiZ3?open=index.tsx, you can see when called periodically, each `Refresh called` message is associated with one `Refresh finished`. However when you click "Refresh Root Level", there are multiple `Refresh called` messages for a single `Refresh finished`.

**Comment by zoheil-ag** [comment] 2023-07-24 14:48
Hi @nwrahnema,

Thank you for providing further details regarding this.

So this is currently working how it was intended.

The logic is as follows: If a second refresh is called and the first refresh had never finished, the second refresh restarts the work done by the first refresh. So when the event fires it's reflective that the store is no longer in a state where it's trying to reload data.
If a `refreshFinished` event is raised by the grid when you have multiple outstanding "pending" refresh requests, you can consider `refreshFinished` to reflect that all outstanding requests for that store level have been closed.

Could you clarify your use case as to why you are expecting a `refreshFinished` for all pending refresh request? If we can understand the specifics of your requirement better we can either guide you to a workaround or make a decision on providing this feature within AG Grid.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment] 2023-07-31 08:52
Hi @nwrahnema,

Thanks again for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If my reply earlier clarified and solved the issue for you, you can ignore this. Alternatively, if you do wish to get back to us, you are welcome to do so.

Kind regards,
Zoheil

**Closed by zoheil-ag** 2023-07-31 08:52 UTC
Labels: pending
