### ISSUE TITLE
After server side sorting selected row is not updated

### ISSUE THREAD

**Issue by Mioleris** [ag-grid/ag-grid#4316] opened 2021-01-21 14:21 UTC
Hello :)
Selected row stays the same when using server side and clicking on header to sort.
Selected row stays the same but content inside that row changes because of sort changed. 
```
To  reproduce:
1. Go to https://www.ag-grid.com/documentation/javascript/server-side-model-selection/
2. In first example select "**China**" row
3. Click sorting by "**Group**"
4. Selected row stays the same but content inside it changes
```

**Comment by makinggoodsoftware** [comment] 2021-01-29 16:29
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-02-11 17:14
Hello!

Thank you for contacting us about this.

This is expected behavior because row selection is only preserved when the grid's rows aren't reloaded from the server. When using the server-side row model with row grouping and then sorting the records, in some circumstances rows are not reloaded (and row selection is preserved), while in others rows are reloaded (and row selection isn't preserved).

Please see this explained here:
https://www.ag-grid.com/documentation/javascript/server-side-model-grouping/#sorting

As described in the link above, when using server-side row model with **partial store**, the group levels are reloaded from the server when sorting on the currently displayed grouped column. This is exactly the case in your scenario, which causes group rows to be reloaded and row selection to be reset (as there's no guarantee that the selected row will be in the block of rows returned from the server). This is why following the sort (and consequent record reload) the grid selects the same record indexes, because now that the rows have been reloaded, it can't locate the previously selected rows content.

If you'd like to maintain row selection when sorting the row groups, please use server-side row model with full store (**serverSideStoreType='full'**). See this scenario implemented here:
https://plnkr.co/edit/Gr7mq7VGkpwdVq90

Please note that in the sample above, if you select "China", then sort the group column, the China record will still be selected (you'll have to scroll down a bit to see it), as you expect.

Please read about the differences between the full and partial two store types here:
https://www.ag-grid.com/documentation/javascript/server-side-model-row-stores/#row-store-types

Thank you for reaching out about this.

**Closed** 2021-02-15 12:30 UTC
Labels: in_zendesk

**Comment by Jlll1** [comment] 2021-09-16 12:36
If this is indeed the expected behavior, is there a way to disable it? We've tried working around this limitation by implementing the selection for our case, but this "feature" keeps fighting us.
