### ISSUE TITLE
Ag Grid Bundle is 4.5% License Comments

### ISSUE THREAD

**Issue by dirthsj** [ag-grid/ag-grid#6465] opened 2023-04-16 21:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

The ag-grid bundle contains many comments that include license information. I am not allowed to configure a bundler or minifier to strip these for legal reasons. After importing the bare minimum to start a grid;

```
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { ModuleRegistry } from '@ag-grid-community/core';
import { Grid } from '@ag-grid-community/core';
```
I have 283 instances of
```
/**
 * @ag-grid-community/core - Advanced Data Grid / Data Table supporting Javascript / Typescript / React / Angular / Vue
 * @version v29.2.0
 * @link https://www.ag-grid.com/
 * @license MIT
 */
```
in the minified bundle. This contains 192 characters, which ends up at a massive **45 KB**. Overall, this bundle (containing only ag-grid) is about 1 MB, meaning... **4.5%** of the bundle size of ag-grid is *license comments*.

**Expected behavior**
The ag-grid bundle contains a minimum number of license comments to reduce bundle size.
**Please tell us about your environment:**
Package Manager: NPM 9.6.3
Bundler: Vite 4.2.0

* **AG Grid version:** 29.2.0

* **Browser:**
N/A

* **Language:** Typescript 5.0.0

**Comment by StephenCooper** [comment] 2023-04-17 08:17
Hi @dirthsj,

Thank you for pointing this out. Seems like this behaviour is not consistent across our minified files and would definitely be a good improvement for bundle size. 

I have raised AG-8357 to record this internally so that we can investigate this further. 

<hr>

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by seanlandsman** [comment] 2023-04-18 09:12
@dirthsj - do you have a reproducible example of this that I can take a look at? I've just tried a simple example using typescript and webpack and the resulting bundle

**Comment by dirthsj** [comment] 2023-04-18 13:50
I have uploaded a reproduction here - https://github.com/dirthsj/ag-grid-bundle-repro

Repro steps:
* Download
* `npm install`
* `npm run build`

The chunk in `.svelte-kit/output/client/_app/immutable/chunks` with `ag-grid` in the name is the ag-grid bundle, generated from `src/ag-grid/ag-grid.ts`. I have used a dynamic import in `src/ag-grid/ag-grid.svelte` to ensure the aforementioned file contains **only** ag-grid code.

**Comment by seanlandsman** [comment] 2023-04-19 06:30
Great thanks - I'll investigate this week and let you know what we find

**Comment by StephenCooper** [comment] 2023-05-02 09:30
You can track it with this reference:
AG-8357 Minified Files Contain multiple License Details bloating bundle size

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-05-02 09:30 UTC
Labels: AG-8357
