### ISSUE TITLE
Refresh issue of fullwidthrows in 31.0.3 

### ISSUE THREAD

**Issue by deepikagupta31** [ag-grid/ag-grid#7807] opened 2024-04-02 16:04 UTC
Hi Team,

Recently we upgraded Angular version to 17 and ag-grid-angular version to 31.0.3

This is a simple table
![ag-grid-simpleTable](https://github.com/ag-grid/ag-grid/assets/12969967/63a509ef-bcf2-47f0-bc2d-bea1acc1f2d3)

We are making use of fullwidth row to show few details of that particular row. It has another ag-grid table with single row and the same information as non-fullwidth row.
Row is fullWidth based on an action and certain attributes are set to fulfill the requirements of the fullWidth row.
Seems like fullwidthrows becomes non-fullwidthrow automatically

Below is the code 

```
    const rowNode = this.gridApi.getRowNode(event.node.id);
    rowNode.setRowHeight(100);
    rowNode.setExpanded(true);
    this.gridApi.redrawRows({ rowNodes: [rowNode] });
```

Current behaviour: 

- Row selections are resetting the fullwidthrow to non-fullwidthrow with the height of fullwidthrow
- Selected checkbox highlights the row on top of the details hiding texts of fullwidthrow
![HighlightNotVisible](https://github.com/ag-grid/ag-grid/assets/12969967/3b8f8872-c112-4679-9a1e-cafefa5837b9)

Expected Behaviour:
- No impact of fullwidthrow
- Not sure about the selection of rows is causing by same issue

**Comment by AG-Zoheil** [comment] 2024-04-03 15:02
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by deepikagupta31** [comment] 2024-04-15 01:48
Hi Team,
@AG-Zoheil 

Can be found on plunker [https://plnkr.co/edit/CBYU8zMycEDCDu2N?open=app.component.ts](url)

Reproducible steps:
- Click on first row(Ireland), it will expand
- Scroll and click on last row(uruguay)
- Scroll back and verify first row is not longer fullwidthrow except the height as it was set programmactically

**Comment by AG-Zoheil** [comment] 2024-04-16 15:38
Hello @deepikagupta31,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11342**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-04-16 15:38 UTC
Labels: AG-11342

**Comment by AG-Zoheil** [comment] 2024-07-29 14:08
Hi @deepikagupta31,

We've looked into this issue and can update you that this is not a bug.

When you scroll down, the Ireland full width row is removed due to row virtualisation.

When scrolling back up, `isFullWidth` is re-run when the row is created. As the code is maintaining a single reference to the expanded row ID, this check fails as it has been overwritten with Uruguay.

Therefore this item has been closed as **Rejected**.

Kind regards,
Zoheil
