### ISSUE TITLE
Chrome 85 - wrong scroll behavior for the RTL mode

### ISSUE THREAD

**Issue by IgorLav** [ag-grid/ag-grid#4055] opened 2020-09-03 10:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario** 
- Enable RTL grid mode. 
- Add a few columns to display a horizontal scrollbar.
- When you have a horizontal scrollbar try to drag it and pay attention to the header cells.
-  [Plunker example: ](https://www.ag-grid.com/javascript-grid-rtl/rl)

**Current behavior**
The grid headers scroll without a grid body.

**Expected behavior**
Grid headers and grid body should work simultaneously.

* **ag-Grid version:** 22.1.1 

* **Browser:**
Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by gportela85** [comment] 2020-09-05 10:26
Closing as duplicate of https://github.com/ag-grid/ag-grid/issues/4045

**Closed by gportela85** 2020-09-05 10:26 UTC
