### ISSUE TITLE
Sticky Groups with pagination Bug (v.30.0.0)

### ISSUE THREAD

**Issue by maximshipko** [ag-grid/ag-grid#6761] opened 2023-06-14 08:51 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
With pagination, sticky groups work only on the first page.
Reproduced on both SSRM and CSRM.

To reproduce the defect, go to the 2d page, open some groups to have vertical scrolling, and observe sticky groups while scrolling. The sticky groups appear on the top, but without any data.

[CSRM example](https://plnkr.co/edit/xvENUvDnIxBZfhum?open=index.tsx)
[SSRM example](https://plnkr.co/edit/bU4FKfraCadfWXIv?open=index.tsx)

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

**Comment by maximshipko** [comment] 2023-06-14 16:18
I've found an inner ticket created [AG-7258](https://ag-grid.com/pipeline/), to support Sticky groups with pagination

**Comment by maximshipko** [comment] 2023-06-14 17:24
normally it should be 0px, 48px, ... 
Hope, this helps to spot the problem.

**Comment by kiril-matev** [comment] 2023-06-14 21:13
Hello,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug in AG Grid v30.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7258 When sticky group rows are used with pagination on non-first page, scrolling down causes group column cell values to disappear**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-06-15 17:48 UTC
Labels: AG-7258
