### ISSUE TITLE
ReactUI impacts performance significantly

### ISSUE THREAD

**Issue by guido-visser** [ag-grid/ag-grid#4920] opened 2022-02-16 13:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When using the ReactUI, the grid has a significant performance drop as opposed to the legacy renderer.
A reproducable environment: https://codesandbox.io/s/ag-grid-reactui-performace-test-f8upcs?file=/src/App.js
I recommend testing this on a system that is not super fast to really experience this issue.

We're now forced to stay at a maximum of `27.x.x` as we are required to use `suppressReactUi` because the performance is way worse in our application itself. We had no problems with performance issues prior to the new ReactUI.

Example video
https://user-images.githubusercontent.com/16164800/154272615-21d0708b-92ea-494a-a102-95b95855e823.mp4

**Expected behavior**
No performance loss by switching to the new React UI.

**Please tell us about your environment:**
Windows 10, VS Code, Yarn

* **AG Grid version:** 
27.0.1

* **Browser:**
Chrome 

* **Language:** all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by dseller** [comment] 2022-02-17 08:30
We have the same issue. For now, we are going to use the `suppressReactUi` prop to disable the React UI until the performance is improved.

**Comment by kiril-matev** [comment] 2022-02-17 12:09
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced the column reordering issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6403 When using ReactUI, column reordering is slower due to rendering lag**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

We've also added a task to investigate cell rendering when using React rendering:
**AG-6404 [React] Investigate improving cell rendering speed when using ReactUI rendering**

We will investigate this and we hope to deliver a further performance improvement soon.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by guido-visser** [comment] 2022-02-17 12:24
Thanks for picking this up! Looking forward to the fixes 😄

**Comment by makinggoodsoftware** [comment] 2022-03-10 16:09
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-03-10 16:09 UTC
Labels: in_zendesk, ag-6403, ag-6404
