### ISSUE TITLE
Value Parser not showing digit zero

### ISSUE THREAD

**Issue by nedimmuminovic** [ag-grid/ag-grid#4354] opened 2021-02-13 11:05 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

**Providing a Reproducible Scenario**
Steps to reproduce a bug:
1. https://plnkr.co/edit/2mlX9KDYwWxLlKo5 or https://www.ag-grid.com/documentation/angular/value-parsers/
2. Enter digit 0 in a column "Good Number"

**Current behavior**
Digit zero is not shown in column "Good Number".

**Expected behavior**
Zero should be shown in column "Good Number".

**Please tell us about your environment:**

* **ag-Grid version:** 25.0.1

* **Browser:**
Firefox 85.0.1, Chrome 88.0.4324.150 
Mozilla/5.0 (Windows NT 10.0; Win64; x64)
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

* **Language:** 
TypeScript 4.0.2

**Comment by makinggoodsoftware** [comment] 2021-02-23 17:12
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-03-04 18:10
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v24.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5133 [Regression] ValueParser parses 0 as empty value**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Please note we will not update this GitHub issue when this bug is fixed in a future version of ag-Grid.

The best way to get an update on this item is to sign up for ag-Grid new release notifications. Once a new ag-Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-03-12 16:21
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-03-12 16:21 UTC
Labels: AG-5133, in_zendesk

**Comment by kiril-matev** [comment] 2021-04-07 11:28
Hi @Mrsevic,

Thank you for following up.

You're still experiencing this issue because it's not yet fixed in a new version of AG Grid. Please use the item reference number above to look it up on our website to get an update on its status on our pipeline page: 
https://www.ag-grid.com/ag-grid-pipeline/

You can also see the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline above.

Once an issue is recorded in our backlog, we close the GitHub issue because we will not update it when this bug is fixed in a future version of ag-Grid.

**The best way to get an update on this item is to sign up for ag-Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

I hope this helps explain the process we follow so you can more easily get an update on any item reported in GitHub.
