### ISSUE TITLE
Using v-model instead of rowData fails checkForBindingConflicts and results with a warning

### ISSUE THREAD

**Issue by ericcirone** [ag-grid/ag-grid#7873] opened 2024-04-19 18:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Using v-model instead of :rowData results in warning messages in the console.

**Expected behavior**
Using v-model or :rowData should be the same. You should be able to use either one, but not both.

**Please tell us about your environment:**
MacOS, vite@5.2.8,  vue@3.4.21

* **AG Grid version:** X.X.X
ag-grid-community@31.2.1
ag-grid-vue3@31.2.1

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

Issue can be seen here:
https://codesandbox.io/p/devbox/aggrid-dw9dlt

Looks like when using v-model instead of rowData, rowData gets filled in with `"AG-VUE-OMITTED-PROPERTY"` and then `checkForBindingConflicts` fails with a warning.

**Comment by AG-Zoheil** [comment] 2024-04-22 08:17
Hi @ericcirone,

Thanks for getting in touch via GitHub. Could you please clarify your expectation in regards to this specific example that you've provided?

I can see the following warning message but no error: `AG Grid: Using both rowData and v-model. rowData will be ignored`.

This seems to be expected. If there's any other steps you'd like us to follow to reproduce the error please let us know.

Kind regards,
Zoheil

**Comment by ericcirone** [comment] 2024-04-22 15:38
> I can see the following warning message but no error: `AG Grid: Using both rowData and v-model. rowData will be ignored`.

While that warning is true, and a good warning, in my particular case it is not applicable. I am only using `v-model` and not using rowData. Yes with the warning everything still works, except it makes you feel like you are doing something wrong. If **BOTH** `rowData` and `v-model` is being used then yes by all means show that warning. But if only one of `rowData` **OR** `v-model` is being used I don't think that warning is justified.

**Comment by AG-Zoheil** [comment] 2024-05-01 10:34
Hello @ericcirone,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11495**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-05-01 10:34 UTC
Labels: AG-11495
