### ISSUE TITLE
ag-grid enterprise Set Filter blanks not working

### ISSUE THREAD

**Issue by ZanyZephy** [ag-grid/ag-grid#4810] opened 2021-11-30 16:43 UTC
import Vue from 'vue';
import { AgGridVue } from 'ag-grid-vue';
import 'ag-grid-enterprise';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';

const VueExample = {
  template: `
        <div style="height: 100%">
            <ag-grid-vue
                style="width: 100%; height: 400px;"
                class="ag-theme-balham"
                :columnDefs="columnDefs"
                :rowData="rowData"></ag-grid-vue>
        </div>
    `,
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data: function () {
    return {
      columnDefs: [
        { field: 'country', filter: 'agSetColumnFilter' },
      ],
      rowData: [{
        country:1
      },{
        country:12
      },{
        country:123
      },{
        country:1234
      },{
        country:null
      }],
    };
  },
};

new Vue({
  el: '#app',
  components: {
    'my-component': VueExample,
  },
});

* **AG Grid version:26.1.0

**Comment by ZanyZephy** [comment] 2021-12-04 11:03
https://plnkr.co/edit/SpJZPVTWe3s1546O?preview

**Comment by ZanyZephy** [comment] 2021-12-04 11:04
https://plnkr.co/edit/SpJZPVTWe3s1546O?preview
// Filter blanks not working

**Comment by ZanyZephy** [comment] 2021-12-12 02:52
![preview1](https://user-images.githubusercontent.com/49486103/145698435-81f376a3-fb90-4c59-b3ad-4bd170c1c4f1.png)

**Comment by makinggoodsoftware** [comment] 2022-01-11 16:16
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-12 10:46
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v26.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6046 [Regression] When de-selecting any non-blank set filter item, blank values also get filtered out from the grid even though the (blanks) set filter item is selected**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:31
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:31 UTC
Labels: in_zendesk, ag-6046

**Comment by preetivedarthi** [comment] 2024-04-02 12:24
I observed that set filter not working properly in server side model when filter list is default all selected and filter list count is more than 400  
Reproduce step - when default all is selected still it's calling api on 'Apply button'normally filter doesn't call any api on clicking on apply button if all is selected in filter list ..

**Comment by kiril-matev** [comment] 2024-04-02 12:40
Hello @preetivedarthi,

Thanks for using AG Grid.

As a user of AG Grid Enterprise, you can report this to our support system to get a quicker response.

Also please note you are reporting a separate issue from the one this GitHub issue was originally opened for over 2 years ago.

We'd like to keep GitHub issues focused on a particular issue instead of reporting multiple different issues in the comments.

This is why, it would be best to submit a new GitHub issue about the behavior you're seeing. Please follow the issue submission template to ensure we can get all the necessary context and advise. Also, when you open a new issue, please update your earlier comment here to add the new issue link to it.

This is important to help better track GitHub issues and allows the community to react more quickly when there's a specific issue open.
