### ISSUE TITLE
More relaxed react version dependency

### ISSUE THREAD

**Issue by alippai** [ag-grid/ag-grid#4530] opened 2021-06-22 13:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Problem**
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/react/package.json contains restriction to react semver ^16 so react version 17 (and the future 18) won't match. React (and react-is) dependency will be duplicated with inconsistent versions, deduplication won't happen.

**Expected behavior**
No strict react 16 dependency

* **AG Grid version:** latest (25.3.0)

**Comment by makinggoodsoftware** [comment] 2021-06-22 15:47
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by alippai** [comment] 2021-06-22 15:49
I'm just guessing here, but maybe it's happening because of this: https://dev.to/layershifter/how-to-kill-tree-shaking-in-webpack-with-static-properties-p72

**Comment by makinggoodsoftware** [comment] 2021-07-01 16:09
Hi,

We just checked and in our end it seems that is matches 16 and 17

"react": "^16.3.0 || ^17.0.0"
"react-dom": "^16.3.0 || ^17.0.0"

This should allow for >= 16.3.0 and any version of 17 

Is this not working on your end?

**Comment by alippai** [comment] 2021-07-01 16:16
The following doesn't match your description:
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/react/package.json#L112-L115

Also yes, after installing `@ag-grid-community/react` running `npm list react-is` reports react-is version 16.x.

**Comment by alippai** [comment] 2021-07-06 13:51
@makinggoodsoftware did you manage to reproduce this little bug or do you need more details?

**Comment by fgblomqvist** [comment] 2021-07-12 15:31
@alippai what you linked is their devdeps, they're irrelevant to you as a user. You should check peerDeps.

**Comment by alippai** [comment] 2021-07-12 15:40
@fgblomqvist did you try it out?

I'm pretty sure that if you install react 17 and ag-grid/react you'll have react-is **_v16_** in the dependency tree and the final bundle.

**Comment by alippai** [comment] 2021-07-12 15:43
@fgblomqvist looks like it's caused by https://github.com/ag-grid/ag-grid/blob/latest/community-modules/react/package.json#L37, that depends on react-is v16: https://github.com/facebook/prop-types/blob/master/package.json#L31

**Comment by alippai** [comment] 2021-07-12 15:47
Filed https://github.com/facebook/prop-types/issues/354

**Comment by fgblomqvist** [comment] 2021-07-12 17:16
We use
```
    "@ag-grid-community/react": "25.3.0",
    "@ag-grid-enterprise/all-modules": "25.3.0",
```
and we have React 17 (in the dep tree and in our package.json).

**Comment by fgblomqvist** [comment] 2021-07-12 17:16
If you can create a package that reproduces the scenario you're describing then it can probably be looked into by the maintainers.

**Comment by alippai** [comment] 2021-07-12 17:43
I was talking about react-is.

**Comment by makinggoodsoftware** [comment] 2021-07-14 16:09
@fgblomqvist thanks for the insight, you are correct in your observations!
@alippai I do think that there is no issue, do you think you could share something that shows your issue, maybe a dummy project?

Thanks

**Comment by alippai** [comment] 2021-07-20 00:15
@makinggoodsoftware this thread has every detail needed, I don't think I can do more about it. If you open the upstream issue (https://github.com/facebook/prop-types/issues/354), you'll see that ag-grid won't be able to fix the issue (if it doesn't remove the prop-types dependency)

**Comment by kiril-matev** [comment] 2021-07-22 13:53
Hello!

Thank you for bringing this up.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
AG-5555 Move `prop-types` out from dependencies to peerDependencies

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. 

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:13
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-09 10:14 UTC
Labels: AG-5555
