### ISSUE TITLE
api setColumnVisible not working correctly

### ISSUE THREAD

**Issue by leonelvsc** [ag-grid/ag-grid#6755] opened 2023-06-13 12:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If i set a columndefinition property to hide: true and attach on the grid event ready function a function that calls the columnApi.setColumnVisible('colKey', true) it doesn't show the column on the grid, it only works if a change the colDef to "initialHide" instead of "hide"

**Expected behavior**
The grid should show the column in either both cases

* **AG Grid version:** X.X.X
30.0.0

* **Browser:**
Chrome 114

***Language:***
 all

**Comment by kiril-matev** [comment] 2023-06-13 14:43
Hi @leonelvsc,

When submitting issues, please follow the submission template, which requires a live sample.

This is expected behavior - you're using the gridReady event, which is fired before any of the columns/rows are rendered so modifying column visibility has no effect. 

Instead, you need to be using the firstDataRendered event, which is when you can control rendering.

See this here:
https://plnkr.co/edit/xhzcZTgbsUMUW60C?open=main.js

Thanks!

**Comment by kiril-matev** [comment] 2023-06-13 15:12
Hello @leonelvsc,

This functionality isn't data dependent. Please note onFirstDataRendered is fired even if there's no rows shown in the grid:
https://www.ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-firstDataRendered

In terms of setting the initial visibility of a column, you should be using the **initialHide** column definition property. Please see this listed in our documentation:
https://www.ag-grid.com/javascript-data-grid/column-updating-definitions/#changing-column-state

This can then correctly be modified by calling columnApi.setColumnVisible or using column state.
https://plnkr.co/edit/xhzcZTgbsUMUW60C?open=main.js

**Comment by leonelvsc** [comment] 2023-06-14 17:49
> Hello @leonelvsc,
> 
> This functionality isn't data dependent. Please note onFirstDataRendered is fired even if there's no rows shown in the grid: https://www.ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-firstDataRendered
> 
> In terms of setting the initial visibility of a column, you should be using the **initialHide** column definition property. Please see this listed in our documentation: https://www.ag-grid.com/javascript-data-grid/column-updating-definitions/#changing-column-state
> 
> This can then correctly be modified by calling columnApi.setColumnVisible or using column state. https://plnkr.co/edit/xhzcZTgbsUMUW60C?open=main.js

Taking this example and passing an empty array doesn't work it doesn't show the column, so i'm missing something here or your assumption for "firstDataRendered" is wrong 

https://plnkr.co/edit/qbeTxDy45SKYC8P9?open=main.js

**Comment by kiril-matev** [comment] 2023-06-16 10:05
Hi @leonelvsc,

You're correct - onFirstDataRendered only gets fired when there's actual rows shown in the grid.

The initial issue you reported is caused by a bug introduced in AG Grid 30. You can work around this bug by setting cellDataType:false - see this working in the sample below:
https://plnkr.co/edit/yM1zCX3cZMWXK7Xk?open=main.js

Note the AGE column is made visible by the call to columnApi.setColumnVisible in onGridReady.

This is a regression from v29.3.5, which works as expected:
https://plnkr.co/edit/j991LlH5X87fbQc2?open=main.js

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8781 [Regression] When applying column state before setting row data with cell data types, the column state is overwritten**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-06-16 10:14 UTC
Labels: AG-8781
