### ISSUE TITLE
I am Getting the same error from cypress automation but in UI it works fin I am using version 31.1.0(Give me Solution for this version) ", Uncaught TypeError: Cannot set properties of null (setting 'textContent')     at ag-grid-community.auto.esm.js:55887:40

### ISSUE THREAD

**Issue by vxp3507** [ag-grid/ag-grid#8003] opened 2024-05-23 06:24 UTC
I am using AG-grid version 31.1.0 I want the solution in this version itself
Uncaught TypeError: Cannot set properties of null (setting 'textContent')
    at ag-grid-community.auto.esm.js:55887:40
    
    Getting this while closing the dialog not getting on my dev application running on server
    Issue coming when I am running cypress testcase upon my dev env Please give me solution cypress said
    The following error originated from your application code, not from Cypress.

> Cannot set properties of null (setting 'textContent')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.[Learn more](https://on.cypress.io/uncaught-exception-from-application)

**Comment by sabahang** [comment] 2024-05-23 10:36
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,

**Comment by vaskevyo2** [comment] 2024-06-13 16:52
Hello, I am getting this error as well, in CirclCI and not locally. Working with version 31.1.1. The failure in automation tests started after the the upgrade was done. 
This is what the failure looks like: 
Summary of all failing tests

    TypeError: Cannot set properties of null (setting 'textContent')

      at node_modules/ag-grid-community/dist/ag-grid-community.cjs.js:55859:52
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)

line 55859 of the library: 

AriaAnnouncementService.prototype.announceValue = function (value) {
        var _this = this;
        if (!this.descriptionContainer) {
            return;
        }
        // screen readers announce a change in content, so we set it to an empty value
        // and then use a setTimeout to force the Screen Reader announcement 
        this.descriptionContainer.textContent = '';
        setTimeout(function () {
            **_this.descriptionContainer.textContent = value;**
        }, 50);

Was this issue fixed in the consequent versions?

**Comment by sabahang** [comment] 2024-07-18 09:57
@vaskevyo2 We have made recent changes that I suspect might be resolving your issue. Please upgrade to latest version and if the issue is not resolved get back to use with a reproducible example (plnkr or min sample project) with steps to reproduce

**Closed by sabahang** 2024-07-18 09:57 UTC
Labels: waiting-for-repro

**Comment by msrmsr621** [comment] 2025-02-19 10:05
> Upgrading to the another AgGrid version resolved the above issue
I am getting same error with latest library
Which Version you have updated?

**Comment by vaskevyo2** [comment] 2025-02-19 15:15
Upgrading to 31.3.2 resolved the issue for me

**Comment by msrmsr621** [comment] 2025-02-19 15:57
> Upgrading to 31.3.2 resolved the issue for me

Thanks. That is resolved
