### ISSUE TITLE
Click event handler not triggering in react v17 (with stopPropagation())

### ISSUE THREAD

**Issue by sag-tobias-frey** [ag-grid/ag-grid#4475] opened 2021-05-09 13:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Click event handlers are not triggered anymore in the newest react version. I have tracked the following two errors in the react project. The first one containing an example including ag-grid-community. The second one is only using react and portals. In my opinion, this is a react issue; however the react team seems not keen on fixing this issue.

-> https://github.com/facebook/react/issues/20848
-> https://github.com/facebook/react/issues/20901

**Expected behavior**
Click event handlers should be triggered correctly.

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
ag-grid-community: 25.0.1
ag-grid-react: 25.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 Edg/90.0.818.42

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all (react)

**Comment by sag-tobias-frey** [comment] 2021-05-09 13:36
This is a duplicate of https://github.com/ag-grid/ag-grid/issues/4457 | However the answer from @icedjello missed an important point of the issue (using stopPropagation()). So even with the requested changes, the issue still occurs and prevents event handler from being triggered.

> @icedjello You have missed one important point. The problem is the event.stopPropagation() on the outter div. If I add that to your example, it is no longer working in v17.
> 
> V17: https://stackblitz.com/edit/t2t-4505-17-5pwi4n?file=index.js [ no longer working with event.stopPropagation() ]
> V16: https://stackblitz.com/edit/t2t-4505-16-syuu8a?file=index.js [ still working with event.stopPropagation() ]
> 
> So the issue is still present with your proposed fix in v17.

**Comment by LouisMoore-agGrid** [comment] 2021-05-18 08:53
Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:

AG-5351: When using React v17 with a framework component and an onClick event on the grid container which contains event.stopPropagation(), the onCellClicked grid event isn't fired

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment] 2021-05-18 10:41
We've looked at this in detail and determined this is not an AG Grid issue but instead a result of an intentional change in the way stopPropagation() works in React 17. 

Please see the full discussion on this change in React and ways to achieve the behavior you're looking for here:
https://github.com/facebook/react/issues/20848

As this behavior isn't caused by AG Grid but instead by the changes in event propagation logic in React 17, we've closed item AG-5351 as WON'T DO.

Thank you for reporting this and for letting us clarify this - much appreciated!

**Comment by sag-tobias-frey** [comment] 2021-05-18 11:13
@kiril-matev The issue you have linked was actually reported by me as well. However, I think the explanation is not matching my example. The explanation talks about the event handler being attached to the document: however the event handler is being attached to an element inside the react tree. Therefore I have reported the following issue: https://github.com/facebook/react/issues/20901

An other point is, ag-grid adds these event handlers which means I cannot add "true" as the third parameter. And here is the same problem as well; I'm stopping the propagation way outside the ag-grid table. I don't get why this would prevent the cell to receive the event. This seems like a bug in my opinion.

**Comment by makinggoodsoftware** [comment] 2021-06-04 15:54
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-06-23 19:47
@sag-tobias-frey:

Thank you for following up.

We've taken a second look at this based on your feedback and have now reinstated this issue. 

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for reporting this!

**Comment by makinggoodsoftware** [comment] 2021-07-01 16:02
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-07-01 16:02 UTC
Labels: AG-5351, in_zendesk
