### ISSUE TITLE
Columns don't animate on drag and drop when rendering with React 18 createRoot

### ISSUE THREAD

**Issue by simonkubica** [ag-grid/ag-grid#6154] opened 2023-02-12 00:06 UTC
```
[x] bug report
```

When you drag a column to re-order it, you won't always get an animation transition between the original and new column order. This failure to animate seems to occur only when the app is rendering with React 18's new createRoot API.

For example, in this [StackBlitz from the ag-grid-react documentation](https://stackblitz.com/edit/ag-grid-react-hello-world?file=index.js), column re-ordering animates perfectly, because the app renders with the deprecated `render(<App />, document.getElementById('root'));`. 

When changed to the createRoot API `createRoot(document.getElementById('root')).render(<App />);`, column re-ordering seems to fail to fire the transition animation around 50% of the time.

I've replicated the problem in this StackBlitz, with a single-line change (+createRoot import) compared to the aforementioned example in the ag-grid docs: https://stackblitz.com/edit/ag-grid-react-hello-world-3kyd45?file=index.js

This occurs on the latest version of AG Grid 29.0.0, in the latest versions of Safari and Chrome on Mac OS.

Video of the bug:

https://user-images.githubusercontent.com/34695713/218286328-e9858b12-2c9e-4d59-9214-ebe162ced56d.mov

**Comment by StephenCooper** [comment] 2023-02-22 16:43
Thank you for reporting this and providing a reproduction. I have raised this internally for further investigation.

**Comment by kiril-matev** [comment] 2023-02-23 00:28
Hello @simonkubica ,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug. At this time you can avoid this issue by switching to legacy React rendering in AG Grid (by setting suppressReactUi flag):
https://plnkr.co/edit/wckJlS6SyuvfzKbK?open=index.tsx
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8065 When using React 18 and createRoot, dragging a column only animates the first time columns switch places**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by StephenCooper** [comment] 2023-03-07 15:47
I can confirm that this will be resolved as part of our next release v29.2 which should be released before the end of the month.

**Closed by StephenCooper** 2023-03-07 15:47 UTC
Labels: in_review
