### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by palmtown** [ag-grid/ag-grid#6562] opened 2023-05-04 15:41 UTC
**I'm submitting a ...**  (check one with "x")
```
X bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When loading a grid with 10 or more records, the error "ResizeObserver loop limit exceeded" is displayed on the screen.

In Chrome:
ResizeObserver loop limit exceeded
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:249:58)

In Firefox:
ERROR
ResizeObserver loop completed with undelivered notifications.

**Expected behavior**
No error is generated/shown on the screen.

**Please tell us about your environment:**
VueJS 3, webpack

* **AG Grid version: 29.3.3

* **Browser:**
Google Chrome: Version 112.0.5615.138 (Official Build) (64-bit)
Firefox: 112.0.1 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript: 5.0.4
webpack-cli: 5.0.2
es6

**Comment by weihe8892** [comment] 2023-05-05 01:51
Got same error with react + ant design + ag-grid version 29.3.4, happens more frequently when open antd modal that contains a grid, it works fine with 29.2.0

**Comment by StephenCooper** [comment] 2023-05-05 09:54
We will need a code reproduction to investigate this. We have not been able to reproduce this ourselves but am keen to see this myself and resolve it.

**Comment by weihe8892** [comment] 2023-05-05 18:59
Please refer to repo: https://github.com/weihe8892/ag-grid-demo-package2, it can be reproduced with "npm start" command.
It seems when I add following code, it trigger the error: 
  const onFirstDataRendered = (params) => {
      params.api.sizeColumnsToFit();
  };
  
By the way, please include enterprise license in index.tsx file

**Comment by weihe8892** [comment] 2023-05-11 21:18
Vertical scrolling is much smoother (faster) in 29.3.4 than previous version 29.2.0, however due to this issue, we cannot upgrade.  Do you have update on when the issue will be addressed?

**Comment by StephenCooper** [comment] 2023-05-12 09:16
As an FYI I am looking into this issue.

**Comment by StephenCooper** [comment] 2023-05-12 10:45
For the provided reproduction I believe a workaround will be to apply the following property.

```
alwaysShowHorizontalScroll: true
```

I would be interested to know if applying these flags resolve the issues in your applications? There is also a corresponding vertical scroll bar flag but I believe it is the horizontal scrollbar that is responsible for the resize observer loop.

**Comment by StephenCooper** [comment] 2023-05-12 16:20
> I still think the best compromise would be `requestAnimationFrame`.
> 

@Elysiome unfortunately this is not an option as there are a number of features that depend on this being synchronous. Instead we would be aiming to locate the root cause and apply a fix there instead.

**Comment by palmtown** [comment] 2023-05-12 18:53
@StephenCooper 

The workaround worked for me.  +1 on locating "the root cause and apply a fix there instead."

**Comment by lbwexler** [comment] 2023-05-14 18:17
@StephenCooper -- thanks for looking into this quickly.  We are very eager to take the critical  react scrolling fixes and have been bit by this.

Showing  the horizontal scroll bar always generally not an option in our case.  Thanks!

**Comment by StephenCooper** [comment] 2023-05-16 08:26
@lbwexler appreciate the honest evaluation of the property. I did have concerns that it would not be a straight drop in and that it may have other side effects given that it is just a polyfill. This is why it is not more widely documented.

**Comment by StephenCooper** [comment] 2023-05-18 10:33
As an update I believe I have a fix that will avoid these errors being thrown without losing any of the improvements removing the debouncing of resizes gave us. 

It is currently undergoing testing and review.

**Comment by StephenCooper** [comment] 2023-05-30 18:59
@neodescis any chance of a reproduction that I can use to ensure the fix covers your use case too? GitHub repo fine for Angular tests.

**Comment by neodescis** [comment] 2023-06-01 20:11
Unfortunately not; I think it'd be a bit of a lift to get something reproducible somewhere publicly accessible. However, I'd be more than happy to test a patch if you can provide it somehow. Of course I realize that's not quite the same thing, but hopefully better than nothing.

**Comment by Klaster1** [comment] 2023-06-15 14:50
@RossKinsella according to the changelog, ag-grid 30 shipped the fix.

**Comment by StephenCooper** [comment] 2023-06-26 13:46
@RossKinsella as it stands we do not intend to patch v29 with this fix as we have rolled it into our v30 release. In general we aim to fix forward as opposed to applying patches to older version. 

As v30 has resolved this issue, as far as we are aware, I am going to be closing this issue now.

**Closed by StephenCooper** 2023-06-26 13:46 UTC
Labels: AG-8567

**Comment by rishikesh12** [comment] 2023-06-27 06:54
While using the FirstDataRenderedEvent, facing same error (version used 30.0.2)

**Comment by StephenCooper** [comment] 2023-06-27 08:12
> While using the FirstDataRenderedEvent, facing same error (version used 30.0.2)

Can you please provide a reproduction of this so that I can investigate and try and work out why the v30 fix hasn't resolved your issue?

**Comment by aman-kumar-ops** [comment] 2024-08-27 05:45
While using the customTooltip component facing this issue. It always happening when I'm hovering on last column cell of the grid.
V 30.2.0

**Comment by akphi** [comment] 2024-09-18 20:32
> As an alternative there is also the following gridOption that will disable the use of ResizeObserver and instead uses a polyfill that periodically checks the grid width and height.
> 
> If you set this to true then this will avoid the above errors.
> 
> https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-miscellaneous-suppressBrowserResizeObserver
> 
> ```
> suppressBrowserResizeObserver: true
> ```

As of `32.2.0` `suppressBrowserResizeObserver` is deprecated so I got the same problem as that of @aman-kumar-ops . Triggering context menu in the last column throws the error `ResizeObserver loop completed with undelivered notifications.`

**Comment by pwh0225** [comment] 2025-01-31 18:01
> While using the customTooltip component facing this issue. It always happening when I'm hovering on last column cell of the grid. V 30.2.0

I am having this same issue, did you find a solution?
