### ISSUE TITLE
AG grid filter accessibility issue

### ISSUE THREAD

**Issue by ChithiraMG** [ag-grid/ag-grid#7341] opened 2023-12-12 10:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
In Ag grid filter list,we are facing accessibility issue while running fast pass using accessibility insights for web.
![image](https://github.com/ag-grid/ag-grid/assets/101738825/c8a88217-f927-4cda-accd-606e0a5409ef)

After fastpass
![image](https://github.com/ag-grid/ag-grid/assets/101738825/a04026c0-9863-4660-8bac-701a30ce23e1)

![image](https://github.com/ag-grid/ag-grid/assets/101738825/cd2515c7-ee06-4838-9f0b-db281167fd23)

Using Accessibility insights for web extension for checking accessibility issues

**Comment by AG-Zoheil** [comment] 2023-12-12 11:08
Hi @ChithiraMG,

Thanks for reporting this.

This is expected behaviour because AG Grid is using a virtualised list to present the list of items in the set filter. This requires that a container element is placed between the filter element and the actual options themselves. This allows the filter to display thousands of set filter items while only using a few actual DOM elements which are reused to display different items when the set filter is scrolled. AG Grid implement custom keyboard navigation, focus handling logic and has the necessary accessibility attributes set to all the necessary elements to ensure they are announced correctly.

In fact the nested items displayed in the AG Grid filter are announced by the screen readers because they are correctly tagged with aria tags.

However, Accessibility audit tools such as Accessibility Insights for Web use static DOM analysis and assume that all elements of AG Grid are rendered in the DOM, which isn't the case due to virtualization. Even though AG Grid handles keyboard navigation, focus and accessibility announcements internally and these are correct in terms of the end-user experience, the accessibility audit tools report these as issues, while in fact when the user is using the grid these aren't actual issues.

Please use this justification to close the issue on your side as not having any impact on the end-user experience.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-12-12 11:08 UTC
