### ISSUE TITLE
Master/Detail last row on page will not expand unless rows per page is incremented

### ISSUE THREAD

**Issue by gregbown** [ag-grid/ag-grid#1722] opened 2017-06-23 00:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On the first page any rows detail row will render if the player name cell is clicked.
On any page other than the first, clicking any row name cell other than the last rows expands to show the detail row just fine. Clicking the last row fails silently.  If the rows per page is increased via the grid options API, the row detail will suddenly render.
**Realy odd behavior**
On the first page, clicking the last row will trigger that rows detail view, however; on paginating to any other pages, clicking the last row will fail.  This leads me to think the render is blocked when rows per page is conditionally checked at any page greater than 1.

**Expected behavior**
It should be consistent. If a detail row is requested, any constraints should apply to all 100 rows.
Ideally the detail row should render no matter what which detail is requested.

**Minimal reproduction of the problem with instructions**
In oreder to duplicate, paginate above first page.  (the issue will not occur on page 1)
https://plnkr.co/edit/MI29es?p=preview

**What is the motivation / use case for changing the behavior?**
I currently work around this by maintaining a count of detail rows and adjust the rows per page to prevent the failure to render. I would prefer the behavior was corrected or consistent for all rows.
Documenting it here may at least help others.

**Please tell us about your environment:**
Windows 10, Chrome Version 56.0.2924.87, Angular 4.24, Typescript 2.4.0, Webpack 2.6.0, Node 6.9.1, npm 4.0.2, ag-Grid 10.1.0, ag-Grid Angular 10.1.0

**Comment by seanlandsman** [comment] 2017-06-23 06:54
Hi

Thanks for reporting this - I've raised issue AG-562 our side. We'll update this thread with updates as soon as we have any

thanks

**Comment by makinggoodsoftware** [comment] 2017-12-19 08:12
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Closed by makinggoodsoftware** 2017-12-19 08:12 UTC
Labels: bug

**Comment by jhaprashant** [comment] 2018-02-13 04:27
Could not find the bug, did you find the resolution to this?

**Comment by dfeinzeig** [comment] 2019-07-19 16:31
bump, any update on this?

**Comment by aydenxiao-gep** [comment] 2021-06-22 15:03
get the same issue, anyone can help us on this issue?

**Comment by AG-DavidG** [comment] 2023-01-04 10:14
This issue is in a very old version of AG-Grid, and the example given no longer works any more.

This works as expected in version 27.0.0.
 
1. Open https://plnkr.co/edit/vC7Z9vcwLAtXz5Bo?open=main.js&preview
2. Go to page 2
3. Expand the bottom row
Actual and expected: Detail Grid appears. It is necessary to scroll, but this happens on all pages.
 
The only time that the last row's detail grid won't appear is when paginateChildRows=true but that is because it is paginated to the beginning of the next page. This is the expected behaviour, and happens on all pages.

If you still come across this issue in a current version, please provide a Plunker with a working example and steps reproduce it

**Comment by jfkonecn** [comment] 2023-06-23 20:25
I am having the same issue in ag-grid-enterprise@29.0.0 

I am using server-side pagination. 
  
It seems like if the first row on the next page is not loaded then it breaks. 
  
So, for example, if I have a page size of 10 and table with 10 rows then this bug happens. 

If, however, I change the server-side page to something like 50 then this fixes the issue on the first few pages until ag-grid needs to request more data where the first row is not loaded yet (so the 5th page breaks if you have a table with 10 rows). 








I'm having the same issue in ag-grid-enterprise@29.0.0
I'm using server side pagination.

It seems like if first row on the next page isn't load then it breaks.

So for example if I have a page size of 10 and table with 10 rows then this bug happens.

If, however, I change the server side page to something like 50 the this fixes the issue on the first few pages until ag-grid needs to request more data where the first row isn't loaded yet (so the 5th page if you have 10 rows).
