### ISSUE TITLE
getDisplayedRowCount() does not change after filterChanged event

### ISSUE THREAD

**Issue by harish-prakash** [ag-grid/ag-grid#7732] opened 2024-03-13 13:38 UTC
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behaviour**
`filterChanged` event does not update `api.getDisplayedRowCount()`

**Expected behaviour**
`api.getDisplayedRowCount()` should always return the updated value because I am not looking at a property for it to become stale, I am calling a function.

**Reproducible Scenario**
Steps in context of ag-grid react
* Take a gird, get its api and console log `api.getDisplayedRowCount()`.
* Apply a filter that reduces the number of rows.
* The count stays the same as in the beginning before the filter was applied.

**Workaround**
Setup a `filterChanged` event listener and update a local state value from there. This gets extremely ugly within cell the status panel cell renderer.

**Please tell us about your environment:**
* MacOS
* Neovim
* Yarn
* NextJS
* AgGridReact

**AG Grid version:**
31.1.1

**Browser:**
Firefox

**Language:**
TypeScript 5.1.3

**Comment by AG-Zoheil** [comment] 2024-03-13 14:48
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by harish-prakash** [comment] 2024-03-13 14:54
I've already spent time investigating the issue, finding the workaround and reporting it as a paying customer. I cannot afford to waste more time creating a plunkr sample. The problem is very simple and the steps to reproduce are right there. If you cannot fix it, I will just use the work around for now 🤷‍♂️

☝️ The border-line rude comment because of the tag `waiting-for-repro` despite my notes on how to reproduce the issue.

**Comment by AG-Zoheil** [comment] 2024-05-20 15:01
Thank you for submitting this on Github.

We have been unable to reproduce this issue.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-05-20 15:01 UTC
Labels: invalid
