### ISSUE TITLE
Columns can overlap after calling sizeColumnsToFit()

### ISSUE THREAD

**Issue by devdeepdive** [ag-grid/ag-grid#4088] opened 2020-09-23 00:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Demo**
https://plnkr.co/plunk/GG2a8CUSMSxEM2PD

<img width="361" alt="overlapping-columns" src="https://user-images.githubusercontent.com/71737878/94030305-ab090d00-fd8b-11ea-9d2a-c0d8e335e109.png">

**Current behavior**
The function `sizeColumnsToFit()` can sometimes position the columns incorrectly such that they overlap one another. This only seems to occur with certain combinations of grid and column widths and is most noticeable with long cell content lengths. The widths/lengths used for the linked Plunker demo were specifically selected because they show the effects of the problem in a very pronounced way.

From what I can tell, the overlapping itself seems to be caused by ag-grid strangely positioning each affected column based on the columnDefs-defined `width` or `minWidth` values of the columns to its left, instead of the actual widths of those columns (as adjusted by `sizeColumnsToFit`), like you would expect.

Note: I found that this problem _does not_ happen if I only specify either `width` or `minWidth` (i.e. not both) on my column definitions. I'm reluctantly using this as a workaround to the problem, but I hope this will just be a temporary limitation.

**Expected behavior**
Typically `sizeColumnsToFit()` performs fine. Columns are resized as best as possible to fit within the grid. If columns cannot be fit into the grid due to `minWidth`, etc. constraints, they simply overflow the grid container and a horizontal scrollbar appears. However, in all cases, the columns should be _positioned_ correctly and not overlap one another.

**Environment:**
MacOS Catalina 10.15.6

* **ag-Grid version:** 24.0.0
I've observed this in 24.0.0 and 23.2.0. I haven't tried any older versions.

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0

* **Language:** Angular framework/TypeScript, vanilla JS

**Comment by makinggoodsoftware** [comment] 2020-09-29 11:15
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2020-09-30 15:54
Hello!

Thank you for submitting this - much appreciated!

We have reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4653 [Regression] Calling sizeColumnsToFit causes column values to bleed into neighboring column instead of being shortened with ellipsis**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for automatic release notifications using the instructions here. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for reporting this.

**Comment by mkralla11** [comment] 2020-10-02 13:52
My team is in the process of creating a temporary solution for this issue since we are already invested in this version and cannot downgrade. We will post the solution to share with the community in the coming days.

**Comment by gportela85** [comment] 2020-10-02 14:24
@devdeepdive @mkralla11 This issue has been fixed in the latest branch. Thanks for reporting it

**Closed by gportela85** 2020-10-02 14:24 UTC
Labels: in_zendesk

**Comment by devdeepdive** [comment] 2020-10-02 17:52
@gportela85 Thanks for the quick response, Guilherme. BTW I separately reported another issue that I think could be related, in case you have a chance to briefly take a look: https://github.com/ag-grid/ag-grid/issues/4097.

**Comment by gportela85** [comment] 2020-10-02 19:38
@devdeepdive same issue, it was fixed by the same commit
