### ISSUE TITLE
Auto height for group rows (ag-grid v27.0.0)

### ISSUE THREAD

**Issue by SerhiiBabii** [ag-grid/ag-grid#4971] opened 2022-03-14 18:45 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
An issue regarding auto height after updated an application from v25.0.1 to v27.0.0.
When you use "getDataPath" for grouping data and add "wrapText: true" and "autoHeight: true" to a column definition, auto height will be work for a cell's content that has "wrapText" and "autoHeight", but also auto height will be launched for section row.
If you will take a look at the example (Plunker), I set height for section row by "getRowHeight". I need to set less height for section row than data's row.
If you will hide the "Material Description" column, the height of the section row will decrease (height will be correct).

_Plunker link:_ https://plnkr.co/edit/yJBmj9WC5I2gzczO?preview

**Current behavior**
The height of a section row does not calculate correctly.

**Expected behavior**
If you will change ag-grid from "27.0.0" to "25.0.1" (in the example above) you will see correct behaviour (the height of the section row will be correct).

* **AG Grid version:** 27.0.0

* **Language:** [ES6/7 (React)]

**Comment by makinggoodsoftware** [comment] 2022-03-16 13:02
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-03-23 11:54
Hello @SerhiiBabii!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v26.2.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6571 [Regression] When using tree data with autoHeight=true on a column, row height values returned by getRowHeight for parent rows are ignored and parent rows are set to default row height**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-03-31 11:16
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-03-31 11:16 UTC
Labels: in_zendesk, ag-6571
