### ISSUE TITLE
Filter horizontal resize doesn't work in RTL

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#6677] opened 2023-05-30 13:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
Filter horizontal resize doesn't work in RTL

**Please tell us about your environment:** MacOS 13.4

* **AG Grid version:** 29.3.5

* **Browser:** Edge 113.0.1774.57

* **Language:** React 18

**Comment by StephenCooper** [comment] 2023-06-01 08:10
Can you please provide a reproduction showing your issue please. That will help us investigate.

**Comment by kiril-matev** [comment] 2023-06-15 17:28
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8786 When enableRtl=true, floating filter popup cannot be resized horizontally or popup moves to incorrect place**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-06-15 17:46 UTC
Labels: AG-8786
