### ISSUE TITLE
Sometimes the scrolling gets stuck

### ISSUE THREAD

**Issue by dmitry-dedukhin** [ag-grid/ag-grid#2635] opened 2018-09-17 14:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://embed.plnkr.co/yZGFIP7SDDjWFCUf19iK/
The plnkr is created from example https://www.ag-grid.com/javascript-grid-column-definitions/ with no any modifications.

1. Using mouse wheel scroll up or down until scrollbar thumb is stoppped. Scroll a few more times at the same direction.
2. With no delay start scrolling in opposite direction.

**Current behavior**
Sometimes on the step 2 the scrolling gets stuck and while I'm spinning mouse wheel nothing is happened.
But if I stop scrolling for a while and start it again, scrolling become working as expected.
Seems it is important that mouse should not be moved.
This is not 100% reproducable, but it happens fairly often.

**Expected behavior**
Scrolling is working.

* **ag-Grid version:** 19.0.0

* **Browser:**
Chrome only (my version 69.0.3497.92).

**Comment by makinggoodsoftware** [comment] 2018-09-26 13:30
Hi,


In relation to your request, we are afraid that your requirements are too niche, we don't think we can provide you in this case with a fully adequate solution.

I hope you understand that try to keep our backlogs as lean as possible, so we can deliver features as efficiently as possible

https://www.ag-grid.com/ag-grid-pipeline/

Even though we understand that this is an issue in your end, since is part of your requirements, we need to make sure that we add the right amount of complexity in the grid so in the longer run we can deliver more features that are useful to as much customer as possible.

We are going to close this ticket. If you are a customer please contact us through our official support channel.

**Comment by yrral86** [comment] 2018-10-08 16:12
I can confirm this is also happening for us nearly every time we scroll up on a grid with many rows.  Scrolling down seems to work fine.  This is a regression that happened sometime between 17.0.0 and 18.1.2.  We have reverted to 17.0.0 for now and the issue is gone.

@makinggoodsoftware

**Comment by makinggoodsoftware** [comment] 2018-10-09 13:16
Hi,

Just so that we can track if this is actually hitting more users, we are going to move this thread to zendesk

**Comment by makinggoodsoftware** [comment] 2018-10-09 13:16
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by dmitry-dedukhin** [comment] 2018-10-09 13:30
It's already there, see AG-2111

**Comment by makinggoodsoftware** [comment] 2018-10-10 15:03
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2111 Scrolling - Sometimes freezes when reaching the bottom and going back up again

**Closed by makinggoodsoftware** 2018-10-10 15:03 UTC
Labels: in_zendesk
