### ISSUE TITLE
Tooltip Component: Tooltip displayed twice giving double border effect.

### ISSUE THREAD

**Issue by Mireille-Medhat** [ag-grid/ag-grid#4589] opened 2021-07-15 14:17 UTC
**I'm submitting a bug report**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
![image](https://user-images.githubusercontent.com/84448529/125800654-c06423cd-fed1-4566-877f-b4e5d4d16306.png)

**Reproducible Scenario**

Create AG grid with React
Add a column with tooltipComponent and tooltipValueGetter
Hover on any cell in the column

**Reproducible in AG official example**

Follow the link https://www.ag-grid.com/javascript-grid/component-tooltip/#example-custom-tooltip-component
Hover on any cell in the Athlete column 
Check the tooltip, it has a thick border on the left and the top (because it is rendered twice)

**Current behavior**
A tooltip is displayed with an empty duplicate behind it. (If you add padding you can see them clearly) Currently it shows as if it has a thick border.

**Expected behavior**
A tooltip should be displayed once with the correct styling provided.

**Environment:**
Windows 10, Visual Studio Code

 **AG Grid version:** 
23.2.1

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

**Language:** 
Javascript (ReactJS)

**Comment by shuheb** [comment] 2021-08-03 12:05
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment] 2021-08-09 10:26
Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:

AG-5587 When adding styles to a custom React grid component, the style is unnecessarily added to the outer div container created by the grid

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Closed by shuheb** 2021-08-09 10:26 UTC
Labels: in_zendesk

**Comment by kiril-matev** [comment] 2021-11-25 13:00
Hi @Mireille-Medhat,

We looked into the issue you reported earlier and found that it's not a bug.

The reason why the styles are applied twice is because:
1. Inside the Tooltip template: <div className="custom-tooltip"
2. Provided via callback: getReactContainerClasses() { return ['custom-tooltip']; }

The first one attaches the CSS class to the DIV that the user provides.
The second attaches the CSS class to the parent DIV.

If the user wants different styles at each level, then they should use different CSS classes.

Either way, with our latest release 26.2, this behavior is gone when using React UI. When reactUi=true, there is no need for the callback. See this plunker with reactUi=true on latest release.
https://plnkr.co/edit/1TiRv5ZNZvlSb9ds

We encourage you to upgrade to v26.2 and use ReactUI for the improve performance and component code as described here:
https://www.ag-grid.com/react-data-grid/reactui/

As this wasn't a bug and there's an easy way to address this, we've closed this item as rejected.

Thank you for your time!
