### ISSUE TITLE
AG grid call stack error.

### ISSUE THREAD

**Issue by KalinduKumarage** [ag-grid/ag-grid#6566] opened 2023-05-09 07:08 UTC
I'm creating multiple AG grids at the same time, by having the <ag-grid-angular></ag-grid-angular> inside of an *ngFor. I have used autoGroupColumnDefs for row grouping and I need to have a custom SVG icon displayed in each row. For that, I thought of using a cell renderer by passing the cell renderer as an innerRenderer in the autoGroupColumnDef. 

When the grids are being rendered I'm getting a call stack error. 

Any idea as to why this is? Is there a solution to this?

**Comment by StephenCooper** [comment] 2023-05-09 08:47
You will need to provide a reproduction, but you may want to check that you are not sharing gridOptions / config objects across the multiple grids.

**Comment by KalinduKumarage** [comment] 2023-05-09 17:23
Hi @StephenCooper , so it's something like this https://plnkr.co/edit/8QEmUF9BfrEnYJHd?open=app%2Fapp.component.ts . 

However I can't seem to recreate the issue in plunker, maybe the actual problem is with my grid options being shared across multiple grids, but still, I'm getting the error only when I use the cell renderer as an innerRenderer in the autoGroupColumnDef as implemented in the link. Any clue on this?

**Comment by StephenCooper** [comment] 2023-06-15 16:42
Closing as its not clear what the issue is and without a reproduction we will not be able to investigate.

**Closed by StephenCooper** 2023-06-15 16:42 UTC
Labels: waiting-for-repro
