### ISSUE TITLE
RichSelect List is Empty in CellEditor

### ISSUE THREAD

**Issue by jboothe** [ag-grid/ag-grid#2033] opened 2017-11-03 15:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
RichSelect List is empty. Inspecting HTML shows no items are added to list. This is happening in my project, your demo page and your Plunker example (which is probably be one in the same). 

![screen shot 2017-11-03 at 11 19 24 am](https://user-images.githubusercontent.com/3723481/32381383-e8d49444-c088-11e7-9134-7d41c657d9ab.png)

**Expected behavior**
Expect list to populate with supplied values. 

**Minimal reproduction of the problem with instructions**
[Go to your demo page](https://www.ag-grid.com/example-angular-editor/)
Attempt to edit any cell in the `Name` field

**What is the motivation / use case for changing the behavior?**
Currently not usable. 

**Please tell us about your environment:**
AG-Grid demo page

* **ag-Grid version:** X.X.X
Whatever version demo page is using
I'm using 14.0.1 in my project

* **Browser:**
Tested Chrome, Safari

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rellis-of-rhindleton** [comment] 2017-11-03 19:48
Are you getting any errors in the console?  I am.

**Comment by jboothe** [comment] 2017-11-03 20:42
Indeed:

```
ERROR TypeError: Cannot read property 'then' of null
    at RichSelectRow.populateWithRenderer (richSelectRow.js:53)
    at RichSelectRow.setState (richSelectRow.js:32)
    at RichSelectCellEditor.createRowComponent (richSelectCellEditor.js:122)
    at VirtualList.insertRow (virtualList.js:129)
    at VirtualList.ensureRowsRendered (virtualList.js:107)
    at VirtualList.drawVirtualRows (virtualList.js:92)
    at VirtualList.refresh (virtualList.js:81)
    at RichSelectCellEditor.afterGuiAttached (richSelectCellEditor.js:146)
    at PopupEditorWrapper.afterGuiAttached (ag-grid.js:22071)
    at CellComp.afterCellEditorCreated (ag-grid.js:15946)
```

**Comment by rellis-of-rhindleton** [comment] 2017-11-06 14:54
To be clear -- this seems to be a problem with 14.0.x -- backdating ag-Grid to 13.x resoves it.  Something in the 14.0 update seems to have broken the richSelect cell editor.

**Comment by jboothe** [comment] 2017-11-07 18:24
Any word on a resolution for this?

**Comment by jboothe** [comment] 2017-11-08 17:16
We would like to use the new Tree Data Grid available in v14 but we're blocked by a broken `richSelect` in other parts of our app. And of course, we're on a deadline. :)

So we just need to know if this is being addressed any time soon so we can make some decisions. Looking forward to a response from your team. Thanks.

**Comment by JoeNewtonBB** [comment] 2017-11-15 21:28
Any word on the timeline for this fix?  My company is also considering using the new Tree Data Grid component but cannot as long as this issue remains unresolved.

**Comment by jboothe** [comment] 2017-11-16 23:05
`ComponentResolver.prototype.createAgGridComponent` gets hit twice in the process of creating renderers for a cell that is activating a *RichSelect* dropdown. 

The first time through, a `RichSelectCellEditor` gets created successfully. 

The second time through, it attempts to create a `cellRenderer`, but unsuccessfully. 

In `CellRendererService.prototype.useRichSelectCellRenderer`, it looks like the issue is due to `cellRendererPromise` resolves to `null` in cellRendererService.js line 62:
`var cellRendererPromise = this.componentRecipes.newCellRenderer(target.cellEditorParams, params); // resolves to null`

Then it hits the `else` block where it doesn't make a lot of sense to modify the `eTarget.innerText` if the block ultimately returns the null `cellRendererPromise`. 

```
CellRendererService.prototype.useRichSelectCellRenderer = function (target, eTarget, params) {
        var cellRendererPromise = this.componentRecipes.newCellRenderer(target.cellEditorParams, params); // ** this resolves to null
        if (cellRendererPromise != null) {
            this.bindToHtml(cellRendererPromise, eTarget);
        }
        else {
            eTarget.innerText = params.valueFormatted != null ? params.valueFormatted : params.value;
        }
        return cellRendererPromise;
    };

```

Do you expect `ComponentProvider.prototype.retrieve` to return `null` when passing in "cellRenderer"? This seems to be the beginning of the end for cellRendererPromise ultimately being `null`.

**Comment by seanlandsman** [comment] 2017-11-17 11:34
Hi,

Thank you for highlighting this - I've raised AG-1127 our side to track this. We'll update this thread with updates as soon as we have any, but it has been marked as a high priority issue.

thanks

**Comment by ceolter** [comment] 2017-11-17 12:14
to work around this problem, put a cell renderer into the config as follows:

```
                cellEditor: 'richSelect',
                cellEditorParams: {
                    values: [
                        "Bob",
                        "Harry",
                    ],
                    cellRenderer: function(params) { return params.value; },
                }
```

i've worked out what's going on, so you can expect a fix in the next release.

**Comment by JoeNewtonBB** [comment] 2017-11-17 12:16
Thank you for the update.

**Comment by ceolter** [comment] 2017-11-17 12:26
code complete. fix will be in next release.

**Closed by ceolter** 2017-11-17 12:26 UTC
Labels: bug

**Comment by jboothe** [comment] 2017-11-17 14:26
@seanlandsman Thanks for the communication. 
@ceolter Thanks for the workaround and forthcoming fix. We look forward to it. 
Feels so much better knowing there's life on planet ag-grid! 🚀

**Comment by jboothe** [comment] 2017-11-28 05:18
Heads up, there is another scenario where this error returns. Just want to make sure the fix you've applied works when using a `cellRendererFramework` component in combination with `cellEditor: 'richSelect'`. This combination below produces the same error: 
```

{ headerName: "Related", field: "related",
          cellRendererFramework: BooleanRendererComponent,
          cellStyle: {"text-align": "center"},
          cellEditor: 'richSelect',
          cellEditorParams: {
            values: [false, true]
          }
      },
```
@ceolter 's workaround does not work for duplication reasons. 
Please reply.

**Comment by jboothe** [comment] 2017-11-30 23:36
@seanlandsman do you have an ETA on release that will include a fix for this? 

Will it also address using `cellRendererFramework` in conjunction with `cellEditor: 'richSelect'`? 

Thanks.

**Comment by makinggoodsoftware** [comment] 2017-12-01 09:14
Hi,

Thanks for raising this, we will make sure that this is taken into consideration when we release the fix...

The eta remains as per next release... Should be within 1-2 weeks from now

**Comment by jboothe** [comment] 2017-12-01 16:38
Great! Thanks for the update.

**Comment by ceolter** [comment] 2017-12-05 10:47
looking at this now, i don't see what the issue is.

see this plunker, i've got the first column set up to use cellRendererFramework for both the cellRenderer and also the cellEditorParams.cellRendererFramework

can you alter the plunker to demonstrate what it not working please?

**Comment by ceolter** [comment] 2017-12-05 11:04
i've noticed there was a problem, when you open the rich select, the 'selected value' cell is not using the cellRendererFramework. I have just fixed this and will be in the next release.

**Comment by JohnMasterson** [comment] 2017-12-19 13:36
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John

**Comment by Marimuthu-Aathi** [comment] 2019-10-18 05:35
Hi, Anyone can help me out from this. 
I'm trying to add 'agrichselectcelleditor'. this is my coulmndef. here i have call the method to get reason code from Api.
{
      headerName: 'Reason Code', field: 'reasonCode', width: 100, suppressMenu: true, suppressSorting: true, suppressFilter: true,
      cellEditor: "agRichSelectCellEditor",
      cellEditorParams: {        
        values: this.getReasonCode(),
      }
    },
But when i going to select reason code it's showing empty column and also got error lik below
core.js:1673 ERROR TypeError: this.params.values.indexOf is not a function
    at RichSelectCellEditor.afterGuiAttached (richSelectCellEditor.js:144)
    at PopupEditorWrapper.push../node_modules/ag-grid/dist/lib/rendering/cellEditors/popupEditorWrapper.js.PopupEditorWrapper.afterGuiAttached (popupEditorWrapper.js:68)
    at CellComp.push../node_modules/ag-grid/dist/lib/rendering/cellComp.js.CellComp.afterCellEditorCreated (cellComp.js:853)
    at Promise.push../node_modules/ag-grid/dist/lib/utils.js.Promise.then (utils.js:1672)
    at CellComp.push../node_modules/ag-grid/dist/lib/rendering/cellComp.js.CellComp.startEditingIfEnabled (cellComp.js:804)
    at CellComp.push../node_modules/ag-grid/dist/lib/rendering/cellComp.js.CellComp.startRowOrCellEdit (cellComp.js:781)
    at CellComp.push../node_modules/ag-grid/dist/lib/rendering/cellComp.js.CellComp.onCellDoubleClicked (cellComp.js:772)
    at CellComp.push../node_modules/ag-grid/dist/lib/rendering/cellComp.js.CellComp.onMouseEvent (cellComp.js:709)
    at GridPanel.push../node_modules/ag-grid/dist/lib/gridPanel/gridPanel.js.GridPanel.processMouseEvent (gridPanel.js:377)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)

Thanks
