### ISSUE TITLE
ag-charts-react support for React 18 and above

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#5438] opened 2022-08-04 07:59 UTC
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

Current behavior:
I'm unable to install ag-charts-react for the latest React version 18.2.0 and 18+, though I'm able to install the charts for React 17.0.2
![image](https://user-images.githubusercontent.com/77911765/182795003-f5e0789d-d81b-4f2b-9507-c679698e13ae.png)

Expected behavior:
I should be able to install and use ag-charts-react for React version >= 18 too.

Environment:
OS: Windows 10
IDE:VSCode
Package Manager: npm

AG Grid version: 28.1.0

Browser: Chrome

**Comment by seanlandsman** [comment] 2022-08-04 13:37
Hi,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a feature request.

We have added this bug to our backlog and we are tracking it with the following reference and description:

AG-7109 Update peer dependencies to add React 18 for AG Charts

For now you should be able to use `--force` or ``legacy-peer-deps` to continue - AG Charts will work just fine with React 18, we just need to update our peer dependencies to reflect this.

We try to fix bugs from one release to the next, so this should be fixed in our next release.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time.

**Closed** 2022-08-09 11:25 UTC
Labels: AG-7109
