### ISSUE TITLE
Safari - While reordering columns the whole window is selected

### ISSUE THREAD

**Issue by jtoming830** [ag-grid/ag-grid#4779] opened 2021-11-17 13:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Bug is reproducible on https://ag-grid.com/

**Current behavior**
All window elements are selected during column reordering
![image](https://user-images.githubusercontent.com/18515380/142211734-5c91b797-d679-4bd8-b1dd-6c695b77fef7.png)

**Expected behavior**
No element selection during column reordering (in Chrome it's fine)

**Please tell us about your environment:**
MacBook Pro (2019 16-inch), MacOS Big Sur 11.4
and
MacBook Air (Retina, 13-inch, 2020), Big Sur 11.6

* **AG Grid version:** 26.1.0+ (I am using 26.1.0, not sure about version on your site)

* **Browser:**
Safari 14.1.1 (16611.2.7.1.4)
and
Safari Version 15.0 (16612.1.29.41.4, 16612)

* **Language:** I am using React 16 with JS (ES2020 I think) but not sure about your site

**Comment by jtoming830** [comment] 2021-11-17 16:44
Seems like this bug is also reproduced via row dragging functionality. 

Well, I have found workaround. I disable text select on `dragStart` event and enable it on `dragStopped`. 
```jsx
onDragStarted={() => {
  document.body.style['-webkit-user-select'] = 'none'
}}
onDragStopped={() => {
  document.body.style['-webkit-user-select'] = 'text'
}}
```

**Comment by makinggoodsoftware** [comment] 2021-11-18 11:45
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-11-22 11:15
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v26.0.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6041 [Regression] When re-ordering grid columns via drag and drop in Safari, all elements on the page are selected**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-12-03 10:45
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Closed by makinggoodsoftware** 2021-12-03 10:45 UTC
Labels: in_zendesk, AG-6041

**Comment by abhishek-shukla-itilite** [comment] 2022-02-25 14:00
> 

Man this has bugged me down since hours!
Thank you so so much for the solution!!!
