### ISSUE TITLE
Column state doesn't restore width

### ISSUE THREAD

**Issue by dominikkurenda** [ag-grid/ag-grid#7601] opened 2024-02-13 12:50 UTC
I'm submitting a
[x] bug report

Column state doesn't restore width.
Where you can check it out :
https://www.ag-grid.com/angular-data-grid/column-state/
at "Save and Apply State" section

Try to resize any column, then save state, resize column again. Try to restore state and nothing happens.

**Comment by AG-Zoheil** [comment] 2024-02-13 12:53
Hello

Thank you for reporting this - much appreciated!

We've already added this bug to our backlog and we are tracking it with the following reference: **AG-10388**

This will be fixed in the next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-02-13 12:53 UTC
Labels: AG-10388

**Comment by vanrijs** [comment] 2024-02-14 08:44
test

**Comment by vanrijs** [comment] 2024-02-14 08:45
Hm same issue here. Very annoying. I think is has something todo with the setting "flex". 
I removed it from the column state data set using this:
```
const test = JSON.parse(localStorage.getItem('orders_column_state')).map(function(item) {
            delete item.flex;
            return item;
        });
```

Maybe you can use something like this too for the time being...

**Comment by vanrijs** [comment] 2024-02-20 15:20
Hm I just tried the latest release but the issue is still there on my side.. 
Can you test it too @dominikkurenda?

**Comment by LukivondemKaff** [comment] 2024-03-15 09:21
I still have the same issue as well with 31.1.1
I only write like in the example the currentState in a useState when onChangeState is triggered. 
Althogh the the gridPreDestroyed is never which will set the initialState to the current State it does change back the widht to the default size. 

I tried it now for more than one day. I think a big issue is that It is not possible to apply the state directly and not via the initial state. If this would be possible like with the columnState it would most likely solve the issue.

**Comment by AG-Zoheil** [comment] 2024-03-15 11:35
Hi all,

You can see this working in `31.1.1` here: https://plnkr.co/edit/6axSgFcYrfp2lzjT

1. Resize a column
2. Click "Save state"
3. Resize the same column to a different size
4. Click "Restore state"

**Actual & Expected: Column size restored.**

If you are still having issues with this (or something else) please open a new GitHub issue with a link to a plunker and steps to describe how to reproduce the issue.

Thank you!
