### ISSUE TITLE
Row selection issue in Infinite Row model after refreshInfiniteCache

### ISSUE THREAD

**Issue by tania-mel** [ag-grid/ag-grid#4652] opened 2021-09-02 08:54 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a grid with Infinite Row model, row selection, server side sorting and inline cell edit. I use refreshInfiniteCache() method after inline editing. If I edit a cell in the sorted column, and after refresh the row moves up, this row stays selected even if I click to another row. If row moved down after refresh - everything is ok. 

This behavior is simple to reproduce even without inline editing. I used example from Server-Side Sorting and filtering page.
https://plnkr.co/edit/0QFhTYhbXcdia5go

In plunker you need to:
1. Sort rows by Age descending.
2. Somewhere on the first page there will be "Will Simpson", select this row.
3. Click Refresh button above the grid.
4. If "Will Simpson" moved down - click again, until it moves up comparing previous position. 
5. Click on another row - both rows become selected.

**Expected behavior**
Row selection should work the same way as normally.

**Please tell us about your environment:**
Windows, WebStorm

* **AG Grid version:** X.X.X
24.1.0 in my environment, 26.0.0 - in plunker

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.0.5 (5.2.7 in plunker).

**Comment by makinggoodsoftware** [comment] 2021-09-06 15:46
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-09-09 14:41
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5745 When using the infinite row model and reordering the selected row above the rest of the rows, the selected row cannot be de-selected anymore**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by tania-mel** [comment] 2021-09-09 14:55
Thanks a lot for the quick feedback!

**Comment by makinggoodsoftware** [comment] 2021-09-16 09:51
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-09-16 09:51 UTC
Labels: in_zendesk, ag-5745
