### ISSUE TITLE
Resetting row height with `resetRowHeights()` ignores `autoHeight` and `wrapText` settings

### ISSUE THREAD

**Issue by CapnCrunchsna** [ag-grid/ag-grid#4883] opened 2022-01-20 20:40 UTC
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Reproducible Scenario**
A plunker of this bug can be found here: https://plnkr.co/edit/6Agf7KqBShd5M66h

**Current behavior**
When calling `gridApi.resetRowHeights()` the rows are resized ignoring cells that have `autoHeight: true` and `wrapText: true`.  The rows are simply all resized to their default (or provided) heights. 

**Expected behavior**
Calling `gridApi.resetRowHeights()` should still take into account cells that should be larger due to having `wrapText: true` and `autoHeight: true`, leaving them at their full height instead of resizing everything to the default.

**Please tell us about your environment:**
The created Plunker was forked from the ag-grid documentation, using the Angular Data Grid ([this example](https://www.ag-grid.com/angular-data-grid/row-height/#example-row-height-change) in particular).

* **AG Grid version:** X.X.X
26.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

* **Language:** 
All

**Comment by benshope** [comment] 2022-01-25 21:43
+1

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:48
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-02-07 11:38
Hello @CapnCrunchsna!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v25.3.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6161 [Regression] When using autoHeight=true and wrapText=true calling the api.resetRowHeights method sets rows height to default and renders the cell value wrapped text over the cells below**

This bug will be fixed in our next release - v27.0.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-17 10:35
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-17 10:35 UTC
Labels: in_zendesk, ag-6161

**Comment by amyzhao-seismic** [comment] 2024-03-08 02:07
Hi, has this problem been resolved? I have encountered the same problem.

**Comment by kiril-matev** [comment] 2024-03-08 09:27
Hello @amyzhao-seismic,

Thanks for using AG Grid.

You can check the release status of any development item in our changelog:
https://www.ag-grid.com/changelog/

In this case, the bug that was opened about this - AG-6161 is listed as resolved in AG Grid v27.0.0.

If you're still experiencing an issue in this area, please submit a new github issue about this as it's clearly a different issue from the one reported and resolved here.

When submitting a bug, please follow the bug submission template.
