### ISSUE TITLE
select all in column filter , select filter values not working well

### ISSUE THREAD

**Issue by TomPony21** [ag-grid/ag-grid#7440] opened 2024-01-16 13:47 UTC
Hello,

I'm facing two issues with AG Grid's 'Select All' and ’Select All Filters’ functionality:

1. Select All Limited by Filter: In the default filter mode on filter, 'Select All' only selects rows that match the current filter, not all rows in the grid.
2. Select All Filter Button Unavailable in Default Mode: The 'Select All Filter' option within the filter is only accessible in Excel Mode and not in the default mode.

I am looking for solutions to have 'Select All' select all rows in the grid, regardless of filtering, and to enable the 'Select All Filters' option in default mode.

Any assistance would be greatly appreciated.

Best,
Tom

**Comment by AG-Zoheil** [comment] 2024-01-16 14:26
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by TomPony21** [comment] 2024-01-16 17:57
Hello Zoheil,

I've encountered a limitation with the 'Select All' functionality in AG Grid's default filtering mode. 
I've attached a video to demonstrate the issue more clearly. Here are the key points:

Selective 'Select All' in Default Filter: When using 'Select All' in the default filter mode, it only selects the items currently visible under the applied filter, not all items in the grid.

Desired Feature: 'S
[Screen Recording 2024-01-16 at 19.48.28.zip](https://github.com/ag-grid/ag-grid/files/13954069/Screen.Recording.2024-01-16.at.19.48.28.zip)
elect All Filtered Results' in Default Mode: The video also shows that in Excel Mode, there is an option to 'Select All Filtered Results'. This feature is exactly what I need in the default filter mode. However, it's currently unavailable without enabling all Excel Mode options.

I appreciate any assistance or guidance on how this can be achieved.

Thank you for your support.

Best regards,
Tom Pony

**Comment by AG-Zoheil** [comment] 2024-01-18 16:21
Hi @TomPony21,

Thanks for getting back. I didn't quite get your requirements.

"When using 'Select All' in the default filter mode, it only selects the items currently visible under the applied filter."

This is by design. For example if you have a list of 100 rows and you enter a phrase or word into the filter, "Select All" will select all items that are matching your word or phrase. Selecting all items in the absolute sense would not make sense here as the user has entered a phrase/word.

"The video also shows that in Excel Mode, there is an option to 'Select All Filtered Results'"

I assume you mean 'Select All Search Results'.
This works in the same way as 'Select All' in default mode, besides the "other Excel mode options".

So for example - for both modes of filter - try the following test case:
1. Set the filter so no rows (blank rows only in Excel mode) are displayed
2. Type in "El" into the filter
3. Tick "Select All" or "Select All Search Results" in Excel mode

Result: In both cases you end up with rows that contain Elephant and Antelope. Not "all" rows.

Could you clarify what your expectation would be for the above test case?

Thanks

**Comment by AG-Zoheil** [comment] 2024-02-19 10:25
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

**Closed by AG-Zoheil** 2024-02-19 10:25 UTC
Labels: waiting-for-repro
