### ISSUE TITLE
Custom editor test fails after upgrading to version 32.1.0

### ISSUE THREAD

**Issue by wein2011** [ag-grid/ag-grid#8570] opened 2024-08-18 20:40 UTC
I'm submitting a ... (check one with "x")

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

This issue is related to: Custom editor test fails after upgrading to version 31.0.3+ <https://github.com/ag-grid/ag-grid/issues/8417>
Issue #8417 was closed due to a potential internal improvement. Unfortunately, it did not resolve this issue.

Reproducible Scenario
Added minmal reproducible test case in attached zip file
[ag-grid custom editor test.zip](https://github.com/user-attachments/files/16651936/ag-grid.custom.editor.test.zip)

To see the issue:

1) Extract the zip file
1) Run npm install
1) Run npm run test

Current behavior
The single test fails with:
Error: Timeout - Async function did not complete within 10000ms (custom timeout)

The issue occured after upgrading to AG Grid: 32.1.0.

The application is a simple 1 row & 1 column grid (see app.component.ts). It is important to note that the domLayout is 'autoHeight'.

The custom editor is a simple Material input (see editor.component.ts). It is important to note that ngAfterViewInit calls nativeElement.focus after a timeout. This is required in the full program due to transition from the renderer to the editor while maintaining the caret position.

The test (Text: a) will fail (see app.component.spec.ts).
The promise to loader.getHarness(MatInputHarness) on line 81 of app.component.spec.ts will never resolve. Additional fixture.detectChanges, fixture.whenStable, or time delays did not provide a work-around. whenStable might also not resolve. This behavior is independent of Angular (tested v17 and 18).

It indicates but does not prove that autoHeight prevents Angular from stabilizing.

Expected behavior
The single test passes.

The test passes when downgrading the version to AG Grid: 31.0.2.

Please tell us about your environment:

Windows: 11

Visual Studio Code: 1.91.1

NPM: 10.7.0

Angular: 18.1.2 (also tested with V17 with same result)

AG Grid version: 31.0.3 and later (issue did not exist with 31.0.2 and prior)

Browser: Karma v 6.4.3 uses Google Chrome v 126.0.6478.185

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
Language: TypeScript 5.5.4
[ag-grid custom editor test.zip](https://github.com/user-attachments/files/16651936/ag-grid.custom.editor.test.zip)

**Comment by sabahang** [comment] 2024-09-02 13:44
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now filed this as a bug report and will be investigating it

We have added this to our backlog and we are tracking it with the following reference and description:
**[AG-12702][Regression] Custom editor test fails after upgrading to version 31.0.3+**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Comment by AG-Zoheil** [comment] 2024-09-12 09:34
Hi @wein2011,

Please note that we have closed this item in our backlog now as the grid works as expected. It seems like this is an integration test being run in form of a unit test - but regardless of the implementation as we do not provide support via GitHub we will not be looking into this matter further.

Thank you for understanding!

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-09-12 09:34 UTC
Labels: AG-12702
