### ISSUE TITLE
Sticky group rows will block the node view navigating to top

### ISSUE THREAD

**Issue by Pumpk1n23** [ag-grid/ag-grid#8053] opened 2024-06-06 07:30 UTC
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I am using tree data of ag-grid with SSRM mode, the grid options 'suppressGroupRowsSticky' is set to true. 
- The parent group node will stick to the top of the grid if I scroll down to view the sub nodes of it.
- Then I am trying to navigate any node by invoking grid.api.ensureNodeVisible(nodeToNavigate, 'top'). 
- It will navigate to it but covered by the parent sticky node. The next node is showing below the sticky parent node.
- For without suppress group rows sticky, it works well.

Current behaviour.
https://www.ag-grid.com/react-data-grid//grid-api/#reference-scrolling-ensureNodeVisible
https://www.ag-grid.com/react-data-grid//grid-options/#reference-rowGrouping-suppressGroupRowsSticky

**Current behavior**
Parent node sticky will cover the node I want to navigate to top

**Expected behavior**
node will be the first after the sticky parent node 

**Please tell us about your environment:**
Windows 11, Visual Studio 2022 17.7.7, React 18.3.1

* **AG Grid version:** X.X.X
"ag-grid-react": "31.2.0"

* **Browser:**
Edge Version 125.0.2535.79

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.9.5 | ES7

**Comment by sabahang** [comment] 2024-06-12 13:59
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. 

Please follow the steps below:

1. Locate an example in our documentation: https://www.ag-grid.com/javascript-grid-range-selection/
2. Select the Framework you’re using from the icons on the top-right of the page
3. On the left top of the example frame, click the bottom button to open it in Plunker or CodeSandbox.
4. Update the example code so the issue is reproduced
5. Keep your code as simple as possible, only show the behavior that demonstrates the issue.
6. Save the plunker (Click the Save button in the top-left corner)

Send us:

- The link to the reproducible scenario (Copy the URL from the browser
- A list of steps to follow to reproduce the issue
- A description of the actual(incorrect) and expected(correct) behavior


Plunker/CodeSandbox is the simplest way to provide a scenario because you can directly modify one of our documentation examples. However, if you prefer, you can use any other web-based tool such as stackblitz, etc.

**Comment by sabahang** [comment] 2024-06-13 15:49
Upon further investigation we were able to reproduce this issue internally. Thank you for reporting this.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-11875 When using ensureNodeVisible sticky rows will cover the node that is scrolled to (sticky parent nodes, grandTotalRow, groupTotalRow)**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed by sabahang** 2024-06-13 15:49 UTC
Labels: AG-11875
