### ISSUE TITLE
Grid with style="width: 100%; height 100%" overflow in ver 20.0.0

### ISSUE THREAD

**Issue by mjonas4356** [ag-grid/ag-grid#2873] opened 2019-01-14 19:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

I'm using this construction 
 <ag-grid-angular
                class="ag-theme-balham"
                style="width: 100%; height: 100%"
                [columnDefs]="cols"
                [rowData]="data"
</ag-grid-angular>

In version 19.1.2 is grid expanded to the rest of screen height and displays scrollbars. This is my wanted behavior. 

After upgrade to version 20.0.0 the grid have height bigger than screen height and vertical scrollbar is missing. Horizontal scrollbar is visible only when I scroll down with arrow keys on keyboard. 

**Please tell us about your environment:**
Angular 7.2.0
NPM 6.5.0
Node.JS 11.6.0
Typescript 3.1.6
Chrome 71
Safari 12

**ag-Grid version:** 20.0.0
[X] Still an issue in the most recent ag-Grid version

**Comment by cs-miller** [comment] 2019-01-15 01:03
having the same issue with react version

**Comment by emjaksa** [comment] 2019-01-15 06:18
Try adding overflow hidden to the style property.
style="width: 100%; height: 100%;overflow: 'hidden' "

**Comment by MehdiSaeedifar** [comment] 2019-01-19 08:20
We also have this issue with version 20.

**Comment by cwhaught** [comment] 2019-01-21 21:16
I believe I am seeing a variation of this as well.

I am using height: 100%; width: 100%; and now have to scroll to see the sidebar.

As far as I can tell it is due to this commit.

https://github.com/ag-grid/ag-grid/commit/3717aa950f1eeb9ad9a996ccd1c2c6266a0cee87#diff-5c4c51f7c1194bc5345fffb50464d1f0

Where width: 0px; was removed from .ag-layout-normal

**Comment by gportela85** [comment] 2019-01-22 18:10
@mjonas4356 Can you provide an example of this issue? I tried with the SideBar + angular, same config as you mentioned above: https://next.plnkr.co/edit/bWC6KexNPcbtDbsE
Looks normal to me, maybe I'm missing some of styles that you are using?

**Comment by jiangyh1024** [comment] 2019-01-23 08:59
@cwhaught  yes you are right, I add   .ag-layout-normal {
    width: 0px
  }
my self and it works

**Comment by jiangyh1024** [comment] 2019-01-23 09:02
@cwhaught  how to fix it , please help

**Comment by jiangyh1024** [comment] 2019-01-23 09:04
@mjonas4356

**Comment by mjonas4356** [comment] 2019-01-23 18:22
> @mjonas4356 Can you provide an example of this issue? I tried with the SideBar + angular, same config as you mentioned above: https://next.plnkr.co/edit/bWC6KexNPcbtDbsE
> Looks normal to me, maybe I'm missing some of styles that you are using?

@gportela85 Hi, my app is based on fuse-angular, I have prepared a fork for you. In package.json is reference on Ag-Grid 19. When you open page /sample you will see a grid with scrolling (headers and toolbar is fixed), everything works perfect.

Ag-Grid is inside container with this style:
.page-layout {
  position: relative;
  overflow: hidden;
  width: 100%;
  min-height: 100%;
}
Ag-Grid itself have style width: 100%, height: 100%

After change on version 20, page /sample will be broken (no scrollbars, not possible to scroll table, only with keyboard). I have found a "fix" for the problem, you could look on page /sample3. I added height: 50px to .page-layout and everything works.

All styles are in file styles.scss.

**Comment by jiangyh1024** [comment] 2019-01-24 03:40
```
<div style="height: calc(100vh - 50px)">
  <ag-grid-angular *ngIf="gridOptions" class="ag-theme-balham" [gridOptions]="gridOptions">
  </ag-grid-angular>

</div>
```

remove flex layout work fine. but this does work in version 19.0.0

**Comment by jiangyh1024** [comment] 2019-01-24 03:47
version 19
![image](https://user-images.githubusercontent.com/34930870/51653291-c8da0980-1fcd-11e9-8d09-465837ef45b5.png)


version 20
![image](https://user-images.githubusercontent.com/34930870/51653302-d4c5cb80-1fcd-11e9-8308-2b276e630385.png)

same code
![image](https://user-images.githubusercontent.com/34930870/51653321-e14a2400-1fcd-11e9-9b8f-d8bd518865f2.png)

**Comment by jiangyh1024** [comment] 2019-01-24 06:40
@gportela85

**Comment by mjonas4356** [comment] 2019-01-24 07:20
Example where 100% height works booth on version 19 and 20 is in this small repo mjonas4356/aggrid20-height-demo on page sample3

![working](https://user-images.githubusercontent.com/10179428/51661283-b1405800-1fb0-11e9-8192-a412821f1225.png)


@jiangyh1024 
`<div style="height: calc(100vh - 50px)">` is not solution because I don't know which size will toolbar have.

**Comment by jiangyh1024** [comment] 2019-01-24 07:23
@mjonas4356  I am sorry, I meant to @gportela85 to let hitm know the weird behavior between version 19 and 20 using flex container as the parent container of aggrid

**Comment by jiangyh1024** [comment] 2019-01-24 08:38
@gportela85  I am not sure. I just want to use flex layout in order to let the grid have the remaining height of the parent container.
```
<div class="flex flex-column height-500px">
    <div class="button-container flex margin-bottom-5px">
         <button>1</button>
         <button>2</button>
         <button>3</button>
     </div>

   <div class="flex-fill">
            <ag-grid-angular></ag-grid-angular>
   </div>

</div>
```
let's say button-container has a height of 20px, using flex,  aggrid will get the remaining height (500px - 20px - 5px (margin-bottom))

**Comment by gportela85** [comment] 2019-01-24 08:44
In that case, your div with `flex:1` should have a limit on how much it's allowed to grow. 
`style="flex: 1; max-width: 100%;`
But i'll take a look at the other examples as well, looks like I have enough info.

**Comment by jiangyh1024** [comment] 2019-01-24 08:46
@gportela85  Thanks a lot

**Comment by makinggoodsoftware** [comment] 2019-01-25 14:44
Hi guys, if you can provide a plunker, we will look into this. I will keep an eye on this thread

**Comment by makinggoodsoftware** [comment] 2019-01-25 14:45
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by gportela85** [comment] 2019-01-25 16:13
@jiangyh1024 To go around this problem we had some properties in the styles before that were not ideal like the normal-layout container set to height: 0 and min-height: 0 which fixed flex-box overflow but broke some item alignments.

One approach here would be to apply `min-height: 0` to your div wrapper. Or even set  it to `overflow: hidden`.

So this: 
```
<div style="flex: 1">
    <ag-grid-angular style="height: 100%; width:100%" *ngIf="gridOptions" class="ag-theme-balham" [gridOptions]="gridOptions">
    </ag-grid-angular>
</div>
```
Should be this: 
```
<div style="flex: 1; min-height: 0">
    <ag-grid-angular style="height: 100%; width:100%" *ngIf="gridOptions" class="ag-theme-balham" [gridOptions]="gridOptions">
    </ag-grid-angular>
</div>
```
or `<div style="flex: 1; overflow: hidden">`

**Comment by jiangyh1024** [comment] 2019-01-25 16:57
thanks for replying.I am ao grateful for your solution

**Comment by makinggoodsoftware** [comment] 2019-01-28 10:51
Hi guys,

This should fix it:

.ag-root-wrapper-body.ag-layout-normal {
    flex: 1;
    height: 0;
    min-height: 0;
}

**Comment by thbiela** [comment] 2019-01-31 10:18
@makinggoodsoftware thanks for your solution. It works in Chrome, but not in Firefox. Any idea about this?

**Comment by makinggoodsoftware** [comment] 2019-02-06 16:07
Hi guys,

This seems to be fixed now, going to close this issue

Thanks

**Closed by makinggoodsoftware** 2019-02-06 16:07 UTC
Labels: ag-grid engaged, in_zendesk

**Comment by cwhaught** [comment] 2019-02-06 16:26
@makinggoodsoftware will this be fixed in AG Grid or will we all have to implement a similar solution to the ones mentioned above?

If so can we get this fix added to the AG Grid repo?

**Comment by nealYangVic** [comment] 2019-02-11 19:56
@makinggoodsoftware Is this fix release yet?

**Comment by marklbarlow** [comment] 2019-02-25 13:07
This still doesn't seem to be fixed in 20.1.0 and unfortunately @makinggoodsoftware 's solution doesn't work for me in Chrome 71 (Angular 7.2.6).

@pako-tech 's solution does work, but would really be good to get this fix applied back in to master.

**Comment by jiangyh1024** [comment] 2019-03-30 02:54
> @makinggoodsoftware thanks for your solution. It works in Chrome, but not in Firefox. Any idea about this?

changing flex: 1 to flex: 1 1 auto

**Comment by shashfrankenstien** [comment] 2023-01-24 19:49
This issue seems to have reappeared in v29.0.0. Not sure if the cause is the same. Works as expected in v28.2.1. Anyone seeing the same issue?
