### ISSUE TITLE
expandAll() on pivot with groupIncludeFooter="true" adds extra row

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1853] opened 2017-08-29 00:10 UTC
Go to this fiddle and click the "Expand All" button:
https://jsfiddle.net/andytaft/8rste6me/6/

As you can see, it adds the total for the "group" and removes values from the group. This behavior is only when "groupIncludeFooter=true".

**Comment by ceolter** [comment] 2017-08-29 13:55
problem appears to be with the grid expanding the lowest level groups when in pivot mode. the lowest level groups we call 'leaf groups', ie groups that contain leafs.

so if you are pivoting and grouping by 'Language' and 'Country', then you should be able to expand language and see country, but you should not be able to expand country to see the child records (as the child records are aggregated into the pivot columns).

the grid [this is the bug] is rendering the leaf groups as expanded when the group is opened. what the grid should do is always render the leaf groups as closed even if they are open (vai the API, or maybe they are open via the UI before the grid was put into pivot mode).

i have this ready to check in, but i'm not going to check it in for todays patch release as it would require full regression (to late in the day to include it). to fix locally, instead of calling 'expand all', you can iterate through all the groups yourself and expand them like this:

```
api.forEachNode( function(rowNode) {
  if (rowNode.group && !rowNode.leafGroup) {
    rowNode.setExpanded(true);
  }
});
```

**Comment by ceolter** [comment] 2017-08-29 14:20
jira is AG-719

**Comment by ataft** [comment] 2017-08-31 22:04
This new code breaks non-pivot grid grouping. For my temporary fix, I've created a variable for "isGridPivoted" and am using that like below:
```
api.forEachNode( function(rowNode) {
    if (rowNode.group && (!isGridPivoted || !rowNode.leafGroup)) {
        rowNode.setExpanded(false);
    }
});

```

**Comment by makinggoodsoftware** [comment] 2017-11-27 16:52
This seems to be working now, (note that the old style is not working but will be fixed in the next release)

https://jsfiddle.net/jmb409q5/

**Closed by makinggoodsoftware** 2017-11-27 16:52 UTC
