### ISSUE TITLE
Console warning when navigating on pinned column via ctrl + arrows

### ISSUE THREAD

**Issue by DerKleineGauss** [ag-grid/ag-grid#4563] opened 2021-07-05 11:46 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Click on a cell of a pinned column within this example: https://www.ag-grid.com/javascript-grid/column-pinning/
- Press ctrl + key_down

**Current behavior**
The console prints the warning 

```
calling ensureIndexVisible on a left pinned column doesn't make sense for column expand
GridPanel.ensureColumnVisible	         @	gridPanel.js?8d57:747
NavigationService.navigateTo	         @	navigationService.js?0ee2:171
NavigationService.onCtrlUpOrDown	 @	navigationService.js?0ee2:190
NavigationService.handlePageScrollingKey @	navigationService.js?0ee2:71
GridPanel.processKeyboardEvent	         @	gridPanel.js?8d57:387
```

**Expected behavior**
No warning

**Please tell us about your environment:**
Windows 10, 
* **AG Grid version:** X.X.X
25.3.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment] 2021-07-14 16:28
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-08-03 11:58
Hello @DerKleineGauss!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5579 When pressing CTRL+LEFT/RIGHT ARROW key to navigate into a pinned column cell, a console warning message is output**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:14
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-09 10:15 UTC
Labels: in_zendesk
