### ISSUE TITLE
[performance] React vertical scroll

### ISSUE THREAD

**Issue by florianJacques** [ag-grid/ag-grid#4341] opened 2021-02-08 15:54 UTC
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Hello,
The vertical scroll seems more efficient when the cursor is placed on a pinned column or when all the columns fit in the window.
As if the cells are rendered asynchronously in these two cases.

Regards

**Please tell us about your environment:**
Chrome, MACOS, React

* **ag-Grid version:** X.X.X
"ag-grid-community": "^25.0.1",
 "ag-grid-react": "^25.0.1"

* **Browser:**
Chrome/88.0.4324.146

Typescript

**Comment by makinggoodsoftware** [comment] 2021-02-09 17:14
Hi,

Would you know how could we test this on our end? I don't see in our docs/demo any big difference.

Thanks

**Comment by florianJacques** [comment] 2021-02-10 12:32
I am preparing an example project during the week, and I will get back to you.

Regards

**Comment by florianJacques** [comment] 2021-02-17 14:26
Hello,
I created a repos on codesandbox, but I don't have the problem.
I don't understand why this problem is real with me :(

**Comment by makinggoodsoftware** [comment] 2021-02-23 16:49
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by florianJacques** [comment] 2021-03-01 09:18
Hi,
Thank you very much for your reply

**Comment by kiril-matev** [comment] 2021-03-05 14:40
Hi Florian,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5137 When using MacOS with Chrome and Firefox, scrolling using the wheel when hovering over the pinned column area causes blank areas when rendering**

You can see the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Please note we will not update this GitHub issue when this bug is fixed in a future version of ag-Grid.

The best way to get an update on this item is to sign up for ag-Grid new release notifications. Once a new ag-Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-03-12 16:21
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-03-12 16:21 UTC
Labels: in_zendesk

**Comment by kiril-matev** [comment] 2021-05-13 10:59
Hi @florianJacques, 

I wanted to give you an update on this.

We took a close look at this whitespace effect. The issue cannot be seen when using any browser on a Windows PC or when using Safari on a Mac. The issue can only be seen on Mac when using Chrome and Firefox browsers. It is caused by the specific way Chrome for Mac and Firefox for Mac implement Animated Frame services. This is why we have rejected this bug.

**You can minimize this whitespace effect by increasing the value of the rowBuffer property (default value is 10).** This allows the grid to render more records before they appear into view and to this have them ready for rendering. See this property documented here:
https://www.ag-grid.com/javascript-grid/dom-virtualisation/#row-virtualisation 

Thank you for reporting this and for letting us clarify how to resolve this!

**Comment by florianJacques** [comment] 2021-06-01 14:57
Thank you for the work!
