### ISSUE TITLE
[RowDrag, Range Selection] rowDrag changes Range Selection while dndSource does not

### ISSUE THREAD

**Issue by githubuser234** [ag-grid/ag-grid#4603] opened 2021-07-28 05:56 UTC
**I'm submitting a ...** 
```
[x] bug report
```
If range selection and rowDrag is enabled, grabbing or clicking on the drag handle, changes the current range selection and the focused cell.
In contrast, activating Drag & Drop (property dndSource), grabbing or clicking the corresponding drag handle does not affect range selection and focused cell.

In this example, the first drag handle is from rowDrag and the second one is from dndSource:

![rowDrag_with_range_selection](https://user-images.githubusercontent.com/83961121/127270945-0464cbc9-2cca-49df-b63d-e724eb1c1981.gif)

**Providing a Reproducible Scenario**
https://plnkr.co/edit/QJbtmMeITUtjjU6Y

**Current behavior**
Clicking on drag handle changes range selection and focused cell.

**Expected behavior**
Clicking on drag handle does not affect range selectin and focused cell (similar to dndSource drag handle).

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:**
Firefox, Chrome

* **OS:**
Windows 10

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:26
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-08-10 12:46
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5604 When the grid has a cell range selected, clicking the drag handle element focuses the cell and clears the selected cell range**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-31 14:42
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-31 14:42 UTC
Labels: in_zendesk, ag-5604

**Comment by kiril-matev** [comment] 2021-09-21 15:39
Hello!



We've discussed this with the product team and this behavior is by design - clicking the drag handle clears the selected cell range.



As this is expected behavior, we've closed this bug as rejected. However, there's a feature request to change this behavior and maintain selected cell ranges as the user clicks the drag handle in a row. This requirement is tracked with:

**AG-4489 [Range Selection] Allow keeping the selected cell range when clicking the row's checkbox (for checkbox selection) or drag handle (for row dragging)**



You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
