### ISSUE TITLE
unable to find bean reference quickFilterService while initialising filterManager. after next build

### ISSUE THREAD

**Issue by hubdncajh** [ag-grid/ag-grid#8063] opened 2024-06-07 15:28 UTC
[#8049 ] again open issue.

**Current behavior**

![image](https://github.com/ag-grid/ag-grid/assets/70308234/095e5ad4-45c2-4188-886b-beab81c65638)
![image](https://github.com/ag-grid/ag-grid/assets/70308234/f7fb7a5d-9401-4a4c-9948-eab007d8ec51)
![image](https://github.com/ag-grid/ag-grid/assets/70308234/5eed1b92-26e4-498e-a767-059a0bfae1c4)

1. yarn next build
2. after next build success, yarn next start
3. first load page in used AG grid. and we can show error that picture.
4. move other page. with next router push.
5. back to the issue page in used AG grid.
6. successful load AG Grid.
7. F5 (refresh). we can show again error.

※ It wasn't happen issue in Develop mode. Only production env with nextjs build

**Expected behavior**

Ref. next.config.js

![image](https://github.com/ag-grid/ag-grid/assets/70308234/cd060dee-8e8d-4590-93d7-ac4f7d27f164)

Try a lot of solution in ag grid git issue ref.  but i can't found to solved method.

**Please tell us about your environment: Window 11, yarn berry

* **AG Grid version:** 31.3.2

* **Browser: Chrome

* **Language: 
- Next : 12.3.4
- React : 18.2.0
- Typescript : 5.1.6

**Comment by djohnsonps** [comment] 2024-06-07 20:36
I am seeing the exact same issue as @hubdncajh and have been trying to solve for 2 days with no luck doing various attempts at fixes.

**Comment by hubdncajh** [comment] 2024-06-10 13:28
i think, it is very critical issue for next developer. 
a lot of try that to solved problem, but I can't have anything result.

**Comment by kwangminn** [comment] 2024-06-13 07:38
I had a exact same issue. I just downgrade to Aggrid 29version. and it works fine

**Comment by AG-Zoheil** [comment] 2024-06-13 11:09
Hi, thank you for your comments.

Are you able to provide a mini-project that would help us reproduce the issue?

Kind regards,
Zoheil

**Comment by hubdncajh** [comment] 2024-06-14 13:17
> Hi, thank you for your comments.
> 
> Are you able to provide a mini-project that would help us reproduce the issue?
> 
> Kind regards, Zoheil

Thanks your response. I was ready to sample next project.
but I can't upload sample because of this zip file 68MB.

so then under the google driver link.

https://drive.google.com/file/d/1XTrnEqLVXS97TDBvwoC7rCZAUIk2uW5q/view?usp=sharing

1. require node version 18
2. require yarn
3. If ready to step 1 and 2, enter the command "yarn" in sample project folder
4. you can show two version. under the command
   4-1. "yarn dev"   => this is next dev mode 
   4-2. before "yarn start", must be "yarn build"  => this is next production mode
5. If you done step 4, enter the address in browser that "localhost:3000"
6. you can find error msg in console log at production mode.

**Comment by hubdncajh** [comment] 2024-06-14 13:25
> I had a exact same issue. I just downgrade to Aggrid 29version. and it works fine (Same env, version with you as well)

Thanks you for me. 
I was try your advice. and solved build issue that addEventListener.
but i can't use resize effect and header style is broken.

I think that Only AGGrid Develop Team can solve this problem.  because we can't access library source file.

**Comment by sabahang** [comment] 2024-06-17 13:51
@hubdncajh when running `npm start` we are unfortunately not able to run your project with following error:
![image](https://github.com/ag-grid/ag-grid/assets/2657540/7b081e1a-66b6-476d-bf90-82195daa19fe)

Please provide us with a minimal reproducible sample that we can run locally

**Comment by hubdncajh** [comment] 2024-06-20 06:05
> @hubdncajh when running `npm start` we are unfortunately not able to run your project with following error: ![image](https://private-user-images.githubusercontent.com/2657540/340328880-7b081e1a-66b6-476d-bf90-82195daa19fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjI5OTIsIm5iZiI6MTcxODg2MjY5MiwicGF0aCI6Ii8yNjU3NTQwLzM0MDMyODg4MC03YjA4MWUxYS02NmI2LTQ3NmQtYmY5MC04MjE5NWRhYTE5ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMDU1MTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQwMDQ5MDRhYzhmNTdjOTdlZjVhZWYwMWQ2YWRiNTEyMjQ1NTczYTg5MGJjZWE4YTE0OGRhMDE0NDNhMDA2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5CDIKlQYLnIwUOB2oRnTW9akxBcOxTvIxOkyMY0h8U0)
> 
> Please provide us with a minimal reproducible sample that we can run locally

This project not support npm because of base to yarn. 

1. Install node 18
2. Enter the command "npm install -g yarn" in your terminal
3. In terminal, you have to change the locate path to downloaded sample project's folder
4. Enter the command "yarn".  If you put command "npm", we will see error message again .
5. Finally last command is "yarn dev" or "yarn start"

**Comment by hubdncajh** [comment] 2024-06-24 09:31
Umm... could you tell me the prgress?

**Comment by hubdncajh** [comment] 2024-06-29 08:28
anything else? something to help you

**Comment by sabahang** [comment] 2024-07-18 09:55
@hubdncajh I've just managed to run your project locally and if you upgrade to version 32 the issue is gone. Given that the issue only occurs in production and not dev mode suggests that something in your build configuration might have cause it. But regardless upgrading to version 32 seems to resolve the issue.

Hope this helps. I'm going to close the issue but if the issue is not resolved by an upgrade feel free to get back to us

**Closed by sabahang** 2024-07-18 09:55 UTC
Labels: waiting-for-repro
