### ISSUE TITLE
[scroll] Scroll seems strange with latest update

### ISSUE THREAD

**Issue by scotthovestadt** [ag-grid/ag-grid#413] opened 2015-09-01 19:25 UTC
I think it's related to the pinned column scroll feature. If I scroll, sometimes the scroll leaves the viewport I'm scrolling in and will scroll the entire page.

**Comment by ceolter** [comment] 2015-09-01 21:54
More information needed!!! Can you describe better please?

My experience is that if on non-pinned, after the current div has scrolled all the way, then the page will scroll. This is default browser behaviour.

On the pinned section, I consume the scroll event, so it doesn't get to the browser, so doesn't happen when on the pinned section.

Which section are you talking about, pinned or not pinned?

**Comment by scotthovestadt** [comment] 2015-09-01 22:30
My experience on mac is that the scroll will fail to be elastic (as in it won't keep scrolling naturally) and if I try to scroll rapidly the window scrolls before I can even get close to the bottom of the grid. This happens on the main page of the demo site.

**Comment by scotthovestadt** [comment] 2015-09-01 22:32
If I mouse over the grid on the angulargrid.com site main page, and use my Mac trackpad to scroll down rapidly, it immediately scrolls the entire window down. I'm unable to quickly scroll the grid.

**Comment by scotthovestadt** [comment] 2015-09-01 22:34
I don't think you're going to get natural scrolling that looks and behaves naturally in all environments unless you implement a solution that allows the grid to scroll naturally without manipulating CSS.

I think the DOM will need to look something like this:
![image](https://cloud.githubusercontent.com/assets/1831484/9618843/e0e961b0-50be-11e5-8c96-ccea74445bdd.png)

**Comment by ceolter** [comment] 2015-09-02 08:19
@scotthovestadt what you say looks interesting and may be true, but i don't have the time to invest in this at the moment. sorry :(

btw - i'm not a mac user, and in my work (banking), all our users are on PC's, so difficult for me to test (no macs around) and little gain for me to be had.

**Comment by S-YOU** [comment] 2015-09-03 09:44
just fyi, i cannot reproduce this in my mac with normal mouse or magic mouse. scroll not very fast but it keep scroll inside div not the whole window.

**Comment by maroy1986** [comment] 2016-09-14 19:36
Is there any advancement on this? We got a similar issue here using the virtual rowModelType specifically on IE11 (yes 💩 ). When scrolling, the pinned columns and the other free columns get constantly desync between them when scrolling fast, to finally get back together. On other browsers it works fine, only IE is an issue.

Are you planning some performance improvement for IE or this is just something we can put in the category "Won't fix" ?

**Comment by ceolter** [comment] 2016-09-15 11:17
@maroy1986 not that we won't fix. we are constantly fixing items and adding features. it's possible it never gets to the top of the list.

**Comment by maroy1986** [comment] 2016-09-15 12:40
@ceolter Thanks for the follow up. I understand it's not a top priority to support a near end-of-life browser. That said, Microsoft Edge also have the same issue, which I found it to be weird...

Keep up the good work you grid is awesome 👍

**Comment by ceolter** [comment] 2017-01-17 16:17
is this still an issue with the latest ag-grid?

**Comment by ceolter** [comment] 2017-01-23 14:41
tracked by https://ag-grid.atlassian.net/browse/AG-64

**Comment by makinggoodsoftware** [comment] 2017-12-19 09:18
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Closed by makinggoodsoftware** 2017-12-19 09:18 UTC
Labels: enhancement
