### ISSUE TITLE
After refreshing columnDefs, excelMode does not work properly

### ISSUE THREAD

**Issue by leey0818** [ag-grid/ag-grid#8056] opened 2024-06-06 12:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/tQrGwcrNlbSZhKIZ?open=main.ts&preview

After refreshing the columnDefs, the excelMode functionality does not work properly, and the buttons also do not function correctly.

**Expected behavior**
Even after refreshing the columnDefs, excelMode should still be applied.

**Please tell us about your environment:**

* **AG Grid version:** 31.3.2

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

* **Language:** ES6

**Comment by sabahang** [comment] 2024-06-14 11:01
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-11878 [SetFilter] ExcelMode does not work properly after refreshing columnDefs via API**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed by sabahang** 2024-06-14 11:01 UTC
