### ISSUE TITLE
The header row wobbles and flickers and doing horizontal scrolling with large amount of columns

### ISSUE THREAD

**Issue by an-account-to-search-github** [ag-grid/ag-grid#7620] opened 2024-02-16 10:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
Not a costumer

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Using ag-grid in a react app, I am using the code below

```
import { AgGridReact } from 'ag-grid-react'; // React Grid Logic
import "ag-grid-community/styles/ag-grid.css"; // Core CSS
import "ag-grid-community/styles/ag-theme-alpine.css"; // Theme
import { useState } from 'react';


function App() {
  // Row Data: The data to be displayed.
  // eslint-disable-next-line
  const [rowData, setRowData] = useState([
    { make: "Tesla", model: "Model Y", price: 64950, electric: true, electric2: true , electric22: true , electric223: true,
    electric2234: true, electric2235: true, electric2236: true, electric2237: true
  },
    { make: "Ford", model: "F-Series", price: 33850, electric: false , electric2: true , electric22: true , electric223: true,
    electric2234: true, electric2235: true, electric2236: true, electric2237: true},
    { make: "Toyota", model: "Corolla", price: 29600, electric: false, electric2: true , electric22: true , electric223: true,
    electric2234: true, electric2235: true, electric2236: true, electric2237: true },
  ]);
  
  // Column Definitions: Defines & controls grid columns.
  // eslint-disable-next-line
  const [colDefs, setColDefs] = useState([
    { field: "make", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "model", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "price" , headerClass: ['age-border'], cellClass: ['age-border'],},
    { field: "electric2", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "electric22", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "electric223" , headerClass: ['age-border'], cellClass: ['age-border'],},
    { field: "electric2234", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "electric2235", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "electric2236", headerClass: ['age-border'], cellClass: ['age-border'], },
    { field: "electric2237", headerClass: ['age-border'], cellClass: ['age-border'], },
  ]);

  // ...

  return (
    // Container
    // Container with theme & dimensions
  <div className="ag-theme-alpine" style={{ height: 1000 }}
  
  onWheel={(ev) => {
    console.log(ev);

   document
    ?.querySelector('.ag-body-viewport')
    ?.addEventListener('wheel', preventScroll2, {
        passive: false,
    });

    const button = document.getElementById('slide');

    button.onclick = () => {
      const ele2 =  document
      ?.querySelector('.ag-body-viewport');
      console.log("TEST",ele2);
    }

    function preventScroll2(e) {
        console.log('HELLO', e);
        return false;
    }
}}>
    <p>Hello</p>
    <button id="slide" type="button">
                Slide right
            </button>
    <AgGridReact rowData={rowData} columnDefs={colDefs} />
  </div>
  )
}

export default App;
```

This gives me 'wobbling' in the header row as can be seen in attached video

https://github.com/ag-grid/ag-grid/assets/160227476/96c6beff-cc90-4ced-a488-0725ee1e810e

If reporting a bug make sure to state.

**Current behavior**
Header flickers, maybe because of too many document queries?

**Expected behavior**
Header row should not flicker

**Please tell us about your environment:**
MacOS Sonoma 14.3.1

* **AG Grid version:** X.X.X
"ag-grid-react": "^31.0.3"

* **Browser:**
Chrome 121.0.6167.160

* **Language:** 
Javascript

**Comment by AG-Zoheil** [comment] 2024-02-16 10:55
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment] 2024-02-19 15:08
Hello,

Thank you for providing the example.

I haven't been able to reproduce this on my machine. However we've had a look at your plunker and can see this would be caused by the excessive logging.
Can we ask if this configuration is being used in a production environment or if this is just something in your dev environment? We would naturally recommend an approach that would only log events that are essential as excessive logging would impact performance on older/slower devices.

Looking forward to hearing back from you.

**Comment by an-account-to-search-github** [comment] 2024-02-20 04:33
@AG-Zoheil in production environment we have many calls running in the background, so to simulate that I have used these loggings. The main crux of the issue is that the header row should not flicker and should stay with all the other rows no matter how much processing is happening in the background, to reproduce you can also try running a screen recorder as it pushes some more pressure on the machine that helps in reproducing

**Comment by AG-Zoheil** [comment] 2024-02-20 09:57
Hello,

Thank you for getting back.

We agree there would be value in us investigating this further and looking to see if there are any performance improvements that can be done. Hence we have added this requirement to our backlog and we are tracking it with the following reference: **AG-10757**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-02-20 09:57 UTC
Labels: AG-10757

**Comment by rui-reevo** [comment] 2024-11-04 05:52
Also run into this issue, my use case is just basic one, using infinite row model with 20 columns. There's a visible flickers when scroll horizontally with or without column virtualisation, as shown in the code: https://stackblitz.com/edit/stackblitz-starters-dv9ve6?file=app%2Fservices%2FexampleDataService.ts


https://github.com/user-attachments/assets/ed1347dd-8b2e-4ded-8001-ce2390333f52
