### ISSUE TITLE
Text filter popup appears at odd position 

### ISSUE THREAD

**Issue by pycraft114** [ag-grid/ag-grid#2005] opened 2017-10-25 10:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[ v ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

<img width="1440" alt="2017-10-25 3 58 46" src="https://user-images.githubusercontent.com/24728657/31995191-64e81910-b9be-11e7-8d69-ed8c5875c274.png">

The top row ( right under the blue button ) is a column header and under that , pinned row takes place. As you can see above, the text filter popup appears at odd position

**Expected behavior**

Expecting position would be right below the column header or the Burger Menu Icon.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by petyosi** [comment] 2017-10-30 10:32
Hey, 

can you replicate the issue in a plunker?

**Comment by rmc-software** [comment] 2017-11-03 10:47
Closing issue for now as we can't reproduce it.

**Closed by rmc-software** 2017-11-03 10:47 UTC
