### ISSUE TITLE
Regression from v31.3.1 -> v31.3.2: Two grids on one page cross-contaminate data 

### ISSUE THREAD

**Issue by jm-pando** [ag-grid/ag-grid#8018] opened 2024-05-29 01:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
**Description*
I have two grids on the same page, and when getting initial data, the rowData assigned to one grid is bound to other one. I have tried using the gridReady event and the onMounted hook and can't get the data to reliably bind to the grid it's assigned to.

I'm using Vue 3. This appears to work correctly with Ag-grid 31.3.1, but does not work consistently in v31.3.2.

Example: (you may need to refresh a few times to see it).
https://codesandbox.io/p/sandbox/ag-grid-vue-3-example-forked-rjqyws

**Current behavior**
With two grids on the same page with different data. the data bound to one grid shows up in the other (wrong) grid.

**Expected behavior**
Two grids on the same page with different data. I expect the the data bound to :rowData to be shown in the grid.

**Please tell us about your environment:**
Tested on Chrome, Firefox, and Edge
Can be reproduced locally (Vite, npm run dev) or in production using a GCP loadbalancer and bucket.
Windows 11, VS Code

* **AG Grid version:** 31.3.2 ONLY!

* **Browser:**
Reproduced on Chrome, Firefox, and Edge

* **Language:** Javascript

**Comment by zwik** [comment] 2024-05-30 13:54
Can confirm. we have the same issue.

**Comment by okueng** [comment] 2024-05-31 07:34
I have the same issue! 

I think it is similar to AG-11657 [Regression] When using multiple grids in Vue rows do not render
in the [pipeline](https://www.ag-grid.com/pipeline/)

**Comment by ThuanLCSE** [comment] 2024-06-03 09:36
I get the same issue. column-defs and row-data is shared across multiples grids in the same page.
I think it is due to a event emitter between grids.
Thank @jm-pando , I'm down grading to 31.3.1.

**Comment by 94ostry** [comment] 2024-06-04 12:29
I get the same issue.

**Comment by DaKar00** [comment] 2024-06-10 17:36
I have the same issue, its the onMounted event that creates this issue, if i choose to load data with a butten press i can successfully load different data into different grids but when i load data after onMounted it wont work

**Comment by qq1031824970** [comment] 2024-06-17 03:33
我也遇到了相同的问题
I get the same issue.

**Comment by AG-Zoheil** [comment] 2024-06-17 14:42
Hello 

Thank you for reporting this - much appreciated!

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11657**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-06-17 14:42 UTC
Labels: AG-11657

**Comment by DaKar00** [comment] 2024-06-17 15:30
While you wait for the bug fix you can use a separate function to load the data into separate grids (like a button press, update grid 1 / update grid 2), in my case it works, just not when using onMounted() fetch(), I'm gonna try to use the fetch().then( fetch() ) to get the first set of data then the next set of data and load them into the grid.
