### ISSUE TITLE
Grid crashes when using `cellRendererFramework` / `cellEditorFramework`, `editType='fullRow'` and `stopEditingWhenCellsLoseFocus=true`

### ISSUE THREAD

**Issue by vmuresanu** [ag-grid/ag-grid#5314] opened 2022-06-28 09:20 UTC
**I'm submitting a bug**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
Grid crashes when using `cellRendererFramework` / `cellEditorFramework`, `editType='fullRow'` and `stopEditingWhenCellsLoseFocus=true`

**Providing a Reproducible Scenario**

1. Use cellRendererFramework, cellEditorFramework for components
2. Set editType='fullRow' in order to update the whole row
3. Set stopEditingWhenCellsLoseFocus=true in order to close edit mode once the user is done updating the rows. 
4. Click on first row and edit a cell
5. Immediately after cell modification, click on another row

**Stackblitz example with error reproduction**
https://stackblitz.com/edit/angular-ivy-rvu5aa?file=src/app/app.component.ts

**Gif summarizing the bug**
![ag-grid-fullrow-bug](https://user-images.githubusercontent.com/26407402/176140472-fc86b906-3c09-4943-bdff-f94907b3f2f5.gif)

**Current behavior**
Grid crashed and there are errors in the console

**Expected behavior**
User proceeds with updating the next row without problems

**Notes**
1. Tested without editType='fullRow' and works as expected
2. Tested without stopEditingWhenCellsLoseFocus and works as expected
3. Tested with default cellRenderer and cellEditor (but with both editType='fullRow' and stopEditingWhenCellsLoseFocus) and works as expected
4. If click outside the grid, works as expected

**Please tell us about your environment:**
AG Grid version 27.3.0:
Angular version 14.0.3 (reproducible also in 13.1.0)

* **Browser:**
 Chrome Version 103.0.5060.53 (Official Build) (64-bit)

* **Language:** Typescript: 4.5.4

**Comment by kiril-matev** [comment] 2022-07-19 17:35
Hello @vmuresanu!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7003 [Regression] When using cell editor components, setting editType=fullRow and stopEditingWhenCellsLoseFocus=true editing a cell doesn't focus it and ending the edit throws a console exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by seanlandsman** [comment] 2022-08-03 12:02
Hi,

Version 28.1.0 have AG-Grid has been released, which includes a fix for this issue.

Thank you for reporting this.

**Closed by seanlandsman** 2022-08-03 12:02 UTC
Labels: in_zendesk, ag-7003
