### ISSUE TITLE
Status bar displays incorrect quantity of selected rows

### ISSUE THREAD

**Issue by daryakalenik** [ag-grid/ag-grid#6370] opened 2023-03-23 13:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. Open URL: https://plnkr.co/edit/QFPJeUAeElno5aqg?open=app%2Fapp.component.ts&preview
2. Click on rows - on the status bar you'll see the number of selected rows

**Current behavior**
Even though rowSelection is set to 'single', status bar displays multiple selected rows

**Expected behavior**
Expect Selected on status bar to be 1 if rowSelection is set to single

Angular 15,
Windows 10 (but it also work the same way on macOs)

AG Grid version: 29.2.0

Browser:
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

**Comment by AndrewGlazier** [comment] 2023-03-23 14:43
Hello,
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-8232 - Status bar selection count is incorrect
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-8232) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

**Closed by AndrewGlazier** 2023-03-23 14:43 UTC
