### ISSUE TITLE
ag grid freeze when switch to other page

### ISSUE THREAD

**Issue by Alkimay** [ag-grid/ag-grid#6328] opened 2023-03-15 20:27 UTC
![image](https://user-images.githubusercontent.com/96352572/225433982-78f74347-7d1b-4afc-8fb3-fba96e619ffe.png)

hello, i found a bug that is very weird in my app and then i checked your demo here
https://www.ag-grid.com/example

if you filter the Language search text by somthing and then you click documantation (or any other tab that switch the screen) 

the screen is freezing.

in Name field it is working fine../

please fix it really hold me back

**Comment by kiril-matev** [comment] 2023-03-15 20:54
Hello @Alkimay,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8075 [Regression] When using floating filters, opening a column set filter and hiding the grid causes the page to become unresponsive**

This bug will be fixed in our next release which is scheduled for March 23rd.

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in the next version of AG Grid. Please sign up for AG Grid new release notifications. 

Thanks again for bringing this up with us - we appreciate your time!

**Comment by Alkimay** [comment] 2023-03-15 21:02
Hey thanks for the quick response, it happend on text columns aswell not just on floating filters. so please check it for all filtering:)

**Comment by rmatesicZavy** [comment] 2023-03-16 04:15
Not sure if this is related to the same bug we are also experiencing this.

We have a reports feature and notice this freezing when we jump from one report to another. 
I have turned on the debug mode on and notice that this occurs around the unmount of the first report as the second report on another page never mounts.

This is a snipper of the log at the time when it hangs. The process in chrome gets to 100% CPI
 
<img width="1126" alt="Screen Shot 2023-03-16 at 3 14 28 pm" src="https://user-images.githubusercontent.com/77592132/225512703-e5c57693-dff1-467d-af62-af7514613a78.png">

I am using these packages for my application.
      
      ag-grid-community": "29.1.0"
      ag-grid-enterprise": "29.1.0"
      ag-grid-react": "29.1.0"
      
 Tested on Chrome Version 111.0.5563.64 (Official Build) (arm64)
 And Firefox 110.0.1 (64bit)

**Comment by Alkimay** [comment] 2023-03-16 04:54
yep somthimes unmounting ag-grid  component  causing to 100% cpu and crash like in the picture i send here. please Handle it.

**Comment by kiril-matev** [comment] 2023-03-16 09:28
Hello @Alkimay,

You are correct - any scenario where a column filter is used - floating/non-floating, text/number/set filter has this issue when unmounting the component.

I can confirm that all these scenarios are covered by the fix for this issue in **AG-8075**.

This bug will be fixed in our next release which is scheduled for March 23rd.
https://www.ag-grid.com/pipeline/?searchQuery=8075

**Comment by StephenCooper** [comment] 2023-03-21 10:50
Please upgrade to 29.2 which was released today and contains the fix for this issue.

**Closed by StephenCooper** 2023-03-21 10:50 UTC
Labels: AG-8075
