### ISSUE TITLE
rowGrouping affect paste operation in ag-grid

### ISSUE THREAD

**Issue by abdelrhman1410** [ag-grid/ag-grid#4309] opened 2021-01-20 14:09 UTC
Hi there!

I'm working on an Angular project that uses ag-grid, I'm trying to use copy & paste features over a column or multiple columns that are separated horizontally by the rows grouping separator 

As in the pictures below [[[open the URL attached]]], I copied the values [1, 2, 3]
Then I pasted them while a separator was in between

Pictures URL: 
 -- copy: https://drive.google.com/file/d/17_MofDLiZtXBZT_RLFtN149A4WuRoG19/view?usp=sharing
 -- paste: https://drive.google.com/file/d/1dAlei6zYT8b04z9P9BIgLt4umvv0lkOT/view?usp=sharing

* What I'm expecting:
 -- 1 pasted in the cell above the separator, 2, 3 shifted and pasted avoiding the separator cell

* What actually happened:
 -- 1 pasted in the cell above the separator, 2 vanishes due to separator cell, 3  pasted after the separator cell

* Angular and ag-grid versions
 -- Angular Version: Angular CLI: 8.0.6

 -- "ag-grid-angular": "^23.0.0",
 -- "ag-grid-community": "^23.0.0",

**Comment by abdelrhman1410** [comment] 2021-01-25 10:34
@makinggoodsoftware 

Could you please explain what this label means?

**Comment by makinggoodsoftware** [comment] 2021-02-03 16:51
Hi @abdelrhman1410 

Should have given you more insight! This works as intended, but it could be potentially workaround using our APIs, for this cases, we flag this tickets as managed-by-community so hopefully someone can help you

Note that we don't have the capacity to offer support on github.

Apologies for not giving you more insightght

**Comment by makinggoodsoftware** [comment] 2021-02-23 16:41
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks

**Closed by makinggoodsoftware** 2021-02-23 16:41 UTC
Labels: managed-by-community
