### ISSUE TITLE
`postProcessPopup` is being triggered multiple times, and resetting left and top styles

### ISSUE THREAD

**Issue by JPlumridge** [ag-grid/ag-grid#5876] opened 2022-12-12 12:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

## Plunker

Forked from example found on this page https://www.ag-grid.com/react-data-grid/column-menu/#repositioning-the-popup

Column "Country" has been set up to demonstrate the issue with the `left` style.
Column "Gold" has not been modified over the example in documentation, and shows a similar issue occurring with `top` style.

https://plnkr.co/edit/iuNqf9kNL2iCP8J5?open=index.jsx

**Current behavior**

Bug.

With the latest version of AG Grid React (`28.2.1`), the `postProcessPopup` callback is being triggered at least twice per popup, and is causing the `left` and `top` style to be reset. e.g. if `left` or `top` style is set in the callback, it effectively gets ignored.

This can be seen in an example plunkr on this documentation page, without any modification: https://www.ag-grid.com/react-data-grid/column-menu/#repositioning-the-popup

This causes the popup to appear in the correct position, then jump to a different position.
In my testing the `right` property is not affected, I am guessing because it's not styled by the default positioning, so is not getting reset.

**Expected behavior**

`postProcessPopup` should allow positioning styles to be set, and not modify them after this, to allow the popup to be positioned dynamically.

**Please tell us about your environment:**

* **AG Grid version:** 28.2.1

* **Browser:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

* **Language:** [all]

# Workaround

For anyone also encountering this, here's a workaround that works for me. It's not pretty but it solves it for now.

I wanted to position the popup by 'right', and setting`left` to empty/auto.
To ignore the `left` value while this bug exists:

1. Create a css class and use `!important` to set the 'left' property you want to `auto`
2. Assign this class to the popup element in your `postProcessPopup` callback.

```
.ag-theme-balham .ag-popup-child.ignores-left-position {
    left: auto !important;
}
```

```
const popupElement = params.ePopup;
popupElement.classList.add('ignores-left-position');
```

**Comment by kiril-matev** [comment] 2022-12-15 10:19
Hello @JPlumridge,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7682 When opening a popup, postProcessPopup callback gets overridden and popup gets returned to original position**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-12-15 11:13 UTC
Labels: in_review
