### ISSUE TITLE
AgGrid Rich Select Dropdown Requires Multiple Clicks to Open with Async Object Values

### ISSUE THREAD

**Issue by maitlandmarshall** [ag-grid/ag-grid#8382] opened 2024-07-23 07:33 UTC
**I'm submitting a ...**
[x] bug report

**Current behavior**
When using async values for an AgGrid rich select, the dropdown needs to be double-clicked multiple times for the list of items to show. This issue only occurs when the lookup displays the "loading..." message, which happens if the values getter takes a second or more to resolve.
![image](https://github.com/user-attachments/assets/b528f219-f392-41d9-8a9b-cd31b678fffc)
![image](https://github.com/user-attachments/assets/237c216e-e37f-454b-9f9a-8907eebe8d1c)
![image](https://github.com/user-attachments/assets/6579e3ef-3d48-4751-9a90-779d44cf6d49)

https://github.com/user-attachments/assets/5ccd5d89-4eb3-4412-a0ac-5b045254f8fa

**Expected behavior**
The dropdown should open and display the list of items with a single click, even when the values are loaded asynchronously and the "loading..." message is shown.

**Please tell us about your environment:**
* **AG Grid version:** 32.0.2
* **Browser:** Edge Version 126.0.2592.113 (Official build) (64-bit)
* **Language:** TypeScript/JavaScript + Vue

**Reproducible Scenario**
A CodeSandbox has been provided to demonstrate the issue: https://codesandbox.io/p/sandbox/aggrid-rich-cell-editor-async-values-display-issue-rnfh3p

The issue can be reproduced using the following column definition:

```typescript
const columnDefs: ColDef[] = [
  {
    field: "gender",
    headerName: "Provided Rich Select",
    cellRenderer: GenderRenderer,
    cellEditor: "agRichSelectCellEditor",
    keyCreator: (params) => {
      console.log(params);
      return params.value.type;
    },
    cellEditorParams: {
      cellRenderer: GenderRenderer,
      values: async () => {
        await new Promise((res) => {
          setTimeout(res, 1000);
        });

        return [
          {
            type: "Male"
          },
          {
            type: "Female"
          }
        ];
      },
      allowTyping: true,
      filterList: true,
      highlightMatch: true
    }
  }
];
```

Steps to reproduce:
1. Set up an AG Grid with the provided column definition.
2. Click on a cell in the "Provided Rich Select" column to enter edit mode.
3. Attempt to open the dropdown by clicking on the dropdown arrow.
4. Observe that the dropdown doesn't open on the first click and requires multiple clicks to display the list of items.

Additional notes:
- The issue is specifically related to the async nature of the `values` function in `cellEditorParams`.
- The problem occurs when the `values` function takes some time to resolve (simulated with a 1-second delay in the provided code).
- Works correctly if the values function returns a list of primitives, only occurs if the values function returns a list of objects.

**Comment by jotting** [comment] 2024-07-26 18:01
I've noticed that this occurs if the cell's value doesn't exist in the values returned from the `values` Promise.

i.e. if the cell value is "English" and the `values` Promise returns: `["French", "English", "Spanish"]`, then it will render correctly.

However if the cell value is not set or is "Japanese", then it will render incorrectly like in this issue.

I have edited the "Async Values" example codesandbox to demonstrate:
https://codesandbox.io/s/rich-select-async-values-forked-g45j2m

**Comment by thebadking** [comment] 2024-07-31 00:50
`import React from 'react';
interface Option {
  label: string;
  value: string;
}

const optionList: Option[] = [
  { label: '', value: '' },
  { label: 'Option 1', value: 'option1' },
  { label: 'Option 2', value: 'option2' },
  { label: 'Option 3', value: 'option3' },
  { label: 'Option 4', value: 'option4' }
];

interface SelectCellImplementedProps {
  setValue?: (value: string) => void;
  value?: string;
  onChange?: (value: string) => void;
}

const SelectCellImplemented: React.FC<SelectCellImplementedProps> = ({
  setValue,
  value,
  onChange
}) => {
  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const newValue = event.target.value;
    if (setValue) {
      setValue(newValue);
    }
    if (onChange) {
      onChange(newValue);
    }
  };

  return (
    <select value={value} onChange={handleChange}>
      {optionList.map((option, index) => (
        <option key={index} value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
};

export default SelectCellImplemented;
`


I have created this custom cell renderer that performs correctly, just needs styling to match your table design,  the issue is that i couldn't access the cellEditorParams from the cell renderer that you can use when using agSelectCellEditor on the cellEditor, if someone can finish that, in my use-case I can create a couple of cell renders because its always the same options.  I've only used AGGrid for a couple of days and I was trying to enrich the cell value, use an object instead of a string,  setting the cellDataType: to 'object' as mentioned in the documentation didn't help, or I did something wrong. if someone can point me to the right direction would be great

**Comment by ava-utting** [comment] 2024-08-14 11:41
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-12585 When using Rich Select Cell Editor, opening the dropdown requires multiple clicks to open with async values**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Ava

**Closed** 2024-08-14 11:50 UTC
Labels: AG-12585
