### ISSUE TITLE
cellRenderer is not working with React 18 new root API

### ISSUE THREAD

**Issue by juhahinkula** [ag-grid/ag-grid#4850] opened 2021-12-27 13:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
cellRenderer / cellRendererFramework renders empty cell when using React 18 RC and new root API. It works when using old root API.

Here is simple test code: https://github.com/juhahinkula/gridtest.git
The button is not rendered but if you switch to old Root API, it is working. It is working with new Root API if you remove strict mode.

New root API means (Not working):
```
const container = document.getElementById('root');
const root = ReactDOM.createRoot(container);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
And old means (working):
```
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```
Here are my column definitions
```
  const columns = [
    {field: 'brand', filter: true, sortable: true},
    {field: 'model', filter: true, sortable: true},
    {
      headerName: '',
      field: 'id',
      sortable: false,
      filter: false,
      width: 100,
      cellRendererFramework: 
        params => 
          <button onClick={() => onDelClick(params.value)}>
             Delete
          </button>
    }  
  ];
```
The button is rendered to cell when using React 18 RC and old root API but it won't be rendered when using React's new root API. The cell is empty but there is no any errors in the console.

Operating system: Windows 10
IDE: VSCode
package manager: npm 
**AG Grid version**    
"ag-grid-community": "^26.2.1",
 "ag-grid-react": "^26.2.0",
 
**Browser** Chrome & Firefox

**Language** Javascript ES6 (React 18 Release Candidate 0)

**Comment by juhahinkula** [comment] 2021-12-27 13:34
Just found out that the button is rendered if you remove <React.StrictMode> from the render in the new Root API.

**Comment by makinggoodsoftware** [comment] 2022-01-11 16:38
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-20 16:05
Hello @juhahinkula!

Thank you for bringing this up with us. 

At this time React 18 is unreleased software and as such subject to change. AG Grid will support React 18 and in order to fully investigate the rendering of AG Grid with React 18 once it is released we have added a task in our backlog. 

You can track it with this reference:
**AG-6266 [React] Investigate AG Grid ReactUI rendering when using React 18**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:34
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:34 UTC
Labels: in_zendesk

**Comment by skalidindi** [comment] 2022-04-14 06:44
React 18 is now released now and there has still been no progress on AG-6266 [React].

**Comment by kiril-matev** [comment] 2022-04-20 10:10
Hello!

We've looked into this again and found this is an issue with React 18 Strict mode when running in development mode.

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6663 When using React 18 with StrictMode in development mode an exception is thrown**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
