### ISSUE TITLE
Writing React filter components using functions and hooks instead of classes

### ISSUE THREAD

**Issue by mvasin** [ag-grid/ag-grid#3008] opened 2019-03-13 17:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
I am able to create React filter components for infinite row model (server side filtering); in a React class component along with regular React lifecycle methods I put instance methods `getModel`, `setModel`, `isFilterActive` and it works just fine.

Now I'd love to figure out how can I write server side filters using functional components and hooks instead of  class components. I'm not sure how do I attach `getModel`, `setModel`, `isFilterActive` to a functional component and if ag-Grid will be able to read/write filter state. A hint would be greatly appreciated.

* **Language:** TypeScript 3.3

**Comment by mvasin** [comment] 2019-03-14 06:43
The very first problem I bump into when I try to render a React **function** component as an ag-Grid filter is the fact it's not rendered at all: plain `() => <p>"hello world"</p>` isn't visible except a small weird dot, and I have this warning in the console:
```
Function components cannot be given refs. Attempts to access this ref will fail.
Did you mean to use React.forwardRef()?
```

**Comment by seanlandsman** [comment] 2019-03-19 09:28
@mvasin functional components will be supported in our next release, due this week

**Comment by makinggoodsoftware** [comment] 2019-03-25 11:49
Hi 20.2 has been released including this improvements

**Closed by makinggoodsoftware** 2019-03-25 11:49 UTC

**Comment by deanp70** [comment] 2020-05-30 19:13
Hi, thanks for creating this awesome software. I'm trying to create a custom filter which is connected to redux. I can make the filter work properly (i.e. filter the row data as intended) but can't manage to get ag-grid to recognize `getModel, setModel, isFilterActive`.

Are there any working examples for a connected filter I can refer to? Thanks!
