### ISSUE TITLE
`api.setCacheBlockSize` can only be called when `gridOptions.rowModelType` is `serverSide`

### ISSUE THREAD

**Issue by Bugophobia** [ag-grid/ag-grid#6022] opened 2023-01-17 14:52 UTC
```
[x] bug report
[] feature request
[] support request
```

# Introduction

When trying to change the pagination size dynamically, this error is thrown by Ag Grid:
![error](https://user-images.githubusercontent.com/59090546/212920224-442533c4-d6c8-40ca-8972-76363fb1c673.png)

The issue https://github.com/ag-grid/ag-grid/issues/2413 is related.

# Reproducible scenario

```js
import * as agGrid from 'ag-grid-community';

document.addEventListener('DOMContentLoaded', () =>
{
	const data = [
		{
			id: 1,
			name: 'A'
		},
		{
			id: 2,
			name: 'B'
		},
		{
			id: 3,
			name: 'C'
		},
		{
			id: 4,
			name: 'D'
		},
		{
			id: 5,
			name: 'E'
		}
	];

	const div = document.createElement('div');
	div.className = 'ag-theme-alpine-dark';

	const paginationSelect = document.createElement('select');
	paginationSelect.append(
		new Option(2, 2, true, true),
		new Option(4, 4, false, false)
	);

	document.body.append(
		paginationSelect,
		div
	);

	new agGrid.Grid(div, {
		rowModelType: 'infinite',
		domLayout: 'autoHeight',
		pagination: true,
		paginationPageSize: paginationSelect.value,
		cacheBlockSize: paginationSelect.value,
		defaultColDef:
		{
			minWidth: 100,
			flex: 1
		},
		columnDefs: [
			{
				field: 'id'
			},
			{
				field: 'name'
			}
		],
		datasource:
		{
			getRows: (params) =>
			{
				console.log(`Datasource called (start row: ${params.startRow}, end row: ${params.endRow})`);
				params.successCallback(data.slice(params.startRow, params.endRow), data.length);
			}
		},
		onGridReady: (event) =>
		{
			paginationSelect.addEventListener('change', () =>
			{
				event.api.setCacheBlockSize(paginationSelect.value);
				event.api.paginationSetPageSize(paginationSelect.value);
				event.api.refreshInfiniteCache();
			});
		}
	});
});
```

# Current behavior

With `rowModelType` defined as `infinite`, we are not able to change the `cacheBlockSize` property (e.g. by a dropdown allowing to select the pagination size). Therefore, the data source is called several times to fill the pagination size with enough rows, which can cause severe performance problems in the case of HTTP requests.

# Expected behavior

The method `api.setCacheBlockSize` should work for both models `serverSide` and `infinite`.

# Environment

- **AG Grid version:** 29.0.0
- **Browser:** all
- **Language:** all

**Comment by StephenCooper** [comment] 2023-01-18 09:47
Can I just confirm that the issue is that you would like to change the `cacheBlockSize` after the grid has been initialised? 

I see that this method has only every supported the `serverSide` row model making this a request for the same support for the `infinite` row model?

**Comment by StephenCooper** [comment] 2023-01-20 15:47
I have recorded this under  AG-7873 and added this to the major project for improving the grid's reactivity. I will close this ticket now as this will be considered as part of that work.

**Closed by StephenCooper** 2023-01-20 15:47 UTC
Labels: AG-7873
