### ISSUE TITLE
Horizontal scroll stops working after scroll to end of content

### ISSUE THREAD

**Issue by tohihaho** [ag-grid/ag-grid#4163] opened 2020-10-27 17:01 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Plunker: https://plnkr.co/edit/5Lsod6RNoY0dGC1n?preview

**Current behavior**
Open this plunker, which is code from your example with no changes at all.
Scroll the horizontal scrollbar all the way to the right (I drag the "thumb" using my mouse all the way to the right and then release it). Try scrolling back to the left.

**Expected behavior**
Scroll should be possible in both directions without issues

**Please tell us about your environment:**
Windows 10,

* **ag-Grid version:** X.X.X
24.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

* **Language:**
all

**Comment by makinggoodsoftware** [comment] 2020-11-02 12:19
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2020-11-03 12:13
Hello!

Thank you for reporting this with an example - this really helps!

We have reproduced this as a regression versus v24.0. Specifically, this issue happens at specific zoom levels (works fine at 100% and 110%, breaks at 125%). Please treat this as a known issue and use v24.0 until we resolve this in our next release.

We have added this to our backlog and we are tracking it with the following reference and description:
**AG-4767 [Regression] Horizontal scrolling breaks at specific zoom levels (due to invalid call to isIOSUserAgent in shouldBlockScrollUpdate)**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I would recommend signing up for automatic release notifications for ag-grid. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up with us.

**Comment by tohihaho** [comment] 2020-11-04 10:39
Thanks for the reply. :)

**Comment by makinggoodsoftware** [comment] 2020-11-10 12:38
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2020-11-10 12:38 UTC
Labels: AG-4767, community-engaged, in_zendesk
