### ISSUE TITLE
Flickering value on cell editing finished with React cell renderer and editor

### ISSUE THREAD

**Issue by Yuvasee** [ag-grid/ag-grid#4588] opened 2021-07-15 10:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
- Create AG grid with React cell renderers and editors
- Edit any value with React cell editor
- Finish editing any possible way

Reproduces even in AG official example:
- Follow the link https://www.ag-grid.com/react-grid/component-cell-renderer/
- Scroll to first grid example
- Edit any value in Bronze/Silver/Gold column (change the number)
- Finish editing any possible way

**Current behavior**
After finished editing for noticeable sub-second time you will see an old value, than a new one.
So we have: new (in editor) -> old (in renderer) -> new (in renderer) value flickering.

**Expected behavior**
After editing finished see new value in renderer without flickering.

**Please tell us about your environment:**
Windows 10

**AG Grid version:**
25.3.0

**Browser:**
Chrome 91.0.4472.124.

**Language:**
TypeScript

**Comment by shuheb** [comment] 2021-08-03 12:01
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-08-05 14:01
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v24.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5588 [Regression] When exiting cell edit mode, React Cell Renderer for edited cell flickers**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:21
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-09 10:21 UTC
Labels: AG-5588

**Comment by kiril-matev** [comment] 2022-10-26 15:59
Hi @gabrielpetersson,

Thanks for reaching out.

We have rebuilt this example with React 18 and AG Grid 28.2 and cannot reproduce the issue.

Please follow the steps below:
1. Open
https://plnkr.co/edit/E7LOJObSip9Qnf2r
2. Click the GOLD column cell in the top row
3. Press F2 to enter edit mode
4. Change cell value to 2
5. Press ENTER key
**Actual & Expected**: Cell value updated, no flicker

If you're still seeing this issue in your application, please FORK and update this plunker to reproduce this issue and send it back with a list of steps to reproduce the issue.

Thank you for your time!
