### ISSUE TITLE
'key' property of ICellEditorParams doesn't work

### ISSUE THREAD

**Issue by Youngbae-Jeon** [ag-grid/ag-grid#4926] opened 2022-02-18 08:05 UTC
Since **27.0.1**, it seems that the property **keyPress** of **ICellEditorParams** has been renamed to **key**.
But it causes(i think) the following issue...

Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)

And the incoming value of 'key' is always 'undefined' in my custom cell editor.

**Comment by makinggoodsoftware** [comment] 2022-02-18 16:42
Hi guys,

Looking at this issue on our end, but we are not sure how to reproduce this, we looked at our examples and it all seems to be working fine, would you mind seeing if you can provide us with a reproducible scenario?

Thanks

**Comment by Youngbae-Jeon** [comment] 2022-02-20 10:58
Let me show a simple version of my custom editor that is a React Functional component.
```ts
import { ICellEditorParams, KeyCode } from 'ag-grid-community';
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';

const SimpleNumberCellEditor = forwardRef((props: ICellEditorParams, ref) => {
    const [value, setValue] = useState<number | null>(props.value);
    const refDiv = useRef<any>(null);

    const focus = (select: boolean) => {
        if (refDiv.current) {
            console.log('refInput.current', refDiv.current);
            const input = (refDiv.current as HTMLElement).querySelector('input');
            if (input) {
                input.focus();
                if (select) {
                    input.select();
                } else {
                    const textLength =  input.value.length;
                    input.setSelectionRange(textLength, textLength);
                }
            }
        }
    }

    useEffect(() => {
        const {charPress, key} = props;

        if (charPress && charPress >= '0' && charPress <= '9') {
            setValue(+charPress);
        } else if (charPress === '-') {
            if (refDiv.current) {
                const input = (refDiv.current as HTMLElement).querySelector('input');
                if (input) {
                    input.value = '-';
                }
            }

        // if del or backspace key comes at start, delete the value
        } else if (key === KeyCode.BACKSPACE || key === KeyCode.DELETE) {
            setValue(null);
        }

        if (props.cellStartedEdit) {
            setTimeout(() => focus(false), 100);
        }
// eslint-disable-next-line react-hooks/exhaustive-deps
}, []);

    useImperativeHandle(ref, () => {
        return {
            getValue() { return value; },
            isCancelBeforeStart() { return false; },
            isCancelAfterEnd() { return false; },
            focusIn(): boolean { return true; },
            focusOut(): boolean { return false; }
        };
    });
 
    return (
        <div ref={refDiv}>
            <input type='text' value={value ? value.toString() : ''} onChange={e => setValue(+e.target.value.replaceAll(/[^0-9_]/g, ''))} />
        </div>
    );
 });

// ......
 const rows = [
    {value: 100}
];
<AgGridReact rowSelection="single" rowData={rows}>
    <AgGridColumn field="percent" headerName={i18n.percent[lang]} type='numericColumn' cellEditor={SimpleNumberCellEditor} />
</AgGridReact>
```
I put the component into cellEditor property of AgGridColumn.

When I double click the cell (or type a key) to start edit, then it produces the following warning .
And I wanted starting with delete key makes delete the value, but the action doesn't work.
```
Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
```

**Comment by kiril-matev** [comment] 2022-03-07 12:28
Hello @Youngbae-Jeon !

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6453 [Regression] When using React, custom Cell Editor props (ICellEditorParams) don't allow accessing key property value due to naming conflict with React**

**This issue will be fixed in the next release.**

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-03-08 22:42 UTC
Labels: ag-grid engaged, ag-6453

**Comment by SerhiiBabii** [comment] 2022-03-14 19:10
Hello @Youngbae-Jeon!
As a temporary solution until ag-grid will be updated.

You can create the function:
```
const getEventKey = (params) => ({
  keyPress: params?.key
});
```

and add this function to the column definition:
```
<AgGridReact rowSelection="single" rowData={rows}>
    <AgGridColumn field="value"
        type='numericColumn'
        cellEditorParams={getEventKey}
        cellEditor={SimpleNumberCellEditor} />
</AgGridReact>
```

and then you can get "keyPress" in your editor:
```
const { keyPress } = props;
```

**Comment by sonicviz** [comment] 2023-01-19 00:17
I'm having similar issues like this, but in Javascript. 

Key is undefined, and this says: AG-6453 - ICellEditorParams.key is deprecated, use ICellEditorParams.eventKey instead.
https://www.ag-grid.com/changelog/?fixVersion=27.1.0

However, all the current Javascript docs at the following refer to .key to test against "enter", which is confusing. 
https://ag-grid.com/javascript-data-grid/keyboard-navigation/
https://ag-grid.com/javascript-data-grid/component-cell-editor/#complementing-cell-editor-params

Is it at all possible to test against the Enter key being pressed in a cell editor, and ignoring it?

**Comment by StephenCooper** [comment] 2023-01-19 09:19
In the linked examples the `.key` is from a real browser event as opposed to our cell editor params. The following code prevents editing when the user presses the `Enter` key. 

```
  init(params: ICellEditorParams) {
    if(params.eventKey === 'Enter'){
      params.stopEditing()
    }
}
```

**Comment by sonicviz** [comment] 2023-01-19 10:52
Thanks for the info. Debugging params, however, I have no params.eventkey either.

**Comment by StephenCooper** [comment] 2023-01-19 11:24
If you press 'Enter'  on the Doubling column in this plunker then you should see `Enter` set as the event key.

https://plnkr.co/edit/EPpyoIfHrvWCB9ft?open=main.ts

**Comment by abhijeetJaisw** [comment] 2024-03-18 12:33
> Let me show a simple version of my custom editor that is a React Functional component.
> 
> ```ts
> import { ICellEditorParams, KeyCode } from 'ag-grid-community';
> import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
> 
> const SimpleNumberCellEditor = forwardRef((props: ICellEditorParams, ref) => {
>     const [value, setValue] = useState<number | null>(props.value);
>     const refDiv = useRef<any>(null);
> 
>     const focus = (select: boolean) => {
>         if (refDiv.current) {
>             console.log('refInput.current', refDiv.current);
>             const input = (refDiv.current as HTMLElement).querySelector('input');
>             if (input) {
>                 input.focus();
>                 if (select) {
>                     input.select();
>                 } else {
>                     const textLength =  input.value.length;
>                     input.setSelectionRange(textLength, textLength);
>                 }
>             }
>         }
>     }
> 
>     useEffect(() => {
>         const {charPress, key} = props;
> 
>         if (charPress && charPress >= '0' && charPress <= '9') {
>             setValue(+charPress);
>         } else if (charPress === '-') {
>             if (refDiv.current) {
>                 const input = (refDiv.current as HTMLElement).querySelector('input');
>                 if (input) {
>                     input.value = '-';
>                 }
>             }
> 
>         // if del or backspace key comes at start, delete the value
>         } else if (key === KeyCode.BACKSPACE || key === KeyCode.DELETE) {
>             setValue(null);
>         }
> 
>         if (props.cellStartedEdit) {
>             setTimeout(() => focus(false), 100);
>         }
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>     }, []);
> 
>     useImperativeHandle(ref, () => {
>         return {
>             getValue() { return value; },
>             isCancelBeforeStart() { return false; },
>             isCancelAfterEnd() { return false; },
>             focusIn(): boolean { return true; },
>             focusOut(): boolean { return false; }
>         };
>     });
>  
>     return (
>         <div ref={refDiv}>
>             <input type='text' value={value ? value.toString() : ''} onChange={e => setValue(+e.target.value.replaceAll(/[^0-9_]/g, ''))} />
>         </div>
>     );
>  });
> 
> // ......
> const rows = [
>     {value: 100}
> ];
> // ......
> <AgGridReact rowSelection="single" rowData={rows}>
>     <AgGridColumn field="value" type='numericColumn' cellEditor={SimpleNumberCellEditor} />
> </AgGridReact>
> ```
> 
> I put the component into cellEditor property of AgGridColumn.
> 
> When I double click the cell (or type a key) to start edit, then it produces the following warning . And I wanted starting with delete key makes delete the value, but the action doesn't work.
> 
> ```
> Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
> ```

Did you find a solution of this one? i want my editor to take decimal and negative values as well. But for some reason that is not triggering the oncellvaluechanged event. and that key warning is still there.
