### ISSUE TITLE
BUG: Animation called when animations are disabled

### ISSUE THREAD

**Issue by Llorx** [ag-grid/ag-grid#4808] opened 2021-11-29 16:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The console shows a warning log.

**Expected behavior**
Clean console warnings.

**Please tell us about your environment:**
Chrome, Windows 10.

* **AG Grid version:** 26.2.0

When I set the option `suppressAnimationFrame: true`, it still calls the animation frame when updating data with `setRowData()`. To reproduce, just create a grid with the animations disabled and call `setRowData(data)` a couple of times.

**Comment by msosa** [comment] 2021-12-06 09:15
I too am having this issue, it is easy to reproduce. Here is the [plunker](https://plnkr.co/edit/qUIpjzwUGVxGHlUk), just run it and open f12 to see the warnings.

Looking at the stacktrace of the warning it seems that the error may be here in [clientSideRowModel.ts line 931](https://github.com/ag-grid/ag-grid/blame/ca102f728390eda5dfe70f583cead91f2841d073/community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts#L931). It seems to always set animate to `true`. However this line of code has been there for 5 years so not really sure why this warning would just appear now.

**Comment by makinggoodsoftware** [comment] 2021-12-22 14:54
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-13 16:11
Hello @Llorx!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6155 [Regression] When setting suppressAnimationFrame: true, console warnings are output**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:30
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:30 UTC
Labels: in_zendesk, waiting-for-repro, ag-6155
