### ISSUE TITLE
Added row in transaction not added at addIndex on sorted table

### ISSUE THREAD

**Issue by leontwo4** [ag-grid/ag-grid#5918] opened 2022-12-21 12:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

The issue can be reproduced in the following plunker: https://plnkr.co/edit/J2WDvusW075X7AuC?open=app%2Fapp.component.ts (28.2.1) 
1. sort list i.e. by "Make"
2. click "Add Item addIndex=2" button
3. remove sort
4. Notice that new row was NOT added at index 2 (but if sort is applied ascending at index 1, if sort is descending at index 3)

In the plunker https://plnkr.co/edit/Gx5DVlcx6T0ZC3tt (25.0.1) from issue https://github.com/ag-grid/ag-grid/issues/4312 it is still working as expected.

I noticed that the issue occurred beginning from version 27.2.0.
Same code in examples, only differing in AG Grid version:
https://stackblitz.com/edit/ag-grid-angular-hello-world-omdfxf?file=src%2Fapp%2Fapp.component.ts (AG Grid 27.1.0) working as expected; row gets added at the specified addIndex
https://stackblitz.com/edit/ag-grid-angular-hello-world-wlf5m8?file=src/app/app.component.ts (AG Grid 27.2.0) NOT working as expected; Row not added at addIndex when sort applied

**Current behavior**

I'm using the applyTransaction method to add a new row in a specific index by using addIndex.
The row is not added at the specified index of the unsorted rowData when sorting is applied at transaction time. This occurs from ag-grid-angular version 27.1.1 onwards. 

**Expected behavior**

As stated in https://github.com/ag-grid/ag-grid/issues/4312#issuecomment-766899851 when
1. sort is applied
6. row is added with addIndex
7. sort is removed

should lead to row added at specified index.

* **AG Grid version:** 28.2.1

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
* **Language:**  TypeScript 4.8

**Comment by StephenCooper** [comment] 2022-12-21 15:17
Thank you for the detailed ticket with examples. I have raised this internally for further investigation.

**Comment by StephenCooper** [comment] 2023-01-06 13:42
Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7767 [Regression] addIndex parameter in applyTransaction API method does not work when sorting is applied

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7767) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-01-06 13:42 UTC
Labels: in_review
