### ISSUE TITLE
Column FilterType Dropdown Not disabling for single filter type till v26.2.0

### ISSUE THREAD

**Issue by ronisaha** [ag-grid/ag-grid#6538] opened 2023-04-29 07:31 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
From ag-grid `>=26.2.0` In the column filter the filter type dropdown is not disabled when there is a single `filterType`. 
<img width="622" alt="latest" src="https://user-images.githubusercontent.com/1433652/235289649-41a05404-c903-49af-a354-4a4f3936d59b.png">

Reproduced Behaviour in V29.3.3 vs v26.2.0 vs 26.1.0 [https://plnkr.co/edit/4cZFyCPfDJGX4Zfq?open=main.js](https://plnkr.co/edit/4cZFyCPfDJGX4Zfq?open=main.js&preview)

**Expected behavior**
The dropdown should be disabled in case of a single `filterType` like the previous version.
<img width="622" alt="old" src="https://user-images.githubusercontent.com/1433652/235289669-21805f94-f0cf-4c1f-a799-65b782867b64.png">

**Please tell us about your environment:**

* **AG Grid version:** >=26.2.0

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

* **Language:** All

**Comment by StephenCooper** [comment] 2023-05-05 09:57
Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8474 When a simple filter has only one option, the dropdown is not disabled**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2023-05-05 09:57 UTC
Labels: in_review
