### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by ArsNV** [ag-grid/ag-grid#4242] opened 2020-12-15 14:36 UTC
**Current behavior**
When we clicked on expand -> merge (vertical , horizontal, etc.) we receive a 
TypeError: Cannot read property 'constructor' of null

node_modules/ag-grid-community/dist/ag-grid-community.cjs.js:544
> 544 | var sourceIsSimpleObject = typeof value === 'object' && value.constructor === Object;
      | ^  545 | if (sourceIsSimpleObject) {
  546 |     res[key] = deepCloneDefinition(value);
  547 | }
 

**Expected behavior**
it must work.

**Please tell us about your environment:**
Windows 10

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Can we change this line to 
var sourceIsSimpleObject = typeof value === 'object' && value && value.constructor === Object;

Thanks.

**Comment by blackbaud-jeremymorgan** [comment] 2020-12-16 15:43
I'm also seeing this behavior when trying to update a column's headerName.

**Comment by jonhenning** [comment] 2020-12-21 18:28
Same issue here.  Basically calling 

var defs = this.gridOptions.api.getColumnDefs() 

will return an array with items that include properties with null values

When you call the inverse, 

this.gridOptions.api.setColumnDefs(defs);

if the defs array has an item with a null property reference it bombs.

My temporary workaround is to remove the null properties right before calling setColumnDefs

      defs.forEach(d => {
        Object.keys(d).forEach((key) => (d[key] == null) && delete d[key]); 
      });
      this.gridOptions.api.setColumnDefs(defs);

**Comment by dennis2k** [comment] 2021-01-22 11:45
Same issue here - updating the columnDefs

**Comment by makinggoodsoftware** [comment] 2021-02-23 16:40
Hi guys,

Since there isn't any repro, we are going to close this one, if you can reproduce this, feel free to open a new ticket and we will have a look

Thanks

**Closed by makinggoodsoftware** 2021-02-23 16:40 UTC
Labels: waiting-for-repro

**Comment by rb-mwindh** [comment] 2021-08-02 09:18
For everyone else who stumbled across this: the problem is fixed since AgGrid 25.0.0.

Fix located at [/community-modules/core/src/ts/utils/object.ts (line 51)](https://github.com/ag-grid/ag-grid/blob/53059eb7f771d8c7268a4cd7e070694e8a2a34d9/community-modules/core/src/ts/utils/object.ts#L51)

Related commit: https://github.com/ag-grid/ag-grid/commit/b3ae873fd4ddbc1098f57d49ea9a3e332c4b14a3
