### ISSUE TITLE
Grid encounters "this.rowIndex is null" when serverSideDataSource changes

### ISSUE THREAD

**Issue by harish-prakash** [ag-grid/ag-grid#5068] opened 2022-04-07 05:07 UTC
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I build the server-side datasource with a `useCallback` and change it when external filters are updated. I need to use this method because, the grid's native external filter solution (reference: [React Data Grid: External Filter](https://www.ag-grid.com/react-data-grid/filter-external/)) does not work for server-side row model, plus I cannot use the request's filterModel because the my external filter is not a column in the grid.

The worst part is, it is not always reproducible thus I cannot provide a plunkr

**Current behavior**
Line 312 in rowNode.ts causes the error because a potential `null` rowIndex is ignored with the use of `!`
https://github.com/ag-grid/ag-grid/blob/c44bb64f1939515f905e7dca6fd68321b55f8ce7/community-modules/core/src/ts/entities/rowNode.ts#L303-L313

**Expected behavior**
* **BugFix**: Handle the `null` rowIndex properly **(or)**
* Allow filterModels to work even when the column is not in the grid **(or)**
* Extend "external filtering" to server-side row model **(or)**
* Allow passing additional payloads to the server-side getRows request (something similar to passing cellRenderParams)

**AG Grid version:** 27.0.1

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0

**Language:** TypeScript 4.5.5

This was already reported once before but it was improperly closed off as a support request: https://github.com/ag-grid/ag-grid/issues/4767

**Comment by kiril-matev** [comment] 2022-08-16 10:35
Hi @harish-prakash!

Thank you for reporting this. 

Apologies for closing this issue earlier, this was done in error. You've submitted a bug report and we'd like to look into this further.

We're keen to start our investigation of this specific issue. We need a live sample to reproduce the issue as per our bug report template. It's fine if the plunker only reproduces the issue on every 5th attempt, we need an example which reproduces the issue. Once we have the example that reproduces the issue, we can then work on the reproduction steps.

Please provide a live example reproducing this issue.

We're looking forward to your response so we can progress this.

**Comment by StephenCooper** [comment] 2023-05-02 09:11
I am going to close this issue as without a reproduction we are unable to resolve this. 

If this is still happening in v29 then feel free to re-open.

**Closed by StephenCooper** 2023-05-02 09:11 UTC

**Comment by StephenCooper** [comment] 2023-05-02 15:58
Please see this comment and subsequent ones for why this assertion is still in place. 

https://github.com/ag-grid/ag-grid/pull/5423#issuecomment-1205355867

**Comment by StephenCooper** [comment] 2023-05-03 08:44
No need to apologise for the rant these issues are hard for users and us as maintainers. 

I would definitely agree with your last statement that server side grids should only be used when required as they are a lot more complicated then client side grids to manage.

**Comment by raivis-v** [comment] 2023-06-29 11:31
I've faced the same problem (with the latest grid version 30.0.2 and previous versions as well). Are there any updates on this issue? I've noticed the problem occurs when using full width rows, when there are existing data in the grid and new data is injected via gridOtions.api.setRowData(newData). As previous writers stated - it is not 100% reproducible.

**Comment by StephenCooper** [comment] 2023-06-29 11:37
> I've faced the same problem (with the latest grid version 30.0.2 and previous versions as well). Are there any updates on this issue? I've noticed the problem occurs when using full width rows, when there are existing data in the grid and new data is injected via gridOtions.api.setRowData(newData). As previous writers stated - it is not 100% reproducible.

It sounds like you are not using ServerSideRowModel? If that is correct could you please open a new ticket and if possible provide a code sample even if it does not 100% reproduce the issue every time. We need as much data as possible to try and track these issues down.

**Comment by raivis-v** [comment] 2023-06-29 11:40
@StephenCooper - yes, you are right, in my case there is no ServerSideRowModel, but the stacktrace indicates the same error in the same line of code. But ok, I will open new ticket tomorrow, cant promise reproducible code though.

**Comment by raivis-v** [comment] 2023-06-30 08:11
I made a ticket in zendesk with reproduceable plunker example. Hope it helps to solve this issue as-well.

**Comment by hckhanh** [comment] 2023-10-17 04:22
I encountered this issue again.

**Comment by AG-Zoheil** [comment] 2023-10-17 09:10
Hi @hckhanh,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue first raised **last year**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil

**Comment by raivis-v** [comment] 2023-10-18 06:23
Hello, @hckhanh !

If I remember it right the problem was still there in version 30.1.0. In my case the first version that did not raise this error was v30.2. I know my case was without server side datasource but still the stack trace of the error was the same. So I encourage you to try latest build. Hope it helps.

Best regards,
Raivis.

**Comment by vetonhaxholli** [comment] 2024-05-17 07:45
I run into this error and just updated my colDef columns from title: '....' -> headerName: '....'; You can pin you columns now.
