### ISSUE TITLE
ag-grid-vue3: Scoped CSS for cell renderers does not working using script setup syntax

### ISSUE THREAD

**Issue by 0biWanKenobi** [ag-grid/ag-grid#7263] opened 2023-11-16 11:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[*] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**

If we use the `script setup` syntax in the component that renders AgGrid in its template, than scoped CSS for cell renderers does not work.  You can see a repro [in this Stackblitz](https://stackblitz.com/edit/vitejs-vite-x6ueuy?file=package.json,src%2FApp.vue,src%2Fcomponents%2FGrid.vue,src%2Fcomponents%2FRenderer.vue,src%2Fstyle.css&terminal=dev).

**Current behavior**

The `data-v-12345` attribute gets stripped away from custom cell renderers, and consequently the scoped CSS is not applied. This _only happens_ when using `script setup`, while the `defineComponent(...)` syntax works fine. If we look at the [rendered preview](https://vitejsvitex6ueuy-jkex--5173--420f2654.local-corp.webcontainer.io/) of the repro, we can see that text in the "Extra" column is not styled ([see](https://stackblitz.com/edit/vitejs-vite-x6ueuy?file=package.json,src%2FApp.vue,src%2Fcomponents%2FGrid.vue,src%2Fcomponents%2FRenderer.vue,src%2Fstyle.css&terminal=dev) `src/components/Renderer.vue` CSS),  even though there is a scoped CSS defined in the component.

**Expected behavior**
Text in the "Extra" column should be colored red (see `src/components/Renderer.vue` CSS). In general, scoped CSS should work.

**Please tell us about your environment:**
* OS: Win 11
* IDE: VSCode
* package manager: npm
* **AG Grid version:** latest

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0'
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'

* **Language:** [TypeScript 5.2.2 | ES6 ]

**Comment by 0biWanKenobi** [comment] 2023-11-16 11:56
While investingating the cause of this issue, I've found that including a separate `script` block, where we export the cell renderer components, is a working fix. Not ideal, but better than giving up on script setup syntax completely. [Working example here](https://stackblitz.com/edit/vitejs-vite-tuyhdh?file=src%2Fcomponents%2FGrid.vue).

**Comment by AG-Zoheil** [comment] 2023-12-01 09:39
Hi @0biWanKenobi,

Thank you for submitting this. As part of our latest release `v31` we've made some improvements to support script setup via **AG-8274**. Could you please confirm if your issues continue to exist on `v31`?

Kind regards,
Zoheil

**Comment by kimjohnsson** [comment] 2023-12-05 14:46
Hi @AG-Zoheil !

I've also experienced this issue in the project I'm working on using Vue and `script setup`.. I just tried updating ag-grid to `v31` but the issue still remains..

**Comment by AG-Zoheil** [comment] 2023-12-05 15:09
Thanks @kimjohnsson,

I'm sorry to hear this is still not working as expected for you. Would you be able to provide a mini-project in form of a zip that reproduces the error you are getting? We'd be keen to look into it.

**Comment by kimjohnsson** [comment] 2023-12-05 16:22
Sure, here is a small project reproducing the issue.

[ag-grid-scoped-style.zip](https://github.com/ag-grid/ag-grid/files/13562662/ag-grid-scoped-style.zip)

**Comment by AG-Zoheil** [comment] 2024-02-14 16:45
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10704**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2024-02-14 16:45 UTC
Labels: AG-10704

**Comment by nachodd** [comment] 2024-11-21 20:41
Due to licensing, I can't upgrade ag-grid as for now. So, in order to fix the issue in a not-so-ugly way... we could use `defineOptions` to register components directly on the `<script setup>` block, so there's no need to open the regular `<script>`

```
<script setup>
// register the renderer like this, in order for scoped styles to work. 
defineOptions({
  components: {
    StatusRenderer,
  },
});

const columnDefs: ColDef[] = [
  {
    field: 'status',
    headerName: 'Status',
    cellRenderer: 'StatusRenderer', // register it as string
  },
];

```

**Comment by zgbjty** [comment] 2025-11-06 08:17
官网中的使用案例
[Official website Case](https://www.ag-grid.com/vue-data-grid/components/#locally-using-defineexpose-with-script-setup)
``` vue
<template>
  <ag-grid-vue v-model="rowData" :columnDefs="columnDefs"/>
</template>

<script setup>
import MyCustomerCellEditor from './App.vue'

const columnDefs = ref([
    { field: "make", cellEditor: 'MyCustomerCellEditor' }
]);

defineExpose({
    // 局部导入组件方式(应该是导入的组件没有引用, 导致被 树摇(Tree Shaking) 掉了)
    // 需要使用vue的注册组件的方式注册,  需要使用vue 内部的 css(scoped) 渲染, 且需要在导出时 使用 一下, 防止树摇删除未使用的代码
    MyCustomerCellEditor    // make MyCustomerCellEditor available to the grid
})
</script>
```
