### ISSUE TITLE
Undo/Redo not working when using valueSetter function to update table data.

### ISSUE THREAD

**Issue by echo-999** [ag-grid/ag-grid#6737] opened 2023-06-09 02:50 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here is a reproducible code in stackblitz
https://stackblitz.com/edit/stackblitz-starters-8zrumn?file=src%2FApp.tsx

**Current behavior**

I am using the `valueSetter` method in the column definitions to update the table data, and once editing is done, I update the app state.
The undo/redo stack does not get properly modified when making changes to the table, causing the undo/redo to not work properly. 

**Expected behavior**

The undo/redo stack gets updated, and clicking the undo/redo buttons will produce correct results.

**Please tell us about your environment:**

Running on Windows 10, using VS Code as an IDE and yarn as package manager

* **AG Grid version:** 29.3.5

* **Browser:** all

* **Language:** all

**Comment by kiril-matev** [comment] 2023-06-14 17:04
Hello @echo-999,

The behavior you've described is expected.

In your example, in onCellValueChanged the row data is being updated. 

Currently, the undo / redo stack is cleared when a data update is made, and this is documented here:
https://ag-grid.com/react-data-grid/undo-redo-edits/. 

This behavior is by design, because if a data update has been applied, the grid is no longer in a consistent state to perform the undo action.

We have a feature request to add this capability to the grid - you can track it with this reference:
**AG-4103 [Cell Editing] Allow pushing your own cell update operations to undo/redo stack to capture data changes performed in user code via API calls**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed by kiril-matev** 2023-06-14 17:04 UTC
Labels: in_zendesk

**Comment by echo-999** [comment] 2023-06-15 02:25
> Hello @echo-999,
> 
> The behavior you've described is expected.
> 
> In your example, in onCellValueChanged the row data is being updated.
> 
> Currently, the undo / redo stack is cleared when a data update is made, and this is documented here: https://ag-grid.com/react-data-grid/undo-redo-edits/.
> 
> This behavior is by design, because if a data update has been applied, the grid is no longer in a consistent state to perform the undo action.
> 
> We have a feature request to add this capability to the grid - you can track it with this reference: **AG-4103 [Cell Editing] Allow pushing your own cell update operations to undo/redo stack to capture data changes performed in user code via API calls**
> 
> You can follow the status of feature requests, bugs and releases using our pipeline: https://www.ag-grid.com/ag-grid-pipeline/
> 
> **Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version: https://www.ag-grid.com/ag-grid-changelog/**
> 
> Thanks again for bringing this up with us - we appreciate your time!

Oooh, so I'm not supposed to update the `rowData` state if I want to be able to utilize the undo/redo function?

**Comment by patriceo** [comment] 2025-12-03 16:21
Hi @kiril-matev, is there any update on AG-4103? It's been in the backlog for a while.

Thanks!
