### ISSUE TITLE
`this.gridBodyCtrl` is undefined on initialising grid

### ISSUE THREAD

**Issue by mattcree** [ag-grid/ag-grid#5532] opened 2022-09-05 14:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When the grid is being initialised, this error is seen in the console. No error obvious error is manifested to the user.

While debugging, it seems the `gridSizeChanged` event is being fired before the `gridReady` -- but ultimately the `api` model is always defined despite the `gridBodyCtrl` only being defined after the `onGridReady` is fired. 

It does not surface on dev machines and was difficult to reproduce. I set CPU throttling to 6x slowdown in the Chrome devtools, so I assume there is some kind of race condition that normally makes this unseen.

Our `onGridSizeChanged` callback looks like the following

```    
onGridSizeChanged({ api }) {
      console.log({ api });
      api.sizeColumnsToFit();
  }
```

This console.log prints before the error seen afterwards -- the `api` object does not have the `gridBodyCtrl` defined on it.

```
ag-grid-community.auto.esm.js?2c53:31198 Uncaught TypeError: Cannot read properties of undefined (reading 'sizeColumnsToFit')
    at GridApi.sizeColumnsToFit (ag-grid-community.auto.esm.js?2c53:31198:1)
    at OurGrid.onGridSizeChanged (our-grid.jsx?1269:50:13)
    at GridOptionsWrapper.globalEventHandler (ag-grid-community.auto.esm.js?2c53:6308:1)
    at eval (ag-grid-community.auto.esm.js?2c53:1083:122)
    at VanillaFrameworkOverrides.dispatchEvent (ag-grid-community.auto.esm.js?2c53:43243:1)
    at eval (ag-grid-community.auto.esm.js?2c53:1083:51)
    at eval (ag-grid-community.auto.esm.js?2c53:1119:45)
    at Array.forEach (<anonymous>)
    at EventService.flushAsyncQueue (ag-grid-community.auto.esm.js?2c53:1119:1)
```

Our trace looks like the following

![Screenshot 2022-09-05 at 15 11 51](https://user-images.githubusercontent.com/3682140/188468992-3b645ec4-0a87-400c-9e84-c2d55089073c.png)

**Expected behavior**
No error in the console.

**Please tell us about your environment:**
This has been logged several hundred times on users with Windows andMac OS on several versions of Safari, Edge, and Chrome.

* **AG Grid version:** 28.1.1

* **Browser:**
All major browsers...

* **Language:** JS and TS

**Comment by night-fury-web** [comment] 2023-01-30 20:34
Same happened to me.

**Comment by StephenCooper** [comment] 2023-05-02 09:16
I am going to close this as without a code sample that can reproduce the error it is very difficult for us to validate. The code in question has been changed in recent releases which may have resolved the issue as well.

If you can reproduce in v29 then feel free to re-open with a reproduction.

**Closed by StephenCooper** 2023-05-02 09:16 UTC
Labels: waiting-for-repro

**Comment by DivyaVirupakshaa** [comment] 2023-09-14 06:31
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [x] bug report => see 'Providing a Reproducible Scenario'
> [] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
> [] support request => see 'Requesting Community Support'
> ```
> 
> **Current behavior** When the grid is being initialised, this error is seen in the console. No error obvious error is manifested to the user.
> 
> While debugging, it seems the `gridSizeChanged` event is being fired before the `gridReady` -- but ultimately the `api` model is always defined despite the `gridBodyCtrl` only being defined after the `onGridReady` is fired.
> 
> It does not surface on dev machines and was difficult to reproduce. I set CPU throttling to 6x slowdown in the Chrome devtools, so I assume there is some kind of race condition that normally makes this unseen.
> 
> Our `onGridSizeChanged` callback looks like the following
> 
> ```
> onGridSizeChanged({ api }) {
>       console.log({ api });
>       api.sizeColumnsToFit();
>   }
> ```
> 
> This console.log prints before the error seen afterwards -- the `api` object does not have the `gridBodyCtrl` defined on it.
> 
> ```
> ag-grid-community.auto.esm.js?2c53:31198 Uncaught TypeError: Cannot read properties of undefined (reading 'sizeColumnsToFit')
>     at GridApi.sizeColumnsToFit (ag-grid-community.auto.esm.js?2c53:31198:1)
>     at OurGrid.onGridSizeChanged (our-grid.jsx?1269:50:13)
>     at GridOptionsWrapper.globalEventHandler (ag-grid-community.auto.esm.js?2c53:6308:1)
>     at eval (ag-grid-community.auto.esm.js?2c53:1083:122)
>     at VanillaFrameworkOverrides.dispatchEvent (ag-grid-community.auto.esm.js?2c53:43243:1)
>     at eval (ag-grid-community.auto.esm.js?2c53:1083:51)
>     at eval (ag-grid-community.auto.esm.js?2c53:1119:45)
>     at Array.forEach (<anonymous>)
>     at EventService.flushAsyncQueue (ag-grid-community.auto.esm.js?2c53:1119:1)
> ```
> 
> Our trace looks like the following
> 
> ![Screenshot 2022-09-05 at 15 11 51](https://user-images.githubusercontent.com/3682140/188468992-3b645ec4-0a87-400c-9e84-c2d55089073c.png)
> 
> **Expected behavior** No error in the console.
> 
> **Please tell us about your environment:** This has been logged several hundred times on users with Windows andMac OS on several versions of Safari, Edge, and Chrome.
> 
> * **AG Grid version:** 28.1.1
> 
> * **Browser:**
>   All major browsers...
> * **Language:** JS and TS

Hi, 
I am facing the same issue after upgrading to React18 and ag-grid v29, is there any workaround to fix this?

**Comment by AG-Zoheil** [comment] 2023-09-14 08:19
Hi @DivyaVirupakshaa,

We'd be keen to look into this again, but as you can see this is quite an old issue from **last year**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Please also note: There have been several new releases since this issue was first discussed. Our current latest version is **30.1.0** and **30.2.0** will be released before the end of the month.

Much appreciated!

Kind regards,
Zoheil
