### ISSUE TITLE
Inconsistent state of data in table and in values shown in Filters panel

### ISSUE THREAD

**Issue by gautamvishant** [ag-grid/ag-grid#5651] opened 2022-10-06 12:21 UTC
**I'm submitting a ...** 
```
[x] bug report
```

**Steps to Reproduce**
1. Use https://plnkr.co/edit/zfX1YdGZv1X1MG38
2. Now unselect `Black` from first column `Case insensitive (default)`
3. Now column 2 `Case sensitive` will shown rows having values `black` and `orange` but in the filters panel `orange` and `black` values are unselected.

**Current behaviour.**
In Table it shows rows have correct data. But some values in filter panel for the column are unselected but values are there in the table.

**Expected behaviour. **
Values shown in Filters panel should be consistent with values in table.

* **AG Grid version:** 28.0.2

* **Browser:**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0

**Comment by StephenCooper** [comment] 2022-10-12 10:04
It looks like you are just missing the config required to make the set filter caseSensitive. I have updated your plunker with the following. https://plnkr.co/edit/GpCmWrgvvVA0T5Gq

```
    {
      headerName: 'Case Sensitive',
      field: 'colour2',
      filter: 'agSetColumnFilter',
      filterParams: {
        caseSensitive: true,
      },
    },
```

I do not believe there is any bug here in our Set Filter just missing application config.

**Comment by gautamvishant** [comment] 2022-10-13 07:36
Hi @StephenCooper, 
We need `caseSensitive: false` and as you can see data in the table in correct but some how the values shown in the filter panel are not consistent.

**Comment by StephenCooper** [comment] 2022-10-13 08:48
Ok I was confused by the column headers. If you want to have case insensitive on both columns then I can see that there does seem to be something off. 

I have reproduced in this simpler plunker which will help us investigate this further. 

https://plnkr.co/edit/uelvYFZU9EUcXU9V?open=main.ts

**Comment by StephenCooper** [comment] 2022-10-13 08:56
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7381 Inconsistent state of data in table and in values shown in Filters panel

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-7381) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed by StephenCooper** 2022-10-13 08:56 UTC

**Comment by kiril-matev** [comment] 2022-10-13 17:23
Hello @gautamvishant!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7381 When using case-insensitive set filter, items with the same value but a different case are unchecked unnecessarily**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
