### ISSUE TITLE
× TypeError: Cannot read property 'addEventListenerOutsideAngular' of null

### ISSUE THREAD

**Issue by MangioneAndrea** [ag-grid/ag-grid#3334] opened 2019-08-27 09:11 UTC
Function.Utils.addSafePassiveEventListener
node_modules/ag-grid-community/dist/lib/utils/general.js:2102
  2099 | } : undefined;
  2100 | 
  2101 | if (isOutsideAngular) {
> 2102 |   frameworkOverrides.addEventListenerOutsideAngular(eElement, event, listener, options);
       | ^  2103 | } else {
  2104 |   eElement.addEventListener(event, listener, options);
  2105 | }

This get thrown after some component re-rendering even if the Ag-Grid hasn't changed

**Comment by davis4acca** [comment] 2019-09-06 13:20
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

Thanks

**Comment by csicky** [comment] 2019-11-14 10:58
This issue `Uncaught TypeError: Cannot read property 'addEventListenerOutsideAngular' of null` comes very often. It is a problem with ag grid not destroying itself properly. It is a **bug on ag grid**. The response ag grid people give on github seems like they don't care. 

We, the users, search for the issues on google. We find the issues on github. However all stops here as there is no resolution. 

The answers like this `ag-grid staff does not provide support through github.` are not helpful and almost rude. We are your clients after all, why are you trying to dictate where we get support? At least you should take notice and be thankful for the free bug report and implement the fix in your product.

**Comment by makinggoodsoftware** [comment] 2019-11-27 13:07
Hi guys,

I hope you understand that there is very little we can do without a repo scenario... I have reopened this, and we will monitor this thread.

Would you be able to provide us with a zip/github etc?

Note that we do have this in the pipeline


AG-3362 | rowClicked and cellFocused events sometimes fire in non-angular zone
-- | --



This might be related, byt we wouldn't know unless we can reproduce it

**Comment by csicky** [comment] 2019-11-27 15:05
![image](https://user-images.githubusercontent.com/3931907/69734475-b40f5a80-1137-11ea-925a-128581a4e06c.png)

In my case it is enough to navigate from a view to another quickly without giving time to ag grid to properly render. We have a Vue single page app with vue router. On the `beforeDestroy` method we already have this:
```
    if (this.gridApi && this.gridApi.destroy) {
      this.gridApi.destroy()
    }
```
We have `this.gridApi` set from the `gridReady` event.

**Comment by MangioneAndrea** [comment] 2019-11-27 15:19
![image](https://user-images.githubusercontent.com/35958935/69735543-24ff4400-1131-11ea-88e8-bbe355813ab1.png)
In my case it's react, and happens at some state re-renders (in react the whole page gets "re-rendered" with hot reloading every time a "state" changes. This can be a input, the background color, a server response or anything that comes in mind).

**Comment by dmitri-afonin** [comment] 2019-12-03 15:25
I have the same issue in Angular unit tests. It does not even provide proper stack trace so I could debug it deeply(

**Comment by angeloocana** [comment] 2019-12-05 21:18
I found out why I was seeing this error and how to fix it.

In the app I'm working on we have tabs and each tab renders a table using ag-grid.
We were seeing the error bellow sometimes when switching tabs:
`TypeError: Cannot read property 'addEventListenerOutsideAngular' of null`

After debugging it, I found out that `onGridReady={params => setGridApi(params.api)}` was running after my effects.
My effects had the "lastest" gridApi but for the old tab.

I fixed it by adding a unique key to the component that has ag-grid:
`<WorksheetTable key={instanceId} />;`

That forces the component to be destroyed and recreated every time we switch tabs.

I hope this fix can help someone.

**Comment by mattspeller** [comment] 2020-01-09 12:07
Thanks to @angeloocana I was able to resolve my version of the issue.
Calling setCoumnState on a destroyed grid api gives the same error.

We have code the updates the state of the grid with clipboard settings when the user pastes. This sets state which tore down and created a new grid instance, and the exception was caused by calling setColumnState on the the old destroyed gridApi instance whilst it was being torn down / recreated and before the gridApi reference was updated. 

I removed the call to setColumnState, instead allowing the grid to recreate and set column state on load, and issue resolved.

**Comment by MangioneAndrea** [comment] 2020-01-09 16:42
@mattspeller @angeloocana Sadly this doesn't work on my case because I'm already watching the lifecycle of the react component. This errors also appears on mount and not on destroy of the grid. Luckly, it's also a non-fatal error, and anyway disappears on the production build.

My thought is that it gets garbage collected after somehow losing the pointer reference aka React forgets about it by creating a copy to be visualized.

FOR ALL WHO ARE USING REACT
I'm using hooks, which don't have proper lifecycles, they basicly get rerendered on every change.
A possibly solution is to save the grid on a useMemo(), but this makes the code a bit messy and less readable. (not good for complex component using multiple states and hooks)

**Comment by Lertis** [comment] 2020-02-03 15:56
@csicky I have the same console error ```ag-Grid: unable to find bean reference fremeworkOverrides while initializing BeanStub.``` Do you have any ideas about why does it appear to the browser?

**Comment by csicky** [comment] 2020-02-03 16:06
@Lertis In my case is because ag-grid component doesn't clean up after itself. When the Vue component is destroyed, I call the ag-grid api method `destroy()` but still it throws these errors. All I have to do is to quickly navigate from a router view containing ag-grid to another and I get the error.

**Comment by Lertis** [comment] 2020-02-05 11:34
@csicky What if I have the same error trying to change the order for the rows? I didn't navigate from one component with ag-grid to another one. 
Maybe we need to follow some rules such as: When the grid is going to be updated (the new data will be fetched via an API call) -> destroy the previous one gridOptions, gridApi, etc?

I think it doesn't make sense which framework we were using. You - Vue, me - Angular.

**Comment by csicky** [comment] 2020-02-05 12:06
> 
> 
> @csicky What if I have the same error trying to change the order for the rows? I didn't navigate from one component with ag-grid to another one.
> Maybe we need to follow some rules such as: When the grid is going to be updated (the new data will be fetched via an API call) -> destroy the previous one gridOptions, gridApi, etc?
> 
> I think it doesn't make sense which framework we were using. You - Vue, me - Angular.

In my case since the destroyed grid throws the error, the app works just fine. On Sentry I created rules to ignore these errors and that's it. It seems Ag Grid people don't care about this error or just can't reproduce it, but anyway, it's their responsibility to fix this, not ours, the users.

**Comment by Lertis** [comment] 2020-02-07 07:56
@csicky We need to be sure that this issue is a coding error of the ag-Grid dev team to confirm the guilt

**Comment by TylerKienVu** [comment] 2020-02-10 23:09
After investigating into the issue, I realized that this error would happen for my project when we are using an Observable to fetch some data for the grid through the server side datasource for the project and switching pages mid fetch. 

The main problem was that once the Observable pushed data to the subscriber and the subscriber tried to handle the data using the gridApi, it would throw the `TypeError: Cannot read property 'addEventListenerOutsideAngular' of null`. I was also getting all of the bean reference errors that @csicky pointed out. 

How I ended up fixing it is on the subscriber callback for the Observable, I added a check to see if the grid is destroyed before handling the response:

```javascript
      const query$ = client.watchQuery({
        query: queryString,
        variables: {
          input: queryInput,
        },
      });

      query$.subscribe(data => {
        handleResponse(params, queryParams, data, this);
      const subscription = query$.subscribe(data => {
        // Check to see if the grid is destroyed. If it isn't destroyed, then
        // handle the response. The grid could be destroyed if the user switched
        // pages while this subscription is still being promised. This will cause
        // the grid to throw an error that will crash the page if not checked.
        if (!params.parentNode.context.destroyed) {
          handleResponse(params, queryParams, data, this);
        } else {
          subscription.unsubscribe();
        }
```

**Comment by csicky** [comment] 2020-02-17 18:26
This error is already too much. Seriously, I don't even know if anybody is reading this thread anymore.
@makinggoodsoftware 

https://www.loom.com/share/d4d478f8310a48bfbc37a449351b416b

Here is a video with the bug in action. I just open a view with ag grid in it and without letting it finish initializing, I simply go to another view. The grid crashes and burns while still trying initializing itself. This is already embarrassing, seriously. In the video you can see that at least you could check for `frameworkOverrides` to not be null before trying to access from it a method named `addEventListenerOutsideAngular`. To be honest I can't even imagine how this all is set up. I am reading this error for years now every day and can't help but wonder about this angular thing. What if it is outside angular? This is vue js not angular. All sorts of questions popping about why does ag grid care that I don't use Angular. Why is it not complaining about not using React, then? Or jQuery? Or Mootools, remember that? Point is, if this is a vanilla js grid and supports frameworks with wrappers and plugins, then why is Angular mentioned so often and so deeply inside the source code everywhere?

Our Sentry integration has so many exception rules added for this one error. Still I get lots of them all the time.

Pleas fix it already, it is time. Make another error, if you wish, for a change, but I really had enough of this one.

**Comment by makinggoodsoftware** [comment] 2020-03-11 14:51
Hi,

Sorry for the frustration, but unfortunately we don't see in the thread any reproducible scenario that we can use in our end.

Has anyone of you found a way for us to reproduce this via plunker / stackblitz etc?

If that is the case we will try to expedite this as fast as possible

**Comment by ybarbaria** [comment] 2020-05-04 02:50
Hi, 
Any news about this bug ?

**Comment by csicky** [comment] 2020-05-04 10:38
I tried to make a new project and reproduce it there, but it doesn't happen. I just created a Vue project and added AG grid there, switched views, didn't happen. It is probably something in our project causing this.

However, Ag Grid team could very easily solve this by just testing if that method exists before calling it. Is there `addEventListenerOutsideAngular` method on that object? Call it, otherwise not. Simple.
Same thing with bean reference thing. Just check if it is there. 
Swallow the errors, we don't care about them. It is just noise in the error tracking software.

The project I work on is very big and complex, I can't tell how much time would it take for me to find what I use from AG grid which fails on quick route change. It is not my job to investigate it.

**I just ask, since it is not my error, do not throw it in my console. That's it.**


P.S. Ag Grid is a main part of the project I work on. We rely on it heavily. If I wouldn't think it is a great product I wouldn't waste time here writing, I would use something else already.

**Comment by makinggoodsoftware** [comment] 2020-05-11 14:06
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment] 2020-05-12 11:39
Hi guys,

We have decided to put a null check:


AG-4206 | Add check around addEventListenerOutsideAngular to prevent false errors
-- | --



This should be available in our next release 23.2.0

Our concern is that this might be hiding a deeper issue, in which case we would potentially see a different error, but we have decided to give it a go and to leave this ticket open so you guys can tell us if this makes things better.

Note that 23.2.0 should be available in 1/2 weeks

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment] 2020-06-11 10:51
Hi guys,

AG-4206 was released with 23.1.1

I will leave this ticket for a few days, can you guys check if this has helped?

Thanks

**Comment by csicky** [comment] 2020-06-11 11:11
Using 23.1.1 and I can confirm that I don't see the error anymore. Thank you for the fix.

**Comment by makinggoodsoftware** [comment] 2020-06-19 11:07
Hi guys,

Will close this ticket next week unless you let us know that this has not fixed this issue

Thanks

**Comment by rahulsharma114** [comment] 2020-06-23 18:08
I see this error in react project. I am using these versions of ag-grid.
    "ag-grid-community": "21.0.0",
    "ag-grid-enterprise": "21.0.0",
    "ag-grid-react": "21.0.0",

**Comment by csicky** [comment] 2020-06-23 18:18
> 
> 
> I am still facing this error in react project. I am using these versions of ag-grid.
> "ag-grid-community": "21.0.0",
> "ag-grid-enterprise": "21.0.0",
> "ag-grid-react": "21.0.0",

It was fixed with version  23.1.1, so obviously on version 21.0.0 it will still show the error.

**Comment by rahulsharma114** [comment] 2020-06-29 21:18
> > I am still facing this error in react project. I am using these versions of ag-grid.
> > "ag-grid-community": "21.0.0",
> > "ag-grid-enterprise": "21.0.0",
> > "ag-grid-react": "21.0.0",
> 
> It was fixed with version 23.1.1, so obviously on version 21.0.0 it will still show the error.

But I am unable to install 23.1.1 version as it says "No matching version found for ag-grid-react@23.1.1" How do I intsall this version?

**Comment by ybarbaria** [comment] 2020-06-29 21:24
npm update ag-grid-react
OR
yarn upgrade ag-grid-react

![image](https://user-images.githubusercontent.com/5574663/86057507-65ea7d00-bab3-11ea-932a-418733ccc8f2.png)

**Comment by rahulsharma114** [comment] 2020-06-29 21:44
@ybarbaria I tried that but in my case its just updating all ag-grid dependencies to ^23.1.0 and not beyond that. I also have the license key for enterprise version but not able to update dependencies to latest version.

**Comment by ybarbaria** [comment] 2020-06-29 21:52
You can try to install the last version : 
`npm i ag-grid-react@latest`
Have you try to update all your package? `npm update`
You can also use `npm outdated` to see Current and Latest version of all packages. 
If still nothing work you still can manually update your package.json and `npm install`

**Comment by rahulsharma114** [comment] 2020-06-29 22:02
manually updating gives the same error "No matching version found for ag-grid-react@23.1.1". The other ways of updating also not working. And its weird that for me latest version is shown as 23.1.0.
![image](https://user-images.githubusercontent.com/8522138/86060451-57d03880-ba82-11ea-882f-e665bc96b2a7.png)

**Comment by ybarbaria** [comment] 2020-06-29 22:12
Can you copy paste your package.json updated ?

**Comment by makinggoodsoftware** [comment] 2020-07-02 11:47
Hi guys, 

I think its safe to say that the issue is fixed in the latest version since I can see there is some activity in the thread, I will keep it open but flag it as managed by the community

Thanks

**Closed** 2020-08-01 13:17 UTC
Labels: managed-by-community, wontfix

**Comment by viplavsoni** [comment] 2020-09-01 10:03
> I found out why I was seeing this error and how to fix it.
> 
> In the app I'm working on we have tabs and each tab renders a table using ag-grid.
> We were seeing the error bellow sometimes when switching tabs:
> `TypeError: Cannot read property 'addEventListenerOutsideAngular' of null`
> 
> After debugging it, I found out that `onGridReady={params => setGridApi(params.api)}` was running after my effects.
> My effects had the "lastest" gridApi but for the old tab.
> 
> I fixed it by adding a unique key to the component that has ag-grid:
> `<WorksheetTable key={instanceId} />;`
> 
> That forces the component to be destroyed and recreated every time we switch tabs.
> 
> I hope this fix can help someone.

Can you explain where you added that key
