### ISSUE TITLE
Screen Readers say "Open Filter Menu" in the header text of Tables With Floating Filters

### ISSUE THREAD

**Issue by frastlin** [ag-grid/ag-grid#4430] opened 2021-04-01 23:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

## Providing a Reproducible Scenario

1. Using either NVDA or Jaws, visit the [Floating Filters](https://www.ag-grid.com/javascript-grid/floating-filters/) example.
2. Navigate to any cell, either with arrow keys, tab, or with table navigation
3. The screen reader will add "Open filter menu" to the end of any column with a filter.

### Current behavior

The screen reader adds "Open filter menu" to the header title of every filtered column.

### Expected behavior

There should be no "open filter menu" appended to the end of the header. There is already a "Open filter menu" button, and adding an element (like a menu) into the header does not change the text, so there is no reason for that extra text.

## Please tell us about your environment:

NVDA 2020.4, Jaws 2019. Chrome version Version 89.0.4389.90 (Official Build) (64-bit).
Windows 10.

## AG Grid version:
Whatever version is on the example:
https://www.ag-grid.com/javascript-grid/floating-filters/

**Comment by makinggoodsoftware** [comment] 2021-04-12 15:59
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-04-27 14:12
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v23.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5284 [Regression] When using a floating filter, floating filter inputs and button get announced by JAWS and NVDA with each cell value**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by frastlin** [comment] 2021-04-27 19:23
Thank you, it really means a lot that you're taking accessibility so seriously. I look forward to not having that "Open Filter Menu" text!

**Comment by makinggoodsoftware** [comment] 2021-05-11 15:49
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-05-11 15:49 UTC
Labels: ag-5284, in_zendesk
