### ISSUE TITLE
Columns overlap while using 'flex' and 'minWidth' properties in column definitions

### ISSUE THREAD

**Issue by roko7** [ag-grid/ag-grid#4956] opened 2022-03-03 12:29 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
I defined column widths using **flex** and **minWidth** properties. A strange behavior appears when **clicking on a drag handle** of a column, after another column has been **resized**. 

I made a **plunker** to demonstrate this: https://plnkr.co/edit/pPUjwhivC2K8nKKg

To **reproduce**, do the following:
- Shrink last column by dragging
- Click, without dragging, on drag handle of first column 

What then seems to happen is that second column stretches overlapping third column. Third column stays in place.

### How columns look after resizing:
![image](https://user-images.githubusercontent.com/11575244/156563725-914d6ec8-742f-47a3-9ff0-9eaea9bd8952.png)

### After clicking drag handle of first column:
![image](https://user-images.githubusercontent.com/11575244/156564253-78dc1c9b-f51f-45f0-a97e-70a5d2da249a.png)

Columns 

* **AG Grid version:**
Imported ag-grid-community@27.0.1 version, same as in Plunker example from Column flex section of documentation.

* **Browser:**
Reproduced in multiple browsers, I don't think this is browser specific.

**Comment by chefnoname** [comment] 2022-03-21 12:47
Hello roko7!

Thank you for your email and for the context you’ve provided.

This is the intended behaviour of the grid, when it comes to column sizing if you manually resize a column with flex either via the API or by dragging the resize handle, flex will automatically be disabled for that column. So as columns A & C are no longer flex but B is. Column B will take up the intended space which was freed by dragging columns A & C. I hope that was a helpful explanation heres a knowledge based article to further clarify the issue.

https://www.ag-grid.com/javascript-data-grid/column-sizing/#column-flex 

Regards,
Chef

**Comment by roko7** [comment] 2022-03-21 13:05
Hello @chefnoname !

Thank you for your reply, but I think you didn't understand the issue here.
I added some more cell content (larger strings) to my plunker example to better highlight how columns overlap.

This is a picture of what i get:
![image](https://user-images.githubusercontent.com/11575244/159266444-bf1ec74d-5108-4592-a5dc-ad0edfad7004.png)

I can't imagine this being intended.

Regards, Roko.

**Comment by kiril-matev** [comment] 2022-03-28 19:15
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6590 When resizing a column down and clicking the resize handle of a column 2 columns left, the middle column cell values render over the right-most column's cell values**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2022-04-07 10:11 UTC
Labels: in_zendesk, ag-6590
