### ISSUE TITLE
Print Ag-grid In RTL

### ISSUE THREAD

**Issue by Planit-Scheduler-Solutions** [ag-grid/ag-grid#5893] opened 2022-12-15 15:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Hi,
I work with angular 14 and ag-grid 28.2.1.
I get some problem when I want to print the ag-grid by use "window.print()".
The problem is when the body's direction is RTL and the ag-grid enableRtl featureis true.
After some debug I found that the grid in print layout move the scroll to the right and get in some conflict with the body css.
For reproduce the problem the only thing that need to do is dounload the demo in github:
https://github.com/Planit-Scheduler-Solutions/ag-grid-print-rtl .
Run npm i and thet run the project.
You will see in the top right print button that need click on.

**Current behavior**
The result that you will see is that the grid try to enter all the columns in side of the view:
![image](https://user-images.githubusercontent.com/82387265/207891759-9528d441-7e77-40b8-972a-8bb49dda4b6b.png)

**Expected behavior**
I expected to see the view like if the body is in ltr direction and enableRtl= false:
![image](https://user-images.githubusercontent.com/82387265/207892517-4c39c592-16ea-4ad1-8fe0-02751b221b0c.png)

**Please tell us about your environment:**
Angular 14.2.12,
typescript  4.7.2
Nodejs 18.12.1
* **AG Grid version:** X.X.X
"@ag-grid-community/angular": "^28.2.1",
    "@ag-grid-community/client-side-row-model": "^28.2.1",
    "@ag-grid-community/core": "^28.2.1",
    "@ag-grid-community/csv-export": "^28.2.1",
    "@ag-grid-community/styles": "^28.2.1",

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~4.7.2"
es2020

Please help.

**Comment by Planit-Scheduler-Solutions** [comment] 2022-12-18 12:56
After some play with the demo that  I create I found, if I don't give direction to the body element and give the direction to to parent div of the grid like this:
`
<div class="main-container" dir="rtl">
    <app-print-list></app-print-list>
</div>
` 

I get broken list like this:
![image](https://user-images.githubusercontent.com/82387265/208299418-9dcc0cc9-9239-4765-8f8d-55a3a4b6b685.png)

Please help.

**Comment by StephenCooper** [comment] 2022-12-19 14:36
I have run your project but for both enableRtl true and false I get all the columns in the print result. See both attached files. So I am not able to reproduce your issue.

[Printltr.pdf](https://github.com/ag-grid/ag-grid/files/10260000/Printltr.pdf)
[PrintRtl.pdf](https://github.com/ag-grid/ag-grid/files/10260001/PrintRtl.pdf)

**Comment by Planit-Scheduler-Solutions** [comment] 2022-12-20 07:31
Hi Stephen,
I have remove the old repository above and create new one that show the broken rows bug.
This is the new repository:

**Comment by StephenCooper** [comment] 2022-12-20 09:22
I do not see an issue with the Grids behavior if you remove the `direction: rtl;` from the main container style. In both cases without that set, the grid prints as expected. I will get a second opinion but I do not believe there is an issue with the grid.

**Comment by Planit-Scheduler-Solutions** [comment] 2022-12-20 09:35
If I remove the direction the grid will show the end of the columns.
![image](https://user-images.githubusercontent.com/82387265/208633806-b8e6d242-325a-4be4-90d3-6c863fb7de67.png)

**Comment by StephenCooper** [comment] 2022-12-23 15:30
Thanks for your patience while I got assistance on this.

This looks like it is the default behavior from printing RTL… apparently it tries to anchor the page from the left even though the direction is RTL.
I don’t think there is anything we can do about it and might be something that has to be addressed by filing a ticket with Chromium.

This example shows the issue without AG Grid. Check the Print behavior with LTR and then with RTL

https://plnkr.co/edit/ezJ3Ig4yRCyz1fjn?open=lib%2Fscript.js

**Closed by StephenCooper** 2022-12-23 15:30 UTC
