### ISSUE TITLE
Support print on demand

### ISSUE THREAD

**Issue by NaNgets** [ag-grid/ag-grid#2172] opened 2018-01-27 22:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I want to view and play with my grid (whilst having domLayout = autoLayout and pagination enabled), and at some point in time I want to print it, I have two problems:
1. I can't dynamically change the domLayout,
2. I can't dynamically cancel\remove pagination.

**Expected behavior**

1. Being able to change the domLayout using api.
2. Being able to remove pagination using api.

**Minimal reproduction of the problem with instructions**

Create a grid with domLayout=autoHeight and pagination enabled, print will not be available.

**What is the motivation / use case for changing the behavior?**

Enabling printing on demand.

**Please tell us about your environment:** Irrelevant.

* **ag-Grid version:** 15.0.0

* **Browser:** All of them

* **Language:** AngularJS 1.5

**Comment by GrandJu13** [comment] 2018-09-19 08:28
I have the same behaviour. I can define domLayout in the gridOptions definition but I can't make `this.gridApi.setDomLayout('print')`
The setDomLayout() api method seems not reachable. Impossible to reproduce the same exemple in the Printing documentation (https://www.ag-grid.com/javascript-grid-for-print/)

**Comment by makinggoodsoftware** [comment] 2018-10-11 15:15
Hi, this has changed quite  a lot since v15.0

I am going to close this, I would suggest you guys have a look at the new API and methods as I think this will cover these cases

If you think there are still pending issues to be fixed, please feel free to open a new ticket

Thanks

**Closed by makinggoodsoftware** 2018-10-11 15:15 UTC
