### ISSUE TITLE
ag grid excel export number format is adding zero's for null values

### ISSUE THREAD

**Issue by srikanthuidev98** [ag-grid/ag-grid#7534] opened 2024-02-02 11:23 UTC
**Description**
using value formatter i'm formatting the numbers using the internationalization. This is how I get data from api "123456.3456 and formatting it by passing a format type #,###;(#,###);0. My grid ui is displaying 123,456 and my excel is also displaying the same but if I get a null value then excel is displaying a 0.

**Providing a Reproducible Scenario**

`
valueFormatter: (params) => {
let format = "#,###;(#,###);0."
let value = params.value
if(format && value) {
return internationalization.formatNumber(Number(value), {format:format});
}
`

**Current behavior**
For null values, ag grid is adding zeros in the excel. In the ag grid ui null are shown empty cells.

**Expected behavior**
For null values export excel should not add zeros, excel should show empty cells.

**Please tell us about your environment:**
`
"dependencies": {
    "@angular/core": "^14",
    "@angular/common": "^14",
    "@angular/forms": "^14",
    "@angular/platform-browser": "^14",
    "ag-grid-angular": "^31.0.2",
    "ag-grid-community": "^31.0.2",
    "ag-grid-enterprise": "^31.0.2",
    "moment-timezone": "0.5.44",
    "date-fns": "3.3.0"
  }
`
@LouisMoore-agGrid  @adam-ag-grid @AndrewGlazier @FahadagGrid @robindenton-ag-grid @LouisMoore-agGrid 

let me know how to resolve this thanks

**Comment by AG-Zoheil** [comment] 2024-02-02 12:14
Hi @srikanthuidev98,

Thank you for reporting this.

We'd be happy to look into this, but I need to clarify a few points beforehand:

1. The most efficient way for us to look into issues would be for you to provide a **live example reproducing the issue**. As you already know, AG Grid can be configured in so many different ways that this saves precious time on both sides. The easiest way to do is would be to send a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

2. The excel export is an enterprise feature. If you are an enterprise customer I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your questions answered.

3. Lastly, when raising issues, there is no need to tag individual people. All issues raised will get addressed in due time by the necessary people.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by srikanthuidev98** [comment] 2024-02-02 15:10
@AG-Zoheil 

for some reason issue is not reproducible inside CodeSandbox, but I have created a sample code here https://codesandbox.io/p/sandbox/ag-grid-modules-forked-jjq6zp?file=%2Fapp.component.ts%3A18%2C76
The same code in vs code is not working, in CodeSandbox inside excel it is not adding zeros for null data but it is adding when i run inside vs code.

**Comment by AG-Zoheil** [comment] 2024-02-05 10:44
Thanks for the codesandbox link @srikanthuidev98.

I'm afraid I am also unable to reproduce it - please double check your configuration and dependencies in your vs code set up.

**Comment by srikanthuidev98** [comment] 2024-03-27 07:02
Still an issue for me, not fixed yet

Thanks,
Srikanth

**Comment by cjdreiss** [comment] 2024-03-27 13:45
So I was able to get it to display the unexpected behavior (null becomes 0) in your demo. 

You didn’t type your excel styles in the demo, and it says “dateType” Number instead of “dataType” Number. 

Actually setting the dataType property to Number causes nulls to get forced to 0. No data type does not. It seems like excel knows it’s a number, so maybe the fix is not to set one? Seems like a bug to me though.

**Comment by kiril-matev** [comment] 2024-04-03 21:38
Hello @srikanthuidev98, @cjdreiss,

I was able to reproduce the behavior you described. Specifically as @cjdreiss mentioned, setting dateType="Number" in the gridOptions.excelStyles, null values are exported as 0 values in Excel.

1. Open https://plnkr.co/edit/2bHqdiWcM1LEDppo?open=main.js
Actual: Second row value in the NUMBER column is empty (null)
2. Click button above grid
3. Open exported Excel file
Actual: Second row value in the NUMBER column is 0

This is the issue you're reporting, correct?

**Comment by cjdreiss** [comment] 2024-04-03 22:57
Yes, that is the issue I'm running into.  Not setting the DataType to Number seems to fix it but I don't think its correct behavior, and might possibly lead to other issues in case that DataType being set to Number is important in some other way I haven't seen yet.

**Comment by kiril-matev** [comment] 2024-04-04 16:16
Hello @srikanthuidev98, @cjdreiss,

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-11256 When setting dateType="Number" in the gridOptions.excelStyles for a column, null values are exported as 0 in Excel**

We try to fix bugs from one release to the next, so this should be fixed in the next release.

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2024-04-15 09:05 UTC
Labels: AG-11256
