### ISSUE TITLE
Any keyboard input in Master/Details mode in details row causes error

### ISSUE THREAD

**Issue by coopernyc** [ag-grid/ag-grid#3038] opened 2019-03-29 03:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

Yes, I'm an enterprise customer, will submit issue too

**Providing a Reproducible Scenario**

In master/detail in details row any keyboard input causes error (see image from your documentation page which has the same bug - Master/Details with Forms)

most likely in the code for GridPanel.ts
....

private processKeyboardEvent(eventName: string, keyboardEvent: KeyboardEvent): void {
        const cellComp = _.getCellCompForEvent(this.gridOptionsWrapper, keyboardEvent);
        const rowNode = cellComp.getRenderedRow().getRowNode();
        const column = cellComp.getColumn();
        const editing = cellComp.isEditing();

        if (!cellComp) { return; }

cellComp is checked for null after it has been used ;(
.....

**Current behavior**

Cannot read property 'getRendererRow' of null in ag-grid-community.js

**Expected behavior**
no error

**Please tell us about your environment:**
Windows, npm

* **ag-Grid version:** 20.2.0
same in 20.1.0
* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 

<img width="1159" alt="Screen Shot 2019-03-28 at 11 20 52 PM" src="https://user-images.githubusercontent.com/11201225/55207490-bbe5bc00-51b0-11e9-81a1-196b291fa01e.png">

**Comment by Christopherjl** [comment] 2019-04-09 16:04
Same here :-)

**Comment by coopernyc** [comment] 2019-04-11 15:12
Fixing it myself for now in a node-modules/ag-grid/community/dist/lib/gridPanel/gridPanel.js
<pre>
GridPanel.prototype.processKeyboardEvent = function (eventName, keyboardEvent) {
        var cellComp = utils_1._.getCellCompForEvent(this.gridOptionsWrapper, keyboardEvent);
        // move this check at the begging
        if (!cellComp) {
            return;
        }
        var rowNode = cellComp.getRenderedRow().getRowNode();
        var column = cellComp.getColumn();
        var editing = cellComp.isEditing();        
        var gridProcessingAllowed = !utils_1._.isUserSuppressingKeyboardEvent(this.gridOptionsWrapper, keyboardEvent, rowNode, column, editing);
        if (gridProcessingAllowed) {
<pre>

**Comment by makinggoodsoftware** [comment] 2019-04-16 15:10
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by nabeelz6** [comment] 2019-05-03 19:43
This is a duplicate of #3088 which was fixed already for the next release. I ran into this myself so looking forward to the official release containing the fix!

**Comment by makinggoodsoftware** [comment] 2019-05-10 09:04
This is in our backlog now and we are tracking it with the following reference and description.

AG-2893 - Docs - Master detail examples throw error when pressing a key in the detail form - (Custom Detail Cell Renderer with a Form)

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Closed by makinggoodsoftware** 2019-05-10 09:04 UTC
Labels: in_zendesk
