### ISSUE TITLE
v30.0.0 - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 0xflumedev** [ag-grid/ag-grid#6744] opened 2023-06-12 00:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
When running with package setup:
```
"ag-grid-community": "^29.0.0",
"ag-grid-react": "^29.0.0",
```
Everything works as intended. When flicking over to v30.0.0 encounter the error and the page does not load:
```
"ag-grid-community": "^30.0.0",
"ag-grid-react": "^30.0.0",
```
```
Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file: .../node_modules/ag-grid-community/dist/ag-grid-community.esm.js (6)
```

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Less than v30 doesn't throw error.

**Expected behavior**
Error is not thrown, and component functionality works as indended.

**Please tell us about your environment:**
React v18.2, next js v13.1, Windows 11, node v18.16, yarn 3.4.1.

* **AG Grid version:**
30.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
any

**Comment by seanlandsman** [comment] 2023-06-12 06:16
Are you able to provide a reproducible example of this issue?

**Comment by 0xflumedev** [comment] 2023-06-12 07:26
Hi @seanlandsman I just tried, and for some reason I don't see the issue on codesandbox, yet I swear I did earlier this morning.

I do however repeatedly get it on our enterprise next.js project, flicking between the two packages v29 (working), v30 (failing) with this error :( Not sure how to direct you from here.

![image](https://github.com/ag-grid/ag-grid/assets/94210181/0ac4e955-d1d9-4b36-b198-75e3da84af55)

**Comment by seanlandsman** [comment] 2023-06-12 07:27
Please note that in version 30 the following change was introduced:

AG-8674 - Default to use ES Modules in main field of package.json for modules

Please see our changelog for more details: https://www.ag-grid.com/changelog/

**Comment by jonahallibone** [comment] 2023-06-12 16:02
We also have this issue with `30.0.0` however we only get it when building.
<img width="1138" alt="Screenshot 2023-06-12 at 12 02 23 PM" src="https://github.com/ag-grid/ag-grid/assets/8886318/bca5c983-a54f-492a-a176-1a0032515772">

**Comment by seanlandsman** [comment] 2023-06-12 18:47
Are you able to provide a reproducible example for this?

I will try to reproduce my side but if you could provide something that would speed things along.

thanks

**Comment by jonahallibone** [comment] 2023-06-12 20:13
@seanlandsman yea definnitely. Here ya go:
https://codesandbox.io/p/sandbox/shy-water-s6mrrn

**Comment by KristjanVall** [comment] 2023-06-13 06:55
+1

**Comment by seanlandsman** [comment] 2023-06-13 10:02
@jonahallibone thanks for the repro - I can reproduce and can confirm that this is a bug

I've raised "AG-8756: ag-grid-community/ag-grid-enterprise with Next: Cannot use import statement outside a module" our side and we'll work to get this fixed in a patch release soon.

You can follow the status of feature requests, bugs and releases using our pipeline (it may take a few hours before this issue appears there):
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by KristjanVall** [comment] 2023-06-15 05:01
> @KristjanVall - can I please check that you're also using next.js?

Yes also using latest nextjs

**Comment by DzLadus** [comment] 2023-06-15 05:56
+1 here, same issue with ag-grid@30.0.0 and next.js

**Comment by DzLadus** [comment] 2023-06-15 05:57
@seanlandsman could u pls put the eta of the fix?
I have to know it bc I need to decide what to do with my current task in the sprint :)

**Comment by max-justice** [comment] 2023-06-15 09:06
Hi,

we have a similar issue but not using next.js
This shows up in our nx workspace space app using angular when trying to run our jest tests.

> Test suite failed to run
>     Jest encountered an unexpected token
>     Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>     Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>     By default "node_modules" folder is ignored by transformers.
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>      • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>  
> 
>     You'll find more details and examples of these config options in the docs:
> https://jestjs.io/docs/configuration
>     For information about custom transformations, see:
> https://jestjs.io/docs/code-transformation
> 
>     Details:
>    ..\node_modules\ag-grid-community\dist\ag-grid-community.esm.js:6
>     import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
>     ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>        at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
>       at ../../node_modules/ag-grid-angular/bundles/ag-grid-angular.umd.js:2:109
>       at Object.<anonymous> (../../node_modules/ag-grid-angular/bundles/ag-grid-angular.umd.js:5:3)

This has only recently shown up after updating to ag-grid@30.0.0, so I think this might be the same issue.

Running the app works without issues though.

If this is not related to this I'm sorry for addressing it here

**Comment by seanlandsman** [comment] 2023-06-16 08:17
@max-justice I think your issue is related but not the same - are you able to provide a repo for this?

**Comment by seanlandsman** [comment] 2023-06-16 08:19
For the Next users unfortunately although I have some changes we'll be releasing to our packages I don't believe that this will help you.

The underlying issue appears to be that Next.js does play nicely with ESM ES6 libraries - it has support but it seems experimental and isn't working for all use cases.

I will attempt to find a way forward for you however and update as soon as possible.

**Comment by max-justice** [comment] 2023-06-16 12:51
@seanlandsman i think [6766](https://github.com/ag-grid/ag-grid/issues/6766) has provided a repo, but it has been closed for this issue here. but its exactly the issue we have observed

**Comment by seanlandsman** [comment] 2023-06-16 12:56
I see - I'll reopen 6766 as I don't believe it's the same issue. Thanks

**Comment by jonahallibone** [comment] 2023-06-16 15:33
https://github.com/vercel/next.js/discussions/35217#discussioncomment-2343861 Not sure if this is a relevant comment which might help

**Comment by seanlandsman** [comment] 2023-06-16 23:43
Can you please try `ag-grid-react` 30.0.2

and add the following to your `next.config.js`: 

`transpilePackages: ['ag-grid-community', 'ag-grid-react'],`

**Comment by DzLadus** [comment] 2023-06-17 17:43
@seanlandsman 
![image](https://github.com/ag-grid/ag-grid/assets/46032365/0b2d91ed-0158-48f7-a635-9eeb8e673ae4)

**Comment by seanlandsman** [comment] 2023-06-19 08:08
@DzLadus please upgrade to `ag-grid-community` 30.0.2 - as you're an enterprise customer I'd recommend you contact support for further assistance at info@ag-grid.com. You'll get much quicker responses.

thanks

**Closed** 2023-06-19 08:47 UTC
Labels: ag-grid engaged, AG-8756

**Comment by jgiunta1** [comment] 2023-06-21 00:18
Why was this closed? Its not fixed

**Comment by DzLadus** [comment] 2023-06-21 08:26
@seanlandsman why you closed that?
It is still not fixed

**Comment by seanlandsman** [comment] 2023-06-21 08:53
@DzLadus based on the repos provided - and my own tests - I believe this to be resolved.

If you can provide a new repro of the issues you're seeing I'd be happy to take another look

**Comment by camiyu1** [comment] 2023-06-28 20:23
> Can you please try `ag-grid-react` 30.0.2
> 
> and add the following to your `next.config.js`:
> 
> `transpilePackages: ['ag-grid-community', 'ag-grid-react'],`

That option solved my issue.

**Comment by cmishra** [comment] 2023-06-29 00:23
Given how popular nextjs is, it might be a good idea to call this out on the onboarding docs for react-ag-grid?

**Comment by seanlandsman** [comment] 2023-06-29 06:29
> Given how popular nextjs is, it might be a good idea to call this out on the onboarding docs for react-ag-grid?

this is reasonable - I've added a note to our breaking changes but will do the same for the getting started docs

**Comment by jonahallibone** [comment] 2023-06-29 18:36
Can we get an explanation in this thread about why that is necessary?

**Comment by seanlandsman** [comment] 2023-07-04 08:23
@jonahallibone I've just released 30.0.3 which makes this step unnecessary now

**Comment by kieren-harvey-shell** [comment] 2023-07-06 06:52
I'm seeing this issue on 30.0.2 and 30.0.3:
```
    Details:

   ~\node_modules\ag-grid-react\lib\main.mjs:2
    export { AgGridReact } from './agGridReact.mjs';
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```
I'm getting this error during test execution (jest). 

My understanding is that we want to exclude it from being transformed? 
jest.config.js
transformIgnorePatterns: ["node_modules/(?!ag-grid-react)"],

In which case it shouldn't really matter what's in my babelrc but just for completeness...
```
  transform: {
    "\\.[jt]s[xm]?$": "babel-jest",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/config/fileTransformer.js",
  },

.babelrc

{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ],
    "@babel/preset-typescript",
    "@babel/modules"
  ],
  "plugins": [
    [
      "babel-plugin-transform-import-ignore",
      {
        "patterns": [".css"]
      }
    ]
  ]
}
```

**Comment by sebas0811buitrago** [comment] 2023-07-10 14:59
Hi  @seanlandsman  I installed the following version 
```
    "ag-grid-community": "^30.0.3",
    "ag-grid-enterprise": "^30.0.3",
    "ag-grid-react": "^30.0.3",
```
and added the following line to my next.config.js

`    transpilePackages: ['ag-grid-community', 'ag-grid-react']`

but I keep getting this error: 

```
Error: require() of ES Module /Users/sebastianbuitrago/Documents/HealthNextProjects/healthnexus-provider-groups-ui/node_modules/ag-grid-react/lib/main.mjs not supported.
Instead change the require of /Users/sebastianbuitrago/Documents/HealthNextProjects/healthnexus-provider-groups-ui/node_modules/ag-grid-react/lib/main.mjs to a dynamic import() which is available in all CommonJS modules.
```

Any suggestion on that?

**Comment by seanlandsman** [comment] 2023-07-11 07:46
@kieren-harvey-shell Please refer to the jest section here: https://www.ag-grid.com/javascript-data-grid/testing/

@sebas0811buitrago please contact info@ag-grid.com for enterprise support

thanks

**Comment by DzLadus** [comment] 2023-07-17 11:05
@kieren-harvey-shell have you fixed your error with jest?
I am getting absolutely the same

**Comment by knovu** [comment] 2023-07-28 15:09
@seanlandsman, still getting same situation with AG-Grid ^30.0.3, we are also an enterprise customer.

**Comment by seanlandsman** [comment] 2023-07-28 15:20
We've just release 30.0.6 - please upgrade and retry.

I'll update here shortly with release notes

**Comment by knovu** [comment] 2023-07-28 15:20
> We've just release 30.0.6 - please upgrade and retry.
> 
> I'll update here shortly with release notes

Thank you will do, and will remove **ag-grid-community** since we don't need.
