### ISSUE TITLE
applyColumnState doesn't always work on gridReady for vue sdk

### ISSUE THREAD

**Issue by sk-tjdownes** [ag-grid/ag-grid#6807] opened 2023-06-24 00:18 UTC
[x] bug report

**Requesting Community Support**

**Reproducible Scenario**
Please see (sorry, plunker does work for me)
https://codesandbox.io/s/aggrid-vue-applycolumnstate-rxxrvp?file=/src/App.vue:1747-1748

**Current behaviour**
When applying column state, AG Grid will not apply the state on `gridready`. Instead, I have to use a `setTimeout` to wait ~1.5 seconds to apply the column settings.

**Expected behaviour**
As per the docs, this should happen on `gridready`

**Environment**
Any OS including Windows 11 Pro 10.0.22621Build 22621
Any browser including Chrome Version 114.0.5735.134 (Official Build) (64-bit)
Vue 3.3.4
Vite 4.3.9
Node 18.x

* **AG Grid version:** 30.0.3
* **Language:** ES6/7

**Comment by kiril-matev** [comment] 2023-06-26 10:13
Hello @sk-tjdownes,

Thank you for reporting this using an example - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8781 [Regression] When applying column state before setting row data with cell data types, the column state is overwritten**

Until this is fixed, you can avoid this bug by turning off automatic data type inference by setting cellDataType=false in defaultColDef. I've modified your example to show this approach working:
https://codesandbox.io/s/aggrid-vue-applycolumnstate-forked-zj55tq?file=/src/App.vue

This bug will be fixed in our next release in mid-July.

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-07-14 14:58 UTC
Labels: AG-8781

**Comment by sk-tjdownes** [comment] 2023-07-20 00:32
Hi @kiril-matev! This looks like your team resolved this issue in 30.0.5, but we still see the problem on our end. Using the original codesandbox I provided and updating it to use 30.0.5 also reflects the problem still exists. Let me know what else I can provide to help resolve the issue.
