### ISSUE TITLE
Internet Explorer 11 is freezing if the dropdown menu of the column filter is open

### ISSUE THREAD

**Issue by dergroncki** [ag-grid/ag-grid#4906] opened 2022-02-04 13:43 UTC
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

Internet Explorer 11 is freezing if the dropdown menu of the column filter is open. Please open the following example in internet explorer 11:
https://www.ag-grid.com/react-data-grid/row-dragging/#example-simple-unmanaged

![AG-Grig-IE11-Freezing](https://user-images.githubusercontent.com/2815398/152537976-53c4dc22-a472-4cf8-a212-50edb9e5dd2a.gif)

I need to support Internet Explorer 11. I'm looking for a hint to locate the error in the right place in ag-grid so I can fix it. Of course, a solution would also be welcome.

I also posted the question on stackoverflow: https://stackoverflow.com/q/70959452/4934881?sem=2

**Expected behavior**

Internet Explorer should not freeze at all.

**Comment by makinggoodsoftware** [comment] 2022-02-17 10:41
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-02-18 19:00
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6416 When using Internet Explorer 11 with AG Grid v26.2, opening the column filter for a column using agTextColumnFilter freezes the page**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-03-03 15:29
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-03-03 15:29 UTC
Labels: in_zendesk, ag-6416
