### ISSUE TITLE
The ag grid document cannot be accessed

### ISSUE THREAD

**Issue by Clareyang213** [ag-grid/ag-grid#7377] opened 2023-12-22 03:31 UTC
The ag grid document cannot be accessed.
![image](https://github.com/ag-grid/ag-grid/assets/32185886/c0a2681a-b527-4241-afea-b9567de62e0c)

**Comment by Clareyang213** [comment] 2023-12-22 03:45
![image](https://github.com/ag-grid/ag-grid/assets/32185886/d5719fde-fe86-4a67-851c-fc4e8c2fe36a)

**Comment by AG-Zoheil** [comment] 2023-12-22 10:35
Hi @Clareyang213,

Can you please confirm the exact link you are trying to access?

I am attempting this link and it works fine for me: https://ag-grid.com/vue-data-grid/getting-started/.

Please also clear your cache before trying.

Thank you!

**Comment by AG-Zoheil** [comment] 2024-01-09 10:54
Thanks @Ravi-Velip,

I am still unable to reproduce this. The page loads fine for me and for my colleagues. I would assume you've cleared your cache already? If not please do so and try again.

To help us investigate this further can you please attempt the following:

1) How are you navigating to this page? Is it via the documentation page or a saved bookmark or a direct link
2) Can you reproduce the same behaviour in an incognito window?
3) Can you paste the exact URL in a comment here please?

Thank you!

**Comment by Clareyang213** [comment] 2024-01-10 09:03
> Thanks @Ravi-Velip,
> 
> I am still unable to reproduce this. The page loads fine for me and for my colleagues. I would assume you've cleared your cache already? If not please do so and try again.
> 
> To help us investigate this further can you please attempt the following:
> 
> 1. How are you navigating to this page? Is it via the documentation page or a saved bookmark or a direct link
> 2. Can you reproduce the same behaviour in an incognito window?
> 3. Can you reproduce the same behaviour in a different browser or even device (like your mobile phone)?
> 4. Can you paste the exact URL in a comment here please?
> 
> Thank you!

1. I accessed it directly through the link
2. Environment: Google Chrome 120.0.6099.200
3. Mobile phone cannot be accessed too
4. https://ag-grid.com/vue-data-grid/getting-started/

**Comment by Clareyang213** [comment] 2024-01-10 09:05
![image](https://github.com/ag-grid/ag-grid/assets/32185886/bc939847-f3bf-4b94-aecc-820dcf5de9ad)
![image](https://github.com/ag-grid/ag-grid/assets/32185886/28ac8d71-079f-4415-abe8-21be5108fd7c)

**Comment by Clareyang213** [comment] 2024-01-10 09:07
The page will first display and then become a blank page

**Comment by Clareyang213** [comment] 2024-01-10 09:30
> Hi @Clareyang213,
> 
> Can you please confirm the exact link you are trying to access?
> 
> I am attempting this link and it works fine for me: https://ag-grid.com/vue-data-grid/getting-started/.
> 
> Please also clear your cache before trying.
> 
> Thank you!

Connected to mobile hotspot, web pages can be accessed normally.
Thank you!

**Comment by AG-Zoheil** [comment] 2024-01-10 10:03
Thank you for confirming. Closing this.

**Closed by AG-Zoheil** 2024-01-10 10:03 UTC
Labels: invalid
