### ISSUE TITLE
resetColumnState ignores `initial` properties on column definitions

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4545] opened 2021-06-25 20:54 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Calling `resetColumnState` leads to ag-grid parsing the initial columnDefs but it completely ignores any `initialX` properties, such as `initialHide`. Instead, it only checks for the stateful (old) ones (e.g. `hide`), and if one can't be found (i.e. it's unset) it goes with the default value (i.e. `false` for `hide`).

Reproduction:
https://plnkr.co/edit/UbcwLHD3QUrlwJNG

As you can see, `athlete` remains hidden at all times because the state is coded as such. However, `age` is hidden initially but once I hit `Reset State` it becomes visible.

The incorrect code lives here:
https://github.com/ag-grid/ag-grid/blob/7489319814f420b013115bd9f0cebd73b862f17f/community-modules/core/src/ts/columns/columnModel.ts#L1785-L1811

An example is `hide` on line 1789:
https://github.com/ag-grid/ag-grid/blob/7489319814f420b013115bd9f0cebd73b862f17f/community-modules/core/src/ts/columns/columnModel.ts#L1789

**Expected behavior**

The logical expected behavior when resetting column state is to take into consideration the `initialX` properties.
E.g.:
1. Check if `hide` is set, if it is, use it
2. If it's not set, check if `initialHide` is set, if it is, use it
3. If none of the above were set, pick a default value (e.g. `false`)

The above could look like this in code:
```ts
const hide = colDef.hide ?? colDef.initialHide ?? false;
```

**Please tell us about your environment:**
Irrelevant.

* **AG Grid version:** 25.3.0 (latest)

* **Browser:** Irrelevant.

* **Language:** Irrelevant.

**Comment by makinggoodsoftware** [comment] 2021-07-01 16:21
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-07-12 19:08
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5521 When calling resetColumnState, initialHide column property value not applied**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-07-14 16:13
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-07-14 16:13 UTC
Labels: ag-5521, in_zendesk
