### ISSUE TITLE
Use agSelectCellEditor to display keys when editing

### ISSUE THREAD

**Issue by himeyon** [ag-grid/ag-grid#5197] opened 2022-05-18 05:56 UTC
When using agSelectCellEditor, the key is displayed with a single click.
Version 27.1.0 or earlier the value was displayed.

https://www.ag-grid.com/javascript-data-grid/reference-data/
https://plnkr.co/edit/rPrMdOM8Ft8nlUs1

![image](https://user-images.githubusercontent.com/4468822/168967403-3ccb5e3e-1243-4c13-ac63-189aa092142c.png)

* **AG Grid version:** 27.2.1 27.3.0
* **Language:** [all]

**Comment by himeyon** [comment] 2022-05-18 06:08
Version 27.1.0 does not occur.

![image](https://user-images.githubusercontent.com/4468822/168968855-cc073544-c6ef-4cb7-83a7-15a341c0a4e0.png)

**Comment by himeyon** [comment] 2022-05-23 08:50
Why is the response so slow despite the obstacle being so obvious?
Would it be faster to contact Enterprise Support?

**Comment by makinggoodsoftware** [comment] 2022-05-26 11:33
Hi,

> Why is the response so slow despite the obstacle being so obvious?
> Would it be faster to contact Enterprise Support?


Yes, if you contact us via enterprise support, you should usually hear from us within hours

**Comment by makinggoodsoftware** [comment] 2022-05-26 11:34
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-06-01 21:22
Hello @himeyon !
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a regression.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6847 [Regression] When starting an edit with agSelectCellEditor the valueFormatter is not called and console warnings are displayed**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-06-10 13:18
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-06-10 13:18 UTC
Labels: in_zendesk, ag-6847
