### ISSUE TITLE
Ag-grid doesn't start when having custom functions in Object.prototype

### ISSUE THREAD

**Issue by Althain** [ag-grid/ag-grid#8650] opened 2024-09-05 09:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Framework: Angular, but potentially others too

Reproduction
[https://stackblitz.com/edit/stackblitz-starters-n21a72?file=src%2Fmain.ts](https://stackblitz.com/edit/stackblitz-starters-n21a72?file=src%2Fmain.ts)

**Current behavior**

- When I extend Object.prototype with any function, then the ag-grid doesn't start due to error: "ERROR TypeError: rowCtrls[i].getAllCellCtrls is not a function"

**Expected behavior**

- When I extend Object.prototype, the ag-grid shouldn't fail

* **AG Grid version:** at least 28

**Comment by sabahang** [comment] 2024-10-07 15:24
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13081 Grid fails to load when extending Object.prototype with custom methods**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed by sabahang** 2024-10-07 15:24 UTC
