### ISSUE TITLE
Bug report: tooltip in detail grid

### ISSUE THREAD

**Issue by saguoran** [ag-grid/ag-grid#4596] opened 2021-07-21 11:49 UTC
**I'm submitting a  bug report**  (check one with "x")

**Providing a Reproducible Scenario**
- https://www.ag-grid.com/angular-grid/master-detail-grids/#example-static-template
- update project/app/app.component.ts line 56
```     { field: 'switchCode', tooltipValueGetter:  (params)=>"he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he he is not foo" },```
- A plunker link: https://plnkr.co/edit/EJxbpTItyq4EtT8U

**Current behavior**

it's in one line and not showing all text.
![image](https://user-images.githubusercontent.com/44708955/126481218-feff8f8c-4859-45a1-92b3-9a7cf56bed73.png)

**Expected behavior**

it should show all content.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by shuheb** [comment] 2021-08-03 13:20
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2021-08-04 09:58
Hello @saguoran !

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5585 When using master-detail, long tooltips are clipped by the detail grid viewport instead of being wrapped on multiple lines**

Please use this workaround until this is fixed - set popupParent: document.body on the detail-level grid as shown below:
https://plnkr.co/edit/n1EG3JKgwJK5i6Qd

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-08-09 10:22
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-08-09 10:22 UTC
Labels: ag-5585
