### ISSUE TITLE
Is there any way to show custom tooltip only when ellipsis is active?

### ISSUE THREAD

**Issue by asmitaghangare** [ag-grid/ag-grid#4761] opened 2021-11-09 11:09 UTC
Is there any way to show custom tooltip only when ellipsis is active. 

Can we customize css for tooltip eg - position - top, bottom, left, right, and margins?

Thanks

**Comment by makinggoodsoftware** [comment] 2021-11-23 15:54
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___
AG-3331
[Tooltip] Allow conditionally rendering tooltips

**Comment by makinggoodsoftware** [comment] 2021-12-03 10:43
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Closed** 2021-12-03 10:44 UTC
Labels: AG-3331

**Comment by c-harding** [comment] 2025-08-21 20:20
Hi @makinggoodsoftware, I see [in the changelog](https://www.ag-grid.com/changelog/) that AG-3331 was flagged as a duplicate, with version 31.0.0. What is it a duplicate of? I can’t see any mention of tooltips in the [release notes for 31](https://blog.ag-grid.com/whats-new-in-ag-grid-31/).

**Comment by AG-Zoheil** [comment] 2025-08-22 08:05
Hi,

This was closed as a duplicate of **AG-3856** which was implemented in v31.2.

Thanks!
