### ISSUE TITLE
Header checkbox selection behaviour change

### ISSUE THREAD

**Issue by flare256** [ag-grid/ag-grid#6399] opened 2023-03-29 20:04 UTC
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
[version 29.1.0](https://plnkr.co/edit/NfnrZEdPVfPXpDex?open=main.js&preview)
[version 29.2.0](https://plnkr.co/edit/QWafDTJrkbxEwKGT?open=main.js&preview)

Type phelps in quick filter and then click header checkbox.

**Current behavior**
Ag grid with column flags headerCheckboxSelection: true, headerCheckboxSelectionFilteredOnly: true, checkboxSelection: true and grid options with rowSelection: 'multiple'. At the beginning no rows are selected. If table is filtered, then click on the header checkbox changes it's status to indeterminate.

**Expected behavior**
When all filtered rows are selected, header checkbox state should be checked as in 29.1.0

* **AG Grid version:** 29.2.0

* **Browser:** all

* **Language:** all

**Comment by WonwooKang** [comment] 2023-03-31 01:45
We are experiencing the same issue.

When performing a 'Select All' after searching with the quick filter, it is not possible to deselect all as well.

The issue can also be reproduced on the example homepage at [Select Everything or Just Filtered](https://www.ag-grid.com/javascript-data-grid/row-selection/?#select-everything-or-just-filtered).

It does not occur in version 29.1.0, but downgrading the version is difficult due to freezing issues(AG-8075).

I am curious about the date when this patch will be applied.

https://user-images.githubusercontent.com/10667582/229001740-cc37f142-7699-4a60-b5ae-703bb0682c3d.mov

**Comment by AndrewGlazier** [comment] 2023-03-31 08:55
Hi,

Thanks for reporting this.

We have this bug to our backlog and we are tracking it with the following reference and description:
AG-8235 - [Regression] headerCheckboxSelectionFilteredOnly is not reversible

We try to fix bugs from one release to the next, so this should be fixed in the next release.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-8235) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks for bringing this up with us.

**Closed by AndrewGlazier** 2023-03-31 08:55 UTC
