### ISSUE TITLE
Custom Group Display Type not working on Pivot Mode

### ISSUE THREAD

**Issue by fabiot21** [ag-grid/ag-grid#6648] opened 2023-05-23 13:36 UTC
**I'm submitting a ...** 
```
[X] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
- When trying to do a custom group display type with pivot mode activated is ignoring "custom" display type and is using "singleColumns" instead.
- 
Live Example: https://plnkr.co/edit/I10vSc1JMSmw1zll?open=main.ts

**Current behavior**
Ignoring "custom" display type and using "singleColumn" display type

**Expected behavior**
should use 'custom' display type instead of 'singleColumn'

**Please tell us about your environment:**
Chrome browser 113.0, MacOS Ventura 13.1. JS Vanilla

* **AG Grid version:** 29.3.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

* **Language:** TypeScript 5.0

**Comment by kiril-matev** [comment] 2023-06-22 11:48
Hello @fabiot21,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8818 When using groupDisplayType: 'custom' with pivoting shows a single group column and turning pivoting off shows empty values in the group columns**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2023-06-22 11:48 UTC

**Comment by sabahang** [comment] 2025-11-25 14:44
Hi 

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise license.

Kind Regards
