### ISSUE TITLE
Dealy in rendering React cells in versions >=25

### ISSUE THREAD

**Issue by robmcm** [ag-grid/ag-grid#4506] opened 2021-06-02 15:52 UTC
**I'm submitting a ...** 
[x] bug report => see 'Providing a Reproducible Scenario'

Note: I am an enterprise customer but currently unable to figure out how to sign up to the Zendesk site, once I figure that out I will report there too.
 
**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Since version 25 React cell rendering has become delayed when loading even for very simple components.
- Delayed React cell rendering in 25+:  http://plnkr.co/plunk/B8Iv860kcklRM15k 
- Non delayed rendering in 24.1: http://plnkr.co/plunk/qdBANpreJx3i6L2h

**Current behavior**
React cells take much longer to render, showing a blank cell or row (if all cells are react) until loaded. 

**Expected behavior**
In version 20 through 24.1 the cells load much faster, not delay is visible compared to the default renders (see punker when scrolling), with one exception in version 22 where the same behavior was visible.

**Please tell us about your environment:**
Punker on Mac OS, Chrome / Firefox 

* **AG Grid version:** 25.1.0
(in every version since 25)

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0"
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"

* **Language:** 
all

**Comment by makinggoodsoftware** [comment] 2021-06-04 16:09
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by robmcm** [comment] 2021-06-07 12:26
> Hi,
> 
> Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)
> 
> We will carry on there with the investigation and we will update you as soon as possible.
> 
> Thanks

Thank you, is there a link to the Zendesk issue? The site just seems to be a few tutorials and faqs (even when logged in).

**Comment by kiril-matev** [comment] 2021-06-10 14:38
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5431 [Regression] When calling redrawRows() API with custom cell renderers, the cell contents flash**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Closed** 2021-06-22 15:41 UTC
Labels: AG-5431, in_zendesk
