### ISSUE TITLE
Default context still displays with `preventDefaultOnContextMenu` and `supressContextMenu`

### ISSUE THREAD

**Issue by rcketscientist** [ag-grid/ag-grid#4655] opened 2021-09-02 18:15 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
`preventDefaultOnContextMenu` and `supressContextMenu` still shows the browser menu.

Repro:
https://stackblitz.com/edit/ag-grid-react-hello-world-oxp5yf

**Expected behavior**

I was hoping this addressed it:

> AG-5505 |   | 26.0.0 | [Regression] When suppressing AG Grid context menu (suppressContextMenu=true) and suppressing browser context menu (preventDefaultOnContextMenu=true), right-clicking still shows browser context menu

**Please tell us about your environment:**

Win, VsCode, npm, Storybook

* **AG Grid version:** X.X.X

26.0.0

* **Browser:**

"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by kiril-matev** [comment] 2021-09-07 14:31
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v25.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5735 [Regression] When setting preventDefaultOnContextMenu=true and right-clicking the ag-grid-community grid, the default context menu is displayed**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2021-09-16 09:53
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2021-09-16 09:53 UTC
Labels: in_zendesk, ag-5735

**Comment by kiril-matev** [comment] 2021-10-12 09:28
Thanks for your response. 

1. As this was previously available, we've now reinstated this as a regression. This is now a live issue for us and you can see it in the pipeline.
2. I agree with your point that the ticket rejection should have been listed in the changelog. This was due an omission on our part to progress this item.
