### ISSUE TITLE
"Toggle Select All Columns" in sideBar doesn't work as expected after upgrade to v25

### ISSUE THREAD

**Issue by iSerganov** [ag-grid/ag-grid#4346] opened 2021-02-10 20:47 UTC
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Versions:
Ag grid - 25.0.1
Angular - 8
Typescript 3.4.5
Browser: Chrome/Firefox

"Toggle Select All Columns" checkbox is misbehaving after update to v25. (on v24 it works correctly).
When I click "Toggle Select All Columns" inside the sideBar it toggles columns visibility only after first time click.
Further clicking on it only changes self checked state and doesn't affect the list of columns:

![image](https://user-images.githubusercontent.com/41109559/107569849-71795700-6bf1-11eb-819e-057c1e3f6bf1.png)

However if I write anything in search column input it will work as expected exactly one time after that and again further clicking will not affect checked state of other column checkboxes.

![image](https://user-images.githubusercontent.com/41109559/107570164-d7fe7500-6bf1-11eb-9dea-bacb3927337c.png)
![image](https://user-images.githubusercontent.com/41109559/107570355-12681200-6bf2-11eb-864a-a9f29c9d6216.png)

**Comment by makinggoodsoftware** [comment] 2021-02-15 12:39
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment] 2021-02-17 15:50
Hi,

Thank you for your email.

This seems to be working on our end.

Please see https://plnkr.co/edit/x2OkhbvGIiE2Qkrb

Could you please fork the example above and reproduce your issue so that we continue investigating?

Thanks

**Comment by iSerganov** [comment] 2021-02-17 19:23
Hello Ahmed,

Thank you for looking into this.

You may find a plnkr with issue below:
https://plnkr.co/edit/BwJsECJQBmo5TtK0

Kind regards,

Igor Serganov

ср, 17 февр. 2021 г. в 17:50, Ahmed Abdel Gadir <notifications@github.com>:

**Comment by kiril-matev** [comment] 2021-02-24 17:23
Hello Igor!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-5089 [Regression] When suppressColumnStateEvents=true, the selectAll checkbox in the columnsMenuTab/columnsToolPanel does not check column items in list**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Please note we will not update this GitHub issue when this is implemented.

The best way to get an update is to sign up for ag-Grid new release notifications. Once a new ag-Grid version is released, look for the item reference above on the changelog page to see if it's included in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us.

**Comment by iSerganov** [comment] 2021-03-09 20:32
@kiril-matev 
Thank you for the investigation and detailed explanation. 
Honestly, to me it is strange when the usage of suggested by the previous version contract breaks functionality after version upgrade (at least there must have been notable messages with label BREAKING in all possible documents).

However the above approach worked for me, therefore if you still do not consider fixing this, you may close the issue.

**Comment by kiril-matev** [comment] 2021-03-10 13:42
Hi @iSerganov!

Thanks for getting back to me.

You're correct - the **suppressColumnStateEvents** property wasn't deprecated as it should have been in v24.0 once the new apply state mechanism was added, giving a lot more flexibility and control over column state. So you're right - the **suppressColumnStateEvents** property should have been deprecated at that point and we should have added this to the changelog as a breaking change, providing the new approach to achieve the same functionality.

I apologise for this oversight and I hope we'll be able to document our breaking changes better going forward.

I appreciate your feedback - please submit new Github issues for any other bugs/issues you'd like to report. We're keen to investigate them!

**Closed** 2021-03-10 18:33 UTC
Labels: in_zendesk
