### ISSUE TITLE
 Uncaught TypeError: Cannot read properties of undefined (reading 'onResizeStart')

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6309] opened 2023-03-14 03:43 UTC
```jsx
headerGroupCellCtrl.js:71 Uncaught TypeError: Cannot read properties of undefined (reading 'onResizeStart')
    at HeaderGroupCellCtrl2.resizeLeafColumnsToFit (headerGroupCellCtrl.js:71:33)
    at ColumnModel2.autoSizeColumnGroupsByColumns (columnModel.js:465:37)
    at ColumnModel2.autoSizeColumns (columnModel.js:406:18)
    at ColumnModel2.autoSizeAllColumns (columnModel.js:481:14)
    at ColumnApi2.autoSizeAllColumns (columnApi.js:180:87)
    at Object.onFirstDataRendered (MyTable.tsx:175:15)
    at GridOptionsWrapper2.globalEventHandler (gridOptionsWrapper.js:1543:30)
    at eventService.js:132:129
    at VanillaFrameworkOverrides2.dispatchEvent (vanillaFrameworkOverrides.js:33:9)
    at eventService.js:132:83
```

```jsx
onFirstDataRendered={(params) => {
              params.columnApi.autoSizeAllColumns(false)
            }}
```

**Comment by StephenCooper** [comment] 2023-03-14 11:02
I have an example here that shows this working. 

https://plnkr.co/edit/nFT0AqYN6IkgC2TT?open=index.tsx

I am not sure why this is not working for you but without a code sample we will not be able to investigate why you are running into that error above.

**Comment by WonwooKang** [comment] 2023-03-14 13:24
I also encountered the same error. 
The error occurred when I followed the steps below:

1. One of the two children of the grouped column located at the end of the table was shadowed on the browser.
2. Loaded grid data.
3. Called the columnApi.autoSizeColumns(colIds, false) function.
-> Error occurred.

Here's an example of a grouped column:

| —————— group ————— |
| — children — | — children — |

The second (right-hand side) child column was partially hidden due to the size of the browser window.

**Comment by WonwooKang** [comment] 2023-03-16 02:05
Here is an example where an error occurs during resizing:

https://plnkr.co/edit/f3WZ9J7hAq5lUB6P?preview

It took a long time because it was difficult to reproduce. I'm sorry about that.

Here is a screenshot of the window size where the error was reproduced.

[before resizing]
![before resizing](https://user-images.githubusercontent.com/10667582/225490688-236e1bc9-7e25-4d1f-a344-5e71dda6f5d0.png)

[after resizing]
![after resizing](https://user-images.githubusercontent.com/10667582/225490751-f2d3a3aa-32a8-441c-83a5-1a6d2c2dda58.png)

I hope my assistance has been helpful in resolving the error.

**Comment by StephenCooper** [comment] 2023-03-16 09:52
Thank you I can reproduce this now with that example so appreciate your efforts as that will make it much easier for us to debug!

I have now raised this internally.

**Comment by ondrejzemanek** [comment] 2023-03-16 15:54
I have another scenario with this error: 

https://plnkr.co/edit/H1fjSN7faiZPUIck?preview

The error is not predictable in this example. Please keep it running with the browser console opened for ~45 seconds.

![image](https://user-images.githubusercontent.com/10475497/225670013-c9a5add1-0941-4e92-b98d-5bb35830adbd.png)

**This example simulates the following scenario:**

You have a web app with multiple screens with different tables (ag-grid). When you switch from one screen to another, the ag-grid package throws you the error in the console. **This happens when the `autoSizeColumns` function is called inside `onGridColumnsChanged` or `onGridSizeChanged` and the auto-sized column is nested in column group.**

Unfortunately, I can't share the real scenario with you. 

I hope this scenario can be fixed too.

Thank you

**Comment by StephenCooper** [comment] 2023-03-16 16:39
Hi, 

I have taken a look at this and can track it down to a difference in rendering order caused by React 18 createRoot. One potential temporary workaround is to set `suppressColumnVirtualisation` as this forces all columns to be created even if they are off the screen. 

However, that is not always suitable if you have many columns but I thought I would give this as one possibility while we resolve the underlying issue.

**Comment by vaynevayne** [comment] 2023-03-17 03:46
thanks

**Comment by StephenCooper** [comment] 2023-03-17 09:26
I have found the cause of the issue and in 29.2 it will no longer throw this error. This is due to be released next week. 

Thanks for reporting this!

**Closed by StephenCooper** 2023-03-17 09:26 UTC
Labels: AG-8205

**Comment by judaihyun** [comment] 2023-07-04 12:35
> May I ask a question? What was the cause of the problem? I noticed that this issue occurred rarely when I called resetColumnGroupState and resetColumnState, followed by autoSizeAllColumns(). I suspected it might be an asynchronous issue. Anyway, thank you for providing a great library.
