### ISSUE TITLE
Chart labels rendered strangely when a chart has no data

### ISSUE THREAD

**Issue by dmathisen** [ag-grid/ag-grid#4823] opened 2021-12-10 16:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When rendering an AG Bar Chart with series labels and no data (all data points are null or 0), the labels float in the middle of the chart.

Plunker: https://plnkr.co/edit/F3GHEWlcSzSfgc1V
See service-data.js and note that all values are 0

![image](https://user-images.githubusercontent.com/684701/145604667-0d28c8db-3114-41c6-8faa-096743b1ce2b.png)

**Expected behavior**
Labels should either not render or maybe render all the way to the left (where they would be if there was a 0 width bar).

**Environment:**
* **AG Grid version:** Latest
* **Browser:** Any
* **OS:** Windows 10
* **Language:** JS/TS

**Comment by makinggoodsoftware** [comment] 2021-12-22 15:04
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment] 2022-01-14 17:36
Hello @dmathisen!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6135 [Regression] When all bar series are hidden via the legend, the Y-axis disappears**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment] 2022-02-04 15:31
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Closed by makinggoodsoftware** 2022-02-04 15:31 UTC
Labels: in_zendesk, ag-6135
