### ISSUE TITLE
Vite Project + React, CaptureThumbnail error TypeError

### ISSUE THREAD

**Issue by yalian-icom** [ag-grid/ag-grid#7194] opened 2023-10-26 10:32 UTC
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
A fresh project with vite - react, with the simple example provided: https://www.ag-grid.com/react-data-grid/getting-started/

**Current behavior**
We get the following warning
`pagedata-script.js:1 CaptureThumbnail error TypeError: a.getContext(...).drawWindow is not a function`
<img width="597" alt="image" src="https://github.com/ag-grid/ag-grid/assets/59922213/67087d7b-a8f6-48f2-b073-9c59bf6d13af">

**Expected behavior**
Don't see this warning

**Please tell us about your environment:**
MacOS, VSCode, bun/npm

* **AG Grid version:** X.X.X
```
"ag-grid-community": "^30.2.0",
"ag-grid-react": "^30.2.0",
```

* **Browser:**
Google Chrome: v118.0.5993.117

**Comment by AG-Zoheil** [comment] 2023-10-31 14:17
Hi @yalian-icom,

Thanks for reporting this.

Vite should work fine with AG Grid.

Looking at the error message it's quite possible that this is caused by something other than AG Grid. Regardless, if you are able to provide a reproduction of it for us to view, we'd be happy to have a look.

Kind regards,

**Comment by AG-Zoheil** [comment] 2023-11-30 10:30
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Closed by AG-Zoheil** 2023-11-30 10:30 UTC
Labels: waiting-for-repro
