### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by giniedp** [ag-grid/ag-grid#2588] opened 2018-08-22 11:47 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
There is no issue during runtime but running our test suite (ci, docker) tests randomly fail because of the following error

`ResizeObserver loop limit exceeded`

**Please tell us about your environment:**

* **ag-Grid version:** 18.1.1

* **Browser:**
Chrome Headless 68 stable (66, 67 and 69 beta also fail)

* **Language:** Typescript 2.8.3 / ES5

Looking through the ag-grid source code i could not spot any issue. This
https://github.com/ag-grid/ag-grid/blob/18.1.1/packages/ag-grid/src/ts/resizeObserver.ts#L396
looks actually ok.

Still i was wondering if the callback itself might be causing a resize event and then run into a loop, but the gotcha here https://developers.google.com/web/updates/2016/10/resizeobserver#gotcha
says that this case is actually protected

However, this does not seem to be the case as this plunkr demonstrates
https://jsfiddle.net/que_etc/ba1ad26e/
so i changed the ag-grid code at
https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid/src/ts/resizeObserver.ts#L396
from this
```ts
for (const entry of entries) {
    callback(entry);
}
```
to this
```ts
for (const entry of entries) {
    setTimeout(function() {
        callback(entry);
    })
}
```
with the result that the error does not occur and the tests don't fail any more.

**Comment by outofgamut** [comment] 2018-08-31 15:36
any plans on a fix for this coming out in a patch release?

**Comment by giniedp** [comment] 2018-08-31 19:49
i was told, its being tracked as a bug now.
see https://www.ag-grid.com/ag-grid-pipeline/ 
Key: AG-2028

**Comment by giniedp** [comment] 2018-09-13 21:38
Looking at the source code, there has been some work on the resize observer, but the issue has not been addressed. The old polyfill observer is gone, but the issue was with the native ResizeObserver when using Chrome and that is processing the callback directly as before.

https://github.com/ag-grid/ag-grid/blob/b19.0.0/packages/ag-grid-community/src/ts/misc/resizeObserverService.ts#L17

**Comment by giniedp** [comment] 2018-09-14 13:31
@Laurensvdw is your project anyhow publicly available where the issue can be reproduced? how often does it occur? ag-grid team asks for a reproducable example. For me it is only happening on a ci server and that is a bit hard to isolate, extract and reproduce.

**Comment by Laurensvdw** [comment] 2018-09-14 13:45
@giniedp Nice "Pink Panter" spy work ;)
I will try to reproduce with a plunker. As it is not possible to share the website (government restricted)...

**Comment by giniedp** [comment] 2018-09-14 14:17
@Laurensvdw i've got a vanilla js ag-grid setup on stackblitz
https://stackblitz.com/edit/js-ag-grid
but i can't break the resize

**Comment by Laurensvdw** [comment] 2018-09-14 14:52
@giniedp It seems that it is not reproducible, my layout is much more complex than this....
[Link to stackblitz example](https://material-ag-grid.stackblitz.io)

Landing on the component and clicking on the button "Toggle menu state", most of the times cause the error, but not in the example :(

**Comment by giniedp** [comment] 2018-09-14 16:42
thx anyway for trying

**Comment by giniedp** [comment] 2018-09-18 08:55
i was able to reproduce the behavior. Repository is located here
https://github.com/giniedp/ag-grid-ro-issue

@Laurensvdw would you mind to review my reproduction and tell if it also breaks on your side?

meanwhile i am reporting back to ag-grid team.

**Comment by giniedp** [comment] 2018-09-18 20:54
I was able to sort out my scenario. We did not include stylesheets into the tests. This might introduce a layout mess into ag-grid. Adding stylesheets does let all tests pass again.

This Leaves @Laurensvdw issue still unresolved.

**Comment by Laurensvdw** [comment] 2018-09-19 07:51
I think it is due to the nature of our "complex" layout. The side navigation has different modes which make the actual content resize. Even if we only have 4 columns, it still happens.

My best guess is that it has something to do with the resizing (animation) of the content, which triggers the grid resizer (for every pixel?).

I hope the team of ag-grid just implements your solution, and that it hopefully resolves the issue.

**Comment by giniedp** [comment] 2018-09-19 11:05
yes, if there are animations, the new behavior of ag-grid will trigger the resize event once per animation step. I have changed my example on stackblitz https://stackblitz.com/edit/js-ag-grid but still cant break it.

**Comment by Laurensvdw** [comment] 2018-09-19 11:34
Used your column/row generation loops and added a transition for the margin-left when toggling the side navigation (to make the resizing even heavier). I can't break it either... I am starting to fear we are dealing with magic... ☠️ 

[The example once again](https://material-ag-grid.stackblitz.io/test1)

**Comment by makinggoodsoftware** [comment] 2018-09-27 15:08
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment] 2018-09-27 15:12
Hi,

We appreciate that there is an issue seen by many users, but we are struggling to reproduce in our end.

Thanks at @giniedp  for the repository.

We are going to add a mechanism to opt-out of the native resize observer

This is going to be in our next release


AG-2066 | Create an opt out of the native ResizeObserver
-- | --



https://www.ag-grid.com/ag-grid-pipeline/

Note that we can't still fully reproduce this in our end, so we are not sure this will fully help you guys.

If you do come up with a simple reproducible scenario, please let us know

**Comment by Laurensvdw** [comment] 2018-09-28 08:46
Hey Alberto, 

Thanks for following it up and providing a possible solution. We will implement the solution when it is available. 

The "bug" is indeed very hard to reproduce, in our case we have it 20% of the time, so no logic there...

**Comment by stepet80** [comment] 2018-11-14 09:08
> I can confirm the error still exists.
> For me the `sizeColumnsToFit()` method is causing the error, resutling in the application to break. It is because I have a left side navigation and closing/opening/pinning the navigation makes the resizer run wild, as the main content holding the grid resizes (it is random, it does not occur every time....).
> 
> @giniedp Thanks for the solution, hopefully this time they will copy past your code ;)

It also works if you do sizeColumnsToFit() before you assign the datasource...

**Comment by sontek** [comment] 2018-11-15 15:08
I'm getting this with:

```
import React from "react";
import ReactDataGrid from 'react-data-grid';
import styles from "../../sass/materials/datagrid.scss";
import { AgGridReact } from 'ag-grid-react';


class DataGrid extends React.PureComponent {
    constructor(props) {
        super(props);

        this.state = {
            columnDefs: [
                {headerName: "Make", field: "make"},
                {headerName: "Model", field: "model"},
                {headerName: "Price", field: "price"}

            ],
            rowData: [
                {make: "Toyota", model: "Celica", price: 35000},
                {make: "Ford", model: "Mondeo", price: 32000},
                {make: "Porsche", model: "Boxter", price: 72000}
            ]
        }
    }

    render() {
        return (
            <div className={styles.dataGrid}>
                <AgGridReact
                    columnDefs={this.state.columnDefs}
                    rowData={this.state.rowData}>
                </AgGridReact>
            </div>
        )
    }
}

export default DataGrid;
```

**Comment by sontek** [comment] 2018-11-15 15:09
We had this problem when we were using ResizeObserver in newer versions of Chrome as well and we just throttled it.

```
        this.resizeObserver = new ResizeObserver(
            debounce(this.handleResize, 10)
        );
```

and it worked perfectly.

**Comment by frankwallis** [comment] 2018-12-05 14:11
For us this appears to be triggered when the side scrollbar is initially visible and then some rows are removed from the grid, so that the scrollbar is not visible any more

**Comment by makinggoodsoftware** [comment] 2019-01-25 15:01
Hi guys,

Quick update, the opt out to not use the resizer is going to be introduced in v20.1 ETA 4/5 weeks, sorry for the long delay

Thanks

**Comment by makinggoodsoftware** [comment] 2019-02-06 15:50
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2066 | Create an opt out of the native ResizeObserver
-- | --

**Closed by makinggoodsoftware** 2019-02-06 15:50 UTC
Labels: ag-grid engaged
