### ISSUE TITLE
exportDataAsCsv exported file formatted for windows

### ISSUE THREAD

**Issue by bteepell** [ag-grid/ag-grid#1468] opened 2017-02-13 16:06 UTC
I am submitting a bug report

**Current behavior**
exportDataAsCsv adds excel token into file   // for Excel, we need \ufeff at the start

**Expected behavior**
File export should only contain column data.  And not formatted for windows.

Possible to use the file for other reasons besides viewing in excel. 

**Please tell us about your environment:**
Mac os 10.x 

* **ag-Grid version:** 8.0.1
* **ag-Grid-React version:** 8.0.0

* **Browser:**
Chrome

**Comment by seanlandsman** [comment] 2017-02-14 08:57
What we'll do here is raise a feature request to optionally exclude this char. 

As this has been the csv export behaviour since introduced if we changed it now it might break expected behaviour for existing users

**Comment by moghthalkushal** [comment] 2017-10-12 10:54
I observed one more thing , if the data is of the type "123                (spaces followed)"  export to excel doesn't work .

Its considering it as a Number.

XML ERROR in Table
REASON:	Bad Value
FILE:	C:\Users\kushal\Documents\export (4).xls
GROUP:	Cell
TAG:	Data
VALUE:	123

**Comment by seanlandsman** [comment] 2017-10-12 13:09
thanks for the update - I've made a note of this

**Comment by makinggoodsoftware** [comment] 2017-12-19 09:03
This should be fixed now

**Closed by makinggoodsoftware** 2017-12-19 09:03 UTC
Labels: bug
